
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class SkillsLookup(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'SkillsLookup',
            'filename': 'skills_lookup',
            'files': ['skills.txt'],
            'queries': ['lookup.sparql'],
            'transformers': ['lowercase', 'lookup']},
 'source': 'skills.owl',
 'time': '2022-04-27 21:15:54.262359'}

    __data = {
    1: [   'entrepreneurship',
           'psychiatrists',
           'practitioners',
           'practitioning',
           'entrepreneurs',
           'communication',
           'entrepreneur',
           'practitioned',
           'perspectives',
           'facilitating',
           'organization',
           'practitioner',
           'psychiatrist',
           'facilitators',
           'facilitator',
           'influencers',
           'chairpeople',
           'facilitated',
           'perspective',
           'influencing',
           'chairperson',
           'legislation',
           'innovations',
           'facilitates',
           'influencors',
           'chairwomen',
           'influenced',
           'inventions',
           'facilitate',
           'forbes.com',
           'influencor',
           'influencer',
           'delivering',
           'innovaters',
           'innovating',
           'advocating',
           'innovators',
           'government',
           'university',
           'chairwoman',
           'creativity',
           'innovation',
           'professor',
           'inventing',
           'innovates',
           'academics',
           'negotiate',
           'activists',
           'inventors',
           'invention',
           'delivered',
           'advocates',
           'innovator',
           'influence',
           'companies',
           'musicians',
           'publisher',
           'innovated',
           'innovatod',
           'artifact',
           'advisors',
           'inventor',
           'beginner',
           'lectures',
           'startups',
           'activist',
           'academic',
           'chairman',
           'advocate',
           'academia',
           'invented',
           'chairing',
           'activism',
           'lectured',
           'musician',
           'creative',
           'lecturer',
           'delivers',
           'producer',
           'chairmen',
           'delivery',
           'deliver',
           'authors',
           'writers',
           'startup',
           'council',
           'mediate',
           'agendas',
           'empathy',
           'ability',
           'adovacy',
           "forum's",
           'founder',
           'company',
           'advisor',
           'expert',
           'author',
           'novice',
           'agenda',
           'writer',
           'mentor',
           'forums',
           'school',
           'policy',
           'forbes',
           'forum',
           'event',
           'skill',
           'role',
           'law',
           'cxo',
           'ceo',
           'cto'],
    2: [   'global_innovation council',
           'national_economic policy',
           'chief_executive officer',
           'chief_technical officer',
           'harvard_business school',
           'social_media influencer',
           'chief_strategy officer',
           'world_economic forum',
           'business creativity',
           'harvard university',
           'board_chair chair',
           'innovation agenda',
           'business academic',
           'serial innovator',
           'she_has lectured',
           'innovator agenda',
           'he_has lectured',
           'business school',
           'master inventor',
           'senior inventor',
           'trusted advisor',
           'inagural member',
           'serial inventor',
           'economic policy',
           'thought leader',
           'senior advisor',
           'personal touch',
           'business role',
           'the economist',
           'present chair',
           'lecturing at',
           'chair person',
           'chair people',
           'she lectures',
           'he lectures',
           'chair woman',
           'chair women',
           'board chair',
           'skill level',
           'past chair',
           'soft skill',
           'chair men',
           'chair man',
           'start ups',
           'start up',
           'chair of'],
    3: [   'global innovation council',
           'national economic policy',
           'chief executive officer',
           'social media influencer',
           'chief technical officer',
           'harvard business school',
           'chief strategy officer',
           'world economic forum',
           'board chair chair',
           'she has lectured',
           'to support those',
           'he has lectured',
           'chair of the'],
    4: ['chairwoman of the board', 'chairman of the board'],
    5: [],
    6: []}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
