from .roles_trie import RolesTrie
from .roles_uses import RolesUses
from .roles_spans import RolesSpans
from .roles_types import RolesTypes
from .roles_lookup import RolesLookup
from .roles_labels import RolesLabels
from .roles_effects import RolesEffects
from .roles_similar import RolesSimilar
from .roles_implies import RolesImplies
from .roles_uses_rev import RolesUsesRev
from .roles_comments import RolesComments
from .roles_synonyms import RolesSynonyms
from .roles_requires import RolesRequires
from .roles_spacy_ner import RolesSpacyNER
from .roles_types_rev import RolesTypesRev
from .roles_ner_depth import RolesNerDepth
from .roles_labels_rev import RolesLabelsRev
from .roles_graffl_ner import RolesGrafflNER
from .roles_implies_rev import RolesImpliesRev
from .roles_similar_rev import RolesSimilarRev
from .roles_effects_rev import RolesEffectsRev
from .roles_ner_taxonomy import RolesNerTaxonomy
from .roles_synonyms_rev import RolesSynonymsRev
from .roles_requires_rev import RolesRequiresRev
from .roles_ner_depth_rev import RolesNerDepthRev
from .roles_spacy_ner_rev import RolesSpacyNERRev
from .roles_in_activities import RolesInActivities
from .roles_graffl_ner_rev import RolesGrafflNERRev
from .roles_in_departments import RolesInDepartments
from .roles_ner_taxonomy_rev import RolesNerTaxonomyRev
from .roles_infer_by_requires import RolesInferByRequires
from .roles_in_activities_rev import RolesInActivitiesRev
from .roles_in_departments_rev import RolesInDepartmentsRev
from .roles_template_constraints import RolesTemplateConstraints
