
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class DefiLabels(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'DefiLabels',
            'filename': 'defi_labels',
            'queries': ['labels.sparql'],
            'reverse': True,
            'transformers': ['labels']},
 'source': 'defi.owl',
 'time': '2022-04-27 21:15:55.013855'}

    __data = {
    'acceptable': ['Acceptable'],
    'access': ['Access'],
    'action': ['Action'],
    'actor': ['Actor'],
    'agency': ['Agency'],
    'algorithmic_stablecoin': ['Algorithmic Stablecoin'],
    'anonymous_founding_team': ['Anonymous Founding Team'],
    'application': ['Application'],
    'arbitrage': ['Arbitrage'],
    'artefact': ['Artefact'],
    'asic_hardware': ['Asic Hardware'],
    'asset': ['Asset'],
    'asset_transfer': ['Asset Transfer'],
    'asymmetric_key_cryptography': ['Asymmetric Key Cryptography'],
    'attribute': ['Attribute'],
    'autonomous_monitoring': ['Autonomous Monitoring'],
    'autonomous_organization': ['Autonomous Organization'],
    'bank': ['Bank'],
    'banking_platform': ['Banking Platform'],
    'banking_system': ['Banking System'],
    'barter': ['Barter'],
    'base_rate': ['Base Rate'],
    'basis_cash': ['Basis Cash'],
    'bitcoin': ['Bitcoin'],
    'bitcoin_foundation': ['Bitcoin Foundation'],
    'block_mine': ['Block Mine'],
    'blockchain': ['Blockchain'],
    'blockchain_contract': ['Blockchain Contract'],
    'bonding_curve': ['Bonding Curve'],
    'bullion': ['Bullion'],
    'canadian_dollar': ['Canadian Dollar'],
    'capability': ['Capability'],
    'cash_economy': ['Cash Economy'],
    'censorship': ['Censorship'],
    'central_bank': ['Central Bank'],
    'centralized_control': ['Centralized Finance'],
    'centralized_exchange': ['Centralized Exchange'],
    'coinbase': ['Coinbase'],
    'coindesk': ['Coindesk'],
    'coinshares': ['Coinshares'],
    'collateral': ['Collateral'],
    'company': ['Company'],
    'consensus': ['Consensus'],
    'consensus_mechanism': ['Consensus Mechanism'],
    'contract': ['Contract'],
    'council': ['Council'],
    'cryptocollateral': ['Cryptocollateral'],
    'cryptocollateralized_stablecoin': ['Cryptocollateralized Stablecoin'],
    'cryptocurrency': ['Cryptocurrency'],
    'cryptographic_scarcity': ['Cryptographic Scarcity'],
    'cryptography': ['Cryptography'],
    'currency': ['Currency'],
    'currency_transfer': ['Currency Transfer'],
    'dai_savings_rate': ['Dai Savings Rate'],
    'dark_pool_stock_trading': ['Dark Pool Stock Trading'],
    'data_source': ['Data Source'],
    'decentralized_application': ['Decentralized Application'],
    'decentralized_autonomous_organization': [   'Decentralized Autonomous '
                                                 'Organization'],
    'decentralized_currency': ['Decentralized Currency'],
    'decentralized_exchange': ['Decentralized Exchange'],
    'decentralized_organization': ['Decentralized Organization'],
    'defi': ['Defi'],
    'defi_protocol': ['Defi Protocol'],
    'defi_version_1': ['Defi Version 1'],
    'defi_version_2': ['Defi Version 2'],
    'defi_version_3': ['Defi Version 3'],
    'deposit': ['Deposit'],
    'digital_asset': ['Digital Asset'],
    'digital_currency': ['Digital Currency'],
    'digital_currency_group': ['Digital Currency Group'],
    'document': ['Document'],
    'dollar': ['Dollar'],
    'durabilty': ['Durable'],
    'economy': ['Economy'],
    'empty_set_dollar': ['Empty Set Dollar'],
    'equality': ['Equality'],
    'equality_of_opportunity': ['Equality of Opportunity'],
    'erc-721': ['Erc-721'],
    'erc_20': ['Erc-20'],
    'esd_governance': ['Esd Governance'],
    'ethereum': ['Ethereum'],
    'euro': ['Euro'],
    'excessive_volatility': ['Excessive Volatility'],
    'exchange': ['Exchange'],
    'exchange_medium': ['Exchange Medium'],
    'exchange_rate': ['Exchange Rate'],
    'expansion': ['Expansion'],
    'explainability': ['Explainability'],
    'fee': ['Fee'],
    'fiat_collaterialized': ['Fiat Collaterialized'],
    'fiat_currency': ['Fiat Currency'],
    'finance': ['Finance'],
    'financial_censorship': ['Financial Censorship'],
    'financial_infrastructure': ['Financial Infrastructure'],
    'financial_primitive': ['Financial Primitive'],
    'financial_system': ['Financial System'],
    'fixed_exchange_rate': ['Fixed Exchange Rate'],
    'float_protocol': ['Float Protocol'],
    'foundation': ['Foundation'],
    'founding_team': ['Founding Team'],
    'fractional_algorithm_stablecoin': ['Fractional Algorithm Stablecoin'],
    'fractional_stablecoin': ['Fractional Stablecoin'],
    'funding_mechanism': ['Funding Mechanism'],
    'fungible_token': ['Fungible Token'],
    'gas_fee': ['Gas Fee'],
    'global_access': ['Global Access'],
    'gold': ['Gold'],
    'gold_standard': ['Gold Standard'],
    'governance': ['Governance'],
    'government_agency': ['Government Agency'],
    'immutable_ledger': ['Immutable Ledger'],
    'incentive_mechanism': ['Incentive Mechanism'],
    'inefficient': ['Inefficient'],
    'inequality': ['Inequality'],
    'inequality_of_opportunity': ['Inequality of Opportunity'],
    'inflation': ['Inflation'],
    'inflation_hedge': ['Inflation Hedge'],
    'infrastructure': ['Infrastructure'],
    'insurance': ['Insurance'],
    'insured_deposit': ['Insured Deposit'],
    'intangible_value': ['Intangible Value'],
    'internet': ['Internet'],
    'internet_of_bodies': ['Internet of Bodies'],
    'internet_of_money': ['Internet of Money'],
    'internet_of_things': ['Internet of Things'],
    'interoperability': ['Interoperability'],
    'jewelry': ['Jewelry'],
    'lack_of_access': ['Lack of Access'],
    'lack_of_interoperability': ['Lack of Interoperability'],
    'ledger': ['Ledger'],
    'leverage': ['Leverage'],
    'limited_access': ['Limited Access'],
    'limited_supply': ['Limited Supply'],
    'linear_bonding_curve': ['Linear Bonding Curve'],
    'liquidity': ['Liquidity'],
    'long_term': ['Long Term'],
    'malicious_action': ['Malicious Action'],
    'malicious_transaction': ['Malicious Transaction'],
    'market_exchange': ['Market Exchange'],
    'mechanism': ['Mechanism'],
    'medium': ['Medium'],
    'metal': ['Metal'],
    'mine': ['Mine'],
    'monitor': ['Monitor'],
    'mutable_ledger': ['Mutable Ledger'],
    'nft': ['Nft'],
    'non_physical_transfer': ['Non Physical Transfer'],
    'on_chain_governance': ['On Chain Governance'],
    'opaque': ['Opaque'],
    'opportunity': ['Opportunity'],
    'oracle': ['Oracle'],
    'organization': ['Organization'],
    'paper_currency': ['Paper Currency'],
    'payment_system': ['Payment System'],
    'paypal': ['Paypal'],
    'physical_transfer': ['Physical Transfer'],
    'platform': ['Platform'],
    'policy': ['Policy'],
    'portable': ['Portable'],
    'position': ['Position'],
    'precious_metal': ['Precious Metal'],
    'primitive': ['Primitive'],
    'privacy': ['Privacy'],
    'private_agency': ['Private Agency'],
    'proof_of_stake': ['Proof of Stake'],
    'proof_of_work': ['Proof of Work'],
    'proto_coinage': ['Proto Coinage'],
    'protocol': ['Protocol'],
    'protocol_controlled_value': ['Protocol Controlled Value'],
    'protocol_governance': ['Protocol Governance'],
    'public_agency': ['Public Agency'],
    'rate': ['Rate'],
    'research_company': ['Research Company'],
    'reserve_currency': ['Reserve Currency'],
    'ring_money': ['Ring Money'],
    'risk': ['Risk'],
    'risk_factor': ['Risk Factor'],
    'scalability': ['Scalability'],
    'scarcity': ['Scarcity'],
    'sec': ['Sec'],
    'security': ['Security'],
    'short_term': ['Short Term'],
    'silver': ['Silver'],
    'smart_contract': ['Smart Contract'],
    'software_protocol': ['Software Protocol'],
    'sovereign_currency': ['Sovereign Currency'],
    'sovereignity': ['Sovereignity'],
    'specie_currency': ['Specie Currency'],
    'stable': ['Stable'],
    'stablecoin': ['Stablecoin'],
    'stablecoin_protocol': ['Stablecoin Protocol'],
    'standard': ['Standard'],
    'state': ['State'],
    'stock_trade': ['Stock Trade'],
    'storage': ['Storage'],
    'store_of_wealth': ['Store of Wealth'],
    'supply': ['Supply'],
    'supply_expansion': ['Supply Expansion'],
    'system': ['System'],
    'tangible_value': ['Tangible Value'],
    'team': ['Team'],
    'token': ['Token'],
    'token_standard': ['Token Standard'],
    'token_swap': ['Token Swap'],
    'trade': ['Trade'],
    'trading_platform': ['Trading Platform'],
    'transaction': ['Transaction'],
    'transfer': ['Transfer'],
    'treasury_governance': ['Treasury Governance'],
    'uncollateralized_stablecoin': ['Uncollateralized Stablecoin'],
    'uniform': ['Uniform'],
    'universal_access': ['Unlimited Access'],
    'unlimited_supply': ['Unlimited Supply'],
    'us_dollar': ['Us Dollar'],
    'user_issued_asset': ['User Issued Asset'],
    'user_sovereignity': ['User Sovereignity'],
    'value': ['Value'],
    'value_standard': ['Value Standard'],
    'value_transfer': ['Value Transfer'],
    'virtual_transfer': ['Virtual Transfer'],
    'volatile': ['Volatile'],
    'zelle': ['Zelle']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
