
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class DefiTypesRev(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'DefiTypes',
            'filename': 'defi_types',
            'queries': ['subclass.sparql'],
            'reverse': True,
            'transformers': ['types']},
 'source': 'defi.owl',
 'time': '2022-04-27 21:15:54.978356'}

    __data = {
    'access': ['limited_access', 'universal_access', 'global_access'],
    'account': ['ethereum_account'],
    'action': [   'consensus',
                  'deposit',
                  'payment',
                  'mediate',
                  'value',
                  'governance',
                  'verify',
                  'access',
                  'transfer',
                  'spend',
                  'mine',
                  'token_minting',
                  'deploy',
                  'malicious_action',
                  'inflation',
                  'decrease',
                  'token_utilization',
                  'increase',
                  'censorship',
                  'trade',
                  'transaction',
                  'monitor',
                  'exchange',
                  'refinance',
                  'hashing',
                  'creation'],
    'actor': [   'miner',
                 'vault_holder',
                 'untrusted_actor',
                 'investor',
                 'trusted_actor',
                 'third_party',
                 'liquidator',
                 'external_actor'],
    'agency': ['private_agency', 'public_agency'],
    'algorithmic_stablecoin': [   'fractional_algorithm_stablecoin',
                                  'empty_set_dollar',
                                  'basis_cash'],
    'application': ['decentralized_application'],
    'artefact': [   'ledger',
                    'vault',
                    'document',
                    'stablecoin',
                    'contract',
                    'account',
                    'standard',
                    'signature',
                    'policy',
                    'data_source',
                    'timestamp',
                    'wallet',
                    'hash',
                    'asset',
                    'requirement'],
    'asset': ['digital_asset', 'user_issued_asset'],
    'asset_fund': ['digital_asset_fund'],
    'asset_transfer': ['currency_transfer'],
    'attribute': [   'scarcity',
                     'difference',
                     'efficiency',
                     'immutability',
                     'inequality',
                     'disadvantage',
                     'advantage',
                     'trust',
                     'niche',
                     'rate',
                     'mutability',
                     'security',
                     'censorship_resistant',
                     'equality',
                     'sovereignity',
                     'explainability',
                     'power',
                     'redundant',
                     'trustworthy',
                     'stable',
                     'identical',
                     'uniform',
                     'durabilty',
                     'robust',
                     'mutable',
                     'flexible',
                     'immutable',
                     'acceptable',
                     'reliable',
                     'capability',
                     'tolerant',
                     'latency',
                     'scalability',
                     'adaptable',
                     'mainstream',
                     'portable',
                     'predictable',
                     'cost',
                     'zero_downtime',
                     'vulnerable',
                     'inefficient'],
    'auction': ['public_auction'],
    'autonomous_organization': ['decentralized_autonomous_organization'],
    'balance': ['token_balance', 'staking_balance'],
    'bank': ['central_bank'],
    'basis': ['pro_rata_basis'],
    'blockchain': ['bitcoin', 'programmable_blockchain'],
    'bonding_curve': [   'sigmoid_bonding_curve',
                         'linear_bonding_curve',
                         'super_linear_bonding_curve',
                         'logistic_bonding_curve'],
    'bullion': ['gold', 'silver'],
    'capability': ['interoperability', 'lack_of_interoperability'],
    'censorship': ['financial_censorship'],
    'centralized_currency': ['euro', 'dollar', 'yuan'],
    'collateral': ['cryptocollateral'],
    'company': [   'coinbase',
                   'research_company',
                   'coindesk',
                   'digital_currency_group',
                   'coinshares'],
    'computational_node': [   'peer_node',
                              'server',
                              'desktop',
                              'laptop',
                              'distributed_node'],
    'consensus': ['distributed_consensus', 'system_consensus'],
    'consensus_mechanism': [   'proof_of_work',
                               'proof_of_authority',
                               'proof_of_identity',
                               'proof_of_activity',
                               'decentralized_consensus',
                               'proof_of_elapsed_time',
                               'proof_of_capacity',
                               'proof_of_stake',
                               'delegated_byzantine_fault_tolerance'],
    'contract': ['smart_contract'],
    'contract_risk': ['smart_contract_risk'],
    'cost': ['energy_cost', 'computing_cost'],
    'council': ['blockchain_council'],
    'creation': ['block_creation'],
    'cryptoasset': ['fungible_cryptoasset', 'non_fungible_cryptoasset'],
    'cryptocurrency': ['ethereum'],
    'cryptography': ['asymmetric_key_cryptography'],
    'currency': [   'digital_currency',
                    'decentralized_currency',
                    'physical_currency',
                    'sovereign_currency',
                    'reserve_currency',
                    'centralized_currency',
                    'fiat_currency'],
    'data_source': ['oracle'],
    'debt': ['overcollaterized_debt'],
    'decentralized_currency': ['cryptocurrency'],
    'decrease': ['monotonical_decrease'],
    'defi': ['defi_version_2', 'defi_version_1', 'defi_version_3'],
    'defi_protocol': ['stablecoin_protocol'],
    'deposit': ['insured_deposit'],
    'digital_asset': ['cryptoasset'],
    'digital_currency': ['digital_yuan', 'electronic_coin'],
    'distributed_consensus': ['distributed_system_consensus'],
    'distributed_ledger': [   'distributed_immutable_ledger',
                              'distributed_mutable_ledger'],
    'distributed_node': ['peer_to_peer_node', 'distributed_timestamp_server'],
    'distributed_system_consensus': ['blockchain_consensus'],
    'distributed_timestamp_server': [   'peer_to_peer_distributed_timestamp_server'],
    'dollar': ['us_dollar', 'canadian_dollar'],
    'economy': ['cash_economy'],
    'electronic_payment_system': ['zelle', 'paypal'],
    'equality': ['equality_of_opportunity'],
    'ethereum_account': ['contract_account', 'externally_owned_account'],
    'exchange': ['barter', 'market_exchange', 'token_swap'],
    'exchange_medium': ['currency', 'metal'],
    'exchange_platform': ['decentralized_exchange', 'centralized_exchange'],
    'exchange_rate': ['fixed_exchange_rate'],
    'expansion': ['supply_expansion'],
    'explainability': ['transparency', 'opaque'],
    'external_actor': ['keeper'],
    'factor': ['risk_factor'],
    'fee': ['gas_fee', 'transaction_fee', 'miner_fee'],
    'financial_institution': ['bank'],
    'financial_mechanism': ['loan', 'debt'],
    'financial_primitive': ['arbitrage', 'leverage', 'risk', 'liquidity'],
    'financial_system': ['gold_standard', 'defi', 'centralized_control'],
    'foundation': ['bitcoin_foundation'],
    'founding_team': ['anonymous_founding_team'],
    'function': ['linear_function', 'super_linear_function'],
    'fund': ['asset_fund'],
    'funding_mechanism': ['fee'],
    'governance': [   'protocol_governance',
                      'on_chain_governance',
                      'esd_governance',
                      'treasury_governance'],
    'government_agency': ['sec'],
    'hardware': ['asic_hardware'],
    'hashing_problem': ['cryptographic_hashing_problem'],
    'horizon': ['long_term', 'short_term'],
    'incentive_mechanism': [   'negative_incentive',
                               'incentive_fee',
                               'direct_incentive',
                               'staked_incentive',
                               'positive_incentive'],
    'increase': ['monotonical_increase'],
    'inequality': ['inequality_of_opportunity'],
    'infrastructure': ['hardware', 'financial_infrastructure'],
    'interest_rate': ['fixed_interest_rate', 'variable_interest_rate'],
    'internet': [   'internet_of_bodies',
                    'internet_of_things',
                    'internet_of_money'],
    'investor': ['early_investor'],
    'ledger': ['immutable_ledger', 'mutable_ledger', 'distributed_ledger'],
    'limited_access': ['lack_of_access'],
    'liquidation': ['collateral_liquidation'],
    'loan': ['collateralized_loan', 'uncollaterialized_loan', 'flash_loan'],
    'loss': ['permanent_loss', 'impermanent_loss'],
    'malicious_action': ['denial_of_service', 'malicious_transaction'],
    'malicious_transaction': ['double_spend'],
    'measurement': ['function', 'ratio', 'bonding_curve'],
    'mechanism': [   'dai_savings_rate',
                     'debt_ceiling',
                     'incentive_mechanism',
                     'consensus_mechanism',
                     'funding_mechanism',
                     'financial_mechanism',
                     'slashing_condition',
                     'escrow_mechanism',
                     'stability_fee'],
    'medium': ['exchange_medium'],
    'mine': ['block_mine'],
    'model': ['trust_model'],
    'monitor': ['autonomous_monitoring'],
    'negative_incentive': ['negative_staked_incentive'],
    'network': ['peer_to_peer_network'],
    'network_protocol': ['peer_to_peer_network_protocol'],
    'node': [   'computational_node',
                'virtual_machine',
                'attacker_node',
                'trusted_node'],
    'non_physical_transfer': ['virtual_transfer'],
    'number': [   'semi_random_number',
                  'nonce',
                  'transaction_number',
                  'random_number'],
    'organization': [   'company',
                        'decentralized_organization',
                        'autonomous_organization',
                        'foundation',
                        'platform',
                        'council',
                        'fund',
                        'financial_institution'],
    'output': ['transaction_output'],
    'payment': ['electronic_payment', 'online_payment'],
    'payment_system': ['electronic_payment_system'],
    'physical_currency': ['paper_currency', 'specie_currency', 'proto_coinage'],
    'platform': [   'payment_system',
                    'trading_platform',
                    'banking_platform',
                    'exchange_platform'],
    'position': ['inflation_hedge'],
    'positive_incentive': ['positive_staked_incentive'],
    'power': ['computing_power'],
    'precious_metal': ['jewelry', 'bullion'],
    'predefined_transaction': ['bitcoin_transaction'],
    'primitive': ['financial_primitive'],
    'problem': ['consensus_problem', 'hashing_problem'],
    'proof': ['zero_knowledge_proof', 'cryptographic_proof'],
    'proof_of_stake': ['delegated_proof_of_stake'],
    'proto_coinage': ['ring_money'],
    'protocol': ['network_protocol', 'software_protocol', 'defi_protocol'],
    'public_agency': ['government_agency'],
    'public_auction': ['keeper_auction'],
    'rate': ['exchange_rate', 'interest_rate', 'base_rate'],
    'ratio': ['collateralization_ratio'],
    'redundancy': ['complete_redundancy', 'partial_redundancy'],
    'redundant': ['redundancy'],
    'requirement': ['collateral_requirement', 'staking_requirement'],
    'reward': ['direct_reward', 'bonus', 'keeper_reward', 'staking_reward'],
    'risk': [   'duration_risk',
                'contract_risk',
                'foreclosure_risk',
                'counterparty_risk'],
    'scarcity': ['cryptographic_scarcity'],
    'security': ['cryptography'],
    'server': ['server_rack', 'timestamp_server'],
    'signature': ['digital_signature'],
    'slashing_condition': [   'complete_slashing',
                              'partial_slashing',
                              'liquidation'],
    'smart_contract': ['blockchain_contract'],
    'software_protocol': ['blockchain'],
    'sovereignity': ['user_sovereignity'],
    'stablecoin': [   'fractional_stablecoin',
                      'fiat_collaterialized',
                      'algorithmic_stablecoin',
                      'uncollateralized_stablecoin',
                      'cryptocollateralized_stablecoin'],
    'stablecoin_protocol': ['float_protocol', 'fei'],
    'standard': ['value_standard', 'token_standard'],
    'state': [   'volatile',
                 'dispute',
                 'position',
                 'solution',
                 'loss',
                 'balance',
                 'stake',
                 'problem'],
    'stock_trade': ['dark_pool_stock_trading'],
    'storage': ['store_of_wealth'],
    'store_of_wealth': ['precious_metal'],
    'supply': ['unlimited_supply', 'limited_supply'],
    'system': [   'financial_system',
                  'centralized_system',
                  'banking_system',
                  'distributed_system'],
    'team': ['founding_team'],
    'third_party': ['trusted_third_party'],
    'timestamp_server': ['peer_to_peer_timestamp_server'],
    'token': ['nft', 'fungible_token', 'synthetic_token', 'voting_token'],
    'token_standard': ['erc_20', 'erc-721'],
    'tolerant': ['fault_tolerant'],
    'trade': ['stock_trade'],
    'transaction': [   'valid_transaction',
                       'irreversible_transaction',
                       'invalid_transaction',
                       'predefined_transaction',
                       'reversible_transaction'],
    'transaction_output': ['unspent_transaction_output'],
    'transfer': [   'non_physical_transfer',
                    'asset_transfer',
                    'physical_transfer',
                    'value_transfer'],
    'trust_model': ['collective_trust_model'],
    'unspent_transaction_output': ['input_utxo', 'output_utxo'],
    'value': [   'intangible_value',
                 'tangible_value',
                 'protocol_controlled_value'],
    'virtual_machine': ['ethereum_virtual_machine'],
    'volatile': ['excessive_volatility'],
    'wallet': ['cryptocurrency_wallet']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
