
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class DefiSpans(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'DefiSpans',
            'filename': 'defi_spans',
            'queries': ['spans.sparql'],
            'transformers': ['spans']},
 'source': 'defi.owl',
 'time': '2022-04-27 21:15:54.649855'}

    __data = {
    'algorithmic': [   {   'canon': 'algorithmic_stablecoin',
                           'content': {'stablecoin'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'anonymous': [   {   'canon': 'anonymous_founding_team',
                         'content': {'founding', 'team'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'asic': [   {   'canon': 'asic_hardware',
                    'content': {'hardware'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'asset': [   {   'canon': 'asset_transfer',
                     'content': {'transfer'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'asymmetric': [   {   'canon': 'asymmetric_key_cryptography',
                          'content': {'cryptography', 'key'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'autonomous': [   {   'canon': 'autonomous_organization',
                          'content': {'organization'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True},
                      {   'canon': 'autonomous_monitoring',
                          'content': {'monitoring'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'bank': [   {   'canon': 'paper_currency',
                    'content': {'note'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'paper_currency',
                    'content': {'notes'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'banking': [   {   'canon': 'banking_platform',
                       'content': {'platform'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'banking_system',
                       'content': {'system'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'base': [   {   'canon': 'base_rate',
                    'content': {'rate'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'basis': [   {   'canon': 'basis_cash',
                     'content': {'cash'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'bitcoin': [   {   'canon': 'bitcoin_foundation',
                       'content': {'foundation'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'block': [   {   'canon': 'block_mine',
                     'content': {'mine'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'blockchain': [   {   'canon': 'blockchain_contract',
                          'content': {'contract'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True},
                      {   'canon': 'blockchain_contract',
                          'content': {'based', 'contract'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'bonding': [   {   'canon': 'bonding_curve',
                       'content': {'curve'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'bonding_curve',
                       'content': {'curves'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'canadian': [   {   'canon': 'canadian_dollar',
                        'content': {'dollar'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'candidate': [   {   'canon': 'consensus_mechanism',
                         'content': {'mechanism', 'consensus'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'cash': [   {   'canon': 'cash_economy',
                    'content': {'economy'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'censorship': [   {   'canon': 'censorship_resistant',
                          'content': {'resistant'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'central': [   {   'canon': 'central_bank',
                       'content': {'bank'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'centralized': [   {   'canon': 'centralized_exchange',
                           'content': {'exchange'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True},
                       {   'canon': 'centralized_exchange',
                           'content': {'finance'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True},
                       {   'canon': 'centralized_control',
                           'content': {'control'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True},
                       {   'canon': 'centralized_control',
                           'content': {'finance'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True},
                       {   'canon': 'centralized_control',
                           'content': {'financial', 'system'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'coin': [   {   'canon': 'specie_currency',
                    'content': {'money'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'coined': [   {   'canon': 'specie_currency',
                      'content': {'money'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'collateral': [   {   'canon': 'collateral_requirement',
                          'content': {'requirement'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True},
                      {   'canon': 'collateral_liquidation',
                          'content': {'liquidation'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True},
                      {   'canon': 'collateral_liquidation',
                          'content': {'liquidated'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'collateralization': [   {   'canon': 'collateral_requirement',
                                 'content': {'rule'},
                                 'distance': 3,
                                 'forward': True,
                                 'reverse': True},
                             {   'canon': 'collateral_requirement',
                                 'content': {'rules'},
                                 'distance': 3,
                                 'forward': True,
                                 'reverse': True}],
    'collaterialization': [   {   'canon': 'collateral_requirement',
                                  'content': {'threshold'},
                                  'distance': 3,
                                  'forward': True,
                                  'reverse': True}],
    'computationally': [   {   'canon': 'irreversible_transaction',
                               'content': {'reverse', 'impractical'},
                               'distance': 3,
                               'forward': True,
                               'reverse': True}],
    'consensus': [   {   'canon': 'consensus_mechanism',
                         'content': {'mechanism'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True},
                     {   'canon': 'consensus_mechanism',
                         'content': {'protocol'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'cryptocollateralized': [   {   'canon': 'cryptocollateralized_stablecoin',
                                    'content': {'stablecoin'},
                                    'distance': 3,
                                    'forward': True,
                                    'reverse': True}],
    'cryptographic': [   {   'canon': 'cryptographic_scarcity',
                             'content': {'scarcity'},
                             'distance': 3,
                             'forward': True,
                             'reverse': True}],
    'currency': [   {   'canon': 'currency_transfer',
                        'content': {'transfer'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'dai': [   {   'canon': 'dai_savings_rate',
                   'content': {'savings', 'rate'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'dark': [   {   'canon': 'dark_pool_stock_trading',
                    'content': {'pool', 'stock', 'trading'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'data': [   {   'canon': 'data_source',
                    'content': {'source'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'ddos': [   {   'canon': 'denial_of_service',
                    'content': {'attack'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'decentralized': [   {   'canon': 'decentralized_exchange',
                             'content': {'exchange'},
                             'distance': 3,
                             'forward': True,
                             'reverse': True},
                         {   'canon': 'decentralized_organization',
                             'content': {'organization'},
                             'distance': 3,
                             'forward': True,
                             'reverse': True},
                         {   'canon': 'decentralized_application',
                             'content': {'application'},
                             'distance': 3,
                             'forward': True,
                             'reverse': True},
                         {   'canon': 'decentralized_currency',
                             'content': {'currency'},
                             'distance': 3,
                             'forward': True,
                             'reverse': True},
                         {   'canon': 'decentralized_autonomous_organization',
                             'content': {'autonomous', 'organization'},
                             'distance': 3,
                             'forward': True,
                             'reverse': True}],
    'defi': [   {   'canon': 'defi_version_2',
                    'content': {'version', '2'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'defi_version_2',
                    'content': {'v2'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'defi_version_1',
                    'content': {'version', '1'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'defi_version_1',
                    'content': {'v1'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'defi_protocol',
                    'content': {'protocol'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'defi_version_3',
                    'content': {'version', '3'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'defi_version_3',
                    'content': {'v3'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'denial': [   {   'canon': 'denial_of_service',
                      'content': {'service'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'digital': [   {   'canon': 'digital_currency',
                       'content': {'currency'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'digital_yuan',
                       'content': {'yuan'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'digital_yuan',
                       'content': {'electronic', 'currency', 'payment'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'digital_yuan',
                       'content': {'reminbi'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'digital_currency_group',
                       'content': {'group', 'currency'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'digital_asset',
                       'content': {'asset'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'distributed': [   {   'canon': 'distributed_ledger',
                           'content': {'ledger'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True},
                       {   'canon': 'distributed_ledger',
                           'content': {'database'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'double': [   {   'canon': 'double_spend',
                      'content': {'spend'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'double_spend',
                      'content': {'spending'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'double_spend',
                      'content': {'spending', 'problem'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'electronic': [   {   'canon': 'digital_currency',
                          'content': {'cash'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'empty': [   {   'canon': 'empty_set_dollar',
                     'content': {'dollar', 'set'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'equal': [   {   'canon': 'equality_of_opportunity',
                     'content': {'opportunity'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'equality': [   {   'canon': 'equality_of_opportunity',
                        'content': {'opportunity'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'erc': [   {   'canon': 'erc_20',
                   'content': {'20'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'erc-20': [   {   'canon': 'erc_20',
                      'content': {'standard', 'token'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'escrow': [   {   'canon': 'escrow_mechanism',
                      'content': {'mechanism'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'esd': [   {   'canon': 'esd_governance',
                   'content': {'governance'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'ethereum': [   {   'canon': 'ethereum_virtual_machine',
                        'content': {'machine', 'virtual'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'excessive': [   {   'canon': 'excessive_volatility',
                         'content': {'volatility'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'exchange': [   {   'canon': 'exchange_medium',
                        'content': {'medium'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'exchange_rate',
                        'content': {'rate'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'externally': [   {   'canon': 'externally_owned_account',
                          'content': {'owned', 'account'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'fault': [   {   'canon': 'fault_tolerant',
                     'content': {'tolerant'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'fault_tolerant',
                     'content': {'tolerance'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'fiat': [   {   'canon': 'fiat_collaterialized',
                    'content': {'collaterialized'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'fiat_currency',
                    'content': {'currency'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'financial': [   {   'canon': 'financial_system',
                         'content': {'system'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True},
                     {   'canon': 'financial_censorship',
                         'content': {'censorship'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True},
                     {   'canon': 'financial_infrastructure',
                         'content': {'infrastructure'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True},
                     {   'canon': 'financial_primitive',
                         'content': {'primitive'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'fixed': [   {   'canon': 'fixed_exchange_rate',
                     'content': {'exchange', 'rate'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'float': [   {   'canon': 'float_protocol',
                     'content': {'protocol'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'founding': [   {   'canon': 'founding_team',
                        'content': {'team'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'fractional': [   {   'canon': 'fractional_stablecoin',
                          'content': {'stablecoin'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True},
                      {   'canon': 'fractional_algorithm_stablecoin',
                          'content': {'stablecoin', 'algorithm'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'funding': [   {   'canon': 'funding_mechanism',
                       'content': {'mechanism'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'fungible': [   {   'canon': 'fungible_token',
                        'content': {'token'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'gas': [   {   'canon': 'gas_fee',
                   'content': {'fee'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'global': [   {   'canon': 'global_access',
                      'content': {'access'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'gold': [   {   'canon': 'gold_standard',
                    'content': {'standard'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'government': [   {   'canon': 'government_agency',
                          'content': {'agency'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'green': [   {   'canon': 'paper_currency',
                     'content': {'backs'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'immutable': [   {   'canon': 'immutable_ledger',
                         'content': {'ledger'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'impractical': [   {   'canon': 'irreversible_transaction',
                           'content': {'reverse'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'in': [   {   'canon': 'specie_currency',
                  'content': {'speciē'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True},
              {   'canon': 'specie_currency',
                  'content': {'currency', 'kind'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    'incented': [   {   'canon': 'incentive_mechanism',
                        'content': {'action'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'incentive': [   {   'canon': 'incentive_mechanism',
                         'content': {'mechanism'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'incentivization': [   {   'canon': 'incentive_mechanism',
                               'content': {'mechanism'},
                               'distance': 3,
                               'forward': True,
                               'reverse': True}],
    'inequality': [   {   'canon': 'inequality_of_opportunity',
                          'content': {'opportunity'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'inflation': [   {   'canon': 'inflation_hedge',
                         'content': {'hedge'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'input': [   {   'canon': 'input_utxo',
                     'content': {'utxo'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'input_utxo',
                     'content': {'uxto'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'insured': [   {   'canon': 'insured_deposit',
                       'content': {'deposit'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'intangible': [   {   'canon': 'intangible_value',
                          'content': {'value'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'internet': [   {   'canon': 'internet_of_bodies',
                        'content': {'bodies'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'internet_of_things',
                        'content': {'things'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'internet_of_money',
                        'content': {'money'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'ireversible': [   {   'canon': 'irreversible_transaction',
                           'content': {'transaction'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'irreversible': [   {   'canon': 'irreversible_transaction',
                            'content': {'transaction'},
                            'distance': 3,
                            'forward': True,
                            'reverse': True}],
    'lack': [   {   'canon': 'lack_of_access',
                    'content': {'access'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'lack_of_interoperability',
                    'content': {'interoperability'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'legal': [   {   'canon': 'sovereign_currency',
                     'content': {'tender'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'limited': [   {   'canon': 'limited_access',
                       'content': {'access'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'limited_supply',
                       'content': {'supply'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'linear': [   {   'canon': 'linear_bonding_curve',
                      'content': {'bonding', 'curve'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'linear_function',
                      'content': {'function'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'liquidate': [   {   'canon': 'collateral_liquidation',
                         'content': {'collateral'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'long': [   {   'canon': 'long_term',
                    'content': {'term'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'long_term',
                    'content': {'term', 'horizon'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'malicious': [   {   'canon': 'malicious_transaction',
                         'content': {'transaction'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True},
                     {   'canon': 'malicious_action',
                         'content': {'action'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True},
                     {   'canon': 'malicious_action',
                         'content': {'task', 'computational'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True},
                     {   'canon': 'malicious_action',
                         'content': {'task'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True},
                     {   'canon': 'malicious_action',
                         'content': {'behavior'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'market': [   {   'canon': 'market_exchange',
                      'content': {'exchange'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'medium': [   {   'canon': 'exchange_medium',
                      'content': {'exchange'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'mined': [   {   'canon': 'block_mine',
                     'content': {'block', 'first'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'miner': [   {   'canon': 'miner_fee',
                     'content': {'fee'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'miners': [   {   'canon': 'miner_fee',
                      'content': {'fee'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'monetary': [   {   'canon': 'financial_system',
                        'content': {'system'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'money': [   {   'canon': 'specie_currency',
                     'content': {'coin'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'monotonical': [   {   'canon': 'monotonical_increase',
                           'content': {'increase'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'monotonically': [   {   'canon': 'monotonical_increase',
                             'content': {'increasing'},
                             'distance': 3,
                             'forward': True,
                             'reverse': True}],
    'mutable': [   {   'canon': 'mutable_ledger',
                       'content': {'ledger'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'non': [   {   'canon': 'irreversible_transaction',
                   'content': {'transaction', 'reversible'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'non_physical_transfer',
                   'content': {'transfer', 'physical'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'nonreversible': [   {   'canon': 'irreversible_transaction',
                             'content': {'transaction'},
                             'distance': 3,
                             'forward': True,
                             'reverse': True}],
    'on': [   {   'canon': 'on_chain_governance',
                  'content': {'chain', 'governance'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    'on-chain': [   {   'canon': 'on_chain_governance',
                        'content': {'governance'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'output': [   {   'canon': 'output_utxo',
                      'content': {'utxo'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'output_utxo',
                      'content': {'uxto'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'p2p': [   {   'canon': 'peer_to_peer_network',
                   'content': {'network'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'peer_to_peer_node',
                   'content': {'node'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'peer_to_peer_network_protocol',
                   'content': {'protocol'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'peer_to_peer_network_protocol',
                   'content': {'network', 'protocol'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'paper': [   {   'canon': 'paper_currency',
                     'content': {'currency'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'paper_currency',
                     'content': {'money'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'payment': [   {   'canon': 'payment_system',
                       'content': {'system'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'peer': [   {   'canon': 'peer_to_peer_network',
                    'content': {'peer', 'network'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'peer_to_peer_network',
                    'content': {'peer'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'peer_to_peer_network',
                    'content': {'peer', '2'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'peer_to_peer_node',
                    'content': {'node', 'peer'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'peer_to_peer_network_protocol',
                    'content': {'protocol', 'peer', 'network'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'peer_to_peer_network_protocol',
                    'content': {'peer', 'protocol'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'peer2peer': [   {   'canon': 'peer_to_peer_network',
                         'content': {'network'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'physical': [   {   'canon': 'physical_transfer',
                        'content': {'transfer'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'precious': [   {   'canon': 'precious_metal',
                        'content': {'metal'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'private': [   {   'canon': 'private_agency',
                       'content': {'agency'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'proof': [   {   'canon': 'proof_of_work',
                     'content': {'work'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'proof_of_stake',
                     'content': {'stake'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'proto': [   {   'canon': 'proto_coinage',
                     'content': {'coinage'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'protocol': [   {   'canon': 'protocol_governance',
                        'content': {'governance'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'protocol_controlled_value',
                        'content': {'controlled', 'value'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'public': [   {   'canon': 'public_agency',
                      'content': {'agency'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'research': [   {   'canon': 'research_company',
                        'content': {'company'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'reserve': [   {   'canon': 'reserve_currency',
                       'content': {'currency'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'reward': [   {   'canon': 'incentive_mechanism',
                      'content': {'actor'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'ring': [   {   'canon': 'ring_money',
                    'content': {'money'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'risk': [   {   'canon': 'risk_factor',
                    'content': {'factor'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'short': [   {   'canon': 'short_term',
                     'content': {'term'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'short_term',
                     'content': {'term', 'horizon'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'simple': [   {   'canon': 'linear_function',
                      'content': {'linear', 'function'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'slashing': [   {   'canon': 'slashing_condition',
                        'content': {'condition'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'slashing_condition',
                        'content': {'mechanism'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'smart': [   {   'canon': 'smart_contract',
                     'content': {'contract'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'software': [   {   'canon': 'software_protocol',
                        'content': {'protocol'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'sovereign': [   {   'canon': 'sovereign_currency',
                         'content': {'currency'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'specie': [   {   'canon': 'specie_currency',
                      'content': {'currency'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'stablecoin': [   {   'canon': 'stablecoin_protocol',
                          'content': {'protocol'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'standard': [   {   'canon': 'value_standard',
                        'content': {'value'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'stock': [   {   'canon': 'stock_trade',
                     'content': {'trade'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'store': [   {   'canon': 'store_of_wealth',
                     'content': {'wealth'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'super': [   {   'canon': 'super_linear_function',
                     'content': {'linear', 'function'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'superlinear': [   {   'canon': 'super_linear_function',
                           'content': {'function'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'supply': [   {   'canon': 'supply_expansion',
                      'content': {'expansion'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'tangible': [   {   'canon': 'tangible_value',
                        'content': {'value'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'token': [   {   'canon': 'token_standard',
                     'content': {'standard'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'token_swap',
                     'content': {'swap'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'trading': [   {   'canon': 'trading_platform',
                       'content': {'platform'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'traditional': [   {   'canon': 'centralized_control',
                           'content': {'finance'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'transfer': [   {   'canon': 'currency_transfer',
                        'content': {'money'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'currency_transfer',
                        'content': {'currency'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'treasury': [   {   'canon': 'treasury_governance',
                        'content': {'governance'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'trusted': [   {   'canon': 'trusted_actor',
                       'content': {'actor'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'trusted_actor',
                       'content': {'party'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'uncollateralized': [   {   'canon': 'uncollateralized_stablecoin',
                                'content': {'stablecoin'},
                                'distance': 3,
                                'forward': True,
                                'reverse': True}],
    'unequal': [   {   'canon': 'inequality_of_opportunity',
                       'content': {'opportunity'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'universal': [   {   'canon': 'universal_access',
                         'content': {'access'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'unlimited': [   {   'canon': 'universal_access',
                         'content': {'access'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True},
                     {   'canon': 'unlimited_supply',
                         'content': {'supply'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'unspent': [   {   'canon': 'unspent_transaction_output',
                       'content': {'transaction', 'output'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'us': [   {   'canon': 'us_dollar',
                  'content': {'dollar'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    'user': [   {   'canon': 'user_sovereignity',
                    'content': {'sovereignity'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'user_issued_asset',
                    'content': {'issued', 'asset'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'value': [   {   'canon': 'value_standard',
                     'content': {'standard'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'value_transfer',
                     'content': {'transfer'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'virtual': [   {   'canon': 'digital_currency',
                       'content': {'currency'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'virtual_machine',
                       'content': {'machine'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'virtual_machine',
                       'content': {'node\n'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'virtual_transfer',
                       'content': {'transfer'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}]}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
