
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class DefiLookup(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'DefiLookup',
            'filename': 'defi_lookup',
            'files': ['defi.txt'],
            'queries': ['lookup.sparql'],
            'transformers': ['lowercase', 'lookup']},
 'source': 'defi.owl',
 'time': '2022-04-27 21:15:54.590855'}

    __data = {
    1: [   'cryptocollateralization',
           'cryptocollateraliz!',
           'cryptocollateraliz',
           'interoperability',
           'cryptocollateral',
           'disadvantageous',
           'opportunisitic',
           'explainability',
           'infrastructure',
           'cryptocurrency',
           'characteristic',
           'accessibility',
           'opportunities',
           'acceptability',
           'vulnerability',
           'sovereignity',
           'cryptography',
           'advantageous',
           'transparency',
           'unchangeable',
           'incentivized',
           'uncensorable',
           'organization',
           'disadvantage',
           'inefficiency',
           'incentivize',
           'blockchains',
           'stablecoins',
           'deployments',
           'application',
           'opportunity',
           'inefficient',
           'reliability',
           'transaction',
           'liquidators',
           'portability',
           'cryptoasset',
           'defi-native',
           'scalability',
           'uniformity',
           'stablecoin',
           'governance',
           'defrauders',
           'autographs',
           'collateral',
           'inequality',
           'efficiency',
           'increasing',
           'coinshares',
           'explainble',
           'acceptable',
           'monitoring',
           'liquidator',
           'blockchain',
           'changeable',
           'volatility',
           'foundation',
           'currencies',
           'timestamps',
           'incentives',
           'signatures',
           'capability',
           'deployment',
           'greenbacks',
           'vulnerable',
           'expansions',
           'mechanisms',
           'fraudulent',
           'defrauding',
           'robustness',
           'censorship',
           'defrauder',
           'bartering',
           'consensus',
           'increased',
           'verifying',
           'benjamins',
           'greenback',
           'escrowers',
           'inflation',
           'incentive',
           'mechanism',
           'immutable',
           'attribute',
           'autograph',
           'ethererum',
           'disputers',
           'downsides',
           'primitive',
           'durabilty',
           'refinance',
           'insurance',
           'monitored',
           'expansion',
           'liquidity',
           'signature',
           'advantage',
           'arbitrage',
           'escrowing',
           'timestamp',
           'mediating',
           'defrauded',
           'disputing',
           'increases',
           'verifiers',
           'protocols',
           'drawbacks',
           'stability',
           'portable',
           'artifact',
           'payments',
           'transfer',
           'contract',
           'ethereum',
           'verifies',
           'exchange',
           'document',
           'escrowed',
           'increase',
           'coindesk',
           'leverage',
           'disputed',
           'protocol',
           'volatile',
           'escrower',
           'factored',
           'deployed',
           'spending',
           'platform',
           'disputer',
           'auctions',
           'downside',
           'currency',
           'defrauds',
           'disputes',
           'monitors',
           'accounts',
           'security',
           'cashless',
           'scalable',
           'scarcity',
           'mediated',
           'equality',
           'drawback',
           'reliable',
           'solution',
           'internet',
           'coinbase',
           'mediates',
           'artefact',
           'verifier',
           'position',
           'standard',
           'bartered',
           'deploys',
           'privacy',
           'payment',
           'finance',
           'deposit',
           'bullion',
           'dispute',
           'erc-721',
           'frauded',
           'durable',
           'bitcoin',
           'factors',
           'council',
           'upsides',
           'opacity',
           'defraud',
           'escrows',
           'mediate',
           'uniform',
           'lending',
           'reminbi',
           'verfied',
           'storage',
           'monitor',
           'ability',
           'auction',
           'control',
           'barters',
           'costing',
           'trading',
           'company',
           'mutable',
           'economy',
           'account',
           'jewelry',
           'system',
           'agency',
           'opaque',
           'silver',
           'dollar',
           'barter',
           'oracle',
           'tasked',
           'tradfi',
           'trades',
           'actors',
           'factor',
           'frauds',
           'supply',
           'deploy',
           'ingots',
           'paypal',
           'erc-20',
           'medium',
           'costed',
           'verify',
           'ledger',
           'stable',
           'robust',
           'token\n',
           'policy',
           'escrow',
           'action',
           'upside',
           'spends',
           'access',
           'miners',
           'monies',
           'crypto',
           'minors',
           'metal',
           'actor',
           'tasks',
           'money',
           'teams',
           'fraud',
           'ingot',
           'mined',
           'spent',
           'state',
           'trade',
           'value',
           'zelle',
           'asset',
           'nonce',
           'minor',
           'token',
           'miner',
           'loans',
           'ether',
           'bonus',
           'spend',
           'cons',
           'rate',
           'team',
           'cash',
           'euro',
           'gold',
           'defi',
           'cost',
           'utxo',
           'mine',
           'yuan',
           'dapp',
           'loan',
           'risk',
           'ddos',
           'bank',
           'task',
           'dcep',
           'iot',
           'sec',
           'fee',
           'pcv',
           'iom',
           'btc',
           'evm',
           'dao',
           'dsr',
           'usd',
           'dex',
           'eth',
           'eoa',
           'p2p',
           'iob',
           'nft',
           'cad'],
    2: [   'decentralized_autonomous organization',
           'digital_currency_electronic payment',
           'fractional_algorithm stablecoin',
           'cryptocollateralized stablecoin',
           'candidate_consensus mechanism',
           'malicious_computational task',
           'centralized_financial system',
           'collateral_can_be liquidated',
           'collaterialization threshold',
           'asymmetric_key cryptography',
           'uncollateralized stablecoin',
           'non_reversible transaction',
           'unspent_transaction output',
           'decentralized organization',
           'decentralized application',
           'incentivization mechanism',
           'nonreversible transaction',
           'blockchain_based contract',
           'protocol_controlled value',
           'irreversible transaction',
           'externally_owned account',
           'financial infrastructure',
           'monotonically increasing',
           'ethereum_virtual machine',
           'double_spending problem',
           'collateralization rules',
           'autonomous organization',
           'ireversible transaction',
           'anonymous_founding team',
           'dark_pool_stock trading',
           'collateral requirement',
           'simple_linear function',
           'decentralized currency',
           'collateral liquidation',
           'decentralized exchange',
           'algorithmic stablecoin',
           'digital_currency group',
           'cryptographic scarcity',
           'collateralization rule',
           'super_linear function',
           'blockchain technology',
           'mined_its_first block',
           'malicious transaction',
           'fractional stablecoin',
           'erc-20_token standard',
           'non_physical transfer',
           'autonomous monitoring',
           'decentralized finance',
           'financial censorship',
           'superlinear function',
           'excessive volatility',
           'censorship resistant',
           'fiat collaterialized',
           'centralized exchange',
           'p2p_network protocol',
           'monotonical increase',
           'linear_bonding curve',
           'distributed database',
           'liquidate collateral',
           'traditional finance',
           'centralized finance',
           'cryptographic nonce',
           'centralized control',
           'financial primitive',
           'incentive mechanism',
           'blockchain contract',
           'stablecoin protocol',
           'protocol governance',
           'governance platform',
           'on-chain governance',
           'on_chain governance',
           'solving_the problem',
           'fixed_exchange rate',
           'consensus mechanism',
           'unequal opportunity',
           'treasury governance',
           'non_fungible token',
           'short_term horizon',
           'slashing mechanism',
           'sovereign currency',
           'consensus protocol',
           'collateral backing',
           'slashing condition',
           'bitcoin foundation',
           'distributed ledger',
           'malicious behavior',
           'funding mechanism',
           'user sovereignity',
           'currency transfer',
           'solving_a problem',
           'peer2peer network',
           'software protocol',
           'government agency',
           'user_issued asset',
           'physical transfer',
           'long_term horizon',
           'equal opportunity',
           'digital currency',
           'unlimited access',
           'immutable ledger',
           'intangible value',
           'empty_set dollar',
           'reserve currency',
           'virtual transfer',
           'solving problems',
           'virtual currency',
           'trading platform',
           'receives_a bonus',
           'malicious action',
           'dai_savings rate',
           'unlimited supply',
           'number_used once',
           'escrow mechanism',
           'in_kind currency',
           'financial system',
           'universal access',
           'supply expansion',
           'research company',
           'banking platform',
           'virtual machine',
           'problem solving',
           'digital reminbi',
           'inflation hedge',
           'exchange medium',
           'market exchange',
           'linear function',
           'canadian dollar',
           'crypto currency',
           'receive_a bonus',
           'electronic cash',
           'fault tolerance',
           'specie currency',
           'double spending',
           'insured deposit',
           'monetary system',
           'incented action',
           'limited access',
           'float protocol',
           'limited supply',
           'fault tolerant',
           'banking system',
           'defi_version 3',
           'malicious task',
           'esd governance',
           'defi_version 2',
           'asset transfer',
           'refinance loan',
           'bonding curves',
           'private agency',
           'paper currency',
           'smart contract',
           'token standard',
           'tangible value',
           'defi_version 1',
           'mutable ledger',
           'precious metal',
           'world computer',
           'value transfer',
           'payment system',
           'value standard',
           'fungible token',
           'proto coinage',
           'money_in coin',
           'trusted party',
           'public agency',
           'defi protocol',
           'bonding curve',
           'digital asset',
           'gold standard',
           'exchange rate',
           'asic hardware',
           'trusted actor',
           'founding team',
           'global access',
           'fiat currency',
           'virtual node\n',
           'double spend',
           'legal tender',
           'central bank',
           'cash economy',
           'coined money',
           'digital yuan',
           'crypto asset',
           'reward actor',
           'block chains',
           'in_the block',
           'p2p protocol',
           'number once',
           'has changed',
           'output uxto',
           'risk factor',
           'p2p network',
           'stock trade',
           'will change',
           'peer_2 peer',
           'green backs',
           'time stamps',
           'data source',
           'ddos attack',
           'block chain',
           'output utxo',
           'paper money',
           'ring money',
           'down sides',
           'short term',
           'can change',
           'basis cash',
           'input uxto',
           'block mine',
           'input utxo',
           'time stamp',
           'miners fee',
           'bank notes',
           'in_a block',
           'coin money',
           'token swap',
           'bank note',
           'miner fee',
           'in speciē',
           'down side',
           'us dollar',
           'base rate',
           'long term',
           'p2p node',
           'up sides',
           'up side',
           'defi v1',
           'gas fee',
           'erc 721',
           'defi v2',
           'defi v3',
           'erc 20'],
    3: [   'decentralized autonomous organization',
           'fractional algorithm stablecoin',
           'candidate consensus mechanism',
           'malicious computational task',
           'centralized financial system',
           'asymmetric key cryptography',
           'unspent transaction output',
           'non reversible transaction',
           'protocol controlled value',
           'blockchain based contract',
           'inequality of opportunity',
           'ethereum virtual machine',
           'lack of interoperability',
           'externally owned account',
           'double spending problem',
           'equality of opportunity',
           'anonymous founding team',
           'impractical to reverse',
           'digital currency group',
           'simple linear function',
           'super linear function',
           'non physical transfer',
           'erc-20 token standard',
           'linear bonding curve',
           'transfer of currency',
           'p2p network protocol',
           'on chain governance',
           'fixed exchange rate',
           'solving the problem',
           'short term horizon',
           'internet of bodies',
           'medium of exchange',
           'non fungible token',
           'internet of things',
           'denial of service',
           'solving a problem',
           'long term horizon',
           'transfer of money',
           'internet of money',
           'standard of value',
           'user issued asset',
           'dai savings rate',
           'in kind currency',
           'receives a bonus',
           'empty set dollar',
           'number used once',
           'store of wealth',
           'receive a bonus',
           'proof of stake',
           'lack of access',
           'defi version 1',
           'defi version 3',
           'defi version 2',
           'money in coin',
           'proof of work',
           'in the block',
           'peer to peer',
           'peer 2 peer',
           'in a block'],
    4: [   'computationally impractical to reverse',
           'digital currency electronic payment',
           'collateral can be liquidated',
           'dark pool stock trading',
           'mined its first block',
           'peer to peer protocol',
           'peer to peer network',
           'peer to peer node'],
    5: [   'u.s. securities and exchange commission',
           'peer to peer network protocol'],
    6: []}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
