
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class DefiTrie(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'DefiTrie',
            'filename': 'defi_trie',
            'queries': ['trie.sparql'],
            'transformers': ['lowercase', 'trie']},
 'source': 'defi.owl',
 'time': '2022-04-27 21:15:54.999855'}

    __data = {
    1: [   'interoperability',
           'cryptocollateral',
           'explainability',
           'cryptocurrency',
           'sovereignity',
           'cryptography',
           'transparency',
           'disadvantage',
           'immutability',
           'trustworthy',
           'inefficient',
           'liquidation',
           'transaction',
           'cryptoasset',
           'requirement',
           'predictable',
           'scalability',
           'stablecoin',
           'governance',
           'mutability',
           'inequality',
           'efficiency',
           'mainstream',
           'coinshares',
           'acceptable',
           'liquidator',
           'blockchain',
           'difference',
           'foundation',
           'redundancy',
           'capability',
           'vulnerable',
           'censorship',
           'consensus',
           'inflation',
           'adaptable',
           'immutable',
           'refinance',
           'durabilty',
           'liquidity',
           'signature',
           'advantage',
           'arbitrage',
           'timestamp',
           'redundant',
           'identical',
           'portable',
           'transfer',
           'contract',
           'exchange',
           'document',
           'ethereum',
           'increase',
           'coindesk',
           'leverage',
           'volatile',
           'platform',
           'flexible',
           'currency',
           'investor',
           'function',
           'security',
           'decrease',
           'scarcity',
           'equality',
           'reliable',
           'solution',
           'coinbase',
           'hardware',
           'tolerant',
           'position',
           'standard',
           'creation',
           'balance',
           'payment',
           'deposit',
           'bullion',
           'dispute',
           'erc-721',
           'bitcoin',
           'council',
           'desktop',
           'mediate',
           'uniform',
           'latency',
           'monitor',
           'hashing',
           'company',
           'mutable',
           'problem',
           'account',
           'jewelry',
           'opaque',
           'silver',
           'dollar',
           'barter',
           'oracle',
           'wallet',
           'keeper',
           'deploy',
           'paypal',
           'verify',
           'ledger',
           'stable',
           'robust',
           'server',
           'policy',
           'access',
           'laptop',
           'metal',
           'vault',
           'ratio',
           'niche',
           'trade',
           'value',
           'zelle',
           'asset',
           'stake',
           'nonce',
           'power',
           'trust',
           'miner',
           'bonus',
           'spend',
           'rate',
           'euro',
           'gold',
           'defi',
           'cost',
           'hash',
           'mine',
           'yuan',
           'loss',
           'debt',
           'loan',
           'fund',
           'risk',
           'bank',
           'sec',
           'fee',
           'fei',
           'nft'],
    2: [   'cryptocollateralized',
           'uncollaterialized',
           'collateralization',
           'uncollateralized',
           'overcollaterized',
           'cryptocurrency',
           'collateralized',
           'computational',
           'cryptographic',
           'decentralized',
           'counterparty',
           'programmable',
           'irreversible',
           'impermanent',
           'monotonical',
           'transaction',
           'distributed',
           'algorithmic',
           'centralized',
           'foreclosure',
           'stablecoin',
           'collateral',
           'fractional',
           'blockchain',
           'reversible',
           'intangible',
           'predefined',
           'electronic',
           'autonomous',
           'government',
           'censorship',
           'permanent',
           'consensus',
           'inflation',
           'incentive',
           'immutable',
           'timestamp',
           'excessive',
           'sovereign',
           'malicious',
           'computing',
           'universal',
           'untrusted',
           'financial',
           'synthetic',
           'stability',
           'unlimited',
           'interest',
           'contract',
           'exchange',
           'ethereum',
           'physical',
           'protocol',
           'attacker',
           'positive',
           'fungible',
           'treasury',
           'external',
           'precious',
           'slashing',
           'currency',
           'research',
           'complete',
           'canadian',
           'software',
           'negative',
           'founding',
           'tangible',
           'duration',
           'payment',
           'trusted',
           'staking',
           'bitcoin',
           'private',
           'banking',
           'reserve',
           'invalid',
           'insured',
           'funding',
           'virtual',
           'limited',
           'central',
           'digital',
           'bonding',
           'network',
           'trading',
           'hashing',
           'mutable',
           'partial',
           'system',
           'online',
           'market',
           'keeper',
           'supply',
           'double',
           'server',
           'specie',
           'public',
           'escrow',
           'voting',
           'energy',
           'output',
           'global',
           'random',
           'linear',
           'staked',
           'direct',
           'block',
           'paper',
           'vault',
           'basis',
           'fault',
           'third',
           'smart',
           'value',
           'input',
           'early',
           'proto',
           'valid',
           'asset',
           'token',
           'trust',
           'miner',
           'short',
           'flash',
           'float',
           'stock',
           'cash',
           'zero',
           'ring',
           'gold',
           'fiat',
           'defi',
           'asic',
           'base',
           'debt',
           'long',
           'user',
           'risk',
           'peer',
           'data',
           'esd',
           'erc',
           'gas',
           'us'],
    3: [   'cryptographic',
           'decentralized',
           'distributed',
           'fractional',
           'externally',
           'electronic',
           'collective',
           'inequality',
           'asymmetric',
           'anonymous',
           'internet',
           'positive',
           'ethereum',
           'negative',
           'logistic',
           'protocol',
           'variable',
           'equality',
           'trusted',
           'unspent',
           'digital',
           'sigmoid',
           'denial',
           'linear',
           'empty',
           'store',
           'fixed',
           'proof',
           'super',
           'smart',
           'semi',
           'defi',
           'zero',
           'lack',
           'user',
           'pro',
           'non',
           'dai',
           'on'],
    4: ['delegated', 'super', 'proof', 'peer', 'dark'],
    5: ['peer'],
    6: ['peer']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
