
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class DefiSynonyms(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'DefiSynonyms',
            'filename': 'defi_synonyms',
            'files': ['defi.txt'],
            'queries': ['synonyms.sparql'],
            'reverse': True,
            'transformers': ['lowercase', 'synonyms']},
 'source': 'defi.owl',
 'time': '2022-04-27 21:15:54.946855'}

    __data = {
    'acceptable': ['acceptability', 'acceptable'],
    'access': ['accessibility', 'access'],
    'account': ['accounts'],
    'action': ['tasked', 'action', 'tasks', 'task'],
    'actor': ['actors', 'actor'],
    'advantage': ['advantageous', 'up sides', 'upsides', 'up side', 'upside'],
    'agency': ['agency'],
    'algorithmic_stablecoin': ['algorithmic stablecoin'],
    'anonymous_founding_team': ['anonymous founding team'],
    'application': ['application'],
    'arbitrage': ['arbitrage'],
    'artefact': ['artifact', 'artefact'],
    'asic_hardware': ['asic hardware'],
    'asset': ['asset'],
    'asset_transfer': ['asset transfer'],
    'asymmetric_key_cryptography': ['asymmetric key cryptography'],
    'attribute': ['characteristic', 'attribute'],
    'auction': ['auctions'],
    'autonomous_monitoring': ['autonomous monitoring'],
    'autonomous_organization': ['autonomous organization'],
    'bank': ['bank'],
    'banking_platform': ['banking platform'],
    'banking_system': ['banking system'],
    'barter': ['peer to peer', 'bartering', 'bartered', 'barters', 'barter'],
    'base_rate': ['base rate'],
    'basis_cash': ['basis cash'],
    'bitcoin': ['bitcoin', 'btc'],
    'bitcoin_foundation': ['bitcoin foundation'],
    'block_mine': ['mined its first block', 'block mine'],
    'blockchain': [   'blockchain technology',
                      'in the block',
                      'block chains',
                      'blockchains',
                      'block chain',
                      'in a block',
                      'blockchain'],
    'blockchain_contract': ['blockchain based contract', 'blockchain contract'],
    'bonding_curve': ['bonding curves', 'bonding curve'],
    'bonus': ['receives a bonus', 'receive a bonus'],
    'bullion': ['bullion'],
    'canadian_dollar': ['canadian dollar', 'cad'],
    'capability': ['capability', 'ability'],
    'cash_economy': ['cash economy'],
    'censorship': ['censorship'],
    'censorship_resistant': ['uncensorable'],
    'central_bank': ['central bank'],
    'centralized_control': [   'centralized financial system',
                               'centralized finance',
                               'traditional finance',
                               'centralized control',
                               'tradfi'],
    'centralized_exchange': ['centralized exchange', 'centralized finance'],
    'coinbase': ['coinbase'],
    'coindesk': ['coindesk'],
    'coinshares': ['coinshares'],
    'collateral': ['collateral backing', 'collateral'],
    'collateral_liquidation': [   'collateral can be liquidated',
                                  'collateral liquidation',
                                  'liquidate collateral'],
    'collateral_requirement': [   'collaterialization threshold',
                                  'collateralization rules',
                                  'collateralization rule'],
    'company': ['company'],
    'consensus': ['consensus'],
    'consensus_mechanism': [   'candidate consensus mechanism',
                               'consensus mechanism',
                               'consensus protocol'],
    'contract': ['contract'],
    'council': ['council'],
    'cryptoasset': ['crypto asset'],
    'cryptocollateral': [   'cryptocollateralization',
                            'cryptocollateraliz!',
                            'cryptocollateraliz',
                            'cryptocollateral'],
    'cryptocollateralized_stablecoin': ['cryptocollateralized stablecoin'],
    'cryptocurrency': ['crypto currency', 'cryptocurrency', 'crypto'],
    'cryptographic_scarcity': ['cryptographic scarcity'],
    'cryptography': ['cryptography'],
    'currency': ['currencies', 'currency', 'monies', 'money'],
    'currency_transfer': [   'transfer of currency',
                             'transfer of money',
                             'currency transfer'],
    'dai_savings_rate': ['dai savings rate', 'dsr'],
    'dark_pool_stock_trading': ['dark pool stock trading'],
    'data_source': ['data source'],
    'decentralized_application': ['decentralized application', 'dapp'],
    'decentralized_autonomous_organization': [   'decentralized autonomous '
                                                 'organization',
                                                 'dao'],
    'decentralized_currency': ['decentralized currency'],
    'decentralized_exchange': ['decentralized exchange', 'dex'],
    'decentralized_organization': ['decentralized organization'],
    'defi': ['decentralized finance', 'defi-native', 'defi'],
    'defi_protocol': ['defi protocol'],
    'defi_version_1': ['defi version 1', 'defi v1'],
    'defi_version_2': ['defi version 2', 'defi v2'],
    'defi_version_3': ['defi version 3', 'defi v3'],
    'denial_of_service': ['ddos attack', 'ddos'],
    'deploy': ['deployments', 'deployment', 'deployed', 'deploys'],
    'deposit': ['deposit'],
    'digital_asset': ['digital asset'],
    'digital_currency': [   'digital currency',
                            'virtual currency',
                            'electronic cash',
                            'cashless'],
    'digital_currency_group': ['digital currency group'],
    'digital_yuan': [   'digital currency electronic payment',
                        'digital reminbi',
                        'dcep'],
    'disadvantage': [   'disadvantageous',
                        'down sides',
                        'down side',
                        'drawbacks',
                        'downsides',
                        'drawback',
                        'downside',
                        'cons'],
    'dispute': ['disputing', 'disputers', 'disputer', 'disputes', 'disputed'],
    'distributed_ledger': ['distributed database'],
    'document': ['document'],
    'dollar': ['dollar'],
    'double_spend': ['double spending problem', 'double spending'],
    'durabilty': ['durabilty', 'durable'],
    'economy': ['economy'],
    'efficiency': ['efficiency'],
    'empty_set_dollar': ['empty set dollar'],
    'equality': ['equality'],
    'equality_of_opportunity': ['equality of opportunity', 'equal opportunity'],
    'erc-721': ['erc-721', 'erc 721'],
    'erc_20': ['erc-20 token standard', 'erc-20', 'erc 20'],
    'escrow_mechanism': [   'escrowers',
                            'escrowing',
                            'escrowed',
                            'escrower',
                            'escrows',
                            'escrow'],
    'esd_governance': ['esd governance'],
    'ethereum': ['world computer', 'ethererum', 'ethereum', 'ether', 'eth'],
    'ethereum_virtual_machine': ['evm'],
    'euro': ['euro'],
    'excessive_volatility': ['excessive volatility'],
    'exchange': ['exchange'],
    'exchange_medium': ['medium of exchange', 'exchange medium'],
    'exchange_rate': ['exchange rate'],
    'expansion': ['expansions', 'expansion'],
    'explainability': ['explainability', 'explainble'],
    'externally_owned_account': ['eoa'],
    'factor': ['factored', 'factors'],
    'fault_tolerant': ['fault tolerance'],
    'fee': ['costing', 'costed', 'cost', 'fee'],
    'fiat_collaterialized': ['fiat collaterialized'],
    'fiat_currency': ['fiat currency'],
    'finance': ['finance'],
    'financial_censorship': ['financial censorship'],
    'financial_infrastructure': ['financial infrastructure'],
    'financial_primitive': ['financial primitive'],
    'financial_system': ['financial system', 'monetary system'],
    'fixed_exchange_rate': ['fixed exchange rate'],
    'float_protocol': ['float protocol'],
    'foundation': ['foundation'],
    'founding_team': ['founding team'],
    'fractional_algorithm_stablecoin': ['fractional algorithm stablecoin'],
    'fractional_stablecoin': ['fractional stablecoin'],
    'funding_mechanism': ['funding mechanism'],
    'fungible_token': ['fungible token'],
    'gas_fee': ['gas fee'],
    'global_access': ['global access'],
    'gold': ['gold'],
    'gold_standard': ['gold standard'],
    'governance': ['governance platform', 'governance', 'control'],
    'government_agency': ['government agency'],
    'immutable': ['unchangeable'],
    'immutable_ledger': ['immutable ledger'],
    'incentive_mechanism': [   'incentivization mechanism',
                               'incentive mechanism',
                               'incented action',
                               'reward actor',
                               'incentivized',
                               'incentivize',
                               'incentives',
                               'incentive'],
    'increase': ['increasing', 'increases', 'increased'],
    'inefficient': ['inefficiency', 'inefficient'],
    'inequality': ['inequality'],
    'inequality_of_opportunity': [   'inequality of opportunity',
                                     'unequal opportunity'],
    'inflation': ['inflation'],
    'inflation_hedge': ['inflation hedge'],
    'infrastructure': ['infrastructure'],
    'input_utxo': ['input uxto'],
    'insurance': ['insurance'],
    'insured_deposit': ['insured deposit'],
    'intangible_value': ['intangible value'],
    'internet': ['internet'],
    'internet_of_bodies': ['internet of bodies', 'iob'],
    'internet_of_money': ['internet of money', 'iom'],
    'internet_of_things': ['internet of things', 'iot'],
    'interoperability': ['interoperability'],
    'irreversible_transaction': [   'computationally impractical to reverse',
                                    'non reversible transaction',
                                    'nonreversible transaction',
                                    'ireversible transaction',
                                    'impractical to reverse'],
    'jewelry': ['jewelry'],
    'lack_of_access': ['lack of access'],
    'lack_of_interoperability': ['lack of interoperability'],
    'ledger': ['ledger'],
    'leverage': ['leverage'],
    'limited_access': ['limited access'],
    'limited_supply': ['limited supply'],
    'linear_bonding_curve': ['linear bonding curve'],
    'linear_function': ['simple linear function'],
    'liquidator': ['liquidators'],
    'liquidity': ['liquidity'],
    'loan': ['lending', 'loans'],
    'long_term': ['long term horizon', 'long term'],
    'malicious_action': [   'malicious computational task',
                            'malicious behavior',
                            'malicious action',
                            'malicious task',
                            'fraudulent',
                            'defrauding',
                            'defrauders',
                            'defrauded',
                            'defrauder',
                            'defrauds',
                            'defraud',
                            'frauded',
                            'frauds',
                            'fraud'],
    'malicious_transaction': ['malicious transaction'],
    'market_exchange': ['market exchange'],
    'mechanism': ['mechanisms', 'mechanism'],
    'mediate': ['mediating', 'mediated', 'mediates'],
    'medium': ['medium'],
    'metal': ['ingots', 'metal', 'ingot'],
    'mine': ['mined', 'mine'],
    'miner': ['minors', 'miners', 'minor'],
    'miner_fee': ['miners fee'],
    'monitor': ['monitoring', 'monitored', 'monitors', 'monitor'],
    'monotonical_increase': ['monotonically increasing'],
    'mutable': ['will change', 'has changed', 'can change', 'changeable'],
    'mutable_ledger': ['mutable ledger'],
    'nft': ['non fungible token', 'nft'],
    'non_physical_transfer': ['non physical transfer'],
    'nonce': ['cryptographic nonce', 'number used once', 'number once'],
    'on_chain_governance': ['on-chain governance', 'on chain governance'],
    'opaque': ['opacity', 'opaque'],
    'opportunity': ['opportunisitic', 'opportunities', 'opportunity'],
    'oracle': ['oracle'],
    'organization': ['organization'],
    'output_utxo': ['output uxto'],
    'paper_currency': [   'paper currency',
                          'paper money',
                          'green backs',
                          'greenbacks',
                          'bank notes',
                          'bank note',
                          'benjamins',
                          'greenback',
                          'cash'],
    'payment': ['payments'],
    'payment_system': ['payment system'],
    'paypal': ['paypal'],
    'peer_to_peer_network': [   'peer2peer network',
                                'peer to peer',
                                'peer 2 peer',
                                'p2p network',
                                'p2p'],
    'peer_to_peer_network_protocol': [   'peer to peer protocol',
                                         'p2p network protocol',
                                         'p2p protocol'],
    'peer_to_peer_node': ['p2p node'],
    'physical_transfer': ['physical transfer'],
    'platform': ['platform'],
    'policy': ['policy'],
    'portable': ['portability', 'portable'],
    'position': ['position'],
    'precious_metal': ['precious metal'],
    'primitive': ['primitive'],
    'privacy': ['privacy'],
    'private_agency': ['private agency'],
    'proof_of_stake': ['proof of stake'],
    'proof_of_work': ['proof of work'],
    'proto_coinage': ['proto coinage'],
    'protocol': ['protocols', 'protocol'],
    'protocol_controlled_value': ['protocol controlled value', 'pcv'],
    'protocol_governance': ['protocol governance'],
    'public_agency': ['public agency'],
    'rate': ['rate'],
    'refinance': ['refinance loan'],
    'reliable': ['reliability'],
    'research_company': ['research company'],
    'reserve_currency': ['reserve currency'],
    'ring_money': ['ring money'],
    'risk': ['risk'],
    'risk_factor': ['risk factor'],
    'robust': ['robustness'],
    'scalability': ['scalability', 'scalable'],
    'scarcity': ['scarcity'],
    'sec': ['u.s. securities and exchange commission', 'sec'],
    'security': ['security'],
    'short_term': ['short term horizon', 'short term'],
    'signature': ['autographs', 'signatures', 'autograph'],
    'silver': ['silver'],
    'slashing_condition': ['slashing mechanism'],
    'smart_contract': ['smart contract'],
    'software_protocol': ['software protocol'],
    'solution': [   'solving the problem',
                    'solving a problem',
                    'solving problems',
                    'problem solving'],
    'sovereign_currency': ['sovereign currency', 'legal tender'],
    'sovereignity': ['sovereignity'],
    'specie_currency': [   'in kind currency',
                           'specie currency',
                           'money in coin',
                           'coined money',
                           'coin money',
                           'in speciē'],
    'spend': ['spending', 'spends', 'spent'],
    'stable': ['stability', 'stable'],
    'stablecoin': ['stablecoins', 'stablecoin'],
    'stablecoin_protocol': ['stablecoin protocol'],
    'standard': ['standard'],
    'state': ['state'],
    'stock_trade': ['stock trade'],
    'storage': ['storage'],
    'store_of_wealth': ['store of wealth'],
    'super_linear_function': ['superlinear function'],
    'supply': ['supply'],
    'supply_expansion': ['supply expansion'],
    'system': ['control', 'system'],
    'tangible_value': ['tangible value'],
    'team': ['teams', 'team'],
    'timestamp': ['time stamps', 'time stamp', 'timestamps'],
    'token': ['token\n'],
    'token_standard': ['token standard'],
    'token_swap': ['token swap'],
    'trade': ['trading', 'trades', 'trade'],
    'trading_platform': ['trading platform'],
    'transaction': ['transaction'],
    'transfer': ['transfer'],
    'transparency': ['transparency'],
    'treasury_governance': ['treasury governance'],
    'trusted_actor': ['trusted party'],
    'uncollateralized_stablecoin': ['uncollateralized stablecoin'],
    'uniform': ['uniformity', 'uniform'],
    'universal_access': ['universal access', 'unlimited access'],
    'unlimited_supply': ['unlimited supply'],
    'unspent_transaction_output': ['utxo'],
    'us_dollar': ['us dollar', 'usd'],
    'user_issued_asset': ['user issued asset'],
    'user_sovereignity': ['user sovereignity'],
    'value': ['value'],
    'value_standard': ['standard of value', 'value standard'],
    'value_transfer': ['value transfer'],
    'verify': ['verifying', 'verifiers', 'verifier', 'verifies', 'verfied'],
    'virtual_machine': ['virtual node\n'],
    'virtual_transfer': ['virtual transfer'],
    'volatile': ['volatility', 'volatile'],
    'vulnerable': ['vulnerability'],
    'yuan': ['reminbi'],
    'zelle': ['zelle']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
