
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class DefiSynonymsRev(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'DefiSynonyms',
            'filename': 'defi_synonyms',
            'files': ['defi.txt'],
            'queries': ['synonyms.sparql'],
            'reverse': True,
            'transformers': ['lowercase', 'synonyms']},
 'source': 'defi.owl',
 'time': '2022-04-27 21:15:54.951855'}

    __data = {
    'ability': ['capability'],
    'acceptability': ['acceptable'],
    'acceptable': ['acceptable'],
    'access': ['access'],
    'accessibility': ['access'],
    'accounts': ['account'],
    'action': ['action'],
    'actor': ['actor'],
    'actors': ['actor'],
    'advantageous': ['advantage'],
    'agency': ['agency'],
    'algorithmic stablecoin': ['algorithmic_stablecoin'],
    'anonymous founding team': ['anonymous_founding_team'],
    'application': ['application'],
    'arbitrage': ['arbitrage'],
    'artefact': ['artefact'],
    'artifact': ['artefact'],
    'asic hardware': ['asic_hardware'],
    'asset': ['asset'],
    'asset transfer': ['asset_transfer'],
    'asymmetric key cryptography': ['asymmetric_key_cryptography'],
    'attribute': ['attribute'],
    'auctions': ['auction'],
    'autograph': ['signature'],
    'autographs': ['signature'],
    'autonomous monitoring': ['autonomous_monitoring'],
    'autonomous organization': ['autonomous_organization'],
    'bank': ['bank'],
    'bank note': ['paper_currency'],
    'bank notes': ['paper_currency'],
    'banking platform': ['banking_platform'],
    'banking system': ['banking_system'],
    'barter': ['barter'],
    'bartered': ['barter'],
    'bartering': ['barter'],
    'barters': ['barter'],
    'base rate': ['base_rate'],
    'basis cash': ['basis_cash'],
    'benjamins': ['paper_currency'],
    'bitcoin': ['bitcoin'],
    'bitcoin foundation': ['bitcoin_foundation'],
    'block chain': ['blockchain'],
    'block chains': ['blockchain'],
    'block mine': ['block_mine'],
    'blockchain': ['blockchain'],
    'blockchain based contract': ['blockchain_contract'],
    'blockchain contract': ['blockchain_contract'],
    'blockchain technology': ['blockchain'],
    'blockchains': ['blockchain'],
    'bonding curve': ['bonding_curve'],
    'bonding curves': ['bonding_curve'],
    'btc': ['bitcoin'],
    'bullion': ['bullion'],
    'cad': ['canadian_dollar'],
    'can change': ['mutable'],
    'canadian dollar': ['canadian_dollar'],
    'candidate consensus mechanism': ['consensus_mechanism'],
    'capability': ['capability'],
    'cash': ['paper_currency'],
    'cash economy': ['cash_economy'],
    'cashless': ['digital_currency'],
    'censorship': ['censorship'],
    'central bank': ['central_bank'],
    'centralized control': ['centralized_control'],
    'centralized exchange': ['centralized_exchange'],
    'centralized finance': ['centralized_exchange', 'centralized_control'],
    'centralized financial system': ['centralized_control'],
    'changeable': ['mutable'],
    'characteristic': ['attribute'],
    'coin money': ['specie_currency'],
    'coinbase': ['coinbase'],
    'coindesk': ['coindesk'],
    'coined money': ['specie_currency'],
    'coinshares': ['coinshares'],
    'collateral': ['collateral'],
    'collateral backing': ['collateral'],
    'collateral can be liquidated': ['collateral_liquidation'],
    'collateral liquidation': ['collateral_liquidation'],
    'collateralization rule': ['collateral_requirement'],
    'collateralization rules': ['collateral_requirement'],
    'collaterialization threshold': ['collateral_requirement'],
    'company': ['company'],
    'computationally impractical to reverse': ['irreversible_transaction'],
    'cons': ['disadvantage'],
    'consensus': ['consensus'],
    'consensus mechanism': ['consensus_mechanism'],
    'consensus protocol': ['consensus_mechanism'],
    'contract': ['contract'],
    'control': ['system', 'governance'],
    'cost': ['fee'],
    'costed': ['fee'],
    'costing': ['fee'],
    'council': ['council'],
    'crypto': ['cryptocurrency'],
    'crypto asset': ['cryptoasset'],
    'crypto currency': ['cryptocurrency'],
    'cryptocollateral': ['cryptocollateral'],
    'cryptocollateraliz': ['cryptocollateral'],
    'cryptocollateraliz!': ['cryptocollateral'],
    'cryptocollateralization': ['cryptocollateral'],
    'cryptocollateralized stablecoin': ['cryptocollateralized_stablecoin'],
    'cryptocurrency': ['cryptocurrency'],
    'cryptographic nonce': ['nonce'],
    'cryptographic scarcity': ['cryptographic_scarcity'],
    'cryptography': ['cryptography'],
    'currencies': ['currency'],
    'currency': ['currency'],
    'currency transfer': ['currency_transfer'],
    'dai savings rate': ['dai_savings_rate'],
    'dao': ['decentralized_autonomous_organization'],
    'dapp': ['decentralized_application'],
    'dark pool stock trading': ['dark_pool_stock_trading'],
    'data source': ['data_source'],
    'dcep': ['digital_yuan'],
    'ddos': ['denial_of_service'],
    'ddos attack': ['denial_of_service'],
    'decentralized application': ['decentralized_application'],
    'decentralized autonomous organization': [   'decentralized_autonomous_organization'],
    'decentralized currency': ['decentralized_currency'],
    'decentralized exchange': ['decentralized_exchange'],
    'decentralized finance': ['defi'],
    'decentralized organization': ['decentralized_organization'],
    'defi': ['defi'],
    'defi protocol': ['defi_protocol'],
    'defi v1': ['defi_version_1'],
    'defi v2': ['defi_version_2'],
    'defi v3': ['defi_version_3'],
    'defi version 1': ['defi_version_1'],
    'defi version 2': ['defi_version_2'],
    'defi version 3': ['defi_version_3'],
    'defi-native': ['defi'],
    'defraud': ['malicious_action'],
    'defrauded': ['malicious_action'],
    'defrauder': ['malicious_action'],
    'defrauders': ['malicious_action'],
    'defrauding': ['malicious_action'],
    'defrauds': ['malicious_action'],
    'deployed': ['deploy'],
    'deployment': ['deploy'],
    'deployments': ['deploy'],
    'deploys': ['deploy'],
    'deposit': ['deposit'],
    'dex': ['decentralized_exchange'],
    'digital asset': ['digital_asset'],
    'digital currency': ['digital_currency'],
    'digital currency electronic payment': ['digital_yuan'],
    'digital currency group': ['digital_currency_group'],
    'digital reminbi': ['digital_yuan'],
    'disadvantageous': ['disadvantage'],
    'disputed': ['dispute'],
    'disputer': ['dispute'],
    'disputers': ['dispute'],
    'disputes': ['dispute'],
    'disputing': ['dispute'],
    'distributed database': ['distributed_ledger'],
    'document': ['document'],
    'dollar': ['dollar'],
    'double spending': ['double_spend'],
    'double spending problem': ['double_spend'],
    'down side': ['disadvantage'],
    'down sides': ['disadvantage'],
    'downside': ['disadvantage'],
    'downsides': ['disadvantage'],
    'drawback': ['disadvantage'],
    'drawbacks': ['disadvantage'],
    'dsr': ['dai_savings_rate'],
    'durabilty': ['durabilty'],
    'durable': ['durabilty'],
    'economy': ['economy'],
    'efficiency': ['efficiency'],
    'electronic cash': ['digital_currency'],
    'empty set dollar': ['empty_set_dollar'],
    'eoa': ['externally_owned_account'],
    'equal opportunity': ['equality_of_opportunity'],
    'equality': ['equality'],
    'equality of opportunity': ['equality_of_opportunity'],
    'erc 20': ['erc_20'],
    'erc 721': ['erc-721'],
    'erc-20': ['erc_20'],
    'erc-20 token standard': ['erc_20'],
    'erc-721': ['erc-721'],
    'escrow': ['escrow_mechanism'],
    'escrowed': ['escrow_mechanism'],
    'escrower': ['escrow_mechanism'],
    'escrowers': ['escrow_mechanism'],
    'escrowing': ['escrow_mechanism'],
    'escrows': ['escrow_mechanism'],
    'esd governance': ['esd_governance'],
    'eth': ['ethereum'],
    'ether': ['ethereum'],
    'ethererum': ['ethereum'],
    'ethereum': ['ethereum'],
    'euro': ['euro'],
    'evm': ['ethereum_virtual_machine'],
    'excessive volatility': ['excessive_volatility'],
    'exchange': ['exchange'],
    'exchange medium': ['exchange_medium'],
    'exchange rate': ['exchange_rate'],
    'expansion': ['expansion'],
    'expansions': ['expansion'],
    'explainability': ['explainability'],
    'explainble': ['explainability'],
    'factored': ['factor'],
    'factors': ['factor'],
    'fault tolerance': ['fault_tolerant'],
    'fee': ['fee'],
    'fiat collaterialized': ['fiat_collaterialized'],
    'fiat currency': ['fiat_currency'],
    'finance': ['finance'],
    'financial censorship': ['financial_censorship'],
    'financial infrastructure': ['financial_infrastructure'],
    'financial primitive': ['financial_primitive'],
    'financial system': ['financial_system'],
    'fixed exchange rate': ['fixed_exchange_rate'],
    'float protocol': ['float_protocol'],
    'foundation': ['foundation'],
    'founding team': ['founding_team'],
    'fractional algorithm stablecoin': ['fractional_algorithm_stablecoin'],
    'fractional stablecoin': ['fractional_stablecoin'],
    'fraud': ['malicious_action'],
    'frauded': ['malicious_action'],
    'frauds': ['malicious_action'],
    'fraudulent': ['malicious_action'],
    'funding mechanism': ['funding_mechanism'],
    'fungible token': ['fungible_token'],
    'gas fee': ['gas_fee'],
    'global access': ['global_access'],
    'gold': ['gold'],
    'gold standard': ['gold_standard'],
    'governance': ['governance'],
    'governance platform': ['governance'],
    'government agency': ['government_agency'],
    'green backs': ['paper_currency'],
    'greenback': ['paper_currency'],
    'greenbacks': ['paper_currency'],
    'has changed': ['mutable'],
    'immutable ledger': ['immutable_ledger'],
    'impractical to reverse': ['irreversible_transaction'],
    'in a block': ['blockchain'],
    'in kind currency': ['specie_currency'],
    'in speciē': ['specie_currency'],
    'in the block': ['blockchain'],
    'incented action': ['incentive_mechanism'],
    'incentive': ['incentive_mechanism'],
    'incentive mechanism': ['incentive_mechanism'],
    'incentives': ['incentive_mechanism'],
    'incentivization mechanism': ['incentive_mechanism'],
    'incentivize': ['incentive_mechanism'],
    'incentivized': ['incentive_mechanism'],
    'increased': ['increase'],
    'increases': ['increase'],
    'increasing': ['increase'],
    'inefficiency': ['inefficient'],
    'inefficient': ['inefficient'],
    'inequality': ['inequality'],
    'inequality of opportunity': ['inequality_of_opportunity'],
    'inflation': ['inflation'],
    'inflation hedge': ['inflation_hedge'],
    'infrastructure': ['infrastructure'],
    'ingot': ['metal'],
    'ingots': ['metal'],
    'input uxto': ['input_utxo'],
    'insurance': ['insurance'],
    'insured deposit': ['insured_deposit'],
    'intangible value': ['intangible_value'],
    'internet': ['internet'],
    'internet of bodies': ['internet_of_bodies'],
    'internet of money': ['internet_of_money'],
    'internet of things': ['internet_of_things'],
    'interoperability': ['interoperability'],
    'iob': ['internet_of_bodies'],
    'iom': ['internet_of_money'],
    'iot': ['internet_of_things'],
    'ireversible transaction': ['irreversible_transaction'],
    'jewelry': ['jewelry'],
    'lack of access': ['lack_of_access'],
    'lack of interoperability': ['lack_of_interoperability'],
    'ledger': ['ledger'],
    'legal tender': ['sovereign_currency'],
    'lending': ['loan'],
    'leverage': ['leverage'],
    'limited access': ['limited_access'],
    'limited supply': ['limited_supply'],
    'linear bonding curve': ['linear_bonding_curve'],
    'liquidate collateral': ['collateral_liquidation'],
    'liquidators': ['liquidator'],
    'liquidity': ['liquidity'],
    'loans': ['loan'],
    'long term': ['long_term'],
    'long term horizon': ['long_term'],
    'malicious action': ['malicious_action'],
    'malicious behavior': ['malicious_action'],
    'malicious computational task': ['malicious_action'],
    'malicious task': ['malicious_action'],
    'malicious transaction': ['malicious_transaction'],
    'market exchange': ['market_exchange'],
    'mechanism': ['mechanism'],
    'mechanisms': ['mechanism'],
    'mediated': ['mediate'],
    'mediates': ['mediate'],
    'mediating': ['mediate'],
    'medium': ['medium'],
    'medium of exchange': ['exchange_medium'],
    'metal': ['metal'],
    'mine': ['mine'],
    'mined': ['mine'],
    'mined its first block': ['block_mine'],
    'miners': ['miner'],
    'miners fee': ['miner_fee'],
    'minor': ['miner'],
    'minors': ['miner'],
    'monetary system': ['financial_system'],
    'money': ['currency'],
    'money in coin': ['specie_currency'],
    'monies': ['currency'],
    'monitor': ['monitor'],
    'monitored': ['monitor'],
    'monitoring': ['monitor'],
    'monitors': ['monitor'],
    'monotonically increasing': ['monotonical_increase'],
    'mutable ledger': ['mutable_ledger'],
    'nft': ['nft'],
    'non fungible token': ['nft'],
    'non physical transfer': ['non_physical_transfer'],
    'non reversible transaction': ['irreversible_transaction'],
    'nonreversible transaction': ['irreversible_transaction'],
    'number once': ['nonce'],
    'number used once': ['nonce'],
    'on chain governance': ['on_chain_governance'],
    'on-chain governance': ['on_chain_governance'],
    'opacity': ['opaque'],
    'opaque': ['opaque'],
    'opportunisitic': ['opportunity'],
    'opportunities': ['opportunity'],
    'opportunity': ['opportunity'],
    'oracle': ['oracle'],
    'organization': ['organization'],
    'output uxto': ['output_utxo'],
    'p2p': ['peer_to_peer_network'],
    'p2p network': ['peer_to_peer_network'],
    'p2p network protocol': ['peer_to_peer_network_protocol'],
    'p2p node': ['peer_to_peer_node'],
    'p2p protocol': ['peer_to_peer_network_protocol'],
    'paper currency': ['paper_currency'],
    'paper money': ['paper_currency'],
    'payment system': ['payment_system'],
    'payments': ['payment'],
    'paypal': ['paypal'],
    'pcv': ['protocol_controlled_value'],
    'peer 2 peer': ['peer_to_peer_network'],
    'peer to peer': ['peer_to_peer_network', 'barter'],
    'peer to peer protocol': ['peer_to_peer_network_protocol'],
    'peer2peer network': ['peer_to_peer_network'],
    'physical transfer': ['physical_transfer'],
    'platform': ['platform'],
    'policy': ['policy'],
    'portability': ['portable'],
    'portable': ['portable'],
    'position': ['position'],
    'precious metal': ['precious_metal'],
    'primitive': ['primitive'],
    'privacy': ['privacy'],
    'private agency': ['private_agency'],
    'problem solving': ['solution'],
    'proof of stake': ['proof_of_stake'],
    'proof of work': ['proof_of_work'],
    'proto coinage': ['proto_coinage'],
    'protocol': ['protocol'],
    'protocol controlled value': ['protocol_controlled_value'],
    'protocol governance': ['protocol_governance'],
    'protocols': ['protocol'],
    'public agency': ['public_agency'],
    'rate': ['rate'],
    'receive a bonus': ['bonus'],
    'receives a bonus': ['bonus'],
    'refinance loan': ['refinance'],
    'reliability': ['reliable'],
    'reminbi': ['yuan'],
    'research company': ['research_company'],
    'reserve currency': ['reserve_currency'],
    'reward actor': ['incentive_mechanism'],
    'ring money': ['ring_money'],
    'risk': ['risk'],
    'risk factor': ['risk_factor'],
    'robustness': ['robust'],
    'scalability': ['scalability'],
    'scalable': ['scalability'],
    'scarcity': ['scarcity'],
    'sec': ['sec'],
    'security': ['security'],
    'short term': ['short_term'],
    'short term horizon': ['short_term'],
    'signatures': ['signature'],
    'silver': ['silver'],
    'simple linear function': ['linear_function'],
    'slashing mechanism': ['slashing_condition'],
    'smart contract': ['smart_contract'],
    'software protocol': ['software_protocol'],
    'solving a problem': ['solution'],
    'solving problems': ['solution'],
    'solving the problem': ['solution'],
    'sovereign currency': ['sovereign_currency'],
    'sovereignity': ['sovereignity'],
    'specie currency': ['specie_currency'],
    'spending': ['spend'],
    'spends': ['spend'],
    'spent': ['spend'],
    'stability': ['stable'],
    'stable': ['stable'],
    'stablecoin': ['stablecoin'],
    'stablecoin protocol': ['stablecoin_protocol'],
    'stablecoins': ['stablecoin'],
    'standard': ['standard'],
    'standard of value': ['value_standard'],
    'state': ['state'],
    'stock trade': ['stock_trade'],
    'storage': ['storage'],
    'store of wealth': ['store_of_wealth'],
    'superlinear function': ['super_linear_function'],
    'supply': ['supply'],
    'supply expansion': ['supply_expansion'],
    'system': ['system'],
    'tangible value': ['tangible_value'],
    'task': ['action'],
    'tasked': ['action'],
    'tasks': ['action'],
    'team': ['team'],
    'teams': ['team'],
    'time stamp': ['timestamp'],
    'time stamps': ['timestamp'],
    'timestamps': ['timestamp'],
    'token\n': ['token'],
    'token standard': ['token_standard'],
    'token swap': ['token_swap'],
    'trade': ['trade'],
    'trades': ['trade'],
    'tradfi': ['centralized_control'],
    'trading': ['trade'],
    'trading platform': ['trading_platform'],
    'traditional finance': ['centralized_control'],
    'transaction': ['transaction'],
    'transfer': ['transfer'],
    'transfer of currency': ['currency_transfer'],
    'transfer of money': ['currency_transfer'],
    'transparency': ['transparency'],
    'treasury governance': ['treasury_governance'],
    'trusted party': ['trusted_actor'],
    'u.s. securities and exchange commission': ['sec'],
    'uncensorable': ['censorship_resistant'],
    'unchangeable': ['immutable'],
    'uncollateralized stablecoin': ['uncollateralized_stablecoin'],
    'unequal opportunity': ['inequality_of_opportunity'],
    'uniform': ['uniform'],
    'uniformity': ['uniform'],
    'universal access': ['universal_access'],
    'unlimited access': ['universal_access'],
    'unlimited supply': ['unlimited_supply'],
    'up side': ['advantage'],
    'up sides': ['advantage'],
    'upside': ['advantage'],
    'upsides': ['advantage'],
    'us dollar': ['us_dollar'],
    'usd': ['us_dollar'],
    'user issued asset': ['user_issued_asset'],
    'user sovereignity': ['user_sovereignity'],
    'utxo': ['unspent_transaction_output'],
    'value': ['value'],
    'value standard': ['value_standard'],
    'value transfer': ['value_transfer'],
    'verfied': ['verify'],
    'verifier': ['verify'],
    'verifiers': ['verify'],
    'verifies': ['verify'],
    'verifying': ['verify'],
    'virtual currency': ['digital_currency'],
    'virtual node\n': ['virtual_machine'],
    'virtual transfer': ['virtual_transfer'],
    'volatile': ['volatile'],
    'volatility': ['volatile'],
    'vulnerability': ['vulnerable'],
    'will change': ['mutable'],
    'world computer': ['ethereum'],
    'zelle': ['zelle']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
