
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class MaryvilleSynonyms(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'MaryvilleSynonyms',
            'filename': 'maryville_synonyms',
            'files': ['maryville.txt'],
            'queries': ['synonyms.sparql'],
            'reverse': True,
            'transformers': ['lowercase', 'synonyms']},
 'source': 'maryville.owl',
 'time': '2022-05-17 11:15:53.963593'}

    __data = {
    'academic_building': ['academic building'],
    'academic_institution': ['academic institution'],
    'academic_offering': ['academic offering'],
    'academic_plan': ['academic plan'],
    'academic_program': ['academic program'],
    'academic_rigor': ['academic rigor'],
    'academic_standard': ['academic standard'],
    'academic_structure': ['academic structure'],
    'academy': ['academy'],
    'access': ['access'],
    'accreditation': ['accreditation'],
    'achievement': ['achievement'],
    'acre_campus_parcel': ['acre campus parcel'],
    'acre_maryville_centre': ['acre maryville centre'],
    'acre_parcel': ['acre parcel'],
    'acreage_adjacent': ['acreage adjacent'],
    'active_learning': ['active learning'],
    'active_learning_ecosystem': ['active learning ecosystem'],
    'active_way': ['active way'],
    'activity': ['activity', 'action'],
    'acute_care': ['acute care'],
    'additional_acreage_adjacent': ['additional acreage adjacent'],
    'additional_campus_facility': ['additional campus facility'],
    'additional_facility': ['additional facility'],
    'additional_physical_facility': ['additional physical facility'],
    'additional_student_apartment_building': [   'additional student apartment '
                                                 'building'],
    'adept_real_estate_investor': ['adept real estate investor'],
    'adjacent': ['adjacent'],
    'administration_building': ['administration building'],
    'administrative_responsibility': ['administrative responsibility'],
    'admission': ['admission'],
    'adult_education_program': ['adult education program'],
    'adult_student': ['adult student'],
    'advanced_practice_registered_nurse': [   'advanced practice registered '
                                              'nurse',
                                              'aprn'],
    'advanced_training': ['advanced training'],
    'age': ['age'],
    'agent': ['agent'],
    'aid_training': ['aid training'],
    'airport': ['airport'],
    'allied_health_program': ['allied health program'],
    'alumnae': ['alumnae'],
    'alumnae_association': ['alumnae association'],
    'alumnae_director': ['alumnae director'],
    'alumnae_office': ['alumnae office'],
    'american': ['american'],
    'american_association_of_colleges_of_nursing': [   'american association '
                                                       'of colleges of nursing',
                                                       'aacn'],
    'american_nurses_association': [   'american nursing association',
                                       'american nurses association',
                                       'ana'],
    'american_red_cross': ['american red cross'],
    'ann_padberg': ['ann padberg'],
    'ann_webster': ['ann webster'],
    'anniversary': ['anniversary'],
    'annual_college_subsidy': ['annual college subsidy'],
    'annual_subsidy': ['annual subsidy'],
    'apartment_building': ['apartment building'],
    'aphasia_clinic': ['aphasia clinic'],
    'apothecary': ['apothecary'],
    'app': ['app'],
    'archives': ['archives'],
    'art_college': ['art college'],
    'art_production_studio': ['art production studio'],
    'art_structure': ['art structure'],
    'artifact': ['artifact', 'artefact'],
    'ashlyn_cunningham': ['ashlyn cunningham'],
    'assistance': ['assistance'],
    'associate_professor': ['associate professor'],
    'associates_degree': [   "associate's degree",
                             'associate degree',
                             'aa degree'],
    'association': ['association'],
    'astronomical_expansion': ['astronomical expansion'],
    'athletic': ['athletic'],
    'athletic_center': ['athletic center'],
    'athletic_event': ['athletic event'],
    'athletic_field': ['athletic field'],
    'athletic_logo': ['athletic logo'],
    'athletic_team': ['athletic team'],
    'attention': ['attention'],
    'audacious_mission': ['audacious mission'],
    'augustinian_academy': ['augustinian academy'],
    'bachelor_of_arts': ['bachelor of arts'],
    'bachelor_of_science': ['bachelor of science'],
    'bachelor_of_science_in_nursing': ['bachelor of science in nursing', 'bsn'],
    'bachelors_degree': [   'baccalaureate level',
                            "bachelor's degree",
                            'bachelor degree'],
    'bank_building': ['bank building'],
    'barat': ['barat'],
    'bascom': ['bascom'],
    'bascom_honors_program': ['bascom honors program'],
    'bascom_honors_scholarship_fund': ['bascom honors scholarship fund'],
    'base': ['base'],
    'baur_commercial_development': ['baur commercial development'],
    'belonging': ['belonging'],
    'beloved_tradition': ['beloved tradition'],
    'benefactor': ['benefactor'],
    'bernard_dog_costume': ['bernard dog costume'],
    'bernard_mascot': ['bernard mascot'],
    'bias': ['bias'],
    'big_red_m': ['big red m'],
    'bird': ['bird'],
    'blish': ['blish'],
    'blue_musical_note': ['blue musical note'],
    'blues_successful_stanley_cup': ['blues successful stanley cup'],
    'board': ['board'],
    'boarding_school': ['boarding school'],
    'boarding_student': ['boarding student'],
    'body': ['body'],
    'bold_logo': ['bold logo'],
    'books': ['books'],
    'bosco': ['bosco'],
    'brand_message': ['brand message'],
    'branding_initiative': ['branding initiative'],
    'brashear_telescope': ['brashear telescope'],
    'buder_family_student_commons': ['buder family student commons'],
    'building': ['building .', 'building ', 'building', 'edifice'],
    'busch_hall': ['busch hall'],
    'business': ['business'],
    'cabin': ['cabin'],
    'cabinet': ['cabinet'],
    'campaign': ['campaign'],
    'campus': ['campus'],
    'campus_activity': ['campus activity'],
    'campus_building': ['campus building'],
    'campus_chapter': ['campus chapter'],
    'campus_constituency': ['campus constituency'],
    'campus_construction': ['campus construction'],
    'campus_expansion': ['campus expansion'],
    'campus_facility': ['campus facility'],
    'campus_parcel': ['campus parcel'],
    'campus_population': ['campus population'],
    'campus_symbolizing_maryville': ['campus symbolizing maryville'],
    'candidate': ['candidate'],
    'cardinal': ['cardinal'],
    'cardinals': ['cardinals'],
    'care_event': ['care event'],
    'care_management': ['care management'],
    'career': ['career'],
    'catholic_church': ['catholic church'],
    'celebration': ['celebration'],
    'centennial_celebration': ['centennial celebration'],
    'center': ['center'],
    'central_association': ['central association'],
    'centre': ['centre'],
    'century': ['century'],
    'certification': ['certification'],
    'challenge': ['challenge'],
    'challenging_study': ['challenging study'],
    'challenging_year': ['challenging year'],
    'chapel': ['chapel'],
    'chapter': ['chapter'],
    'charitable_entity': ['charitable entity'],
    'chemist': ['chemist'],
    'child': ['child'],
    'childhood_language_disorders': ['childhood language disorders'],
    'church': ['church'],
    'city': ['city'],
    'city_center': ['city center'],
    'city_limit': ['city limit'],
    'civil_rights_movement': ['civil rights movement'],
    'civil_war': ['civil war'],
    'class': ['class'],
    'class_inconvenient': ['class inconvenient'],
    'class_neighborhood': ['class neighborhood'],
    'class_year': ['class year'],
    'classroom_duty': ['classroom duty'],
    'claude_pritchard': ['claude pritchard'],
    'clinic': ['clinic'],
    'clinic_service': ['clinic service'],
    'clinical_competency': ['clinical competency'],
    'clinical_evaluation': ['clinical evaluation'],
    'clinical_outcome': ['clinical outcome'],
    'clinical_outcome_evaluation': ['clinical outcome evaluation'],
    'clinical_training': [   'advanced clinical training',
                             'clinical training',
                             'clinical course'],
    'closure': ['set to close', 'closure'],
    'club': ['club'],
    'coach': ['coach'],
    'college': ['college'],
    'college_credit': ['college credit'],
    'college_degree': ['college degree'],
    'college_enrollment': ['college enrollment'],
    'college_physics_student': ['college physics student'],
    'college_presidency': ['college presidency'],
    'college_president': ['college president'],
    'college_student': ['college student'],
    'college_subsidy': ['college subsidy'],
    'commercial_development': ['commercial development'],
    'committee': ['committee'],
    'commons': ['commons'],
    'communication_skill_necessary': ['communication skill necessary'],
    'community': ['community'],
    'community_center': ['community center'],
    'community_figure': ['community figure'],
    'community_member': ['community member'],
    'company': ['company'],
    'competency': ['competency'],
    'completion': ['completion'],
    'component': ['component'],
    'condition': ['condition\n'],
    'conference': ['conference'],
    'conference_room': ['conference room'],
    'confidential_plan': ['confidential plan'],
    'confine': ['confine'],
    'constellation': ['constellation'],
    'constituency': ['constituency'],
    'construction': ['construction'],
    'contemporary_dichotomy': ['contemporary dichotomy'],
    'contemporary_dress': ['contemporary dress'],
    'continent': ['continent'],
    'continuous_learning': ['continuous learning', 'continued learning'],
    'contract': ['contract'],
    'convenient_highway_access': ['convenient highway access'],
    'convenient_location': ['convenient location'],
    'convent': ['convent'],
    'conway_road': ['conway road'],
    'corporate_college': ['corporate college'],
    'costume': ['costume'],
    'counseling': ['counseling'],
    'counseling_center': ['counseling center'],
    'country': ['country'],
    'county': ['county'],
    'county_campus': ['county campus'],
    'county_location': ['county location'],
    'county_parcel': ['county parcel'],
    'county_site': ['county site'],
    'course': ['course'],
    'course_hour': ['course hour'],
    'course_material': ['course material'],
    'courtyard_hotel_adjacent': ['courtyard hotel adjacent'],
    'coveted_bascom_honors_program': ['coveted bascom honors program'],
    'credit': ['credit'],
    'cross': ['cross'],
    'cultural_trip_downtown': ['cultural trip downtown'],
    'cultural_value': ['cultural value'],
    'culture': ['culture'],
    'cunningham': ['cunningham'],
    'cup': ['cup'],
    'cushion': ['cushion'],
    'custom': ['custom'],
    'dan_viele': ['dan viele'],
    'dante_course': ['dante course'],
    'date': ['date'],
    'day_school': ['day school'],
    'day_trip': ['day trip'],
    'day_voyage': ['day voyage'],
    'deal': ['deal'],
    'decision': ['decision'],
    'dedicated_alumnae': ['dedicated alumnae'],
    'dedicated_team': ['dedicated team'],
    'degree': ['degree'],
    'degree_program': ['degree program'],
    'department': ['department'],
    'depression': ['depression'],
    'design': ['design'],
    'design_building': ['design building'],
    'developer_taylor_morley_simon': ['developer taylor morley simon'],
    'development': ['development'],
    'dichotomy': ['dichotomy'],
    'different_academic_institution': ['different academic institution'],
    'difficult_time': ['difficult time'],
    'difficulty': ['difficulty'],
    'digital_age': ['digital age'],
    'digital_resource': ['digital resource'],
    'digital_world': ['digital world'],
    'dii_conference': ['dii conference'],
    'dining_hall': ['dining hall'],
    'dining_room': ['dining room'],
    'diploma': ['diploma'],
    'director': ['director'],
    'disorders': ['disorders'],
    'display_cabinet': ['display cabinet'],
    'distinguished_educational_institution': [   'distinguished educational '
                                                 'institution'],
    'distinguished_scholar': ['distinguished scholar'],
    'diverse_program': ['diverse program'],
    'division_ii': ['division ii'],
    'doctoral_degree': [   'doctoral degree program',
                           'doctoral degree',
                           'doctoral',
                           'phd'],
    'dog_costume': ['dog costume'],
    'dominant_brand_message': ['dominant brand message'],
    'dominant_esport_team': ['dominant esport team'],
    'donation': ['donation'],
    'downtown': ['downtown'],
    'dozen_year': ['dozen year'],
    'dress': ['dress'],
    'duchesne': ['duchesne'],
    'duchesne_hall': ['duchesne hall'],
    'duty': ['duty'],
    'dynamic_academic_offering': ['dynamic academic offering'],
    'dynamic_online_education_platform': ['dynamic online education platform'],
    'early_june': ['early june'],
    'early_year': ['early year'],
    'ecosystem': ['ecosystem'],
    'edge_university': ['edge university'],
    'edition': ['edition'],
    'education': ['education'],
    'education_course': ['education course'],
    'education_dan_viele': ['education dan viele'],
    'education_landscape': ['education landscape'],
    'education_leadership': ['education leadership'],
    'education_pin': ['education pin'],
    'education_platform': ['education platform'],
    'education_program': ['education program'],
    'educational_institution': ['educational institution'],
    'educational_opportunity': ['educational opportunity'],
    'educational_program': ['educational program'],
    'educational_reach': ['educational reach'],
    'educational_system': ['educational system'],
    'educator': ['educator'],
    'edwards': ['edwards'],
    'effective_study_habit': ['effective study habit'],
    'eighth_president': ['eighth president'],
    'elapsed_time': ['elapsed time', 'duration'],
    'elderly_patient': ['elderly patient'],
    'emergency_room': ['emergency room', 'er'],
    'empathy': ['empathy'],
    'endowment_today': ['endowment today'],
    'english_language': ['english language'],
    'enrollment': ['enrollment'],
    'enrollment_growth': ['enrollment growth'],
    'entity': ['entity'],
    'environment': ['environment'],
    'episcopal_city': ['episcopal city'],
    'era': ['era'],
    'era_evoke_story': ['era evoke story'],
    'esport_team': ['esport team'],
    'essential_value': ['essential value'],
    'estate_investor': ['estate investor'],
    'ethical_practice': ['code for ethical practice', 'ethical practice'],
    'europe': ['europe'],
    'evaluation': ['evaluation'],
    'evening_class': ['evening class'],
    'evening_college': ['evening college'],
    'event': ['event'],
    'evidence': ['evidence'],
    'evoke_story': ['evoke story'],
    'existence_today': ['existence today'],
    'expansion': ['expansion'],
    'experience': ['experience'],
    'extensive_national_search': ['extensive national search'],
    'extensive_undergraduate': ['extensive undergraduate'],
    'extracurricular_activity': ['extracurricular activity'],
    'facility': ['facility'],
    'facility_closure': ['facility closure'],
    'factor': ['factor'],
    'faculty': ['faculty'],
    'faculty_contract': ['faculty contract'],
    'faculty_lounge': ['faculty lounge'],
    'faculty_member': ['faculty member'],
    'fail_to_rescue_rate': ['failure-to-rescue rates', 'fail to rescue rate'],
    'fair_pay': ['fair pay'],
    'faith': ['faith'],
    'famed_german_firm': ['famed german firm'],
    'family_home': ['family home'],
    'family_member': ['family member'],
    'family_nurse_practitioner': ['family nurse practitioner', 'fnp'],
    'family_responsibility': ['family responsibility'],
    'family_student_commons': ['family student commons'],
    'fashionable_office': ['fashionable office'],
    'favorite_tradition': ['favorite tradition'],
    'female_patient': ['female patient'],
    'field': ['field'],
    'fifth_window': ['fifth window'],
    'figure': ['figure'],
    'financial_assistance': ['financial assistance'],
    'financial_challenge': ['financial challenge'],
    'financial_cushion': ['financial cushion'],
    'financial_difficulty': ['financial difficulty'],
    'financial_predicament': ['financial predicament'],
    'financial_reason': ['financial reason'],
    'financial_resource': ['financial resource'],
    'financial_status': ['financial status'],
    'financial_success': ['financial success'],
    'firm': ['firm'],
    'fledgling_campus': ['fledgling campus'],
    'florence_nightingale': ['florence nightingale'],
    'focus': ['focus'],
    'following_year': ['following year'],
    'footprint': ['footprint'],
    'fortune': ['fortune'],
    'foundation': ['foundation'],
    'foundation_grant': ['foundation grant'],
    'founders_hall': ['founders hall'],
    'fourth_president': ['fourth president'],
    'fourth_time': ['fourth time'],
    'franklin_county': ['franklin county'],
    'free_learning_app': ['free learning app'],
    'free_school': ['free school'],
    'freshmen_student': ['freshmen student'],
    'full_potential': ['full potential'],
    'fund': ['fund'],
    'fundraising_campaign': ['fundraising campaign'],
    'fundraising_event': ['fundraising event'],
    'gander': ['gander'],
    'gander_hall': ['gander hall'],
    'gender_bias': ['gender bias'],
    'geographic_location': ['geographic location'],
    'geopolitical_entity': ['geopolitical entity'],
    'german_firm': ['german firm'],
    'german_immigrant': ['german immigrant'],
    'gidionsen': ['gidionsen'],
    'glass_window': ['glass window'],
    'glee_club': ['glee club'],
    'good_fortune': ['good fortune'],
    'good_time': ['good time'],
    'good_way': ['good way'],
    'gothic_chapel': ['gothic chapel'],
    'graduate_level': ['graduate level'],
    'graduate_mother_marion_rose_bascom': [   'graduate mother marion rose '
                                              'bascom'],
    'graduate_offering': ['graduate offering'],
    'graduate_program': ['graduate program'],
    'graduate_student': ['graduate student'],
    'grant': ['grant'],
    'graphic_design': ['graphic design'],
    'gray_mcnally': ['gray mcnally'],
    'great_achievement': ['great achievement'],
    'great_books': ['great books'],
    'great_deal': ['great deal'],
    'great_depression': ['great depression'],
    'great_lakes_valley_conference': ['great lakes valley conference'],
    'great_peril': ['great peril'],
    'great_pioneer': ['great pioneer'],
    'great_sense': ['great sense'],
    'group': ['group'],
    'group_therapy': ['group therapy'],
    'growth': ['growth'],
    'growth_impact': ['growth impact'],
    'guidance_maryville': ['guidance maryville'],
    'gym_class': ['gym class'],
    'habit': ['habit'],
    'hall': ['hall'],
    'harriet_ann_padberg': ['harriet ann padberg'],
    'harriet_switzer': ['harriet switzer'],
    'health': ['health'],
    'health_care': ['health care'],
    'health_care_education': ['health care education'],
    'health_care_management': ['health care management'],
    'health_care_provider': ['health care provider'],
    'health_care_quality': ['health care quality'],
    'health_care_reform': ['health care reform'],
    'health_care_specialist': [   'health care specialist',
                                  'health care provider'],
    'health_challenge': ['health challenge'],
    'health_department': ['health department'],
    'health_profession_education': ['health profession education'],
    'health_program': ['health program'],
    'health_service': ['health service'],
    'heart_convent': ['heart convent'],
    'heart_era': ['heart era'],
    'heart_school': ['heart school'],
    'hellmuth': ['hellmuth'],
    'high': ['high'],
    'high_academic_standard': ['high academic standard'],
    'high_class': ['high class'],
    'high_education_landscape': ['high education landscape'],
    'high_learning': ['high learning'],
    'high_school': ['high school'],
    'highway_access': ['highway access'],
    'hildegarde_hellmuth': ['hildegarde hellmuth'],
    'historical_nursing': ['historical nursing'],
    'history': ['history'],
    'holiday_edition': ['holiday edition'],
    'holland_gidionsen': ['holland gidionsen'],
    'home': ['home'],
    'honor_student': ['honor student'],
    'honors_program': ['honors program'],
    'honors_scholarship_fund': ['honors scholarship fund'],
    'hospital': ['hospital'],
    'hospital_conference_room': ['hospital conference room'],
    'host_city': ['host city'],
    'hotel_adjacent': ['hotel adjacent'],
    'hotel_facility': ['hotel facility'],
    'hour': ['hour'],
    'house_production_specialist': ['house production specialist'],
    'huttig_chapel': ['huttig chapel'],
    'huttig_memorial_chapel': ['huttig memorial chapel'],
    'ideal_institutional_foundation': ['ideal institutional foundation'],
    'ii': ['ii'],
    'immigrant': ['immigrant'],
    'impact': ['impact'],
    'important_component': ['important component'],
    'important_decision': ['important decision'],
    'important_factor': ['important factor'],
    'impressive_stone_structure': ['impressive stone structure'],
    'improvement_plan': ['improvement plan'],
    'inconvenient': ['inconvenient'],
    'independent_accreditation': ['independent accreditation'],
    'independent_charitable_entity': ['independent charitable entity'],
    'individual_donation': ['individual donation'],
    'information': ['information'],
    'initial_construction': ['initial construction'],
    'initial_degree': ['initial degree'],
    'initiative': ['initiative'],
    'innovative_investment': ['innovative investment'],
    'innovative_leadership': ['innovative leadership'],
    'innovative_member': ['innovative member'],
    'innovative_technology': ['innovative technology'],
    'institute': ['institute'],
    'institution': ['institution'],
    'institutional_foundation': ['institutional foundation'],
    'instrument': ['instrument'],
    'intellectual_life': ['intellectual life'],
    'interior_design': ['interior design'],
    'investment': ['investment'],
    'investor': ['investor'],
    'jefferson_county': ['jefferson county'],
    'john_bosco': ['john bosco'],
    'john_mullanphy': ['john mullanphy'],
    'johnson_and_johnson': ['johnson and johnson', 'johnson & johnson', 'j&j'],
    'joseph_gander': ['joseph gander'],
    'journey': ['journey'],
    'joyous_centennial_celebration': ['joyous centennial celebration'],
    'june': ['june'],
    'junior_college': ['junior college'],
    'kate_kline': ['kate kline'],
    'keith_lovin': ['keith lovin'],
    'kernaghan': ['kernaghan'],
    'kernaghan_hall': ['kernaghan hall'],
    'key_role': ['key role'],
    'kline': ['kline'],
    'labor_event': ['labor event'],
    'lakes_valley_conference': ['lakes valley conference'],
    'landscape': ['landscape'],
    'language': ['language'],
    'language_disorders': ['language disorders'],
    'lapel_pin': ['lapel pin'],
    'large_site': ['large site'],
    'lay_board': ['lay board'],
    'lay_president': ['lay president'],
    'leader': ['leader'],
    'leadership': ['leadership'],
    'leadership_fundraising_campaign': ['leadership fundraising campaign'],
    'learning': ['learning'],
    'learning_app': ['learning app'],
    'learning_ecosystem': ['learning ecosystem'],
    'learning_environment': ['learning environment'],
    'learning_style': ['learning style'],
    'level': ['level'],
    'level_speech': ['level speech'],
    'liberal_art_college': ['liberal art college'],
    'life': ['life'],
    'life_coach': ['life coach'],
    'like_focus': ['like focus'],
    'limit': ['limit'],
    'lincoln_county': ['lincoln county'],
    'line': ['line'],
    'little_ship_rebecca': ['little ship rebecca'],
    'local_board': ['local board'],
    'location': ['location'],
    'log_cabin': ['log cabin'],
    'logo': ['logo'],
    'logo_design': ['logo design'],
    'lombardi': ['lombardi'],
    'long_journey': ['long journey'],
    'long_term_health_care': ['long term health care', 'long-term health care'],
    'longtime_maryville_benefactor': ['longtime maryville benefactor'],
    'louis_blues_successful_stanley_cup': [   'louis blues successful stanley '
                                              'cup'],
    'louis_campus': ['louis campus'],
    'louis_cardinals': ['louis cardinals'],
    'louis_city_limit': ['louis city limit'],
    'louis_county_campus': ['louis county campus'],
    'louis_county_parcel': ['louis county parcel'],
    'louis_county_site': ['louis county site'],
    'louis_culture': ['louis culture'],
    'louis_landscape': ['louis landscape'],
    'louis_region': ['louis region'],
    'louis_scottish_rite_masons': ['louis scottish rite masons'],
    'louis_speaker_series': ['louis speaker series'],
    'louis_university': ['louis university'],
    'louise_padberg': ['louise padberg'],
    'lounge': ['lounge'],
    'lovin': ['lovin'],
    'low_level': ['low level'],
    'm': ['m'],
    'madeleine_sophie_barat': ['madeleine sophie barat'],
    'main_campus_building': ['main campus building'],
    'main_chapel': ['main chapel'],
    'main_staircase': ['main staircase'],
    'major': ['major'],
    'male_leader': ['male leader'],
    'male_patient': ['male patient'],
    'male_student': ['male student'],
    'man': ['man'],
    'management': ['management'],
    'mandate': ['mandate'],
    'marie_kernaghan': ['marie kernaghan'],
    'marie_louise_padberg': ['marie louise padberg'],
    'marie_odeide_mouton': ['marie odeide mouton'],
    'marion_bascom': ['marion bascom'],
    'marion_bascom_honors_scholarship_fund': [   'marion bascom honors '
                                                 'scholarship fund'],
    'marion_rose_bascom': ['marion rose bascom'],
    'mark_lombardi': ['mark lombardi'],
    'market': ['market'],
    'marriott_courtyard_hotel_adjacent': ['marriott courtyard hotel adjacent'],
    'mary_blish': ['mary blish'],
    'mary_gray_mcnally': ['mary gray mcnally'],
    'mary_robert_edwards': ['mary robert edwards'],
    'mary_roch_rocklage': ['mary roch rocklage'],
    'maryville': ['maryville'],
    'maryville_academy': ['maryville academy'],
    'maryville_alumnae': ['maryville alumnae'],
    'maryville_benefactor': ['maryville benefactor'],
    'maryville_building': ['maryville building'],
    'maryville_career': ['maryville career'],
    'maryville_centre': ['maryville centre'],
    'maryville_college_physics_student': ['maryville college physics student'],
    'maryville_community': ['maryville community'],
    'maryville_education': ['maryville education'],
    'maryville_faculty': ['maryville faculty'],
    'maryville_glee_club': ['maryville glee club'],
    'maryville_saints': ['maryville saints'],
    'maryville_science_club': ['maryville science club'],
    'maryville_university_archives': ['maryville university archives'],
    'mascot': ['mascot'],
    'masons': ['masons'],
    'master_course_material': ['master course material'],
    'master_of_arts': ['master of arts'],
    'master_of_science': ['master of science', 'msc'],
    'master_of_science_in_nursing': ['master of science in nursing', 'msn'],
    'masters_degree': ["master's degree", 'master degree', "master's"],
    'material': ['material'],
    'mba_degree': ['mba degree'],
    'mcgarry': ['mcgarry'],
    'mcnally': ['mcnally'],
    'meaningful_online_learning': ['meaningful online learning'],
    'medical_building': ['medical building'],
    'medical_facility_closure': ['medical facility closure'],
    'member': ['member'],
    'member_local_board': ['member local board'],
    'memorial_chapel': ['memorial chapel'],
    'mental_health': ['mental health'],
    'mental_health_challenge': ['mental health challenge'],
    'mental_health_service': ['mental health service'],
    'mercy_department': ['mercy department'],
    'mercy_grant': ['mercy grant'],
    'mercy_hospital': ['mercy hospital'],
    'mercy_junior_college': ['mercy junior college'],
    'message': ['message'],
    'mission': ['mission'],
    'mississippi_river': ['mississippi river'],
    'missouri_institute': ['missouri institute'],
    'missouri_river': ['missouri river'],
    'mobile_access': ['mobile access'],
    'modern_high': ['modern high'],
    'modern_nursing': ['modern nursing'],
    'money': ['money'],
    'more': ['more'],
    'morley_simon': ['morley simon'],
    'mortality_rate': ['mortality rate'],
    'mother_bascom': ['mother bascom'],
    'mother_kernaghan': ['mother kernaghan'],
    'mother_marie_kernaghan': ['mother marie kernaghan'],
    'mother_marie_odeide_mouton': ['mother marie odeide mouton'],
    'mother_marion_bascom': ['mother marion bascom'],
    'mother_marion_bascom_honors_scholarship_fund': [   'mother marion bascom '
                                                        'honors scholarship '
                                                        'fund'],
    'mother_marion_rose_bascom': ['mother marion rose bascom'],
    'mother_mary_blish': ['mother mary blish'],
    'mother_mary_gray_mcnally': ['mother mary gray mcnally'],
    'motivated_student': ['motivated student'],
    'mouton': ['mouton'],
    'mouton_hall': ['mouton hall'],
    'movement': ['movement'],
    'mullanphy': ['mullanphy'],
    'multidimensional_leadership': ['multidimensional leadership'],
    'munich_style': ['munich style'],
    'music_therapy': ['music therapy'],
    'music_therapy_program': ['music therapy program'],
    'musical_note': ['musical note'],
    'nation_pride': ['nation pride'],
    'national_attention': ['national attention'],
    'national_certification': ['national certification'],
    'national_institution': ['national institution'],
    'national_scale': ['national scale'],
    'national_search': ['national search'],
    'national_student_base': ['national student base'],
    'national_university': ['national university'],
    'nationality': ['nationality'],
    'ncaa_division_ii': ['ncaa division ii'],
    'nearby_mississippi_river': ['nearby mississippi river'],
    'necessary': ['necessary'],
    'need': ['need'],
    'neighborhood': ['neighborhood'],
    'new_athletic_logo': ['new athletic logo'],
    'new_branding_initiative': ['new branding initiative'],
    'new_building': ['new building'],
    'new_campus': ['new campus'],
    'new_constellation': ['new constellation'],
    'new_family_member': ['new family member'],
    'new_home': ['new home'],
    'new_initiative': ['new initiative'],
    'new_market': ['new market'],
    'new_mercy_department': ['new mercy department'],
    'new_official': ['new official'],
    'new_phase': ['new phase'],
    'new_property': ['new property'],
    'new_religious': ['new religious'],
    'new_residence_hall': ['new residence hall'],
    'new_school': ['new school'],
    'new_south_wing': ['new south wing'],
    'new_structure': ['new structure'],
    'noble_peace_prize_winner': ['noble peace prize winner'],
    'north_central_association': ['north central association'],
    'note': ['note'],
    'notebook': ['notebook'],
    'number': ['number'],
    'nurse': ['nurse'],
    'nurse_educator': ['nurse educator'],
    'nurse_practitioner': ['nurse practitioner', 'nps', 'np'],
    'nursing': ['nursing'],
    'nursing_diploma': ['nursing diploma'],
    'nursing_education': ['nursing education'],
    'nursing_home': ['nursing home'],
    'nursing_major': ['nursing major'],
    'nursing_program': ['nursing program'],
    'nursing_school': ['nursing school'],
    'nursing_student': ['nursing student'],
    'oakwood_retirement_center': ['oakwood retirement center'],
    'observer': ['observer'],
    'occupational_therapy': ['occupational therapy'],
    'odeide_mouton': ['odeide mouton'],
    'offering': ['offering'],
    'office': ['office'],
    'official': ['official'],
    'official_program': ['official program'],
    'old_campus': ['old campus'],
    'old_child': ['old child'],
    'old_institution': ['old institution'],
    'old_log_cabin': ['old log cabin'],
    'old_maryville_building': ['old maryville building'],
    'old_university_logo': ['old university logo'],
    'ongoing_training': ['ongoing training'],
    'online_degree_program': ['online degree program'],
    'online_education_dan_viele': ['online education dan viele'],
    'online_education_platform': ['online education platform'],
    'online_learning': ['online learning'],
    'open_field': ['open field'],
    'opportunity': ['opportunity'],
    'opportunity_transforming_business': ['opportunity transforming business'],
    'optimum_learning_style': ['optimum learning style'],
    'order': ['order'],
    'ordinal': ['ordinal'],
    'organization': ['organization'],
    'original_building': ['original building'],
    'original_campus': ['original campus'],
    'original_logo_design': ['original logo design'],
    'ornate_student_lounge': ['ornate student lounge'],
    'outcome': ['outcome'],
    'outcome_evaluation': ['outcome evaluation'],
    'outreach': ['outreach'],
    'outright_grant': ['outright grant'],
    'outstanding_team': ['outstanding team'],
    'oxford_university_graduate_mother_marion_rose_bascom': [   'oxford '
                                                                'university '
                                                                'graduate '
                                                                'mother marion '
                                                                'rose bascom'],
    'padberg': ['padberg'],
    'padberg_mcgarry': ['padberg mcgarry'],
    'parcel': ['parcel'],
    'parent_training': ['parent training'],
    'path': ['path'],
    'patient': ['patient'],
    'patient_care': ['patient care coordination', 'patient care'],
    'patient_treatment': ['patient treatment'],
    'patient_treatment_plan': ['patient treatment plan'],
    'pay': ['salary', 'pay'],
    'peace_prize_winner': ['peace prize winner'],
    'pediactric_patient': ['pediactric patient'],
    'peer_review': ['periodic peer review', 'peer review'],
    'peggy_padberg_mcgarry': ['peggy padberg mcgarry'],
    'percent': ['percent'],
    'peril': ['peril'],
    'period': ['period'],
    'permanent': ['permanent'],
    'permanent_alumnae_office': ['permanent alumnae office'],
    'person': ['person'],
    'personal_belonging': ['personal belonging'],
    'personal_notebook': ['personal notebook'],
    'personal_quality': ['personal quality'],
    'personal_touch': ['personal touch'],
    'pharmacist': ['pharmacist'],
    'pharmacy': ['pharmacy'],
    'phase': ['phase'],
    'philanthropist_john_mullanphy': ['philanthropist john mullanphy'],
    'philippine': ['philippine'],
    'philippine_duchesne': ['philippine duchesne'],
    'physical_campus': ['physical campus'],
    'physical_education_course': ['physical education course'],
    'physical_facility': ['physical facility'],
    'physical_site': ['physical site'],
    'physical_therapy': ['physical therapy'],
    'physical_transformation': ['physical transformation'],
    'physician': ['physician'],
    'physics_student': ['physics student'],
    'pin': ['pin'],
    'pioneer': ['pioneer'],
    'pivotal_role': ['pivotal role'],
    'plan': ['plan\n', 'plan'],
    'planning_committee': ['planning committee'],
    'platform': ['platform'],
    'platform_education': ['platform education'],
    'political_activity': ['political activity'],
    'political_group': ['political group'],
    'political_science': ['political science'],
    'population': ['population'],
    'portable_brashear_telescope': ['portable brashear telescope'],
    'postpandemic_era': ['postpandemic era'],
    'potential': ['potential'],
    'potter_hall': ['potter hall'],
    'powell_symphony_hall': ['powell symphony hall'],
    'practice': ['practice'],
    'predicament': ['predicament'],
    'preliminary_evidence': ['preliminary evidence'],
    'premier_dii_conference': ['premier dii conference'],
    'presidency': ['presidency'],
    'president': ['president'],
    'pride': ['pride'],
    'primary_care': ['primary care'],
    'pritchard': ['pritchard'],
    'private_high_school': ['private high school'],
    'private_institution': ['private institution'],
    'prize_winner': ['prize winner'],
    'problem_mother_kernaghan': ['problem mother kernaghan'],
    'product': ['product'],
    'production_specialist': ['production specialist'],
    'production_studio': ['production studio'],
    'profession': ['profession'],
    'profession_education': ['profession education'],
    'professional_career': ['professional career'],
    'professional_development': ['professional development'],
    'professor': ['professor'],
    'profile': ['profile'],
    'profile_information': ['profile information'],
    'program': ['program'],
    'proper_training': ['proper training'],
    'property': ['property'],
    'protestant_church': ['protestant church'],
    'provider': ['provider'],
    'psychiatric_mental_health_nurse_practitioner': [   'psychiatric mental '
                                                        'health nurse '
                                                        'practitioner',
                                                        'pmhnp'],
    'public_fundraising_campaign': ['public fundraising campaign'],
    'public_health_department': ['public health department'],
    'qualified_student': ['qualified student'],
    'quality': ['quality'],
    'quantifiable_measurement': ['quantifiable measurement'],
    'quantity': ['quantity'],
    'racial_bias': ['racial bias', 'race bias'],
    'range_strategic_plan': ['range strategic plan'],
    'reach': ['reach'],
    'readmission': ['readmission'],
    'readmission_rate': ['readmission rate'],
    'real_estate_investor': ['real estate investor'],
    'reason': ['reason'],
    'rebecca': ['rebecca'],
    'receiver': ['receiver'],
    'red_bird': ['red bird'],
    'red_cross': ['red cross'],
    'red_m': ['red m'],
    'reform': ['reformation', 'reform'],
    'region': ['region'],
    'registered_nurse': ['registered nurse', 'rns', 'rn'],
    'regulation': ['regulation'],
    'rehabilitation_counseling': ['rehabilitation counseling'],
    'relaxation_room': ['relaxation room'],
    'relief': ['relief'],
    'religious': ['religious'],
    'religious_group': ['religious group'],
    'religious_order': ['religious order'],
    'remote_location': ['remote location'],
    'required_number': ['required number'],
    'residence_hall': ['residence hall'],
    'residential_campus_population': ['residential campus population'],
    'residential_developer_taylor_morley_simon': [   'residential developer '
                                                     'taylor morley simon'],
    'residential_student': ['residential student'],
    'resource': ['resource'],
    'respected_faculty': ['respected faculty'],
    'responsibility': ['responsibility'],
    'retirement_center': ['retirement center'],
    'retirement_year': ['retirement year'],
    'rich_experience': ['rich experience'],
    'rich_history': ['rich history'],
    'rights_movement': ['rights movement'],
    'rigor': ['rigor'],
    'risk_child': ['risk child'],
    'rite_clinic': ['rite clinic'],
    'rite_masons': ['rite masons'],
    'river': ['river'],
    'road': ['road'],
    'robert_edwards': ['robert edwards'],
    'robust_expansion': ['robust expansion'],
    'robust_learning_environment': ['robust learning environment'],
    'roch_rocklage': ['roch rocklage'],
    'rocklage': ['rocklage'],
    'role': ['role'],
    'roman_catholic_church': ['roman catholic church'],
    'room': ['room'],
    'room_adjacent': ['room adjacent'],
    'rose_bascom': ['rose bascom'],
    'rose_philippine': ['rose philippine'],
    'rose_philippine_duchesne': ['rose philippine duchesne'],
    'rose_window': ['rose window'],
    'rosemary_holland_gidionsen': ['rosemary holland gidionsen'],
    'round_window': ['round window'],
    'rule': ['rule\n'],
    'rural_campus': ['rural campus'],
    'rural_community': ['rural community'],
    'rural_confine': ['rural confine'],
    'sacred_heart_convent': ['sacred heart convent'],
    'sacred_heart_era': ['sacred heart era'],
    'sacred_heart_school': ['sacred heart school'],
    'saint_bernard_dog_costume': ['saint bernard dog costume'],
    'saint_bernard_mascot': ['saint bernard mascot'],
    'saint_louis_university': ['saint louis university'],
    'saint_madeleine_sophie_barat': ['saint madeleine sophie barat'],
    'saint_rose_philippine': ['saint rose philippine'],
    'saint_rose_philippine_duchesne': ['saint rose philippine duchesne'],
    'saints': ['saints'],
    'saints_athletic': ['saints athletic'],
    'saints_hall': ['saints hall'],
    'saints_nation_pride': ['saints nation pride'],
    'satellite_location': ['satellite location'],
    'scale': ['scale'],
    'scholar': ['scholar'],
    'scholarship_fund': ['scholarship fund'],
    'school': ['school'],
    'school_custom': ['school custom'],
    'school_diploma': ['school diploma'],
    'school_year': ['school year'],
    'science': ['science'],
    'science_club': ['science club'],
    'science_department': ['science department'],
    'science_instrument': ['science instrument'],
    'scottish_rite_clinic': ['scottish rite clinic'],
    'scottish_rite_masons': ['scottish rite masons'],
    'search': ['search'],
    'secret_planning_committee': ['secret planning committee'],
    'select_faculty': ['select faculty'],
    'select_number': ['select number'],
    'sense': ['sense'],
    'series': ['series'],
    'service': ['service'],
    'service_man': ['service man'],
    'session': ['session'],
    'ship_rebecca': ['ship rebecca'],
    'short_year': ['short year'],
    'shortage': ['shortage'],
    'significant_achievement': ['significant achievement'],
    'significant_enrollment_growth': ['significant enrollment growth'],
    'simon': ['simon'],
    'simon_school': ['simon school'],
    'single_red_bird': ['single red bird'],
    'sister_ann_webster': ['sister ann webster'],
    'sister_harriet_ann_padberg': ['sister harriet ann padberg'],
    'sister_harriet_switzer': ['sister harriet switzer'],
    'sister_hildegarde_hellmuth': ['sister hildegarde hellmuth'],
    'sister_mary_robert_edwards': ['sister mary robert edwards'],
    'sister_mary_roch_rocklage': ['sister mary roch rocklage'],
    'sister_padberg': ['sister padberg'],
    'sister_rocklage': ['sister rocklage'],
    'sister_switzer': ['sister switzer'],
    'sister_webster': ['sister webster'],
    'site': ['site'],
    'sixth_president': ['sixth president'],
    'skill': ['skill'],
    'skill_necessary': ['skill necessary'],
    'small_academy': ['small academy'],
    'small_apple': ['small apple'],
    'small_grant': ['small grant'],
    'small_personal_notebook': ['small personal notebook'],
    'social_event': ['social event'],
    'societal_more': ['societal more'],
    'soft_skill': ['soft skill'],
    'sophie_barat': ['sophie barat'],
    'south_county_location': ['south county location'],
    'south_wing': ['south wing'],
    'spain': ['spain'],
    'spanish': ['spanish'],
    'spanish_hospital': ['spanish hospital'],
    'speaker_series': ['speaker series'],
    'special_fundraising_event': ['special fundraising event'],
    'special_holiday_edition': ['special holiday edition'],
    'special_need': ['special need'],
    'specialist': ['specialist'],
    'speech': ['speech'],
    'sporadic_growth': ['sporadic growth'],
    'sport_business': ['sport business'],
    'stable_foundation': ['stable foundation'],
    'staff': ['staff'],
    'staffing': ['staffing'],
    'staffing_level': ['staffing level'],
    'staffing_shortage': ['staffing shortage'],
    'staircase': ['staircase'],
    'standard': ['standard'],
    'stanley_cup': ['stanley cup'],
    'state_educational_system': ['state educational system'],
    'state_mandate': ['state mandate'],
    'status': ['status'],
    'stone_structure': ['stone structure'],
    'stone_terrace': ['stone terrace'],
    'story': ['story'],
    'story_administration_building': ['story administration building'],
    'story_dining_hall': ['story dining hall'],
    'story_tall': ['story tall'],
    'strategic_plan': ['strategic plan'],
    'strike': ['strike'],
    'strong_faith': ['strong faith'],
    'strong_footprint': ['strong footprint'],
    'structure': ['structure'],
    'student': ['student'],
    'student_apartment_building': ['student apartment building'],
    'student_base': ['student base'],
    'student_body': ['student body'],
    'student_commons': ['student commons'],
    'student_enrollment': ['student enrollment'],
    'student_lounge': ['student lounge'],
    'student_master_course_material': ['student master course material'],
    'student_mental_health': ['student mental health'],
    'student_outcome': ['student outcome'],
    'student_outreach': ['student outreach'],
    'student_profile': ['student profile'],
    'studio': ['studio'],
    'study': ['study'],
    'study_habit': ['study habit'],
    'style': ['style'],
    'subsequent_year': ['subsequent year'],
    'subsidy': ['subsidy'],
    'success': ['success'],
    'successful_completion': ['successful completion'],
    'successful_stanley_cup': ['successful stanley cup'],
    'successful_tenure': ['successful tenure'],
    'sufficient_number': ['sufficient number'],
    'suitable_course': ['suitable course'],
    'superior_class': ['superior class'],
    'support_line': ['support line'],
    'supportive_community_member': ['supportive community member'],
    'surgeon': ['surgeon'],
    'surgery': ['surgery'],
    'switzer': ['switzer'],
    'symbolizing_maryville': ['symbolizing maryville'],
    'symphony_hall': ['symphony hall'],
    'system': ['system'],
    'tall': ['tall'],
    'taylor_morley_simon': ['taylor morley simon'],
    'teaching_career': ['teaching career'],
    'team': ['team'],
    'technology': ['technology'],
    'telescope': ['telescope'],
    'temporary': ['temporarily', 'temporary'],
    'tenure': ['tenure'],
    'terrace': ['terrace'],
    'therapy': ['therapy'],
    'therapy_program': ['therapy program'],
    'therapy_session': ['therapy session'],
    'thought_leader': ['thought leader'],
    'time': ['time'],
    'time_residential_student': ['time residential student'],
    'time_student': ['time student'],
    'today': ['today'],
    'tradition': ['tradition'],
    'traditional_college': ['traditional college'],
    'traditional_path': ['traditional path'],
    'traditional_undergraduate_student': ['traditional undergraduate student'],
    'training': ['training'],
    'training_event': ['training event'],
    'transformation': ['transformation'],
    'transforming_business': ['transforming business'],
    'treatment_event': ['treatment event'],
    'trip': ['trip'],
    'trip_downtown': ['trip downtown'],
    'tutorial_program': ['tutorial program'],
    'undergraduate': ['undergraduate'],
    'undergraduate_student': ['undergraduate student'],
    'underprivileged_student': ['underprivileged student'],
    'university': ['university'],
    'university_archives': ['university archives'],
    'university_center': ['university center'],
    'university_graduate_mother_marion_rose_bascom': [   'university graduate '
                                                         'mother marion rose '
                                                         'bascom'],
    'university_logo': ['university logo'],
    'university_status': ['university status'],
    'unprecedented_growth': ['unprecedented growth'],
    'urban_location': ['urban location'],
    'urgent_care': ['urgent care clinic', 'urgent care site', 'urgent care'],
    'valley_conference': ['valley conference'],
    'value': ['value'],
    'varied_campus_constituency': ['varied campus constituency'],
    'vice_president': ['vice president'],
    'viele': ['viele'],
    'villa_duchesne': ['villa duchesne'],
    'virtual_relaxation_room': ['virtual relaxation room'],
    'volunteer_faculty_member': ['volunteer faculty member'],
    'voyage': ['voyage'],
    'walker_clinic_service': ['walker clinic service'],
    'walker_college': ['walker college'],
    'walker_hall': ['walker hall'],
    'walker_scottish_rite_clinic': ['walker scottish rite clinic'],
    'war': ['war'],
    'war_ii': ['war ii'],
    'war_relief': ['war relief'],
    'washington_university': ['washington university'],
    'way': ['way'],
    'webster': ['webster'],
    'weekday_class_inconvenient': ['weekday class inconvenient'],
    'weekend_college_student': ['weekend college student'],
    'weekly_dante_course': ['weekly dante course'],
    'well_observer': ['well observer'],
    'wide_improvement_plan': ['wide improvement plan'],
    'wide_main_staircase': ['wide main staircase'],
    'wide_mental_health_service': ['wide mental health service'],
    'window': ['window'],
    'wing': ['wing'],
    'winner': ['winner'],
    'wise_guidance_maryville': ['wise guidance maryville'],
    'woman': ['woman'],
    'wooden_display_cabinet': ['wooden display cabinet'],
    'work_of_art': ['work of art'],
    'world': ['world'],
    'world_leader': ['world leader'],
    'world_war_ii': ['world war ii'],
    'year': ['year'],
    'year_anniversary': ['year anniversary'],
    'year_college': ['year college'],
    'year_degree': ['year degree'],
    'year_period': ['year period'],
    'young_candidate': ['young candidate'],
    'young_college_president': ['young college president'],
    'young_woman': ['young woman']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
