
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class MaryvilleSynonymsRev(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'MaryvilleSynonyms',
            'filename': 'maryville_synonyms',
            'files': ['maryville.txt'],
            'queries': ['synonyms.sparql'],
            'reverse': True,
            'transformers': ['lowercase', 'synonyms']},
 'source': 'maryville.owl',
 'time': '2022-05-17 11:15:53.977093'}

    __data = {
    'aa degree': ['associates_degree'],
    'aacn': ['american_association_of_colleges_of_nursing'],
    'academic building': ['academic_building'],
    'academic institution': ['academic_institution'],
    'academic offering': ['academic_offering'],
    'academic plan': ['academic_plan'],
    'academic program': ['academic_program'],
    'academic rigor': ['academic_rigor'],
    'academic standard': ['academic_standard'],
    'academic structure': ['academic_structure'],
    'academy': ['academy'],
    'access': ['access'],
    'accreditation': ['accreditation'],
    'achievement': ['achievement'],
    'acre campus parcel': ['acre_campus_parcel'],
    'acre maryville centre': ['acre_maryville_centre'],
    'acre parcel': ['acre_parcel'],
    'acreage adjacent': ['acreage_adjacent'],
    'action': ['activity'],
    'active learning': ['active_learning'],
    'active learning ecosystem': ['active_learning_ecosystem'],
    'active way': ['active_way'],
    'activity': ['activity'],
    'acute care': ['acute_care'],
    'additional acreage adjacent': ['additional_acreage_adjacent'],
    'additional campus facility': ['additional_campus_facility'],
    'additional facility': ['additional_facility'],
    'additional physical facility': ['additional_physical_facility'],
    'additional student apartment building': [   'additional_student_apartment_building'],
    'adept real estate investor': ['adept_real_estate_investor'],
    'adjacent': ['adjacent'],
    'administration building': ['administration_building'],
    'administrative responsibility': ['administrative_responsibility'],
    'admission': ['admission'],
    'adult education program': ['adult_education_program'],
    'adult student': ['adult_student'],
    'advanced clinical training': ['clinical_training'],
    'advanced practice registered nurse': [   'advanced_practice_registered_nurse'],
    'advanced training': ['advanced_training'],
    'age': ['age'],
    'agent': ['agent'],
    'aid training': ['aid_training'],
    'airport': ['airport'],
    'allied health program': ['allied_health_program'],
    'alumnae': ['alumnae'],
    'alumnae association': ['alumnae_association'],
    'alumnae director': ['alumnae_director'],
    'alumnae office': ['alumnae_office'],
    'american': ['american'],
    'american association of colleges of nursing': [   'american_association_of_colleges_of_nursing'],
    'american nurses association': ['american_nurses_association'],
    'american nursing association': ['american_nurses_association'],
    'american red cross': ['american_red_cross'],
    'ana': ['american_nurses_association'],
    'ann padberg': ['ann_padberg'],
    'ann webster': ['ann_webster'],
    'anniversary': ['anniversary'],
    'annual college subsidy': ['annual_college_subsidy'],
    'annual subsidy': ['annual_subsidy'],
    'apartment building': ['apartment_building'],
    'aphasia clinic': ['aphasia_clinic'],
    'apothecary': ['apothecary'],
    'app': ['app'],
    'aprn': ['advanced_practice_registered_nurse'],
    'archives': ['archives'],
    'art college': ['art_college'],
    'art production studio': ['art_production_studio'],
    'art structure': ['art_structure'],
    'artefact': ['artifact'],
    'artifact': ['artifact'],
    'ashlyn cunningham': ['ashlyn_cunningham'],
    'assistance': ['assistance'],
    'associate degree': ['associates_degree'],
    'associate professor': ['associate_professor'],
    "associate's degree": ['associates_degree'],
    'association': ['association'],
    'astronomical expansion': ['astronomical_expansion'],
    'athletic': ['athletic'],
    'athletic center': ['athletic_center'],
    'athletic event': ['athletic_event'],
    'athletic field': ['athletic_field'],
    'athletic logo': ['athletic_logo'],
    'athletic team': ['athletic_team'],
    'attention': ['attention'],
    'audacious mission': ['audacious_mission'],
    'augustinian academy': ['augustinian_academy'],
    'baccalaureate level': ['bachelors_degree'],
    'bachelor degree': ['bachelors_degree'],
    'bachelor of arts': ['bachelor_of_arts'],
    'bachelor of science': ['bachelor_of_science'],
    'bachelor of science in nursing': ['bachelor_of_science_in_nursing'],
    "bachelor's degree": ['bachelors_degree'],
    'bank building': ['bank_building'],
    'barat': ['barat'],
    'bascom': ['bascom'],
    'bascom honors program': ['bascom_honors_program'],
    'bascom honors scholarship fund': ['bascom_honors_scholarship_fund'],
    'base': ['base'],
    'baur commercial development': ['baur_commercial_development'],
    'belonging': ['belonging'],
    'beloved tradition': ['beloved_tradition'],
    'benefactor': ['benefactor'],
    'bernard dog costume': ['bernard_dog_costume'],
    'bernard mascot': ['bernard_mascot'],
    'bias': ['bias'],
    'big red m': ['big_red_m'],
    'bird': ['bird'],
    'blish': ['blish'],
    'blue musical note': ['blue_musical_note'],
    'blues successful stanley cup': ['blues_successful_stanley_cup'],
    'board': ['board'],
    'boarding school': ['boarding_school'],
    'boarding student': ['boarding_student'],
    'body': ['body'],
    'bold logo': ['bold_logo'],
    'books': ['books'],
    'bosco': ['bosco'],
    'brand message': ['brand_message'],
    'branding initiative': ['branding_initiative'],
    'brashear telescope': ['brashear_telescope'],
    'bsn': ['bachelor_of_science_in_nursing'],
    'buder family student commons': ['buder_family_student_commons'],
    'building': ['building'],
    'building ': ['building'],
    'building .': ['building'],
    'busch hall': ['busch_hall'],
    'business': ['business'],
    'cabin': ['cabin'],
    'cabinet': ['cabinet'],
    'campaign': ['campaign'],
    'campus': ['campus'],
    'campus activity': ['campus_activity'],
    'campus building': ['campus_building'],
    'campus chapter': ['campus_chapter'],
    'campus constituency': ['campus_constituency'],
    'campus construction': ['campus_construction'],
    'campus expansion': ['campus_expansion'],
    'campus facility': ['campus_facility'],
    'campus parcel': ['campus_parcel'],
    'campus population': ['campus_population'],
    'campus symbolizing maryville': ['campus_symbolizing_maryville'],
    'candidate': ['candidate'],
    'cardinal': ['cardinal'],
    'cardinals': ['cardinals'],
    'care event': ['care_event'],
    'care management': ['care_management'],
    'career': ['career'],
    'catholic church': ['catholic_church'],
    'celebration': ['celebration'],
    'centennial celebration': ['centennial_celebration'],
    'center': ['center'],
    'central association': ['central_association'],
    'centre': ['centre'],
    'century': ['century'],
    'certification': ['certification'],
    'challenge': ['challenge'],
    'challenging study': ['challenging_study'],
    'challenging year': ['challenging_year'],
    'chapel': ['chapel'],
    'chapter': ['chapter'],
    'charitable entity': ['charitable_entity'],
    'chemist': ['chemist'],
    'child': ['child'],
    'childhood language disorders': ['childhood_language_disorders'],
    'church': ['church'],
    'city': ['city'],
    'city center': ['city_center'],
    'city limit': ['city_limit'],
    'civil rights movement': ['civil_rights_movement'],
    'civil war': ['civil_war'],
    'class': ['class'],
    'class inconvenient': ['class_inconvenient'],
    'class neighborhood': ['class_neighborhood'],
    'class year': ['class_year'],
    'classroom duty': ['classroom_duty'],
    'claude pritchard': ['claude_pritchard'],
    'clinic': ['clinic'],
    'clinic service': ['clinic_service'],
    'clinical competency': ['clinical_competency'],
    'clinical course': ['clinical_training'],
    'clinical evaluation': ['clinical_evaluation'],
    'clinical outcome': ['clinical_outcome'],
    'clinical outcome evaluation': ['clinical_outcome_evaluation'],
    'clinical training': ['clinical_training'],
    'closure': ['closure'],
    'club': ['club'],
    'coach': ['coach'],
    'code for ethical practice': ['ethical_practice'],
    'college': ['college'],
    'college credit': ['college_credit'],
    'college degree': ['college_degree'],
    'college enrollment': ['college_enrollment'],
    'college physics student': ['college_physics_student'],
    'college presidency': ['college_presidency'],
    'college president': ['college_president'],
    'college student': ['college_student'],
    'college subsidy': ['college_subsidy'],
    'commercial development': ['commercial_development'],
    'committee': ['committee'],
    'commons': ['commons'],
    'communication skill necessary': ['communication_skill_necessary'],
    'community': ['community'],
    'community center': ['community_center'],
    'community figure': ['community_figure'],
    'community member': ['community_member'],
    'company': ['company'],
    'competency': ['competency'],
    'completion': ['completion'],
    'component': ['component'],
    'condition\n': ['condition'],
    'conference': ['conference'],
    'conference room': ['conference_room'],
    'confidential plan': ['confidential_plan'],
    'confine': ['confine'],
    'constellation': ['constellation'],
    'constituency': ['constituency'],
    'construction': ['construction'],
    'contemporary dichotomy': ['contemporary_dichotomy'],
    'contemporary dress': ['contemporary_dress'],
    'continent': ['continent'],
    'continued learning': ['continuous_learning'],
    'continuous learning': ['continuous_learning'],
    'contract': ['contract'],
    'convenient highway access': ['convenient_highway_access'],
    'convenient location': ['convenient_location'],
    'convent': ['convent'],
    'conway road': ['conway_road'],
    'corporate college': ['corporate_college'],
    'costume': ['costume'],
    'counseling': ['counseling'],
    'counseling center': ['counseling_center'],
    'country': ['country'],
    'county': ['county'],
    'county campus': ['county_campus'],
    'county location': ['county_location'],
    'county parcel': ['county_parcel'],
    'county site': ['county_site'],
    'course': ['course'],
    'course hour': ['course_hour'],
    'course material': ['course_material'],
    'courtyard hotel adjacent': ['courtyard_hotel_adjacent'],
    'coveted bascom honors program': ['coveted_bascom_honors_program'],
    'credit': ['credit'],
    'cross': ['cross'],
    'cultural trip downtown': ['cultural_trip_downtown'],
    'cultural value': ['cultural_value'],
    'culture': ['culture'],
    'cunningham': ['cunningham'],
    'cup': ['cup'],
    'cushion': ['cushion'],
    'custom': ['custom'],
    'dan viele': ['dan_viele'],
    'dante course': ['dante_course'],
    'date': ['date'],
    'day school': ['day_school'],
    'day trip': ['day_trip'],
    'day voyage': ['day_voyage'],
    'deal': ['deal'],
    'decision': ['decision'],
    'dedicated alumnae': ['dedicated_alumnae'],
    'dedicated team': ['dedicated_team'],
    'degree': ['degree'],
    'degree program': ['degree_program'],
    'department': ['department'],
    'depression': ['depression'],
    'design': ['design'],
    'design building': ['design_building'],
    'developer taylor morley simon': ['developer_taylor_morley_simon'],
    'development': ['development'],
    'dichotomy': ['dichotomy'],
    'different academic institution': ['different_academic_institution'],
    'difficult time': ['difficult_time'],
    'difficulty': ['difficulty'],
    'digital age': ['digital_age'],
    'digital resource': ['digital_resource'],
    'digital world': ['digital_world'],
    'dii conference': ['dii_conference'],
    'dining hall': ['dining_hall'],
    'dining room': ['dining_room'],
    'diploma': ['diploma'],
    'director': ['director'],
    'disorders': ['disorders'],
    'display cabinet': ['display_cabinet'],
    'distinguished educational institution': [   'distinguished_educational_institution'],
    'distinguished scholar': ['distinguished_scholar'],
    'diverse program': ['diverse_program'],
    'division ii': ['division_ii'],
    'doctoral': ['doctoral_degree'],
    'doctoral degree': ['doctoral_degree'],
    'doctoral degree program': ['doctoral_degree'],
    'dog costume': ['dog_costume'],
    'dominant brand message': ['dominant_brand_message'],
    'dominant esport team': ['dominant_esport_team'],
    'donation': ['donation'],
    'downtown': ['downtown'],
    'dozen year': ['dozen_year'],
    'dress': ['dress'],
    'duchesne': ['duchesne'],
    'duchesne hall': ['duchesne_hall'],
    'duration': ['elapsed_time'],
    'duty': ['duty'],
    'dynamic academic offering': ['dynamic_academic_offering'],
    'dynamic online education platform': ['dynamic_online_education_platform'],
    'early june': ['early_june'],
    'early year': ['early_year'],
    'ecosystem': ['ecosystem'],
    'edge university': ['edge_university'],
    'edifice': ['building'],
    'edition': ['edition'],
    'education': ['education'],
    'education course': ['education_course'],
    'education dan viele': ['education_dan_viele'],
    'education landscape': ['education_landscape'],
    'education leadership': ['education_leadership'],
    'education pin': ['education_pin'],
    'education platform': ['education_platform'],
    'education program': ['education_program'],
    'educational institution': ['educational_institution'],
    'educational opportunity': ['educational_opportunity'],
    'educational program': ['educational_program'],
    'educational reach': ['educational_reach'],
    'educational system': ['educational_system'],
    'educator': ['educator'],
    'edwards': ['edwards'],
    'effective study habit': ['effective_study_habit'],
    'eighth president': ['eighth_president'],
    'elapsed time': ['elapsed_time'],
    'elderly patient': ['elderly_patient'],
    'emergency room': ['emergency_room'],
    'empathy': ['empathy'],
    'endowment today': ['endowment_today'],
    'english language': ['english_language'],
    'enrollment': ['enrollment'],
    'enrollment growth': ['enrollment_growth'],
    'entity': ['entity'],
    'environment': ['environment'],
    'episcopal city': ['episcopal_city'],
    'er': ['emergency_room'],
    'era': ['era'],
    'era evoke story': ['era_evoke_story'],
    'esport team': ['esport_team'],
    'essential value': ['essential_value'],
    'estate investor': ['estate_investor'],
    'ethical practice': ['ethical_practice'],
    'europe': ['europe'],
    'evaluation': ['evaluation'],
    'evening class': ['evening_class'],
    'evening college': ['evening_college'],
    'event': ['event'],
    'evidence': ['evidence'],
    'evoke story': ['evoke_story'],
    'existence today': ['existence_today'],
    'expansion': ['expansion'],
    'experience': ['experience'],
    'extensive national search': ['extensive_national_search'],
    'extensive undergraduate': ['extensive_undergraduate'],
    'extracurricular activity': ['extracurricular_activity'],
    'facility': ['facility'],
    'facility closure': ['facility_closure'],
    'factor': ['factor'],
    'faculty': ['faculty'],
    'faculty contract': ['faculty_contract'],
    'faculty lounge': ['faculty_lounge'],
    'faculty member': ['faculty_member'],
    'fail to rescue rate': ['fail_to_rescue_rate'],
    'failure-to-rescue rates': ['fail_to_rescue_rate'],
    'fair pay': ['fair_pay'],
    'faith': ['faith'],
    'famed german firm': ['famed_german_firm'],
    'family home': ['family_home'],
    'family member': ['family_member'],
    'family nurse practitioner': ['family_nurse_practitioner'],
    'family responsibility': ['family_responsibility'],
    'family student commons': ['family_student_commons'],
    'fashionable office': ['fashionable_office'],
    'favorite tradition': ['favorite_tradition'],
    'female patient': ['female_patient'],
    'field': ['field'],
    'fifth window': ['fifth_window'],
    'figure': ['figure'],
    'financial assistance': ['financial_assistance'],
    'financial challenge': ['financial_challenge'],
    'financial cushion': ['financial_cushion'],
    'financial difficulty': ['financial_difficulty'],
    'financial predicament': ['financial_predicament'],
    'financial reason': ['financial_reason'],
    'financial resource': ['financial_resource'],
    'financial status': ['financial_status'],
    'financial success': ['financial_success'],
    'firm': ['firm'],
    'fledgling campus': ['fledgling_campus'],
    'florence nightingale': ['florence_nightingale'],
    'fnp': ['family_nurse_practitioner'],
    'focus': ['focus'],
    'following year': ['following_year'],
    'footprint': ['footprint'],
    'fortune': ['fortune'],
    'foundation': ['foundation'],
    'foundation grant': ['foundation_grant'],
    'founders hall': ['founders_hall'],
    'fourth president': ['fourth_president'],
    'fourth time': ['fourth_time'],
    'franklin county': ['franklin_county'],
    'free learning app': ['free_learning_app'],
    'free school': ['free_school'],
    'freshmen student': ['freshmen_student'],
    'full potential': ['full_potential'],
    'fund': ['fund'],
    'fundraising campaign': ['fundraising_campaign'],
    'fundraising event': ['fundraising_event'],
    'gander': ['gander'],
    'gander hall': ['gander_hall'],
    'gender bias': ['gender_bias'],
    'geographic location': ['geographic_location'],
    'geopolitical entity': ['geopolitical_entity'],
    'german firm': ['german_firm'],
    'german immigrant': ['german_immigrant'],
    'gidionsen': ['gidionsen'],
    'glass window': ['glass_window'],
    'glee club': ['glee_club'],
    'good fortune': ['good_fortune'],
    'good time': ['good_time'],
    'good way': ['good_way'],
    'gothic chapel': ['gothic_chapel'],
    'graduate level': ['graduate_level'],
    'graduate mother marion rose bascom': [   'graduate_mother_marion_rose_bascom'],
    'graduate offering': ['graduate_offering'],
    'graduate program': ['graduate_program'],
    'graduate student': ['graduate_student'],
    'grant': ['grant'],
    'graphic design': ['graphic_design'],
    'gray mcnally': ['gray_mcnally'],
    'great achievement': ['great_achievement'],
    'great books': ['great_books'],
    'great deal': ['great_deal'],
    'great depression': ['great_depression'],
    'great lakes valley conference': ['great_lakes_valley_conference'],
    'great peril': ['great_peril'],
    'great pioneer': ['great_pioneer'],
    'great sense': ['great_sense'],
    'group': ['group'],
    'group therapy': ['group_therapy'],
    'growth': ['growth'],
    'growth impact': ['growth_impact'],
    'guidance maryville': ['guidance_maryville'],
    'gym class': ['gym_class'],
    'habit': ['habit'],
    'hall': ['hall'],
    'harriet ann padberg': ['harriet_ann_padberg'],
    'harriet switzer': ['harriet_switzer'],
    'health': ['health'],
    'health care': ['health_care'],
    'health care education': ['health_care_education'],
    'health care management': ['health_care_management'],
    'health care provider': ['health_care_specialist', 'health_care_provider'],
    'health care quality': ['health_care_quality'],
    'health care reform': ['health_care_reform'],
    'health care specialist': ['health_care_specialist'],
    'health challenge': ['health_challenge'],
    'health department': ['health_department'],
    'health profession education': ['health_profession_education'],
    'health program': ['health_program'],
    'health service': ['health_service'],
    'heart convent': ['heart_convent'],
    'heart era': ['heart_era'],
    'heart school': ['heart_school'],
    'hellmuth': ['hellmuth'],
    'high': ['high'],
    'high academic standard': ['high_academic_standard'],
    'high class': ['high_class'],
    'high education landscape': ['high_education_landscape'],
    'high learning': ['high_learning'],
    'high school': ['high_school'],
    'highway access': ['highway_access'],
    'hildegarde hellmuth': ['hildegarde_hellmuth'],
    'historical nursing': ['historical_nursing'],
    'history': ['history'],
    'holiday edition': ['holiday_edition'],
    'holland gidionsen': ['holland_gidionsen'],
    'home': ['home'],
    'honor student': ['honor_student'],
    'honors program': ['honors_program'],
    'honors scholarship fund': ['honors_scholarship_fund'],
    'hospital': ['hospital'],
    'hospital conference room': ['hospital_conference_room'],
    'host city': ['host_city'],
    'hotel adjacent': ['hotel_adjacent'],
    'hotel facility': ['hotel_facility'],
    'hour': ['hour'],
    'house production specialist': ['house_production_specialist'],
    'huttig chapel': ['huttig_chapel'],
    'huttig memorial chapel': ['huttig_memorial_chapel'],
    'ideal institutional foundation': ['ideal_institutional_foundation'],
    'ii': ['ii'],
    'immigrant': ['immigrant'],
    'impact': ['impact'],
    'important component': ['important_component'],
    'important decision': ['important_decision'],
    'important factor': ['important_factor'],
    'impressive stone structure': ['impressive_stone_structure'],
    'improvement plan': ['improvement_plan'],
    'inconvenient': ['inconvenient'],
    'independent accreditation': ['independent_accreditation'],
    'independent charitable entity': ['independent_charitable_entity'],
    'individual donation': ['individual_donation'],
    'information': ['information'],
    'initial construction': ['initial_construction'],
    'initial degree': ['initial_degree'],
    'initiative': ['initiative'],
    'innovative investment': ['innovative_investment'],
    'innovative leadership': ['innovative_leadership'],
    'innovative member': ['innovative_member'],
    'innovative technology': ['innovative_technology'],
    'institute': ['institute'],
    'institution': ['institution'],
    'institutional foundation': ['institutional_foundation'],
    'instrument': ['instrument'],
    'intellectual life': ['intellectual_life'],
    'interior design': ['interior_design'],
    'investment': ['investment'],
    'investor': ['investor'],
    'j&j': ['johnson_and_johnson'],
    'jefferson county': ['jefferson_county'],
    'john bosco': ['john_bosco'],
    'john mullanphy': ['john_mullanphy'],
    'johnson & johnson': ['johnson_and_johnson'],
    'johnson and johnson': ['johnson_and_johnson'],
    'joseph gander': ['joseph_gander'],
    'journey': ['journey'],
    'joyous centennial celebration': ['joyous_centennial_celebration'],
    'june': ['june'],
    'junior college': ['junior_college'],
    'kate kline': ['kate_kline'],
    'keith lovin': ['keith_lovin'],
    'kernaghan': ['kernaghan'],
    'kernaghan hall': ['kernaghan_hall'],
    'key role': ['key_role'],
    'kline': ['kline'],
    'labor event': ['labor_event'],
    'lakes valley conference': ['lakes_valley_conference'],
    'landscape': ['landscape'],
    'language': ['language'],
    'language disorders': ['language_disorders'],
    'lapel pin': ['lapel_pin'],
    'large site': ['large_site'],
    'lay board': ['lay_board'],
    'lay president': ['lay_president'],
    'leader': ['leader'],
    'leadership': ['leadership'],
    'leadership fundraising campaign': ['leadership_fundraising_campaign'],
    'learning': ['learning'],
    'learning app': ['learning_app'],
    'learning ecosystem': ['learning_ecosystem'],
    'learning environment': ['learning_environment'],
    'learning style': ['learning_style'],
    'level': ['level'],
    'level speech': ['level_speech'],
    'liberal art college': ['liberal_art_college'],
    'life': ['life'],
    'life coach': ['life_coach'],
    'like focus': ['like_focus'],
    'limit': ['limit'],
    'lincoln county': ['lincoln_county'],
    'line': ['line'],
    'little ship rebecca': ['little_ship_rebecca'],
    'local board': ['local_board'],
    'location': ['location'],
    'log cabin': ['log_cabin'],
    'logo': ['logo'],
    'logo design': ['logo_design'],
    'lombardi': ['lombardi'],
    'long journey': ['long_journey'],
    'long term health care': ['long_term_health_care'],
    'long-term health care': ['long_term_health_care'],
    'longtime maryville benefactor': ['longtime_maryville_benefactor'],
    'louis blues successful stanley cup': [   'louis_blues_successful_stanley_cup'],
    'louis campus': ['louis_campus'],
    'louis cardinals': ['louis_cardinals'],
    'louis city limit': ['louis_city_limit'],
    'louis county campus': ['louis_county_campus'],
    'louis county parcel': ['louis_county_parcel'],
    'louis county site': ['louis_county_site'],
    'louis culture': ['louis_culture'],
    'louis landscape': ['louis_landscape'],
    'louis region': ['louis_region'],
    'louis scottish rite masons': ['louis_scottish_rite_masons'],
    'louis speaker series': ['louis_speaker_series'],
    'louis university': ['louis_university'],
    'louise padberg': ['louise_padberg'],
    'lounge': ['lounge'],
    'lovin': ['lovin'],
    'low level': ['low_level'],
    'm': ['m'],
    'madeleine sophie barat': ['madeleine_sophie_barat'],
    'main campus building': ['main_campus_building'],
    'main chapel': ['main_chapel'],
    'main staircase': ['main_staircase'],
    'major': ['major'],
    'male leader': ['male_leader'],
    'male patient': ['male_patient'],
    'male student': ['male_student'],
    'man': ['man'],
    'management': ['management'],
    'mandate': ['mandate'],
    'marie kernaghan': ['marie_kernaghan'],
    'marie louise padberg': ['marie_louise_padberg'],
    'marie odeide mouton': ['marie_odeide_mouton'],
    'marion bascom': ['marion_bascom'],
    'marion bascom honors scholarship fund': [   'marion_bascom_honors_scholarship_fund'],
    'marion rose bascom': ['marion_rose_bascom'],
    'mark lombardi': ['mark_lombardi'],
    'market': ['market'],
    'marriott courtyard hotel adjacent': ['marriott_courtyard_hotel_adjacent'],
    'mary blish': ['mary_blish'],
    'mary gray mcnally': ['mary_gray_mcnally'],
    'mary robert edwards': ['mary_robert_edwards'],
    'mary roch rocklage': ['mary_roch_rocklage'],
    'maryville': ['maryville'],
    'maryville academy': ['maryville_academy'],
    'maryville alumnae': ['maryville_alumnae'],
    'maryville benefactor': ['maryville_benefactor'],
    'maryville building': ['maryville_building'],
    'maryville career': ['maryville_career'],
    'maryville centre': ['maryville_centre'],
    'maryville college physics student': ['maryville_college_physics_student'],
    'maryville community': ['maryville_community'],
    'maryville education': ['maryville_education'],
    'maryville faculty': ['maryville_faculty'],
    'maryville glee club': ['maryville_glee_club'],
    'maryville saints': ['maryville_saints'],
    'maryville science club': ['maryville_science_club'],
    'maryville university archives': ['maryville_university_archives'],
    'mascot': ['mascot'],
    'masons': ['masons'],
    'master course material': ['master_course_material'],
    'master degree': ['masters_degree'],
    'master of arts': ['master_of_arts'],
    'master of science': ['master_of_science'],
    'master of science in nursing': ['master_of_science_in_nursing'],
    "master's": ['masters_degree'],
    "master's degree": ['masters_degree'],
    'material': ['material'],
    'mba degree': ['mba_degree'],
    'mcgarry': ['mcgarry'],
    'mcnally': ['mcnally'],
    'meaningful online learning': ['meaningful_online_learning'],
    'medical building': ['medical_building'],
    'medical facility closure': ['medical_facility_closure'],
    'member': ['member'],
    'member local board': ['member_local_board'],
    'memorial chapel': ['memorial_chapel'],
    'mental health': ['mental_health'],
    'mental health challenge': ['mental_health_challenge'],
    'mental health service': ['mental_health_service'],
    'mercy department': ['mercy_department'],
    'mercy grant': ['mercy_grant'],
    'mercy hospital': ['mercy_hospital'],
    'mercy junior college': ['mercy_junior_college'],
    'message': ['message'],
    'mission': ['mission'],
    'mississippi river': ['mississippi_river'],
    'missouri institute': ['missouri_institute'],
    'missouri river': ['missouri_river'],
    'mobile access': ['mobile_access'],
    'modern high': ['modern_high'],
    'modern nursing': ['modern_nursing'],
    'money': ['money'],
    'more': ['more'],
    'morley simon': ['morley_simon'],
    'mortality rate': ['mortality_rate'],
    'mother bascom': ['mother_bascom'],
    'mother kernaghan': ['mother_kernaghan'],
    'mother marie kernaghan': ['mother_marie_kernaghan'],
    'mother marie odeide mouton': ['mother_marie_odeide_mouton'],
    'mother marion bascom': ['mother_marion_bascom'],
    'mother marion bascom honors scholarship fund': [   'mother_marion_bascom_honors_scholarship_fund'],
    'mother marion rose bascom': ['mother_marion_rose_bascom'],
    'mother mary blish': ['mother_mary_blish'],
    'mother mary gray mcnally': ['mother_mary_gray_mcnally'],
    'motivated student': ['motivated_student'],
    'mouton': ['mouton'],
    'mouton hall': ['mouton_hall'],
    'movement': ['movement'],
    'msc': ['master_of_science'],
    'msn': ['master_of_science_in_nursing'],
    'mullanphy': ['mullanphy'],
    'multidimensional leadership': ['multidimensional_leadership'],
    'munich style': ['munich_style'],
    'music therapy': ['music_therapy'],
    'music therapy program': ['music_therapy_program'],
    'musical note': ['musical_note'],
    'nation pride': ['nation_pride'],
    'national attention': ['national_attention'],
    'national certification': ['national_certification'],
    'national institution': ['national_institution'],
    'national scale': ['national_scale'],
    'national search': ['national_search'],
    'national student base': ['national_student_base'],
    'national university': ['national_university'],
    'nationality': ['nationality'],
    'ncaa division ii': ['ncaa_division_ii'],
    'nearby mississippi river': ['nearby_mississippi_river'],
    'necessary': ['necessary'],
    'need': ['need'],
    'neighborhood': ['neighborhood'],
    'new athletic logo': ['new_athletic_logo'],
    'new branding initiative': ['new_branding_initiative'],
    'new building': ['new_building'],
    'new campus': ['new_campus'],
    'new constellation': ['new_constellation'],
    'new family member': ['new_family_member'],
    'new home': ['new_home'],
    'new initiative': ['new_initiative'],
    'new market': ['new_market'],
    'new mercy department': ['new_mercy_department'],
    'new official': ['new_official'],
    'new phase': ['new_phase'],
    'new property': ['new_property'],
    'new religious': ['new_religious'],
    'new residence hall': ['new_residence_hall'],
    'new school': ['new_school'],
    'new south wing': ['new_south_wing'],
    'new structure': ['new_structure'],
    'noble peace prize winner': ['noble_peace_prize_winner'],
    'north central association': ['north_central_association'],
    'note': ['note'],
    'notebook': ['notebook'],
    'np': ['nurse_practitioner'],
    'nps': ['nurse_practitioner'],
    'number': ['number'],
    'nurse': ['nurse'],
    'nurse educator': ['nurse_educator'],
    'nurse practitioner': ['nurse_practitioner'],
    'nursing': ['nursing'],
    'nursing diploma': ['nursing_diploma'],
    'nursing education': ['nursing_education'],
    'nursing home': ['nursing_home'],
    'nursing major': ['nursing_major'],
    'nursing program': ['nursing_program'],
    'nursing school': ['nursing_school'],
    'nursing student': ['nursing_student'],
    'oakwood retirement center': ['oakwood_retirement_center'],
    'observer': ['observer'],
    'occupational therapy': ['occupational_therapy'],
    'odeide mouton': ['odeide_mouton'],
    'offering': ['offering'],
    'office': ['office'],
    'official': ['official'],
    'official program': ['official_program'],
    'old campus': ['old_campus'],
    'old child': ['old_child'],
    'old institution': ['old_institution'],
    'old log cabin': ['old_log_cabin'],
    'old maryville building': ['old_maryville_building'],
    'old university logo': ['old_university_logo'],
    'ongoing training': ['ongoing_training'],
    'online degree program': ['online_degree_program'],
    'online education dan viele': ['online_education_dan_viele'],
    'online education platform': ['online_education_platform'],
    'online learning': ['online_learning'],
    'open field': ['open_field'],
    'opportunity': ['opportunity'],
    'opportunity transforming business': ['opportunity_transforming_business'],
    'optimum learning style': ['optimum_learning_style'],
    'order': ['order'],
    'ordinal': ['ordinal'],
    'organization': ['organization'],
    'original building': ['original_building'],
    'original campus': ['original_campus'],
    'original logo design': ['original_logo_design'],
    'ornate student lounge': ['ornate_student_lounge'],
    'outcome': ['outcome'],
    'outcome evaluation': ['outcome_evaluation'],
    'outreach': ['outreach'],
    'outright grant': ['outright_grant'],
    'outstanding team': ['outstanding_team'],
    'oxford university graduate mother marion rose bascom': [   'oxford_university_graduate_mother_marion_rose_bascom'],
    'padberg': ['padberg'],
    'padberg mcgarry': ['padberg_mcgarry'],
    'parcel': ['parcel'],
    'parent training': ['parent_training'],
    'path': ['path'],
    'patient': ['patient'],
    'patient care': ['patient_care'],
    'patient care coordination': ['patient_care'],
    'patient treatment': ['patient_treatment'],
    'patient treatment plan': ['patient_treatment_plan'],
    'pay': ['pay'],
    'peace prize winner': ['peace_prize_winner'],
    'pediactric patient': ['pediactric_patient'],
    'peer review': ['peer_review'],
    'peggy padberg mcgarry': ['peggy_padberg_mcgarry'],
    'percent': ['percent'],
    'peril': ['peril'],
    'period': ['period'],
    'periodic peer review': ['peer_review'],
    'permanent': ['permanent'],
    'permanent alumnae office': ['permanent_alumnae_office'],
    'person': ['person'],
    'personal belonging': ['personal_belonging'],
    'personal notebook': ['personal_notebook'],
    'personal quality': ['personal_quality'],
    'personal touch': ['personal_touch'],
    'pharmacist': ['pharmacist'],
    'pharmacy': ['pharmacy'],
    'phase': ['phase'],
    'phd': ['doctoral_degree'],
    'philanthropist john mullanphy': ['philanthropist_john_mullanphy'],
    'philippine': ['philippine'],
    'philippine duchesne': ['philippine_duchesne'],
    'physical campus': ['physical_campus'],
    'physical education course': ['physical_education_course'],
    'physical facility': ['physical_facility'],
    'physical site': ['physical_site'],
    'physical therapy': ['physical_therapy'],
    'physical transformation': ['physical_transformation'],
    'physician': ['physician'],
    'physics student': ['physics_student'],
    'pin': ['pin'],
    'pioneer': ['pioneer'],
    'pivotal role': ['pivotal_role'],
    'plan': ['plan'],
    'plan\n': ['plan'],
    'planning committee': ['planning_committee'],
    'platform': ['platform'],
    'platform education': ['platform_education'],
    'pmhnp': ['psychiatric_mental_health_nurse_practitioner'],
    'political activity': ['political_activity'],
    'political group': ['political_group'],
    'political science': ['political_science'],
    'population': ['population'],
    'portable brashear telescope': ['portable_brashear_telescope'],
    'postpandemic era': ['postpandemic_era'],
    'potential': ['potential'],
    'potter hall': ['potter_hall'],
    'powell symphony hall': ['powell_symphony_hall'],
    'practice': ['practice'],
    'predicament': ['predicament'],
    'preliminary evidence': ['preliminary_evidence'],
    'premier dii conference': ['premier_dii_conference'],
    'presidency': ['presidency'],
    'president': ['president'],
    'pride': ['pride'],
    'primary care': ['primary_care'],
    'pritchard': ['pritchard'],
    'private high school': ['private_high_school'],
    'private institution': ['private_institution'],
    'prize winner': ['prize_winner'],
    'problem mother kernaghan': ['problem_mother_kernaghan'],
    'product': ['product'],
    'production specialist': ['production_specialist'],
    'production studio': ['production_studio'],
    'profession': ['profession'],
    'profession education': ['profession_education'],
    'professional career': ['professional_career'],
    'professional development': ['professional_development'],
    'professor': ['professor'],
    'profile': ['profile'],
    'profile information': ['profile_information'],
    'program': ['program'],
    'proper training': ['proper_training'],
    'property': ['property'],
    'protestant church': ['protestant_church'],
    'provider': ['provider'],
    'psychiatric mental health nurse practitioner': [   'psychiatric_mental_health_nurse_practitioner'],
    'public fundraising campaign': ['public_fundraising_campaign'],
    'public health department': ['public_health_department'],
    'qualified student': ['qualified_student'],
    'quality': ['quality'],
    'quantifiable measurement': ['quantifiable_measurement'],
    'quantity': ['quantity'],
    'race bias': ['racial_bias'],
    'racial bias': ['racial_bias'],
    'range strategic plan': ['range_strategic_plan'],
    'reach': ['reach'],
    'readmission': ['readmission'],
    'readmission rate': ['readmission_rate'],
    'real estate investor': ['real_estate_investor'],
    'reason': ['reason'],
    'rebecca': ['rebecca'],
    'receiver': ['receiver'],
    'red bird': ['red_bird'],
    'red cross': ['red_cross'],
    'red m': ['red_m'],
    'reform': ['reform'],
    'reformation': ['reform'],
    'region': ['region'],
    'registered nurse': ['registered_nurse'],
    'regulation': ['regulation'],
    'rehabilitation counseling': ['rehabilitation_counseling'],
    'relaxation room': ['relaxation_room'],
    'relief': ['relief'],
    'religious': ['religious'],
    'religious group': ['religious_group'],
    'religious order': ['religious_order'],
    'remote location': ['remote_location'],
    'required number': ['required_number'],
    'residence hall': ['residence_hall'],
    'residential campus population': ['residential_campus_population'],
    'residential developer taylor morley simon': [   'residential_developer_taylor_morley_simon'],
    'residential student': ['residential_student'],
    'resource': ['resource'],
    'respected faculty': ['respected_faculty'],
    'responsibility': ['responsibility'],
    'retirement center': ['retirement_center'],
    'retirement year': ['retirement_year'],
    'rich experience': ['rich_experience'],
    'rich history': ['rich_history'],
    'rights movement': ['rights_movement'],
    'rigor': ['rigor'],
    'risk child': ['risk_child'],
    'rite clinic': ['rite_clinic'],
    'rite masons': ['rite_masons'],
    'river': ['river'],
    'rn': ['registered_nurse'],
    'rns': ['registered_nurse'],
    'road': ['road'],
    'robert edwards': ['robert_edwards'],
    'robust expansion': ['robust_expansion'],
    'robust learning environment': ['robust_learning_environment'],
    'roch rocklage': ['roch_rocklage'],
    'rocklage': ['rocklage'],
    'role': ['role'],
    'roman catholic church': ['roman_catholic_church'],
    'room': ['room'],
    'room adjacent': ['room_adjacent'],
    'rose bascom': ['rose_bascom'],
    'rose philippine': ['rose_philippine'],
    'rose philippine duchesne': ['rose_philippine_duchesne'],
    'rose window': ['rose_window'],
    'rosemary holland gidionsen': ['rosemary_holland_gidionsen'],
    'round window': ['round_window'],
    'rule\n': ['rule'],
    'rural campus': ['rural_campus'],
    'rural community': ['rural_community'],
    'rural confine': ['rural_confine'],
    'sacred heart convent': ['sacred_heart_convent'],
    'sacred heart era': ['sacred_heart_era'],
    'sacred heart school': ['sacred_heart_school'],
    'saint bernard dog costume': ['saint_bernard_dog_costume'],
    'saint bernard mascot': ['saint_bernard_mascot'],
    'saint louis university': ['saint_louis_university'],
    'saint madeleine sophie barat': ['saint_madeleine_sophie_barat'],
    'saint rose philippine': ['saint_rose_philippine'],
    'saint rose philippine duchesne': ['saint_rose_philippine_duchesne'],
    'saints': ['saints'],
    'saints athletic': ['saints_athletic'],
    'saints hall': ['saints_hall'],
    'saints nation pride': ['saints_nation_pride'],
    'salary': ['pay'],
    'satellite location': ['satellite_location'],
    'scale': ['scale'],
    'scholar': ['scholar'],
    'scholarship fund': ['scholarship_fund'],
    'school': ['school'],
    'school custom': ['school_custom'],
    'school diploma': ['school_diploma'],
    'school year': ['school_year'],
    'science': ['science'],
    'science club': ['science_club'],
    'science department': ['science_department'],
    'science instrument': ['science_instrument'],
    'scottish rite clinic': ['scottish_rite_clinic'],
    'scottish rite masons': ['scottish_rite_masons'],
    'search': ['search'],
    'secret planning committee': ['secret_planning_committee'],
    'select faculty': ['select_faculty'],
    'select number': ['select_number'],
    'sense': ['sense'],
    'series': ['series'],
    'service': ['service'],
    'service man': ['service_man'],
    'session': ['session'],
    'set to close': ['closure'],
    'ship rebecca': ['ship_rebecca'],
    'short year': ['short_year'],
    'shortage': ['shortage'],
    'significant achievement': ['significant_achievement'],
    'significant enrollment growth': ['significant_enrollment_growth'],
    'simon': ['simon'],
    'simon school': ['simon_school'],
    'single red bird': ['single_red_bird'],
    'sister ann webster': ['sister_ann_webster'],
    'sister harriet ann padberg': ['sister_harriet_ann_padberg'],
    'sister harriet switzer': ['sister_harriet_switzer'],
    'sister hildegarde hellmuth': ['sister_hildegarde_hellmuth'],
    'sister mary robert edwards': ['sister_mary_robert_edwards'],
    'sister mary roch rocklage': ['sister_mary_roch_rocklage'],
    'sister padberg': ['sister_padberg'],
    'sister rocklage': ['sister_rocklage'],
    'sister switzer': ['sister_switzer'],
    'sister webster': ['sister_webster'],
    'site': ['site'],
    'sixth president': ['sixth_president'],
    'skill': ['skill'],
    'skill necessary': ['skill_necessary'],
    'small academy': ['small_academy'],
    'small apple': ['small_apple'],
    'small grant': ['small_grant'],
    'small personal notebook': ['small_personal_notebook'],
    'social event': ['social_event'],
    'societal more': ['societal_more'],
    'soft skill': ['soft_skill'],
    'sophie barat': ['sophie_barat'],
    'south county location': ['south_county_location'],
    'south wing': ['south_wing'],
    'spain': ['spain'],
    'spanish': ['spanish'],
    'spanish hospital': ['spanish_hospital'],
    'speaker series': ['speaker_series'],
    'special fundraising event': ['special_fundraising_event'],
    'special holiday edition': ['special_holiday_edition'],
    'special need': ['special_need'],
    'specialist': ['specialist'],
    'speech': ['speech'],
    'sporadic growth': ['sporadic_growth'],
    'sport business': ['sport_business'],
    'stable foundation': ['stable_foundation'],
    'staff': ['staff'],
    'staffing': ['staffing'],
    'staffing level': ['staffing_level'],
    'staffing shortage': ['staffing_shortage'],
    'staircase': ['staircase'],
    'standard': ['standard'],
    'stanley cup': ['stanley_cup'],
    'state educational system': ['state_educational_system'],
    'state mandate': ['state_mandate'],
    'status': ['status'],
    'stone structure': ['stone_structure'],
    'stone terrace': ['stone_terrace'],
    'story': ['story'],
    'story administration building': ['story_administration_building'],
    'story dining hall': ['story_dining_hall'],
    'story tall': ['story_tall'],
    'strategic plan': ['strategic_plan'],
    'strike': ['strike'],
    'strong faith': ['strong_faith'],
    'strong footprint': ['strong_footprint'],
    'structure': ['structure'],
    'student': ['student'],
    'student apartment building': ['student_apartment_building'],
    'student base': ['student_base'],
    'student body': ['student_body'],
    'student commons': ['student_commons'],
    'student enrollment': ['student_enrollment'],
    'student lounge': ['student_lounge'],
    'student master course material': ['student_master_course_material'],
    'student mental health': ['student_mental_health'],
    'student outcome': ['student_outcome'],
    'student outreach': ['student_outreach'],
    'student profile': ['student_profile'],
    'studio': ['studio'],
    'study': ['study'],
    'study habit': ['study_habit'],
    'style': ['style'],
    'subsequent year': ['subsequent_year'],
    'subsidy': ['subsidy'],
    'success': ['success'],
    'successful completion': ['successful_completion'],
    'successful stanley cup': ['successful_stanley_cup'],
    'successful tenure': ['successful_tenure'],
    'sufficient number': ['sufficient_number'],
    'suitable course': ['suitable_course'],
    'superior class': ['superior_class'],
    'support line': ['support_line'],
    'supportive community member': ['supportive_community_member'],
    'surgeon': ['surgeon'],
    'surgery': ['surgery'],
    'switzer': ['switzer'],
    'symbolizing maryville': ['symbolizing_maryville'],
    'symphony hall': ['symphony_hall'],
    'system': ['system'],
    'tall': ['tall'],
    'taylor morley simon': ['taylor_morley_simon'],
    'teaching career': ['teaching_career'],
    'team': ['team'],
    'technology': ['technology'],
    'telescope': ['telescope'],
    'temporarily': ['temporary'],
    'temporary': ['temporary'],
    'tenure': ['tenure'],
    'terrace': ['terrace'],
    'therapy': ['therapy'],
    'therapy program': ['therapy_program'],
    'therapy session': ['therapy_session'],
    'thought leader': ['thought_leader'],
    'time': ['time'],
    'time residential student': ['time_residential_student'],
    'time student': ['time_student'],
    'today': ['today'],
    'tradition': ['tradition'],
    'traditional college': ['traditional_college'],
    'traditional path': ['traditional_path'],
    'traditional undergraduate student': ['traditional_undergraduate_student'],
    'training': ['training'],
    'training event': ['training_event'],
    'transformation': ['transformation'],
    'transforming business': ['transforming_business'],
    'treatment event': ['treatment_event'],
    'trip': ['trip'],
    'trip downtown': ['trip_downtown'],
    'tutorial program': ['tutorial_program'],
    'undergraduate': ['undergraduate'],
    'undergraduate student': ['undergraduate_student'],
    'underprivileged student': ['underprivileged_student'],
    'university': ['university'],
    'university archives': ['university_archives'],
    'university center': ['university_center'],
    'university graduate mother marion rose bascom': [   'university_graduate_mother_marion_rose_bascom'],
    'university logo': ['university_logo'],
    'university status': ['university_status'],
    'unprecedented growth': ['unprecedented_growth'],
    'urban location': ['urban_location'],
    'urgent care': ['urgent_care'],
    'urgent care clinic': ['urgent_care'],
    'urgent care site': ['urgent_care'],
    'valley conference': ['valley_conference'],
    'value': ['value'],
    'varied campus constituency': ['varied_campus_constituency'],
    'vice president': ['vice_president'],
    'viele': ['viele'],
    'villa duchesne': ['villa_duchesne'],
    'virtual relaxation room': ['virtual_relaxation_room'],
    'volunteer faculty member': ['volunteer_faculty_member'],
    'voyage': ['voyage'],
    'walker clinic service': ['walker_clinic_service'],
    'walker college': ['walker_college'],
    'walker hall': ['walker_hall'],
    'walker scottish rite clinic': ['walker_scottish_rite_clinic'],
    'war': ['war'],
    'war ii': ['war_ii'],
    'war relief': ['war_relief'],
    'washington university': ['washington_university'],
    'way': ['way'],
    'webster': ['webster'],
    'weekday class inconvenient': ['weekday_class_inconvenient'],
    'weekend college student': ['weekend_college_student'],
    'weekly dante course': ['weekly_dante_course'],
    'well observer': ['well_observer'],
    'wide improvement plan': ['wide_improvement_plan'],
    'wide main staircase': ['wide_main_staircase'],
    'wide mental health service': ['wide_mental_health_service'],
    'window': ['window'],
    'wing': ['wing'],
    'winner': ['winner'],
    'wise guidance maryville': ['wise_guidance_maryville'],
    'woman': ['woman'],
    'wooden display cabinet': ['wooden_display_cabinet'],
    'work of art': ['work_of_art'],
    'world': ['world'],
    'world leader': ['world_leader'],
    'world war ii': ['world_war_ii'],
    'year': ['year'],
    'year anniversary': ['year_anniversary'],
    'year college': ['year_college'],
    'year degree': ['year_degree'],
    'year period': ['year_period'],
    'young candidate': ['young_candidate'],
    'young college president': ['young_college_president'],
    'young woman': ['young_woman']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
