
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class MaryvilleTypesRev(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'MaryvilleTypes',
            'filename': 'maryville_types',
            'queries': ['subclass.sparql'],
            'reverse': True,
            'transformers': ['types']},
 'source': 'maryville.owl',
 'time': '2022-05-17 11:15:54.032593'}

    __data = {
    'academic_institution': ['different_academic_institution'],
    'academic_offering': ['dynamic_academic_offering'],
    'academic_standard': ['high_academic_standard'],
    'academy': ['small_academy', 'maryville_academy', 'augustinian_academy'],
    'access': ['mobile_access', 'highway_access'],
    'accreditation': ['independent_accreditation'],
    'achievement': ['significant_achievement', 'great_achievement'],
    'acreage_adjacent': ['additional_acreage_adjacent'],
    'activity': [   'political_activity',
                    'practice',
                    'campus_activity',
                    'extracurricular_activity'],
    'adjacent': ['acreage_adjacent', 'room_adjacent', 'hotel_adjacent'],
    'administration_building': ['story_administration_building'],
    'admission': ['readmission'],
    'advanced_practice_registered_nurse': ['nurse_practitioner'],
    'age': ['digital_age'],
    'agent': ['provider', 'receiver', 'person', 'group'],
    'alumnae': ['maryville_alumnae', 'dedicated_alumnae'],
    'alumnae_office': ['permanent_alumnae_office'],
    'ann_padberg': ['harriet_ann_padberg'],
    'ann_webster': ['sister_ann_webster'],
    'anniversary': ['year_anniversary'],
    'apartment_building': ['student_apartment_building'],
    'app': ['learning_app'],
    'apple': ['small_apple'],
    'archives': ['university_archives'],
    'art_college': ['liberal_art_college'],
    'artifact': ['regulation', 'diploma', 'plan', 'rule'],
    'assistance': ['financial_assistance'],
    'association': [   'american_nurses_association',
                       'central_association',
                       'american_association_of_colleges_of_nursing',
                       'alumnae_association'],
    'athletic': ['saints_athletic'],
    'athletic_logo': ['new_athletic_logo'],
    'attention': ['national_attention'],
    'bachelor_of_science': ['bachelor_of_science_in_nursing'],
    'bachelors_degree': ['bachelor_of_science', 'bachelor_of_arts'],
    'barat': ['sophie_barat'],
    'bascom': [   'marion_rose_bascom',
                  'rose_bascom',
                  'mother_bascom',
                  'marion_bascom'],
    'bascom_honors_program': ['coveted_bascom_honors_program'],
    'bascom_honors_scholarship_fund': ['marion_bascom_honors_scholarship_fund'],
    'base': ['student_base'],
    'belonging': ['personal_belonging'],
    'benefactor': ['maryville_benefactor'],
    'bernard_dog_costume': ['saint_bernard_dog_costume'],
    'bernard_mascot': ['saint_bernard_mascot'],
    'bias': ['gender_bias', 'racial_bias'],
    'bird': ['red_bird'],
    'blish': ['mary_blish'],
    'blues_successful_stanley_cup': ['louis_blues_successful_stanley_cup'],
    'board': ['local_board', 'lay_board'],
    'body': ['student_body'],
    'books': ['great_books'],
    'bosco': ['john_bosco'],
    'brand_message': ['dominant_brand_message'],
    'branding_initiative': ['new_branding_initiative'],
    'brashear_telescope': ['portable_brashear_telescope'],
    'building': [   'design_building',
                    'home',
                    'airport',
                    'room',
                    'apartment_building',
                    'maryville_building',
                    'department',
                    'site',
                    'academic_building',
                    'clinic',
                    'campus_building',
                    'new_building',
                    'school',
                    'administration_building',
                    'medical_building',
                    'original_building',
                    'bank_building'],
    'business': ['transforming_business', 'sport_business'],
    'cabin': ['log_cabin'],
    'cabinet': ['display_cabinet'],
    'campaign': ['fundraising_campaign'],
    'campus': [   'louis_campus',
                  'new_campus',
                  'county_campus',
                  'rural_campus',
                  'original_campus',
                  'physical_campus',
                  'old_campus',
                  'fledgling_campus'],
    'campus_building': ['main_campus_building'],
    'campus_constituency': ['varied_campus_constituency'],
    'campus_facility': ['additional_campus_facility'],
    'campus_parcel': ['acre_campus_parcel'],
    'campus_population': ['residential_campus_population'],
    'candidate': ['young_candidate'],
    'cardinals': ['louis_cardinals'],
    'care_event': ['health_care'],
    'care_management': ['health_care_management'],
    'career': ['teaching_career', 'professional_career', 'maryville_career'],
    'catholic_church': ['roman_catholic_church'],
    'celebration': ['centennial_celebration'],
    'centennial_celebration': ['joyous_centennial_celebration'],
    'center': [   'athletic_center',
                  'counseling_center',
                  'retirement_center',
                  'city_center',
                  'university_center',
                  'community_center'],
    'central_association': ['north_central_association'],
    'centre': ['maryville_centre'],
    'certification': ['national_certification'],
    'challenge': ['health_challenge', 'financial_challenge'],
    'chapel': [   'memorial_chapel',
                  'main_chapel',
                  'gothic_chapel',
                  'huttig_chapel'],
    'chapter': ['campus_chapter'],
    'charitable_entity': ['independent_charitable_entity'],
    'child': ['risk_child', 'old_child'],
    'church': ['catholic_church', 'protestant_church'],
    'city': ['episcopal_city', 'host_city'],
    'city_limit': ['louis_city_limit'],
    'class': ['evening_class', 'high_class', 'superior_class', 'gym_class'],
    'class_inconvenient': ['weekday_class_inconvenient'],
    'clinic': ['rite_clinic', 'aphasia_clinic'],
    'clinic_service': ['walker_clinic_service'],
    'clinical_evaluation': ['clinical_outcome_evaluation'],
    'closure': ['facility_closure'],
    'club': ['science_club', 'glee_club'],
    'coach': ['life_coach'],
    'college': [   'year_college',
                   'art_college',
                   'junior_college',
                   'corporate_college',
                   'traditional_college',
                   'walker_college',
                   'evening_college'],
    'college_physics_student': ['maryville_college_physics_student'],
    'college_president': ['young_college_president'],
    'college_student': ['weekend_college_student'],
    'college_subsidy': ['annual_college_subsidy'],
    'commercial_development': ['baur_commercial_development'],
    'committee': ['planning_committee'],
    'commons': ['student_commons'],
    'community': ['rural_community', 'maryville_community'],
    'community_member': ['supportive_community_member'],
    'company': ['johnson_and_johnson'],
    'competency': ['clinical_competency'],
    'completion': ['successful_completion'],
    'component': ['important_component'],
    'condition': ['health'],
    'conference': ['valley_conference', 'dii_conference'],
    'conference_room': ['hospital_conference_room'],
    'confine': ['rural_confine'],
    'constellation': ['new_constellation'],
    'constituency': ['campus_constituency'],
    'construction': ['initial_construction', 'campus_construction'],
    'continent': ['europe'],
    'contract': ['faculty_contract'],
    'convent': ['heart_convent'],
    'costume': ['dog_costume'],
    'counseling': ['rehabilitation_counseling'],
    'country': ['spain'],
    'county': ['franklin_county', 'jefferson_county', 'lincoln_county'],
    'county_campus': ['louis_county_campus'],
    'county_location': ['south_county_location'],
    'county_parcel': ['louis_county_parcel'],
    'county_site': ['louis_county_site'],
    'course': ['dante_course', 'suitable_course', 'education_course'],
    'course_material': ['master_course_material'],
    'courtyard_hotel_adjacent': ['marriott_courtyard_hotel_adjacent'],
    'credit': ['college_credit'],
    'cross': ['red_cross'],
    'culture': ['louis_culture'],
    'cunningham': ['ashlyn_cunningham'],
    'cup': ['stanley_cup'],
    'cushion': ['financial_cushion'],
    'custom': ['school_custom'],
    'dan_viele': ['education_dan_viele'],
    'dante_course': ['weekly_dante_course'],
    'deal': ['great_deal'],
    'decision': ['important_decision'],
    'degree': ['year_degree', 'initial_degree', 'mba_degree', 'college_degree'],
    'degree_program': ['online_degree_program'],
    'department': [   'mercy_department',
                      'health_department',
                      'science_department'],
    'depression': ['great_depression'],
    'design': ['logo_design', 'interior_design', 'graphic_design'],
    'developer_taylor_morley_simon': [   'residential_developer_taylor_morley_simon'],
    'development': ['professional_development', 'commercial_development'],
    'dichotomy': ['contemporary_dichotomy'],
    'difficulty': ['financial_difficulty'],
    'dii_conference': ['premier_dii_conference'],
    'dining_hall': ['story_dining_hall'],
    'diploma': [   'associates_degree',
                   'school_diploma',
                   'masters_degree',
                   'bachelors_degree',
                   'doctoral_degree',
                   'nursing_diploma'],
    'director': ['alumnae_director'],
    'disorders': ['language_disorders'],
    'display_cabinet': ['wooden_display_cabinet'],
    'division_ii': ['ncaa_division_ii'],
    'dog_costume': ['bernard_dog_costume'],
    'donation': ['individual_donation'],
    'downtown': ['trip_downtown'],
    'dress': ['contemporary_dress'],
    'duchesne': ['philippine_duchesne', 'villa_duchesne'],
    'duty': ['classroom_duty'],
    'ecosystem': ['learning_ecosystem'],
    'edition': ['holiday_edition'],
    'education': [   'training',
                     'learning',
                     'development',
                     'maryville_education',
                     'health_care_education',
                     'profession_education',
                     'platform_education'],
    'education_course': ['physical_education_course'],
    'education_dan_viele': ['online_education_dan_viele'],
    'education_landscape': ['high_education_landscape'],
    'education_platform': ['online_education_platform'],
    'education_program': ['adult_education_program'],
    'educational_institution': ['distinguished_educational_institution'],
    'educational_system': ['state_educational_system'],
    'educator': ['nurse_educator'],
    'edwards': ['robert_edwards'],
    'elapsed_time': ['temporary', 'permanent'],
    'enrollment': ['college_enrollment', 'student_enrollment'],
    'enrollment_growth': ['significant_enrollment_growth'],
    'entity': ['charitable_entity'],
    'environment': ['learning_environment'],
    'era': ['postpandemic_era', 'heart_era'],
    'esport_team': ['dominant_esport_team'],
    'estate_investor': ['real_estate_investor'],
    'evaluation': ['clinical_evaluation', 'outcome_evaluation', 'peer_review'],
    'event': [   'evaluation',
                 'labor_event',
                 'history',
                 'care_event',
                 'pay',
                 'century',
                 'closure',
                 'quality',
                 'outcome',
                 'fundraising_event',
                 'athletic_event',
                 'treatment_event',
                 'admission',
                 'shortage',
                 'staffing',
                 'social_event',
                 'reform',
                 'training_event'],
    'evidence': ['preliminary_evidence'],
    'evoke_story': ['era_evoke_story'],
    'expansion': [   'robust_expansion',
                     'astronomical_expansion',
                     'campus_expansion'],
    'experience': ['rich_experience'],
    'facility': [   'additional_facility',
                    'physical_facility',
                    'hotel_facility',
                    'campus_facility'],
    'facility_closure': ['medical_facility_closure'],
    'factor': ['important_factor'],
    'faculty': ['select_faculty', 'respected_faculty', 'maryville_faculty'],
    'faculty_member': ['volunteer_faculty_member'],
    'faith': ['strong_faith'],
    'family_member': ['new_family_member'],
    'family_student_commons': ['buder_family_student_commons'],
    'field': ['athletic_field', 'open_field'],
    'figure': ['community_figure'],
    'firm': ['german_firm'],
    'focus': ['like_focus'],
    'footprint': ['strong_footprint'],
    'fortune': ['good_fortune'],
    'foundation': ['institutional_foundation', 'stable_foundation'],
    'fund': ['scholarship_fund'],
    'fundraising_campaign': [   'public_fundraising_campaign',
                                'leadership_fundraising_campaign'],
    'fundraising_event': ['special_fundraising_event'],
    'gander': ['joseph_gander'],
    'geopolitical_entity': ['city', 'country'],
    'german_firm': ['famed_german_firm'],
    'gidionsen': ['holland_gidionsen'],
    'glee_club': ['maryville_glee_club'],
    'graduate_mother_marion_rose_bascom': [   'university_graduate_mother_marion_rose_bascom'],
    'grant': [   'outright_grant',
                 'mercy_grant',
                 'small_grant',
                 'foundation_grant'],
    'gray_mcnally': ['mary_gray_mcnally'],
    'group': ['political_group', 'association', 'religious_group'],
    'growth': ['unprecedented_growth', 'sporadic_growth', 'enrollment_growth'],
    'guidance_maryville': ['wise_guidance_maryville'],
    'habit': ['study_habit'],
    'hall': [   'gander_hall',
                'saints_hall',
                'symphony_hall',
                'potter_hall',
                'walker_hall',
                'mouton_hall',
                'dining_hall',
                'duchesne_hall',
                'busch_hall',
                'residence_hall',
                'kernaghan_hall',
                'founders_hall'],
    'harriet_ann_padberg': ['sister_harriet_ann_padberg'],
    'harriet_switzer': ['sister_harriet_switzer'],
    'health': ['mental_health'],
    'health_care': [   'patient_care',
                       'primary_care',
                       'acute_care',
                       'long_term_health_care'],
    'health_care_education': ['nursing_education'],
    'health_care_specialist': ['pharmacist', 'nurse', 'physician'],
    'health_challenge': ['mental_health_challenge'],
    'health_department': ['public_health_department'],
    'health_program': ['allied_health_program'],
    'health_service': ['mental_health_service'],
    'heart_convent': ['sacred_heart_convent'],
    'heart_era': ['sacred_heart_era'],
    'heart_school': ['sacred_heart_school'],
    'hellmuth': ['hildegarde_hellmuth'],
    'high': ['modern_high'],
    'high_school': ['private_high_school'],
    'highway_access': ['convenient_highway_access'],
    'hildegarde_hellmuth': ['sister_hildegarde_hellmuth'],
    'history': ['rich_history'],
    'holiday_edition': ['special_holiday_edition'],
    'holland_gidionsen': ['rosemary_holland_gidionsen'],
    'home': ['family_home', 'nursing_home', 'new_home'],
    'honors_program': ['bascom_honors_program'],
    'honors_scholarship_fund': ['bascom_honors_scholarship_fund'],
    'hospital': ['mercy_hospital', 'spanish_hospital'],
    'hotel_adjacent': ['courtyard_hotel_adjacent'],
    'hour': ['course_hour'],
    'ii': ['war_ii', 'division_ii'],
    'immigrant': ['german_immigrant'],
    'impact': ['growth_impact'],
    'improvement_plan': ['wide_improvement_plan'],
    'inconvenient': ['class_inconvenient'],
    'information': ['profile_information'],
    'initiative': ['new_initiative', 'branding_initiative'],
    'institute': ['missouri_institute'],
    'institution': [   'educational_institution',
                       'old_institution',
                       'academic_institution',
                       'private_institution',
                       'national_institution'],
    'institutional_foundation': ['ideal_institutional_foundation'],
    'instrument': ['science_instrument'],
    'investment': ['innovative_investment'],
    'investor': ['estate_investor'],
    'john_mullanphy': ['philanthropist_john_mullanphy'],
    'journey': ['long_journey'],
    'june': ['early_june'],
    'junior_college': ['mercy_junior_college'],
    'kernaghan': ['mother_kernaghan', 'marie_kernaghan'],
    'kline': ['kate_kline'],
    'labor_event': ['strike'],
    'lakes_valley_conference': ['great_lakes_valley_conference'],
    'landscape': ['louis_landscape', 'education_landscape'],
    'language': ['english_language'],
    'language_disorders': ['childhood_language_disorders'],
    'leader': ['male_leader', 'thought_leader', 'world_leader'],
    'leadership': [   'multidimensional_leadership',
                      'education_leadership',
                      'innovative_leadership'],
    'learning': [   'continuous_learning',
                    'high_learning',
                    'online_learning',
                    'active_learning'],
    'learning_app': ['free_learning_app'],
    'learning_ecosystem': ['active_learning_ecosystem'],
    'learning_environment': ['robust_learning_environment'],
    'learning_style': ['optimum_learning_style'],
    'level': ['graduate_level', 'low_level'],
    'life': ['intellectual_life'],
    'limit': ['city_limit'],
    'line': ['support_line'],
    'local_board': ['member_local_board'],
    'location': [   'county_location',
                    'urban_location',
                    'convenient_location',
                    'continent',
                    'remote_location',
                    'satellite_location',
                    'geographic_location'],
    'log_cabin': ['old_log_cabin'],
    'logo': ['bold_logo', 'university_logo', 'athletic_logo'],
    'logo_design': ['original_logo_design'],
    'lombardi': ['mark_lombardi'],
    'louis_university': ['saint_louis_university'],
    'louise_padberg': ['marie_louise_padberg'],
    'lounge': ['faculty_lounge', 'student_lounge'],
    'lovin': ['keith_lovin'],
    'm': ['red_m'],
    'madeleine_sophie_barat': ['saint_madeleine_sophie_barat'],
    'main_staircase': ['wide_main_staircase'],
    'major': ['nursing_major'],
    'man': ['service_man'],
    'management': ['care_management'],
    'mandate': ['state_mandate'],
    'marie_kernaghan': ['mother_marie_kernaghan'],
    'marie_odeide_mouton': ['mother_marie_odeide_mouton'],
    'marion_bascom': ['mother_marion_bascom'],
    'marion_bascom_honors_scholarship_fund': [   'mother_marion_bascom_honors_scholarship_fund'],
    'marion_rose_bascom': ['mother_marion_rose_bascom'],
    'market': ['new_market'],
    'mary_blish': ['mother_mary_blish'],
    'mary_gray_mcnally': ['mother_mary_gray_mcnally'],
    'mary_robert_edwards': ['sister_mary_robert_edwards'],
    'mary_roch_rocklage': ['sister_mary_roch_rocklage'],
    'maryville': ['guidance_maryville', 'symbolizing_maryville'],
    'maryville_benefactor': ['longtime_maryville_benefactor'],
    'maryville_building': ['old_maryville_building'],
    'maryville_centre': ['acre_maryville_centre'],
    'mascot': ['bernard_mascot'],
    'masons': ['rite_masons'],
    'master_course_material': ['student_master_course_material'],
    'master_of_science': ['master_of_science_in_nursing'],
    'masters_degree': ['master_of_arts', 'master_of_science'],
    'material': ['course_material'],
    'mcgarry': ['padberg_mcgarry'],
    'mcnally': ['gray_mcnally'],
    'medical_building': ['hospital', 'pharmacy', 'urgent_care', 'surgery'],
    'member': [   'community_member',
                  'family_member',
                  'faculty_member',
                  'innovative_member'],
    'memorial_chapel': ['huttig_memorial_chapel'],
    'mental_health': ['student_mental_health'],
    'mental_health_service': ['wide_mental_health_service'],
    'mercy_department': ['new_mercy_department'],
    'message': ['brand_message'],
    'mission': ['audacious_mission'],
    'mississippi_river': ['nearby_mississippi_river'],
    'more': ['societal_more'],
    'morley_simon': ['taylor_morley_simon'],
    'mother_kernaghan': ['problem_mother_kernaghan'],
    'mother_marion_rose_bascom': ['graduate_mother_marion_rose_bascom'],
    'mouton': ['odeide_mouton'],
    'movement': ['rights_movement'],
    'mullanphy': ['john_mullanphy'],
    'musical_note': ['blue_musical_note'],
    'nation_pride': ['saints_nation_pride'],
    'national_search': ['extensive_national_search'],
    'nationality': ['american', 'spanish'],
    'necessary': ['skill_necessary'],
    'need': ['special_need'],
    'neighborhood': ['class_neighborhood'],
    'note': ['musical_note'],
    'notebook': ['personal_notebook'],
    'number': ['sufficient_number', 'required_number', 'select_number'],
    'nurse': ['registered_nurse'],
    'nurse_practitioner': [   'psychiatric_mental_health_nurse_practitioner',
                              'family_nurse_practitioner'],
    'nursing': ['historical_nursing', 'modern_nursing'],
    'observer': ['well_observer'],
    'odeide_mouton': ['marie_odeide_mouton'],
    'offering': ['academic_offering', 'graduate_offering'],
    'office': ['fashionable_office', 'alumnae_office'],
    'official': ['new_official'],
    'online_education_platform': ['dynamic_online_education_platform'],
    'online_learning': ['meaningful_online_learning'],
    'opportunity': ['educational_opportunity'],
    'order': ['religious_order'],
    'organization': ['company'],
    'outcome': ['clinical_outcome', 'student_outcome'],
    'outreach': ['student_outreach'],
    'padberg': ['sister_padberg', 'louise_padberg', 'ann_padberg'],
    'padberg_mcgarry': ['peggy_padberg_mcgarry'],
    'parcel': ['campus_parcel', 'acre_parcel', 'county_parcel'],
    'path': ['traditional_path'],
    'patient': [   'male_patient',
                   'elderly_patient',
                   'female_patient',
                   'pediactric_patient'],
    'pay': ['fair_pay'],
    'peace_prize_winner': ['noble_peace_prize_winner'],
    'peril': ['great_peril'],
    'period': ['year_period'],
    'person': ['florence_nightingale'],
    'personal_notebook': ['small_personal_notebook'],
    'pharmacist': ['apothecary'],
    'phase': ['new_phase'],
    'philippine': ['rose_philippine'],
    'philippine_duchesne': ['rose_philippine_duchesne'],
    'physical_facility': ['additional_physical_facility'],
    'physics_student': ['college_physics_student'],
    'pin': ['lapel_pin', 'education_pin'],
    'pioneer': ['great_pioneer'],
    'plan': [   'patient_treatment_plan',
                'improvement_plan',
                'strategic_plan',
                'academic_plan',
                'confidential_plan'],
    'planning_committee': ['secret_planning_committee'],
    'platform': ['education_platform'],
    'population': ['campus_population'],
    'potential': ['full_potential'],
    'practice': ['ethical_practice'],
    'predicament': ['financial_predicament'],
    'presidency': ['college_presidency'],
    'president': [   'fourth_president',
                     'vice_president',
                     'eighth_president',
                     'sixth_president',
                     'lay_president',
                     'college_president'],
    'pride': ['nation_pride'],
    'pritchard': ['claude_pritchard'],
    'prize_winner': ['peace_prize_winner'],
    'production_specialist': ['house_production_specialist'],
    'production_studio': ['art_production_studio'],
    'profession': ['nursing'],
    'profession_education': ['health_profession_education'],
    'professor': ['associate_professor'],
    'profile': ['student_profile'],
    'program': [   'diverse_program',
                   'academic_program',
                   'nursing_program',
                   'honors_program',
                   'educational_program',
                   'therapy_program',
                   'tutorial_program',
                   'graduate_program',
                   'education_program',
                   'official_program',
                   'health_program',
                   'degree_program'],
    'property': ['new_property'],
    'provider': [   'surgeon',
                    'health_care_provider',
                    'specialist',
                    'staff',
                    'educator',
                    'chemist'],
    'quality': ['health_care_quality', 'competency', 'personal_quality'],
    'quantifiable_measurement': [   'mortality_rate',
                                    'staffing_level',
                                    'readmission_rate',
                                    'fail_to_rescue_rate'],
    'quantity': ['quantifiable_measurement'],
    'reach': ['educational_reach'],
    'real_estate_investor': ['adept_real_estate_investor'],
    'reason': ['financial_reason'],
    'rebecca': ['ship_rebecca'],
    'receiver': ['patient', 'student'],
    'red_bird': ['single_red_bird'],
    'red_cross': ['american_red_cross'],
    'red_m': ['big_red_m'],
    'reform': ['health_care_reform'],
    'region': ['louis_region'],
    'registered_nurse': ['advanced_practice_registered_nurse'],
    'relaxation_room': ['virtual_relaxation_room'],
    'relief': ['war_relief'],
    'religious': ['new_religious'],
    'religious_group': ['church'],
    'residence_hall': ['new_residence_hall'],
    'residential_student': ['time_residential_student'],
    'resource': ['financial_resource', 'digital_resource'],
    'responsibility': [   'family_responsibility',
                          'administrative_responsibility'],
    'retirement_center': ['oakwood_retirement_center'],
    'rights_movement': ['civil_rights_movement'],
    'rigor': ['academic_rigor'],
    'rite_clinic': ['scottish_rite_clinic'],
    'rite_masons': ['scottish_rite_masons'],
    'river': ['missouri_river', 'mississippi_river'],
    'road': ['conway_road'],
    'robert_edwards': ['mary_robert_edwards'],
    'roch_rocklage': ['mary_roch_rocklage'],
    'rocklage': ['sister_rocklage', 'roch_rocklage'],
    'role': ['key_role', 'pivotal_role'],
    'room': [   'emergency_room',
                'dining_room',
                'conference_room',
                'relaxation_room'],
    'rose_philippine': ['saint_rose_philippine'],
    'rose_philippine_duchesne': ['saint_rose_philippine_duchesne'],
    'saints': ['maryville_saints'],
    'scale': ['national_scale'],
    'scholar': ['distinguished_scholar'],
    'scholarship_fund': ['honors_scholarship_fund'],
    'school': [   'high_school',
                  'nursing_school',
                  'college',
                  'boarding_school',
                  'day_school',
                  'simon_school',
                  'free_school',
                  'new_school',
                  'heart_school'],
    'science': ['political_science'],
    'science_club': ['maryville_science_club'],
    'scottish_rite_clinic': ['walker_scottish_rite_clinic'],
    'scottish_rite_masons': ['louis_scottish_rite_masons'],
    'search': ['national_search'],
    'sense': ['great_sense'],
    'series': ['speaker_series'],
    'service': ['health_service', 'clinic_service'],
    'session': ['therapy_session'],
    'ship_rebecca': ['little_ship_rebecca'],
    'shortage': ['staffing_shortage'],
    'simon': ['morley_simon'],
    'site': ['county_site', 'physical_site', 'large_site'],
    'skill': ['soft_skill'],
    'skill_necessary': ['communication_skill_necessary'],
    'soft_skill': ['personal_touch', 'empathy'],
    'sophie_barat': ['madeleine_sophie_barat'],
    'south_wing': ['new_south_wing'],
    'speaker_series': ['louis_speaker_series'],
    'specialist': ['production_specialist', 'health_care_specialist'],
    'speech': ['level_speech'],
    'staircase': ['main_staircase'],
    'standard': ['academic_standard'],
    'stanley_cup': ['successful_stanley_cup'],
    'status': ['university_status', 'financial_status'],
    'stone_structure': ['impressive_stone_structure'],
    'story': ['evoke_story'],
    'strategic_plan': ['range_strategic_plan'],
    'structure': [   'academic_structure',
                     'new_structure',
                     'art_structure',
                     'stone_structure'],
    'student': [   'residential_student',
                   'underprivileged_student',
                   'time_student',
                   'motivated_student',
                   'graduate_student',
                   'male_student',
                   'boarding_student',
                   'nursing_student',
                   'undergraduate_student',
                   'freshmen_student',
                   'honor_student',
                   'qualified_student',
                   'adult_student',
                   'physics_student',
                   'college_student'],
    'student_apartment_building': ['additional_student_apartment_building'],
    'student_base': ['national_student_base'],
    'student_commons': ['family_student_commons'],
    'student_lounge': ['ornate_student_lounge'],
    'studio': ['production_studio'],
    'study': ['challenging_study'],
    'study_habit': ['effective_study_habit'],
    'style': ['learning_style', 'munich_style'],
    'subsidy': ['college_subsidy', 'annual_subsidy'],
    'success': ['financial_success'],
    'successful_stanley_cup': ['blues_successful_stanley_cup'],
    'switzer': ['harriet_switzer', 'sister_switzer'],
    'symbolizing_maryville': ['campus_symbolizing_maryville'],
    'symphony_hall': ['powell_symphony_hall'],
    'system': ['educational_system'],
    'tall': ['story_tall'],
    'taylor_morley_simon': ['developer_taylor_morley_simon'],
    'team': [   'outstanding_team',
                'athletic_team',
                'esport_team',
                'dedicated_team'],
    'technology': ['innovative_technology'],
    'telescope': ['brashear_telescope'],
    'tenure': ['successful_tenure'],
    'terrace': ['stone_terrace'],
    'therapy': [   'occupational_therapy',
                   'music_therapy',
                   'physical_therapy',
                   'group_therapy'],
    'therapy_program': ['music_therapy_program'],
    'time': ['elapsed_time', 'difficult_time', 'good_time', 'fourth_time'],
    'today': ['existence_today', 'endowment_today'],
    'tradition': ['beloved_tradition', 'favorite_tradition'],
    'training': [   'ongoing_training',
                    'aid_training',
                    'proper_training',
                    'certification',
                    'clinical_training',
                    'parent_training',
                    'advanced_training'],
    'training_event': ['course'],
    'transformation': ['physical_transformation'],
    'transforming_business': ['opportunity_transforming_business'],
    'treatment_event': ['patient_treatment'],
    'trip': ['day_trip'],
    'trip_downtown': ['cultural_trip_downtown'],
    'undergraduate': ['extensive_undergraduate'],
    'undergraduate_student': ['traditional_undergraduate_student'],
    'university': [   'louis_university',
                      'washington_university',
                      'national_university',
                      'edge_university'],
    'university_archives': ['maryville_university_archives'],
    'university_graduate_mother_marion_rose_bascom': [   'oxford_university_graduate_mother_marion_rose_bascom'],
    'university_logo': ['old_university_logo'],
    'valley_conference': ['lakes_valley_conference'],
    'value': ['cultural_value', 'essential_value'],
    'viele': ['dan_viele'],
    'voyage': ['day_voyage'],
    'war': ['civil_war'],
    'war_ii': ['world_war_ii'],
    'way': ['active_way', 'good_way'],
    'webster': ['ann_webster', 'sister_webster'],
    'window': ['glass_window', 'fifth_window', 'round_window', 'rose_window'],
    'wing': ['south_wing'],
    'winner': ['prize_winner'],
    'woman': ['young_woman'],
    'world': ['digital_world'],
    'year': [   'dozen_year',
                'early_year',
                'retirement_year',
                'short_year',
                'following_year',
                'challenging_year',
                'class_year',
                'subsequent_year',
                'school_year']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
