
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class MaryvilleGrafflNERRev(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'MaryvilleGrafflNER',
            'filename': 'maryville_graffl_ner',
            'firstonly': False,
            'queries': ['ner.sparql % $PREFIX=maryville $NER=grafflNER'],
            'reverse': True,
            'transformers': ['ner']},
 'source': 'maryville.owl',
 'time': '2022-05-17 11:15:53.851593'}

    __data = {
    'ACTIVITY': [   'practice',
                    'activity',
                    'code for ethical practice',
                    'ethical practice',
                    'action',
                    'political activity'],
    'AGENT': [   'pharmacist',
                 'surgeon',
                 'provider',
                 'receiver',
                 'nurse',
                 'physician',
                 'person',
                 'specialist',
                 'patient',
                 'apothecary',
                 'association',
                 'group',
                 'agent',
                 'church',
                 'staff',
                 'educator',
                 'chemist',
                 'student',
                 'aacn',
                 'catholic church',
                 'family nurse practitioner',
                 'pediactric patient',
                 'religious group',
                 'nurse practitioner',
                 'florence nightingale',
                 'health care specialist',
                 'female patient',
                 'pmhnp',
                 'nurse educator',
                 'registered nurse',
                 'american nursing association',
                 'aprn',
                 'np',
                 'elderly patient',
                 'political group',
                 'advanced practice registered nurse',
                 'rns',
                 'rn',
                 'health care provider',
                 'psychiatric mental health nurse practitioner',
                 'male patient',
                 'american association of colleges of nursing',
                 'ana',
                 'nps',
                 'american nurses association',
                 'nursing student',
                 'protestant church',
                 'fnp'],
    'ARTIFACT': [   'regulation',
                    'diploma',
                    'plan',
                    'artifact',
                    'rule',
                    'doctoral',
                    'phd',
                    'msn',
                    'doctoral degree',
                    'bachelor of arts',
                    'master of science in nursing',
                    'msc',
                    'bachelor of science',
                    'nursing diploma',
                    "associate's degree",
                    'baccalaureate level',
                    'patient treatment plan',
                    'master of arts',
                    'bsn',
                    "master's",
                    'aa degree',
                    'master of science',
                    'doctoral degree program',
                    'master degree',
                    'bachelor degree',
                    "bachelor's degree",
                    'associate degree',
                    'artefact',
                    'bachelor of science in nursing',
                    "master's degree"],
    'ASSOC': [   'association',
                 'aacn',
                 'american nursing association',
                 'american association of colleges of nursing',
                 'ana',
                 'american nurses association'],
    'BIAS': ['bias', 'race bias', 'racial bias', 'gender bias'],
    'CARE': [   'acute care',
                'primary care',
                'care event',
                'health care',
                'long term health care',
                'long-term health care',
                'patient care coordination',
                'patient care'],
    'COND': ['health', 'condition', 'mental health'],
    'DIPLOMA': [   'diploma',
                   'doctoral',
                   'phd',
                   'msn',
                   'doctoral degree',
                   'bachelor of arts',
                   'master of science in nursing',
                   'msc',
                   'bachelor of science',
                   'nursing diploma',
                   "associate's degree",
                   'baccalaureate level',
                   'master of arts',
                   'bsn',
                   "master's",
                   'aa degree',
                   'master of science',
                   'doctoral degree program',
                   'master degree',
                   'bachelor degree',
                   "bachelor's degree",
                   'associate degree',
                   'bachelor of science in nursing',
                   "master's degree"],
    'EDU': [   'training',
               'learning',
               'certification',
               'development',
               'education',
               'health care education',
               'professional development',
               'continuous learning',
               'nursing education',
               'advanced clinical training',
               'national certification',
               'continued learning',
               'clinical training',
               'clinical course'],
    'EVAL': [   'evaluation',
                'outcome evaluation',
                'clinical evaluation',
                'clinical outcome evaluation',
                'periodic peer review',
                'peer review'],
    'GROUP': [   'association',
                 'group',
                 'church',
                 'aacn',
                 'catholic church',
                 'religious group',
                 'american nursing association',
                 'political group',
                 'american association of colleges of nursing',
                 'ana',
                 'american nurses association',
                 'protestant church'],
    'MEASURE': [   'fail to rescue rate',
                   'mortality rate',
                   'quantifiable measurement',
                   'failure-to-rescue rates',
                   'staffing level',
                   'readmission rate'],
    'PROFESSION': [   'profession',
                      'nursing',
                      'historical nursing',
                      'modern nursing'],
    'QUALITY': [   'quality',
                   'competency',
                   'health care quality',
                   'clinical competency'],
    'REG': ['regulation'],
    'RULE': ['rule'],
    'SKILL': ['empathy', 'skill', 'personal touch', 'soft skill']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
