
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class MaryvilleLookup(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'MaryvilleLookup',
            'filename': 'maryville_lookup',
            'files': ['maryville.txt'],
            'queries': ['lookup.sparql'],
            'transformers': ['lowercase', 'lookup']},
 'source': 'maryville.owl',
 'time': '2022-05-17 11:15:52.929593'}

    __data = {
    1: [   'responsibility',
           'transformation',
           'undergraduate',
           'constellation',
           'certification',
           'accreditation',
           'neighborhood',
           'construction',
           'inconvenient',
           'constituency',
           'organization',
           'temporarily',
           'opportunity',
           'celebration',
           'anniversary',
           'predicament',
           'environment',
           'achievement',
           'reformation',
           'association',
           'nationality',
           'institution',
           'information',
           'development',
           'readmission',
           'pharmacist',
           'benefactor',
           'specialist',
           'regulation',
           'presidency',
           'instrument',
           'foundation',
           'management',
           'population',
           'assistance',
           'evaluation',
           'initiative',
           'leadership',
           'difficulty',
           'enrollment',
           'cunningham',
           'university',
           'technology',
           'department',
           'experience',
           'philippine',
           'profession',
           'condition\n',
           'apothecary',
           'depression',
           'completion',
           'conference',
           'competency',
           'investment',
           'counseling',
           'temporary',
           'maryville',
           'dichotomy',
           'cardinals',
           'kernaghan',
           'mullanphy',
           'professor',
           'community',
           'education',
           'attention',
           'physician',
           'admission',
           'disorders',
           'condition',
           'gidionsen',
           'institute',
           'religious',
           'committee',
           'telescope',
           'landscape',
           'necessary',
           'structure',
           'expansion',
           'president',
           'continent',
           'immigrant',
           'component',
           'potential',
           'candidate',
           'permanent',
           'staircase',
           'ecosystem',
           'challenge',
           'tradition',
           'pritchard',
           'footprint',
           'belonging',
           'rocklage',
           'material',
           'downtown',
           'platform',
           'facility',
           'receiver',
           'donation',
           'pharmacy',
           'lombardi',
           'contract',
           'practice',
           'standard',
           'official',
           'duration',
           'business',
           'hellmuth',
           'provider',
           "master's",
           'director',
           'language',
           'resource',
           'archives',
           'campaign',
           'notebook',
           'educator',
           'staffing',
           'shortage',
           'doctoral',
           'adjacent',
           'investor',
           'training',
           'quantity',
           'location',
           'observer',
           'artefact',
           'offering',
           'property',
           'building',
           'american',
           'decision',
           'outreach',
           'cardinal',
           'duchesne',
           'evidence',
           'learning',
           'activity',
           'athletic',
           'movement',
           'artifact',
           'hospital',
           'edifice',
           'therapy',
           'mission',
           'pioneer',
           'program',
           'college',
           'commons',
           'history',
           'costume',
           'spanish',
           'confine',
           'session',
           'webster',
           'convent',
           'surgeon',
           'century',
           'mandate',
           'journey',
           'cabinet',
           'ordinal',
           'percent',
           'cushion',
           'academy',
           'closure',
           'culture',
           'country',
           'product',
           'alumnae',
           'profile',
           'chapter',
           'edwards',
           'mcnally',
           'chemist',
           'diploma',
           'mcgarry',
           'rebecca',
           'scholar',
           'empathy',
           'edition',
           'airport',
           'surgery',
           'quality',
           'terrace',
           'science',
           'student',
           'subsidy',
           'patient',
           'switzer',
           'company',
           'faculty',
           'fortune',
           'success',
           'message',
           'service',
           'nursing',
           'outcome',
           'padberg',
           'winner',
           'member',
           'status',
           'county',
           'salary',
           'saints',
           'europe',
           'leader',
           'person',
           'series',
           'region',
           'health',
           'center',
           'strike',
           'reform',
           'factor',
           'chapel',
           'action',
           'mouton',
           'entity',
           'lounge',
           'custom',
           'impact',
           'period',
           'clinic',
           'growth',
           'access',
           'centre',
           'masons',
           'design',
           'window',
           'reason',
           'tenure',
           'gander',
           'studio',
           'church',
           'school',
           'figure',
           'number',
           'credit',
           'mascot',
           'course',
           'office',
           'market',
           'search',
           'system',
           'voyage',
           'degree',
           'speech',
           'campus',
           'career',
           'bascom',
           'relief',
           'parcel',
           'staff',
           'grant',
           'value',
           'rigor',
           'lovin',
           'pride',
           'level',
           'blish',
           'pmhnp',
           'dress',
           'peril',
           'story',
           'faith',
           'habit',
           'scale',
           'field',
           'style',
           'major',
           'rule\n',
           'bosco',
           'cross',
           'agent',
           'focus',
           'viele',
           'books',
           'plan\n',
           'world',
           'study',
           'woman',
           'river',
           'sense',
           'cabin',
           'today',
           'barat',
           'event',
           'group',
           'nurse',
           'phase',
           'board',
           'order',
           'limit',
           'child',
           'skill',
           'class',
           'kline',
           'coach',
           'spain',
           'simon',
           'reach',
           'money',
           'year',
           'rule',
           'road',
           'time',
           'tall',
           'deal',
           'home',
           'hall',
           'firm',
           'aprn',
           'life',
           'body',
           'june',
           'team',
           'aacn',
           'city',
           'wing',
           'more',
           'base',
           'logo',
           'room',
           'line',
           'trip',
           'plan',
           'note',
           'site',
           'club',
           'hour',
           'bias',
           'fund',
           'path',
           'date',
           'duty',
           'bird',
           'need',
           'role',
           'high',
           'pay',
           'phd',
           'era',
           'app',
           'ana',
           'fnp',
           'nps',
           'msc',
           'age',
           'msn',
           'j&j',
           'cup',
           'war',
           'rns',
           'man',
           'bsn',
           'way',
           'pin',
           'er',
           'ii',
           'rn',
           'np',
           'm'],
    2: [   'university_graduate_mother_marion_rose bascom',
           'mother_marion_bascom_honors_scholarship fund',
           'psychiatric_mental_health_nurse practitioner',
           'residential_developer_taylor_morley simon',
           'marion_bascom_honors_scholarship fund',
           'additional_student_apartment building',
           'distinguished_educational institution',
           'graduate_mother_marion_rose bascom',
           'advanced_practice_registered nurse',
           'louis_blues_successful_stanley cup',
           'marriott_courtyard_hotel adjacent',
           'traditional_undergraduate student',
           'maryville_college_physics student',
           'opportunity_transforming business',
           'dynamic_online_education platform',
           'leadership_fundraising campaign',
           'bascom_honors_scholarship fund',
           'student_master_course material',
           'saint_rose_philippine duchesne',
           'different_academic institution',
           'ideal_institutional foundation',
           'independent_charitable entity',
           'coveted_bascom_honors program',
           'story_administration building',
           'great_lakes_valley conference',
           'longtime_maryville benefactor',
           'philanthropist_john mullanphy',
           'maryville_university archives',
           'administrative responsibility',
           'developer_taylor_morley simon',
           'joyous_centennial celebration',
           'communication_skill necessary',
           'residential_campus population',
           'significant_enrollment growth',
           'blues_successful_stanley cup',
           'saint_madeleine_sophie barat',
           'american_nursing association',
           'campus_symbolizing maryville',
           'additional_physical facility',
           'buder_family_student commons',
           'childhood_language disorders',
           'baur_commercial development',
           'additional_acreage adjacent',
           'supportive_community member',
           'robust_learning environment',
           'house_production specialist',
           'american_nurses association',
           'public_fundraising campaign',
           'health_profession education',
           'portable_brashear telescope',
           'walker_scottish_rite clinic',
           'multidimensional leadership',
           'clinical_outcome evaluation',
           'sister_harriet_ann padberg',
           'weekday_class inconvenient',
           'sister_mary_robert edwards',
           'additional_campus facility',
           'online_education_dan viele',
           'student_apartment building',
           'adept_real_estate investor',
           'varied_campus constituency',
           'louis_scottish_rite masons',
           'mother_marie_odeide mouton',
           'rosemary_holland gidionsen',
           'wide_mental_health service',
           'advanced_clinical training',
           'meaningful_online learning',
           'impressive_stone structure',
           'sister_hildegarde hellmuth',
           'rehabilitation counseling',
           'patient_care coordination',
           'active_learning ecosystem',
           'physical_education course',
           'north_central association',
           'secret_planning committee',
           'family_nurse practitioner',
           'special_fundraising event',
           'oakwood_retirement center',
           'independent accreditation',
           'sister_mary_roch rocklage',
           'dynamic_academic offering',
           'online_education platform',
           'saint_bernard_dog costume',
           'convenient_highway access',
           'extensive_national search',
           'mother_marion_rose bascom',
           'professional development',
           'noble_peace_prize winner',
           'hospital_conference room',
           'medical_facility closure',
           'permanent_alumnae office',
           'extracurricular activity',
           'nearby_mississippi river',
           'rose_philippine duchesne',
           'public_health department',
           'quantifiable measurement',
           'high_education landscape',
           'state_educational system',
           'mother_mary_gray mcnally',
           'volunteer_faculty member',
           'courtyard_hotel adjacent',
           'time_residential student',
           'institutional foundation',
           'problem_mother kernaghan',
           'extensive undergraduate',
           'weekend_college student',
           'wise_guidance maryville',
           'educational opportunity',
           'honors_scholarship fund',
           'physical transformation',
           'significant achievement',
           'college_physics student',
           'doctoral_degree program',
           'virtual_relaxation room',
           'failure-to-rescue rates',
           'lakes_valley conference',
           'underprivileged student',
           'educational institution',
           'administration building',
           'young_college president',
           'special_holiday edition',
           'mental_health challenge',
           'new_branding initiative',
           'adult_education program',
           'small_personal notebook',
           'family_student commons',
           'high_academic standard',
           'successful_stanley cup',
           'premier_dii conference',
           'madeleine_sophie barat',
           'patient_treatment plan',
           'optimum_learning style',
           'master_course material',
           'saint_louis university',
           'cultural_trip downtown',
           'astronomical expansion',
           'dominant_brand message',
           'national certification',
           'health_care management',
           'annual_college subsidy',
           'centennial celebration',
           'maryville_science club',
           'health_care specialist',
           'wooden_display cabinet',
           'contemporary dichotomy',
           'commercial development',
           'huttig_memorial chapel',
           'old_maryville building',
           'mother_marie kernaghan',
           'sister_harriet switzer',
           'peggy_padberg mcgarry',
           'effective_study habit',
           'online_degree program',
           'innovative investment',
           'long-term health_care',
           'innovative leadership',
           'roman_catholic church',
           'ornate_student lounge',
           'allied_health program',
           'wide_improvement plan',
           'bascom_honors program',
           'washington university',
           'saint rose_philippine',
           'successful completion',
           'distinguished scholar',
           'student mental_health',
           'south_county location',
           'long-term_health care',
           'saint_rose philippine',
           'student_mental health',
           'walker_clinic service',
           'civil_rights movement',
           'mental_health service',
           'family responsibility',
           'undergraduate student',
           'transforming business',
           'innovative technology',
           'financial predicament',
           'long_term_health care',
           'symbolizing maryville',
           'acre_maryville centre',
           'production specialist',
           'national_student base',
           'music_therapy program',
           'health_care education',
           'art_production studio',
           'original_logo design',
           'main_campus building',
           'louis_speaker series',
           'maryville benefactor',
           'financial assistance',
           'mother_marion bascom',
           'sacred_heart convent',
           'profession education',
           'scottish_rite masons',
           'dominant_esport team',
           'mercy_junior college',
           'academic institution',
           'unprecedented growth',
           'real_estate investor',
           'saint_bernard mascot',
           'new_mercy department',
           'occupational therapy',
           'scottish_rite clinic',
           'learning environment',
           'financial difficulty',
           'florence nightingale',
           'marie_louise padberg',
           'education leadership',
           'national institution',
           'health_care provider',
           'periodic_peer review',
           'initial construction',
           'powell_symphony hall',
           'range_strategic plan',
           'fundraising campaign',
           'preliminary evidence',
           'maryville_glee club',
           'hildegarde hellmuth',
           'baccalaureate level',
           'professional career',
           'clinical competency',
           'residential student',
           'individual donation',
           'sacred_heart school',
           'old_university logo',
           'education landscape',
           'geopolitical entity',
           'maryville education',
           'louis_county parcel',
           'maryville community',
           'bernard_dog costume',
           'harriet_ann padberg',
           'traditional college',
           'liberal_art college',
           'important component',
           'branding initiative',
           'clinical evaluation',
           'profile information',
           'taylor_morley simon',
           'marie_odeide mouton',
           'education_dan viele',
           'mary_robert edwards',
           'louis_county campus',
           'continuous learning',
           'saints_nation pride',
           'associate professor',
           'central association',
           'campus constituency',
           'little_ship rebecca',
           'campus construction',
           'national university',
           'philippine duchesne',
           'educational program',
           'health_care quality',
           'convenient location',
           'augustinian academy',
           'financial challenge',
           'wide_main staircase',
           'university archives',
           'weekly_dante course',
           'additional facility',
           'private institution',
           'alumnae association',
           'private_high school',
           'geographic location',
           'sister_ann webster',
           'mary_roch rocklage',
           'science department',
           'brashear telescope',
           'science instrument',
           'educational system',
           'nurse practitioner',
           'acre_campus parcel',
           'apartment building',
           'financial resource',
           'health_care reform',
           'personal belonging',
           'marion_rose bascom',
           'class inconvenient',
           'college enrollment',
           'education platform',
           'important decision',
           'planning committee',
           'historical nursing',
           'language disorders',
           'satellite location',
           'favorite tradition',
           'college presidency',
           "associate's degree",
           'class neighborhood',
           'contemporary dress',
           'fashionable office',
           'learning ecosystem',
           'continued learning',
           'academic structure',
           'outcome evaluation',
           'american_red cross',
           'missouri institute',
           'student enrollment',
           'new_residence hall',
           'guidance maryville',
           'national attention',
           'peace_prize winner',
           'member_local board',
           'political activity',
           'platform education',
           'maryville building',
           'pediactric patient',
           'urgent_care clinic',
           'staffing shortage',
           'great achievement',
           'charitable entity',
           'clinical training',
           'johnson_& johnson',
           'production studio',
           'advanced training',
           'famed_german firm',
           'dedicated alumnae',
           'political science',
           'counseling center',
           'motivated student',
           'financial success',
           'intellectual life',
           'innovative member',
           'original building',
           'maryville alumnae',
           'blue_musical note',
           'university status',
           'health department',
           'story_dining hall',
           'qualified student',
           'louis_county site',
           'valley conference',
           'academic standard',
           'educational reach',
           'retirement center',
           'academic offering',
           'mother_mary blish',
           'physical facility',
           'graduate offering',
           'sufficient number',
           'nursing education',
           'successful tenure',
           'mary_gray mcnally',
           'university center',
           'education program',
           'associates degree',
           'confidential plan',
           'corporate college',
           'personal notebook',
           'ashlyn cunningham',
           'maryville academy',
           'campus population',
           'fundraising event',
           'free_learning app',
           'stable foundation',
           'patient treatment',
           'mississippi river',
           'beloved tradition',
           'college president',
           'maryville faculty',
           "bachelor's degree",
           'challenging study',
           'audacious mission',
           'financial cushion',
           'holland gidionsen',
           'protestant church',
           'new constellation',
           'enrollment growth',
           'respected faculty',
           'new_athletic logo',
           'academic building',
           'new_family member',
           'alumnae director',
           'eighth president',
           'official program',
           'boarding student',
           'personal quality',
           'digital resource',
           'postpandemic era',
           'maryville career',
           'maryville saints',
           'maryville centre',
           'student outreach',
           'german immigrant',
           'community figure',
           'claude pritchard',
           'spanish hospital',
           'physical therapy',
           'fourth president',
           'graduate program',
           'important factor',
           'improvement plan',
           'facility closure',
           'financial status',
           'health challenge',
           'ongoing training',
           'clinical outcome',
           'louis university',
           'education course',
           'campus expansion',
           'faculty contract',
           'english language',
           'registered nurse',
           'acreage adjacent',
           'readmission rate',
           'ethical practice',
           'mercy department',
           'sacred_heart era',
           'medical building',
           'traditional path',
           'scholarship fund',
           'graduate student',
           'challenging year',
           'community center',
           'great depression',
           'freshmen student',
           'robust expansion',
           'academic program',
           'year anniversary',
           'urgent_care site',
           'community member',
           'outstanding team',
           'bachelors degree',
           'financial reason',
           'jefferson county',
           'mother kernaghan',
           'tutorial program',
           'foundation grant',
           'ncaa_division ii',
           'associate degree',
           'louis_city limit',
           'fledgling campus',
           'strong footprint',
           'single_red bird',
           'doctoral degree',
           'endowment today',
           'rural community',
           'holiday edition',
           'national search',
           'diverse program',
           'campus activity',
           'sporadic growth',
           'proper training',
           'political group',
           'college subsidy',
           'college student',
           'campus building',
           'retirement year',
           'old institution',
           'physics student',
           'therapy program',
           'student commons',
           'course material',
           'conference room',
           'remote location',
           'rose philippine',
           'sister rocklage',
           'rich experience',
           'active learning',
           'nursing diploma',
           'louis cardinals',
           'therapy session',
           'catholic church',
           'estate investor',
           'sixth president',
           'padberg mcgarry',
           'athletic center',
           'franklin county',
           'edge university',
           'care management',
           'student profile',
           'nursing program',
           'treatment event',
           'essential value',
           'student outcome',
           "master's degree",
           'bachelor degree',
           'teaching career',
           'religious group',
           'era_evoke story',
           'evening college',
           'interior design',
           'original campus',
           'subsequent year',
           'parent training',
           'rights movement',
           'campus facility',
           'display cabinet',
           'harriet switzer',
           'boarding school',
           'relaxation room',
           'existence today',
           'religious order',
           'elderly patient',
           'university logo',
           'county location',
           'online learning',
           'skill necessary',
           'louis landscape',
           'design building',
           'marie kernaghan',
           'physical campus',
           'young candidate',
           'clinical course',
           'stone structure',
           'required number',
           'suitable course',
           'memorial chapel',
           'nursing student',
           'saints athletic',
           'campus chapter',
           'junior college',
           'main staircase',
           'episcopal city',
           'learning style',
           'robert edwards',
           'kernaghan hall',
           'nurse educator',
           'athletic field',
           'dii conference',
           'college degree',
           'select faculty',
           'faculty lounge',
           'cultural value',
           'health program',
           'school diploma',
           'alumnae office',
           'female patient',
           'sister webster',
           'aphasia clinic',
           'faculty member',
           'louise padberg',
           'difficult time',
           'walker college',
           'residence hall',
           'national scale',
           'nursing school',
           'graduate level',
           'masters degree',
           'health service',
           'mercy hospital',
           'emergency room',
           'college credit',
           'bernard mascot',
           'classroom duty',
           'urban location',
           'honors program',
           'villa duchesne',
           'vice president',
           'highway access',
           'superior class',
           'full potential',
           'graphic design',
           'hotel facility',
           'training event',
           'athletic event',
           'annual subsidy',
           'mortality rate',
           'student lounge',
           'clinic service',
           'new initiative',
           'outright grant',
           'thought leader',
           'john mullanphy',
           'sport business',
           'new_south wing',
           'modern nursing',
           'personal touch',
           'speaker series',
           'degree program',
           'strategic plan',
           'dedicated team',
           'initial degree',
           'sister padberg',
           'following year',
           'sister switzer',
           'lincoln county',
           'staffing level',
           'hotel adjacent',
           'academic rigor',
           'missouri river',
           'county campus',
           'bank building',
           'state mandate',
           'evening class',
           'stone terrace',
           'county parcel',
           'trip downtown',
           'athletic logo',
           'heart convent',
           'new structure',
           'brand message',
           'symphony hall',
           'athletic team',
           'select number',
           'adult student',
           'louis culture',
           'societal more',
           'family member',
           'music therapy',
           'education pin',
           'group therapy',
           'lay president',
           'roch rocklage',
           'school custom',
           'physical site',
           'small academy',
           'academic plan',
           'joseph gander',
           'marion bascom',
           'campus parcel',
           'mental health',
           'gothic chapel',
           'room adjacent',
           'master degree',
           'digital world',
           'mother bascom',
           'mark lombardi',
           'rural confine',
           'honor student',
           'founders hall',
           'high learning',
           'odeide mouton',
           'nursing major',
           'great pioneer',
           'old_log cabin',
           'art structure',
           'growth impact',
           'huttig chapel',
           'mobile access',
           'duchesne hall',
           'new religious',
           'well observer',
           'prize winner',
           'world_war ii',
           'pivotal role',
           'munich style',
           'fifth window',
           'simon school',
           'student body',
           'louis campus',
           'year college',
           'male patient',
           'time student',
           'social event',
           'glass window',
           'good fortune',
           'rich history',
           'new property',
           'learning app',
           'round window',
           'aid training',
           'special need',
           'louis region',
           'heart school',
           'morley simon',
           'world leader',
           'male student',
           'ship rebecca',
           'dante course',
           'new building',
           'elapsed time',
           'rural campus',
           'long journey',
           'patient care',
           'primary care',
           'new official',
           'strong faith',
           'student base',
           'support line',
           'nursing home',
           'level speech',
           'musical note',
           'gray mcnally',
           'science club',
           'sophie barat',
           'nation pride',
           'rite clinic',
           'stanley cup',
           'high school',
           'modern high',
           'school year',
           'ann webster',
           'city center',
           'german firm',
           'racial bias',
           'saints hall',
           'potter hall',
           'keith lovin',
           'free school',
           'small grant',
           'year degree',
           'young woman',
           'fourth time',
           'walker hall',
           'gander hall',
           'digital age',
           'family home',
           'service man',
           'mouton hall',
           'great sense',
           'male leader',
           'gender bias',
           'urgent care',
           'mercy grant',
           'county site',
           'rose window',
           'logo design',
           'conway road',
           'year period',
           'local board',
           'dining room',
           'health care',
           'main chapel',
           'rose bascom',
           'peer review',
           'art college',
           'acre parcel',
           'dining hall',
           'evoke story',
           'small apple',
           'rite masons',
           'great books',
           'course hour',
           'ann padberg',
           'esport team',
           'dog costume',
           'labor event',
           'study habit',
           'great peril',
           'division ii',
           'early year',
           'life coach',
           'john bosco',
           'great deal',
           'large site',
           'dozen year',
           'new school',
           'kate kline',
           'new market',
           'like focus',
           'high class',
           'short year',
           'class year',
           'day voyage',
           'new campus',
           'south wing',
           'building .',
           'risk child',
           'city limit',
           'acute care',
           'day school',
           'soft skill',
           'active way',
           'war relief',
           'busch hall',
           'story tall',
           'open field',
           'old campus',
           'early june',
           'mba degree',
           'care event',
           'mary blish',
           'gym class',
           'log cabin',
           'old child',
           'good time',
           'bold logo',
           'heart era',
           'new phase',
           'host city',
           'red cross',
           'lapel pin',
           'big_red m',
           'building ',
           'glee club',
           'race bias',
           'lay board',
           'civil war',
           'aa degree',
           'low level',
           'dan viele',
           'fair pay',
           'new home',
           'red bird',
           'key role',
           'good way',
           'day trip',
           'war ii',
           'red m'],
    3: [   'distinguished educational institution',
           'opportunity transforming business',
           'traditional undergraduate student',
           'leadership fundraising campaign',
           'ideal institutional foundation',
           'different academic institution',
           'maryville university archives',
           'longtime maryville benefactor',
           'independent charitable entity',
           'significant enrollment growth',
           'residential campus population',
           'communication skill necessary',
           'philanthropist john mullanphy',
           'joyous centennial celebration',
           'story administration building',
           'american nursing association',
           'additional physical facility',
           'campus symbolizing maryville',
           'childhood language disorders',
           'portable brashear telescope',
           'american nurses association',
           'public fundraising campaign',
           'robust learning environment',
           'supportive community member',
           'baur commercial development',
           'additional acreage adjacent',
           'health profession education',
           'clinical outcome evaluation',
           'house production specialist',
           'impressive stone structure',
           'rosemary holland gidionsen',
           'additional campus facility',
           'student apartment building',
           'meaningful online learning',
           'varied campus constituency',
           'advanced clinical training',
           'weekday class inconvenient',
           'sister hildegarde hellmuth',
           'extensive national search',
           'special fundraising event',
           'dynamic academic offering',
           'family nurse practitioner',
           'patient care coordination',
           'physical education course',
           'north central association',
           'online education platform',
           'active learning ecosystem',
           'secret planning committee',
           'convenient highway access',
           'oakwood retirement center',
           'rose philippine duchesne',
           'time residential student',
           'state educational system',
           'medical facility closure',
           'high education landscape',
           'hospital conference room',
           'permanent alumnae office',
           'courtyard hotel adjacent',
           'nearby mississippi river',
           'problem mother kernaghan',
           'volunteer faculty member',
           'public health department',
           'lakes valley conference',
           'special holiday edition',
           'doctoral degree program',
           'wise guidance maryville',
           'weekend college student',
           'small personal notebook',
           'mental health challenge',
           'virtual relaxation room',
           'adult education program',
           'new branding initiative',
           'college physics student',
           'honors scholarship fund',
           'young college president',
           'dominant brand message',
           'maryville science club',
           'optimum learning style',
           'master course material',
           'high academic standard',
           'wooden display cabinet',
           'successful stanley cup',
           'saint louis university',
           'cultural trip downtown',
           'madeleine sophie barat',
           'health care management',
           'premier dii conference',
           'sister harriet switzer',
           'health care specialist',
           'old maryville building',
           'mother marie kernaghan',
           'annual college subsidy',
           'patient treatment plan',
           'family student commons',
           'huttig memorial chapel',
           'roman catholic church',
           'effective study habit',
           'allied health program',
           'national student base',
           'online degree program',
           'saint rose philippine',
           'mental health service',
           'acre maryville centre',
           'civil rights movement',
           'peggy padberg mcgarry',
           'ornate student lounge',
           'music therapy program',
           'health care education',
           'south county location',
           'bascom honors program',
           'wide improvement plan',
           'art production studio',
           'long-term health care',
           'student mental health',
           'walker clinic service',
           'powell symphony hall',
           'scottish rite masons',
           'new mercy department',
           'range strategic plan',
           'scottish rite clinic',
           'dominant esport team',
           'periodic peer review',
           'health care provider',
           'real estate investor',
           'main campus building',
           'saint bernard mascot',
           'mother marion bascom',
           'mercy junior college',
           'sacred heart convent',
           'marie louise padberg',
           'original logo design',
           'louis speaker series',
           'louis county parcel',
           'health care quality',
           'taylor morley simon',
           'johnson and johnson',
           'saints nation pride',
           'louis county campus',
           'maryville glee club',
           'wide main staircase',
           'sacred heart school',
           'private high school',
           'bernard dog costume',
           'old university logo',
           'bachelor of science',
           'marie odeide mouton',
           'education dan viele',
           'weekly dante course',
           'mary robert edwards',
           'harriet ann padberg',
           'liberal art college',
           'little ship rebecca',
           'member local board',
           'urgent care clinic',
           'health care reform',
           'sister ann webster',
           'marion rose bascom',
           'american red cross',
           'acre campus parcel',
           'mary roch rocklage',
           'peace prize winner',
           'new residence hall',
           'mary gray mcnally',
           'famed german firm',
           'story dining hall',
           'free learning app',
           'louis county site',
           'new athletic logo',
           'johnson & johnson',
           'master of science',
           'new family member',
           'blue musical note',
           'mother mary blish',
           'louis city limit',
           'bachelor of arts',
           'sacred heart era',
           'urgent care site',
           'ncaa division ii',
           'single red bird',
           'era evoke story',
           'new south wing',
           'master of arts',
           'old log cabin',
           'world war ii',
           'set to close',
           'work of art',
           'big red m'],
    4: [   'additional student apartment building',
           'advanced practice registered nurse',
           'marriott courtyard hotel adjacent',
           'dynamic online education platform',
           'maryville college physics student',
           'student master course material',
           'bascom honors scholarship fund',
           'saint rose philippine duchesne',
           'coveted bascom honors program',
           'great lakes valley conference',
           'developer taylor morley simon',
           'blues successful stanley cup',
           'saint madeleine sophie barat',
           'buder family student commons',
           'walker scottish rite clinic',
           'adept real estate investor',
           'sister mary robert edwards',
           'online education dan viele',
           'louis scottish rite masons',
           'sister harriet ann padberg',
           'mother marie odeide mouton',
           'wide mental health service',
           'saint bernard dog costume',
           'sister mary roch rocklage',
           'mother marion rose bascom',
           'code for ethical practice',
           'mother mary gray mcnally',
           'noble peace prize winner',
           'long term health care',
           'fail to rescue rate'],
    5: [   'psychiatric mental health nurse practitioner',
           'residential developer taylor morley simon',
           'marion bascom honors scholarship fund',
           'graduate mother marion rose bascom',
           'louis blues successful stanley cup',
           'bachelor of science in nursing',
           'master of science in nursing'],
    6: [   'university graduate mother marion rose bascom',
           'mother marion bascom honors scholarship fund',
           'american association of colleges of nursing'],
    7: ['oxford university graduate mother marion rose bascom']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
