
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class MaryvilleLabelsRev(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'MaryvilleLabels',
            'filename': 'maryville_labels',
            'queries': ['labels.sparql'],
            'reverse': True,
            'transformers': ['labels']},
 'source': 'maryville.owl',
 'time': '2022-05-17 11:15:54.190593'}

    __data = {
    'Academic Building': ['academic_building'],
    'Academic Institution': ['academic_institution'],
    'Academic Offering': ['academic_offering'],
    'Academic Plan': ['academic_plan'],
    'Academic Program': ['academic_program'],
    'Academic Rigor': ['academic_rigor'],
    'Academic Standard': ['academic_standard'],
    'Academic Structure': ['academic_structure'],
    'Academy': ['academy'],
    'Access': ['access'],
    'Accreditation': ['accreditation'],
    'Achievement': ['achievement'],
    'Acre Campus Parcel': ['acre_campus_parcel'],
    'Acre Maryville Centre': ['acre_maryville_centre'],
    'Acre Parcel': ['acre_parcel'],
    'Acreage Adjacent': ['acreage_adjacent'],
    'Active Learning': ['active_learning'],
    'Active Learning Ecosystem': ['active_learning_ecosystem'],
    'Active Way': ['active_way'],
    'Activity': ['activity'],
    'Acute Care': ['acute_care'],
    'Additional Acreage Adjacent': ['additional_acreage_adjacent'],
    'Additional Campus Facility': ['additional_campus_facility'],
    'Additional Facility': ['additional_facility'],
    'Additional Physical Facility': ['additional_physical_facility'],
    'Additional Student Apartment Building': [   'additional_student_apartment_building'],
    'Adept Real Estate Investor': ['adept_real_estate_investor'],
    'Adjacent': ['adjacent'],
    'Administration Building': ['administration_building'],
    'Administrative Responsibility': ['administrative_responsibility'],
    'Admission': ['admission'],
    'Adult Education Program': ['adult_education_program'],
    'Adult Student': ['adult_student'],
    'Advanced Practice Registered Nurse': [   'advanced_practice_registered_nurse'],
    'Advanced Training': ['advanced_training'],
    'Age': ['age'],
    'Agent': ['agent'],
    'Aid Training': ['aid_training'],
    'Airport': ['airport'],
    'Allied Health Program': ['allied_health_program'],
    'Alumnae': ['alumnae'],
    'Alumnae Association': ['alumnae_association'],
    'Alumnae Director': ['alumnae_director'],
    'Alumnae Office': ['alumnae_office'],
    'American': ['american'],
    'American Association of Colleges of Nursing': [   'american_association_of_colleges_of_nursing'],
    'American Nurses Association': ['american_nurses_association'],
    'American Red Cross': ['american_red_cross'],
    'Ann Padberg': ['ann_padberg'],
    'Ann Webster': ['ann_webster'],
    'Anniversary': ['anniversary'],
    'Annual College Subsidy': ['annual_college_subsidy'],
    'Annual Subsidy': ['annual_subsidy'],
    'Apartment Building': ['apartment_building'],
    'Aphasia Clinic': ['aphasia_clinic'],
    'Apothecary': ['apothecary'],
    'App': ['app'],
    'Archives': ['archives'],
    'Art College': ['art_college'],
    'Art Production Studio': ['art_production_studio'],
    'Art Structure': ['art_structure'],
    'Artifact': ['artifact'],
    'Ashlyn Cunningham': ['ashlyn_cunningham'],
    'Assistance': ['assistance'],
    'Associate Professor': ['associate_professor'],
    "Associate's Degree": ['associates_degree'],
    'Association': ['association'],
    'Astronomical Expansion': ['astronomical_expansion'],
    'Athletic': ['athletic'],
    'Athletic Center': ['athletic_center'],
    'Athletic Event': ['athletic_event'],
    'Athletic Field': ['athletic_field'],
    'Athletic Logo': ['athletic_logo'],
    'Athletic Team': ['athletic_team'],
    'Attention': ['attention'],
    'Audacious Mission': ['audacious_mission'],
    'Augustinian Academy': ['augustinian_academy'],
    'Bachelor of Arts': ['bachelor_of_arts'],
    'Bachelor of Science': ['bachelor_of_science'],
    'Bachelor of Science in Nursing': ['bachelor_of_science_in_nursing'],
    "Bachelor's Degree": ['bachelors_degree'],
    'Bank Building': ['bank_building'],
    'Barat': ['barat'],
    'Bascom': ['bascom'],
    'Bascom Honors Program': ['bascom_honors_program'],
    'Bascom Honors Scholarship Fund': ['bascom_honors_scholarship_fund'],
    'Base': ['base'],
    'Baur Commercial Development': ['baur_commercial_development'],
    'Belonging': ['belonging'],
    'Beloved Tradition': ['beloved_tradition'],
    'Benefactor': ['benefactor'],
    'Bernard Dog Costume': ['bernard_dog_costume'],
    'Bernard Mascot': ['bernard_mascot'],
    'Bias': ['bias'],
    'Big Red M': ['big_red_m'],
    'Bird': ['bird'],
    'Blish': ['blish'],
    'Blue Musical Note': ['blue_musical_note'],
    'Blues Successful Stanley Cup': ['blues_successful_stanley_cup'],
    'Board': ['board'],
    'Boarding School': ['boarding_school'],
    'Boarding Student': ['boarding_student'],
    'Body': ['body'],
    'Bold Logo': ['bold_logo'],
    'Books': ['books'],
    'Bosco': ['bosco'],
    'Brand Message': ['brand_message'],
    'Branding Initiative': ['branding_initiative'],
    'Brashear Telescope': ['brashear_telescope'],
    'Buder Family Student Commons': ['buder_family_student_commons'],
    'Building': ['building'],
    'Building .': ['building'],
    'Busch Hall': ['busch_hall'],
    'Business': ['business'],
    'Cabin': ['cabin'],
    'Cabinet': ['cabinet'],
    'Campaign': ['campaign'],
    'Campus': ['campus'],
    'Campus Activity': ['campus_activity'],
    'Campus Building': ['campus_building'],
    'Campus Chapter': ['campus_chapter'],
    'Campus Constituency': ['campus_constituency'],
    'Campus Construction': ['campus_construction'],
    'Campus Expansion': ['campus_expansion'],
    'Campus Facility': ['campus_facility'],
    'Campus Parcel': ['campus_parcel'],
    'Campus Population': ['campus_population'],
    'Campus Symbolizing Maryville': ['campus_symbolizing_maryville'],
    'Candidate': ['candidate'],
    'Cardinal': ['cardinal'],
    'Cardinals': ['cardinals'],
    'Care Event': ['care_event'],
    'Care Management': ['care_management'],
    'Career': ['career'],
    'Catholic Church': ['catholic_church'],
    'Celebration': ['celebration'],
    'Centennial Celebration': ['centennial_celebration'],
    'Center': ['center'],
    'Central Association': ['central_association'],
    'Centre': ['centre'],
    'Century': ['century'],
    'Certification': ['certification'],
    'Challenge': ['challenge'],
    'Challenging Study': ['challenging_study'],
    'Challenging Year': ['challenging_year'],
    'Chapel': ['chapel'],
    'Chapter': ['chapter'],
    'Charitable Entity': ['charitable_entity'],
    'Chemist': ['chemist'],
    'Child': ['child'],
    'Childhood Language Disorders': ['childhood_language_disorders'],
    'Church': ['church'],
    'City': ['city'],
    'City Center': ['city_center'],
    'City Limit': ['city_limit'],
    'Civil Rights Movement': ['civil_rights_movement'],
    'Civil War': ['civil_war'],
    'Class': ['class'],
    'Class Inconvenient': ['class_inconvenient'],
    'Class Neighborhood': ['class_neighborhood'],
    'Class Year': ['class_year'],
    'Classroom Duty': ['classroom_duty'],
    'Claude Pritchard': ['claude_pritchard'],
    'Clinic': ['clinic'],
    'Clinic Service': ['clinic_service'],
    'Clinical Competency': ['clinical_competency'],
    'Clinical Evaluation': ['clinical_evaluation'],
    'Clinical Outcome': ['clinical_outcome'],
    'Clinical Outcome Evaluation': ['clinical_outcome_evaluation'],
    'Clinical Training': ['clinical_training'],
    'Closure': ['closure'],
    'Club': ['club'],
    'Coach': ['coach'],
    'College': ['college'],
    'College Credit': ['college_credit'],
    'College Degree': ['college_degree'],
    'College Enrollment': ['college_enrollment'],
    'College Physics Student': ['college_physics_student'],
    'College Presidency': ['college_presidency'],
    'College President': ['college_president'],
    'College Student': ['college_student'],
    'College Subsidy': ['college_subsidy'],
    'Commercial Development': ['commercial_development'],
    'Committee': ['committee'],
    'Commons': ['commons'],
    'Communication Skill Necessary': ['communication_skill_necessary'],
    'Community': ['community'],
    'Community Center': ['community_center'],
    'Community Figure': ['community_figure'],
    'Community Member': ['community_member'],
    'Company': ['company'],
    'Competency': ['competency'],
    'Completion': ['completion'],
    'Component': ['component'],
    'Condition': ['condition'],
    'Conference': ['conference'],
    'Conference Room': ['conference_room'],
    'Confidential Plan': ['confidential_plan'],
    'Confine': ['confine'],
    'Constellation': ['constellation'],
    'Constituency': ['constituency'],
    'Construction': ['construction'],
    'Contemporary Dichotomy': ['contemporary_dichotomy'],
    'Contemporary Dress': ['contemporary_dress'],
    'Continent': ['continent'],
    'Continuous Learning': ['continuous_learning'],
    'Contract': ['contract'],
    'Convenient Highway Access': ['convenient_highway_access'],
    'Convenient Location': ['convenient_location'],
    'Convent': ['convent'],
    'Conway Road': ['conway_road'],
    'Corporate College': ['corporate_college'],
    'Costume': ['costume'],
    'Counseling': ['counseling'],
    'Counseling Center': ['counseling_center'],
    'Country': ['country'],
    'County': ['county'],
    'County Campus': ['county_campus'],
    'County Location': ['county_location'],
    'County Parcel': ['county_parcel'],
    'County Site': ['county_site'],
    'Course': ['course'],
    'Course Hour': ['course_hour'],
    'Course Material': ['course_material'],
    'Courtyard Hotel Adjacent': ['courtyard_hotel_adjacent'],
    'Coveted Bascom Honors Program': ['coveted_bascom_honors_program'],
    'Credit': ['credit'],
    'Cross': ['cross'],
    'Cultural Trip Downtown': ['cultural_trip_downtown'],
    'Cultural Value': ['cultural_value'],
    'Culture': ['culture'],
    'Cunningham': ['cunningham'],
    'Cup': ['cup'],
    'Cushion': ['cushion'],
    'Custom': ['custom'],
    'Dan Viele': ['dan_viele'],
    'Dante Course': ['dante_course'],
    'Date': ['date'],
    'Day School': ['day_school'],
    'Day Trip': ['day_trip'],
    'Day Voyage': ['day_voyage'],
    'Deal': ['deal'],
    'Decision': ['decision'],
    'Dedicated Alumnae': ['dedicated_alumnae'],
    'Dedicated Team': ['dedicated_team'],
    'Degree': ['degree'],
    'Degree Program': ['degree_program'],
    'Department': ['department'],
    'Depression': ['depression'],
    'Design': ['design'],
    'Design Building': ['design_building'],
    'Developer Taylor Morley Simon': ['developer_taylor_morley_simon'],
    'Development': ['development'],
    'Dichotomy': ['dichotomy'],
    'Different Academic Institution': ['different_academic_institution'],
    'Difficult Time': ['difficult_time'],
    'Difficulty': ['difficulty'],
    'Digital Age': ['digital_age'],
    'Digital Resource': ['digital_resource'],
    'Digital World': ['digital_world'],
    'Dii Conference': ['dii_conference'],
    'Dining Hall': ['dining_hall'],
    'Dining Room': ['dining_room'],
    'Diploma': ['diploma'],
    'Director': ['director'],
    'Disorders': ['disorders'],
    'Display Cabinet': ['display_cabinet'],
    'Distinguished Educational Institution': [   'distinguished_educational_institution'],
    'Distinguished Scholar': ['distinguished_scholar'],
    'Diverse Program': ['diverse_program'],
    'Division Ii': ['division_ii'],
    'Doctoral Degree': ['doctoral_degree'],
    'Dog Costume': ['dog_costume'],
    'Dominant Brand Message': ['dominant_brand_message'],
    'Dominant Esport Team': ['dominant_esport_team'],
    'Donation': ['donation'],
    'Downtown': ['downtown'],
    'Dozen Year': ['dozen_year'],
    'Dress': ['dress'],
    'Duchesne': ['duchesne'],
    'Duchesne Hall': ['duchesne_hall'],
    'Duty': ['duty'],
    'Dynamic Academic Offering': ['dynamic_academic_offering'],
    'Dynamic Online Education Platform': ['dynamic_online_education_platform'],
    'Early June': ['early_june'],
    'Early Year': ['early_year'],
    'Ecosystem': ['ecosystem'],
    'Edge University': ['edge_university'],
    'Edition': ['edition'],
    'Education': ['education'],
    'Education Course': ['education_course'],
    'Education Dan Viele': ['education_dan_viele'],
    'Education Landscape': ['education_landscape'],
    'Education Leadership': ['education_leadership'],
    'Education Pin': ['education_pin'],
    'Education Platform': ['education_platform'],
    'Education Program': ['education_program'],
    'Educational Institution': ['educational_institution'],
    'Educational Opportunity': ['educational_opportunity'],
    'Educational Program': ['educational_program'],
    'Educational Reach': ['educational_reach'],
    'Educational System': ['educational_system'],
    'Educator': ['educator'],
    'Edwards': ['edwards'],
    'Effective Study Habit': ['effective_study_habit'],
    'Eighth President': ['eighth_president'],
    'Elapsed Time': ['elapsed_time'],
    'Elderly Patient': ['elderly_patient'],
    'Emergency Room': ['emergency_room'],
    'Empathy': ['empathy'],
    'Endowment Today': ['endowment_today'],
    'English Language': ['english_language'],
    'Enrollment': ['enrollment'],
    'Enrollment Growth': ['enrollment_growth'],
    'Entity': ['entity'],
    'Environment': ['environment'],
    'Episcopal City': ['episcopal_city'],
    'Era': ['era'],
    'Era Evoke Story': ['era_evoke_story'],
    'Esport Team': ['esport_team'],
    'Essential Value': ['essential_value'],
    'Estate Investor': ['estate_investor'],
    'Ethical Practice': ['ethical_practice'],
    'Europe': ['europe'],
    'Evaluation': ['evaluation'],
    'Evening Class': ['evening_class'],
    'Evening College': ['evening_college'],
    'Event': ['event'],
    'Evidence': ['evidence'],
    'Evoke Story': ['evoke_story'],
    'Existence Today': ['existence_today'],
    'Expansion': ['expansion'],
    'Experience': ['experience'],
    'Extensive National Search': ['extensive_national_search'],
    'Extensive Undergraduate': ['extensive_undergraduate'],
    'Extracurricular Activity': ['extracurricular_activity'],
    'Facility': ['facility'],
    'Facility Closure': ['facility_closure'],
    'Factor': ['factor'],
    'Faculty': ['faculty'],
    'Faculty Contract': ['faculty_contract'],
    'Faculty Lounge': ['faculty_lounge'],
    'Faculty Member': ['faculty_member'],
    'Fail To Rescue Rate': ['fail_to_rescue_rate'],
    'Fair Pay': ['fair_pay'],
    'Faith': ['faith'],
    'Famed German Firm': ['famed_german_firm'],
    'Family Home': ['family_home'],
    'Family Member': ['family_member'],
    'Family Nurse Practitioner': ['family_nurse_practitioner'],
    'Family Responsibility': ['family_responsibility'],
    'Family Student Commons': ['family_student_commons'],
    'Fashionable Office': ['fashionable_office'],
    'Favorite Tradition': ['favorite_tradition'],
    'Female Patient': ['female_patient'],
    'Field': ['field'],
    'Fifth Window': ['fifth_window'],
    'Figure': ['figure'],
    'Financial Assistance': ['financial_assistance'],
    'Financial Challenge': ['financial_challenge'],
    'Financial Cushion': ['financial_cushion'],
    'Financial Difficulty': ['financial_difficulty'],
    'Financial Predicament': ['financial_predicament'],
    'Financial Reason': ['financial_reason'],
    'Financial Resource': ['financial_resource'],
    'Financial Status': ['financial_status'],
    'Financial Success': ['financial_success'],
    'Firm': ['firm'],
    'Fledgling Campus': ['fledgling_campus'],
    'Florence Nightingale': ['florence_nightingale'],
    'Focus': ['focus'],
    'Following Year': ['following_year'],
    'Footprint': ['footprint'],
    'Fortune': ['fortune'],
    'Foundation': ['foundation'],
    'Foundation Grant': ['foundation_grant'],
    'Founders Hall': ['founders_hall'],
    'Fourth President': ['fourth_president'],
    'Fourth Time': ['fourth_time'],
    'Franklin County': ['franklin_county'],
    'Free Learning App': ['free_learning_app'],
    'Free School': ['free_school'],
    'Freshmen Student': ['freshmen_student'],
    'Full Potential': ['full_potential'],
    'Fund': ['fund'],
    'Fundraising Campaign': ['fundraising_campaign'],
    'Fundraising Event': ['fundraising_event'],
    'Gander': ['gander'],
    'Gander Hall': ['gander_hall'],
    'Gender Bias': ['gender_bias'],
    'Geographic Location': ['geographic_location'],
    'Geopolitical Entity': ['geopolitical_entity'],
    'German Firm': ['german_firm'],
    'German Immigrant': ['german_immigrant'],
    'Gidionsen': ['gidionsen'],
    'Glass Window': ['glass_window'],
    'Glee Club': ['glee_club'],
    'Good Fortune': ['good_fortune'],
    'Good Time': ['good_time'],
    'Good Way': ['good_way'],
    'Gothic Chapel': ['gothic_chapel'],
    'Graduate Level': ['graduate_level'],
    'Graduate Mother Marion Rose Bascom': [   'graduate_mother_marion_rose_bascom'],
    'Graduate Offering': ['graduate_offering'],
    'Graduate Program': ['graduate_program'],
    'Graduate Student': ['graduate_student'],
    'Grant': ['grant'],
    'Graphic Design': ['graphic_design'],
    'Gray Mcnally': ['gray_mcnally'],
    'Great Achievement': ['great_achievement'],
    'Great Books': ['great_books'],
    'Great Deal': ['great_deal'],
    'Great Depression': ['great_depression'],
    'Great Lakes Valley Conference': ['great_lakes_valley_conference'],
    'Great Peril': ['great_peril'],
    'Great Pioneer': ['great_pioneer'],
    'Great Sense': ['great_sense'],
    'Group': ['group'],
    'Group Therapy': ['group_therapy'],
    'Growth': ['growth'],
    'Growth Impact': ['growth_impact'],
    'Guidance Maryville': ['guidance_maryville'],
    'Gym Class': ['gym_class'],
    'Habit': ['habit'],
    'Hall': ['hall'],
    'Harriet Ann Padberg': ['harriet_ann_padberg'],
    'Harriet Switzer': ['harriet_switzer'],
    'Health': ['health'],
    'Health Care': ['health_care'],
    'Health Care Education': ['health_care_education'],
    'Health Care Management': ['health_care_management'],
    'Health Care Provider': ['health_care_provider'],
    'Health Care Quality': ['health_care_quality'],
    'Health Care Reform': ['health_care_reform'],
    'Health Care Specialist': ['health_care_specialist'],
    'Health Challenge': ['health_challenge'],
    'Health Department': ['health_department'],
    'Health Profession Education': ['health_profession_education'],
    'Health Program': ['health_program'],
    'Health Service': ['health_service'],
    'Heart Convent': ['heart_convent'],
    'Heart Era': ['heart_era'],
    'Heart School': ['heart_school'],
    'Hellmuth': ['hellmuth'],
    'High': ['high'],
    'High Academic Standard': ['high_academic_standard'],
    'High Class': ['high_class'],
    'High Education Landscape': ['high_education_landscape'],
    'High Learning': ['high_learning'],
    'High School': ['high_school'],
    'Highway Access': ['highway_access'],
    'Hildegarde Hellmuth': ['hildegarde_hellmuth'],
    'Historical Nursing': ['historical_nursing'],
    'History': ['history'],
    'Holiday Edition': ['holiday_edition'],
    'Holland Gidionsen': ['holland_gidionsen'],
    'Home': ['home'],
    'Honor Student': ['honor_student'],
    'Honors Program': ['honors_program'],
    'Honors Scholarship Fund': ['honors_scholarship_fund'],
    'Hospital': ['hospital'],
    'Hospital Conference Room': ['hospital_conference_room'],
    'Host City': ['host_city'],
    'Hotel Adjacent': ['hotel_adjacent'],
    'Hotel Facility': ['hotel_facility'],
    'Hour': ['hour'],
    'House Production Specialist': ['house_production_specialist'],
    'Huttig Chapel': ['huttig_chapel'],
    'Huttig Memorial Chapel': ['huttig_memorial_chapel'],
    'Ideal Institutional Foundation': ['ideal_institutional_foundation'],
    'Ii': ['ii'],
    'Immigrant': ['immigrant'],
    'Impact': ['impact'],
    'Important Component': ['important_component'],
    'Important Decision': ['important_decision'],
    'Important Factor': ['important_factor'],
    'Impressive Stone Structure': ['impressive_stone_structure'],
    'Improvement Plan': ['improvement_plan'],
    'Inconvenient': ['inconvenient'],
    'Independent Accreditation': ['independent_accreditation'],
    'Independent Charitable Entity': ['independent_charitable_entity'],
    'Individual Donation': ['individual_donation'],
    'Information': ['information'],
    'Initial Construction': ['initial_construction'],
    'Initial Degree': ['initial_degree'],
    'Initiative': ['initiative'],
    'Innovative Investment': ['innovative_investment'],
    'Innovative Leadership': ['innovative_leadership'],
    'Innovative Member': ['innovative_member'],
    'Innovative Technology': ['innovative_technology'],
    'Institute': ['institute'],
    'Institution': ['institution'],
    'Institutional Foundation': ['institutional_foundation'],
    'Instrument': ['instrument'],
    'Intellectual Life': ['intellectual_life'],
    'Interior Design': ['interior_design'],
    'Investment': ['investment'],
    'Investor': ['investor'],
    'Jefferson County': ['jefferson_county'],
    'John Bosco': ['john_bosco'],
    'John Mullanphy': ['john_mullanphy'],
    'Johnson & Johnson': ['johnson_and_johnson'],
    'Joseph Gander': ['joseph_gander'],
    'Journey': ['journey'],
    'Joyous Centennial Celebration': ['joyous_centennial_celebration'],
    'June': ['june'],
    'Junior College': ['junior_college'],
    'Kate Kline': ['kate_kline'],
    'Keith Lovin': ['keith_lovin'],
    'Kernaghan': ['kernaghan'],
    'Kernaghan Hall': ['kernaghan_hall'],
    'Key Role': ['key_role'],
    'Kline': ['kline'],
    'Labor Event': ['labor_event'],
    'Lakes Valley Conference': ['lakes_valley_conference'],
    'Landscape': ['landscape'],
    'Language': ['language'],
    'Language Disorders': ['language_disorders'],
    'Lapel Pin': ['lapel_pin'],
    'Large Site': ['large_site'],
    'Lay Board': ['lay_board'],
    'Lay President': ['lay_president'],
    'Leader': ['leader'],
    'Leadership': ['leadership'],
    'Leadership Fundraising Campaign': ['leadership_fundraising_campaign'],
    'Learning': ['learning'],
    'Learning App': ['learning_app'],
    'Learning Ecosystem': ['learning_ecosystem'],
    'Learning Environment': ['learning_environment'],
    'Learning Style': ['learning_style'],
    'Level': ['level'],
    'Level Speech': ['level_speech'],
    'Liberal Art College': ['liberal_art_college'],
    'Life': ['life'],
    'Life Coach': ['life_coach'],
    'Like Focus': ['like_focus'],
    'Limit': ['limit'],
    'Lincoln County': ['lincoln_county'],
    'Line': ['line'],
    'Little Ship Rebecca': ['little_ship_rebecca'],
    'Local Board': ['local_board'],
    'Location': ['location'],
    'Log Cabin': ['log_cabin'],
    'Logo': ['logo'],
    'Logo Design': ['logo_design'],
    'Lombardi': ['lombardi'],
    'Long Journey': ['long_journey'],
    'Long Term Health Care': ['long_term_health_care'],
    'Longtime Maryville Benefactor': ['longtime_maryville_benefactor'],
    'Louis Blues Successful Stanley Cup': [   'louis_blues_successful_stanley_cup'],
    'Louis Campus': ['louis_campus'],
    'Louis Cardinals': ['louis_cardinals'],
    'Louis City Limit': ['louis_city_limit'],
    'Louis County Campus': ['louis_county_campus'],
    'Louis County Parcel': ['louis_county_parcel'],
    'Louis County Site': ['louis_county_site'],
    'Louis Culture': ['louis_culture'],
    'Louis Landscape': ['louis_landscape'],
    'Louis Region': ['louis_region'],
    'Louis Scottish Rite Masons': ['louis_scottish_rite_masons'],
    'Louis Speaker Series': ['louis_speaker_series'],
    'Louis University': ['louis_university'],
    'Louise Padberg': ['louise_padberg'],
    'Lounge': ['lounge'],
    'Lovin': ['lovin'],
    'Low Level': ['low_level'],
    'M': ['m'],
    'Madeleine Sophie Barat': ['madeleine_sophie_barat'],
    'Main Campus Building': ['main_campus_building'],
    'Main Chapel': ['main_chapel'],
    'Main Staircase': ['main_staircase'],
    'Major': ['major'],
    'Male Leader': ['male_leader'],
    'Male Patient': ['male_patient'],
    'Male Student': ['male_student'],
    'Man': ['man'],
    'Management': ['management'],
    'Mandate': ['mandate'],
    'Marie Kernaghan': ['marie_kernaghan'],
    'Marie Louise Padberg': ['marie_louise_padberg'],
    'Marie Odeide Mouton': ['marie_odeide_mouton'],
    'Marion Bascom': ['marion_bascom'],
    'Marion Bascom Honors Scholarship Fund': [   'marion_bascom_honors_scholarship_fund'],
    'Marion Rose Bascom': ['marion_rose_bascom'],
    'Mark Lombardi': ['mark_lombardi'],
    'Market': ['market'],
    'Marriott Courtyard Hotel Adjacent': ['marriott_courtyard_hotel_adjacent'],
    'Mary Blish': ['mary_blish'],
    'Mary Gray Mcnally': ['mary_gray_mcnally'],
    'Mary Robert Edwards': ['mary_robert_edwards'],
    'Mary Roch Rocklage': ['mary_roch_rocklage'],
    'Maryville': ['maryville'],
    'Maryville Academy': ['maryville_academy'],
    'Maryville Alumnae': ['maryville_alumnae'],
    'Maryville Benefactor': ['maryville_benefactor'],
    'Maryville Building': ['maryville_building'],
    'Maryville Career': ['maryville_career'],
    'Maryville Centre': ['maryville_centre'],
    'Maryville College Physics Student': ['maryville_college_physics_student'],
    'Maryville Community': ['maryville_community'],
    'Maryville Education': ['maryville_education'],
    'Maryville Faculty': ['maryville_faculty'],
    'Maryville Glee Club': ['maryville_glee_club'],
    'Maryville Saints': ['maryville_saints'],
    'Maryville Science Club': ['maryville_science_club'],
    'Maryville University Archives': ['maryville_university_archives'],
    'Mascot': ['mascot'],
    'Masons': ['masons'],
    'Master Course Material': ['master_course_material'],
    'Master of Arts': ['master_of_arts'],
    'Master of Science': ['master_of_science'],
    'Master of Science in Nursing': ['master_of_science_in_nursing'],
    "Master's Degree": ['masters_degree'],
    'Material': ['material'],
    'Mba Degree': ['mba_degree'],
    'Mcgarry': ['mcgarry'],
    'Mcnally': ['mcnally'],
    'Meaningful Online Learning': ['meaningful_online_learning'],
    'Medical Building': ['medical_building'],
    'Medical Facility Closure': ['medical_facility_closure'],
    'Member': ['member'],
    'Member Local Board': ['member_local_board'],
    'Memorial Chapel': ['memorial_chapel'],
    'Mental Health': ['mental_health'],
    'Mental Health Challenge': ['mental_health_challenge'],
    'Mental Health Service': ['mental_health_service'],
    'Mercy Department': ['mercy_department'],
    'Mercy Grant': ['mercy_grant'],
    'Mercy Hospital': ['mercy_hospital'],
    'Mercy Junior College': ['mercy_junior_college'],
    'Message': ['message'],
    'Mission': ['mission'],
    'Mississippi River': ['mississippi_river'],
    'Missouri Institute': ['missouri_institute'],
    'Missouri River': ['missouri_river'],
    'Mobile Access': ['mobile_access'],
    'Modern High': ['modern_high'],
    'Modern Nursing': ['modern_nursing'],
    'Money': ['money'],
    'More': ['more'],
    'Morley Simon': ['morley_simon'],
    'Mortality Rate': ['mortality_rate'],
    'Mother Bascom': ['mother_bascom'],
    'Mother Kernaghan': ['mother_kernaghan'],
    'Mother Marie Kernaghan': ['mother_marie_kernaghan'],
    'Mother Marie Odeide Mouton': ['mother_marie_odeide_mouton'],
    'Mother Marion Bascom': ['mother_marion_bascom'],
    'Mother Marion Bascom Honors Scholarship Fund': [   'mother_marion_bascom_honors_scholarship_fund'],
    'Mother Marion Rose Bascom': ['mother_marion_rose_bascom'],
    'Mother Mary Blish': ['mother_mary_blish'],
    'Mother Mary Gray Mcnally': ['mother_mary_gray_mcnally'],
    'Motivated Student': ['motivated_student'],
    'Mouton': ['mouton'],
    'Mouton Hall': ['mouton_hall'],
    'Movement': ['movement'],
    'Mullanphy': ['mullanphy'],
    'Multidimensional Leadership': ['multidimensional_leadership'],
    'Munich Style': ['munich_style'],
    'Music Therapy': ['music_therapy'],
    'Music Therapy Program': ['music_therapy_program'],
    'Musical Note': ['musical_note'],
    'Nation Pride': ['nation_pride'],
    'National Attention': ['national_attention'],
    'National Certification': ['national_certification'],
    'National Institution': ['national_institution'],
    'National Scale': ['national_scale'],
    'National Search': ['national_search'],
    'National Student Base': ['national_student_base'],
    'National University': ['national_university'],
    'Nationality': ['nationality'],
    'Ncaa Division Ii': ['ncaa_division_ii'],
    'Nearby Mississippi River': ['nearby_mississippi_river'],
    'Necessary': ['necessary'],
    'Need': ['need'],
    'Neighborhood': ['neighborhood'],
    'New Athletic Logo': ['new_athletic_logo'],
    'New Branding Initiative': ['new_branding_initiative'],
    'New Building': ['new_building'],
    'New Campus': ['new_campus'],
    'New Constellation': ['new_constellation'],
    'New Family Member': ['new_family_member'],
    'New Home': ['new_home'],
    'New Initiative': ['new_initiative'],
    'New Market': ['new_market'],
    'New Mercy Department': ['new_mercy_department'],
    'New Official': ['new_official'],
    'New Phase': ['new_phase'],
    'New Property': ['new_property'],
    'New Religious': ['new_religious'],
    'New Residence Hall': ['new_residence_hall'],
    'New School': ['new_school'],
    'New South Wing': ['new_south_wing'],
    'New Structure': ['new_structure'],
    'Noble Peace Prize Winner': ['noble_peace_prize_winner'],
    'North Central Association': ['north_central_association'],
    'Note': ['note'],
    'Notebook': ['notebook'],
    'Number': ['number'],
    'Nurse': ['nurse'],
    'Nurse Educator': ['nurse_educator'],
    'Nurse Practitioner': ['nurse_practitioner'],
    'Nursing': ['nursing'],
    'Nursing Diploma': ['nursing_diploma'],
    'Nursing Education': ['nursing_education'],
    'Nursing Home': ['nursing_home'],
    'Nursing Major': ['nursing_major'],
    'Nursing Program': ['nursing_program'],
    'Nursing School': ['nursing_school'],
    'Nursing Student': ['nursing_student'],
    'Oakwood Retirement Center': ['oakwood_retirement_center'],
    'Observer': ['observer'],
    'Occupational Therapy': ['occupational_therapy'],
    'Odeide Mouton': ['odeide_mouton'],
    'Offering': ['offering'],
    'Office': ['office'],
    'Official': ['official'],
    'Official Program': ['official_program'],
    'Old Campus': ['old_campus'],
    'Old Child': ['old_child'],
    'Old Institution': ['old_institution'],
    'Old Log Cabin': ['old_log_cabin'],
    'Old Maryville Building': ['old_maryville_building'],
    'Old University Logo': ['old_university_logo'],
    'Ongoing Training': ['ongoing_training'],
    'Online Degree Program': ['online_degree_program'],
    'Online Education Dan Viele': ['online_education_dan_viele'],
    'Online Education Platform': ['online_education_platform'],
    'Online Learning': ['online_learning'],
    'Open Field': ['open_field'],
    'Opportunity': ['opportunity'],
    'Opportunity Transforming Business': ['opportunity_transforming_business'],
    'Optimum Learning Style': ['optimum_learning_style'],
    'Order': ['order'],
    'Ordinal': ['ordinal'],
    'Organization': ['organization'],
    'Original Building': ['original_building'],
    'Original Campus': ['original_campus'],
    'Original Logo Design': ['original_logo_design'],
    'Ornate Student Lounge': ['ornate_student_lounge'],
    'Outcome': ['outcome'],
    'Outcome Evaluation': ['outcome_evaluation'],
    'Outreach': ['outreach'],
    'Outright Grant': ['outright_grant'],
    'Outstanding Team': ['outstanding_team'],
    'Oxford University Graduate Mother Marion Rose Bascom': [   'oxford_university_graduate_mother_marion_rose_bascom'],
    'Padberg': ['padberg'],
    'Padberg Mcgarry': ['padberg_mcgarry'],
    'Parcel': ['parcel'],
    'Parent Training': ['parent_training'],
    'Path': ['path'],
    'Patient': ['patient'],
    'Patient Care': ['patient_care'],
    'Patient Treatment': ['patient_treatment'],
    'Patient Treatment Plan': ['patient_treatment_plan'],
    'Pay': ['pay'],
    'Peace Prize Winner': ['peace_prize_winner'],
    'Pediactric Patient': ['pediactric_patient'],
    'Peer Review': ['peer_review'],
    'Peggy Padberg Mcgarry': ['peggy_padberg_mcgarry'],
    'Percent': ['percent'],
    'Peril': ['peril'],
    'Period': ['period'],
    'Permanent': ['permanent'],
    'Permanent Alumnae Office': ['permanent_alumnae_office'],
    'Person': ['person'],
    'Personal Belonging': ['personal_belonging'],
    'Personal Notebook': ['personal_notebook'],
    'Personal Quality': ['personal_quality'],
    'Personal Touch': ['personal_touch'],
    'Pharmacist': ['pharmacist'],
    'Pharmacy': ['pharmacy'],
    'Phase': ['phase'],
    'Philanthropist John Mullanphy': ['philanthropist_john_mullanphy'],
    'Philippine': ['philippine'],
    'Philippine Duchesne': ['philippine_duchesne'],
    'Physical Campus': ['physical_campus'],
    'Physical Education Course': ['physical_education_course'],
    'Physical Facility': ['physical_facility'],
    'Physical Site': ['physical_site'],
    'Physical Therapy': ['physical_therapy'],
    'Physical Transformation': ['physical_transformation'],
    'Physician': ['physician'],
    'Physics Student': ['physics_student'],
    'Pin': ['pin'],
    'Pioneer': ['pioneer'],
    'Pivotal Role': ['pivotal_role'],
    'Plan': ['plan', 'plan'],
    'Planning Committee': ['planning_committee'],
    'Platform': ['platform'],
    'Platform Education': ['platform_education'],
    'Political Activity': ['political_activity'],
    'Political Group': ['political_group'],
    'Political Science': ['political_science'],
    'Population': ['population'],
    'Portable Brashear Telescope': ['portable_brashear_telescope'],
    'Postpandemic Era': ['postpandemic_era'],
    'Potential': ['potential'],
    'Potter Hall': ['potter_hall'],
    'Powell Symphony Hall': ['powell_symphony_hall'],
    'Practice': ['practice'],
    'Predicament': ['predicament'],
    'Preliminary Evidence': ['preliminary_evidence'],
    'Premier Dii Conference': ['premier_dii_conference'],
    'Presidency': ['presidency'],
    'President': ['president'],
    'Pride': ['pride'],
    'Primary Care': ['primary_care'],
    'Pritchard': ['pritchard'],
    'Private High School': ['private_high_school'],
    'Private Institution': ['private_institution'],
    'Prize Winner': ['prize_winner'],
    'Problem Mother Kernaghan': ['problem_mother_kernaghan'],
    'Product': ['product'],
    'Production Specialist': ['production_specialist'],
    'Production Studio': ['production_studio'],
    'Profession': ['profession'],
    'Profession Education': ['profession_education'],
    'Professional Career': ['professional_career'],
    'Professional Development': ['professional_development'],
    'Professor': ['professor'],
    'Profile': ['profile'],
    'Profile Information': ['profile_information'],
    'Program': ['program'],
    'Proper Training': ['proper_training'],
    'Property': ['property'],
    'Protestant Church': ['protestant_church'],
    'Provider': ['provider'],
    'Psychiatric Mental Health Nurse Practitioner': [   'psychiatric_mental_health_nurse_practitioner'],
    'Public Fundraising Campaign': ['public_fundraising_campaign'],
    'Public Health Department': ['public_health_department'],
    'Qualified Student': ['qualified_student'],
    'Quality': ['quality'],
    'Quantifiable Measurement': ['quantifiable_measurement'],
    'Quantity': ['quantity'],
    'Racial Bias': ['racial_bias'],
    'Range Strategic Plan': ['range_strategic_plan'],
    'Reach': ['reach'],
    'Readmission': ['readmission'],
    'Readmission Rate': ['readmission_rate'],
    'Real Estate Investor': ['real_estate_investor'],
    'Reason': ['reason'],
    'Rebecca': ['rebecca'],
    'Receiver': ['receiver'],
    'Red Bird': ['red_bird'],
    'Red Cross': ['red_cross'],
    'Red M': ['red_m'],
    'Reform': ['reform'],
    'Region': ['region'],
    'Registered Nurse': ['registered_nurse'],
    'Regulation': ['regulation'],
    'Rehabilitation Counseling': ['rehabilitation_counseling'],
    'Relaxation Room': ['relaxation_room'],
    'Relief': ['relief'],
    'Religious': ['religious'],
    'Religious Group': ['religious_group'],
    'Religious Order': ['religious_order'],
    'Remote Location': ['remote_location'],
    'Required Number': ['required_number'],
    'Residence Hall': ['residence_hall'],
    'Residential Campus Population': ['residential_campus_population'],
    'Residential Developer Taylor Morley Simon': [   'residential_developer_taylor_morley_simon'],
    'Residential Student': ['residential_student'],
    'Resource': ['resource'],
    'Respected Faculty': ['respected_faculty'],
    'Responsibility': ['responsibility'],
    'Retirement Center': ['retirement_center'],
    'Retirement Year': ['retirement_year'],
    'Rich Experience': ['rich_experience'],
    'Rich History': ['rich_history'],
    'Rights Movement': ['rights_movement'],
    'Rigor': ['rigor'],
    'Risk Child': ['risk_child'],
    'Rite Clinic': ['rite_clinic'],
    'Rite Masons': ['rite_masons'],
    'River': ['river'],
    'Road': ['road'],
    'Robert Edwards': ['robert_edwards'],
    'Robust Expansion': ['robust_expansion'],
    'Robust Learning Environment': ['robust_learning_environment'],
    'Roch Rocklage': ['roch_rocklage'],
    'Rocklage': ['rocklage'],
    'Role': ['role'],
    'Roman Catholic Church': ['roman_catholic_church'],
    'Room': ['room'],
    'Room Adjacent': ['room_adjacent'],
    'Rose Bascom': ['rose_bascom'],
    'Rose Philippine': ['rose_philippine'],
    'Rose Philippine Duchesne': ['rose_philippine_duchesne'],
    'Rose Window': ['rose_window'],
    'Rosemary Holland Gidionsen': ['rosemary_holland_gidionsen'],
    'Round Window': ['round_window'],
    'Rule': ['rule'],
    'Rural Campus': ['rural_campus'],
    'Rural Community': ['rural_community'],
    'Rural Confine': ['rural_confine'],
    'Sacred Heart Convent': ['sacred_heart_convent'],
    'Sacred Heart Era': ['sacred_heart_era'],
    'Sacred Heart School': ['sacred_heart_school'],
    'Saint Bernard Dog Costume': ['saint_bernard_dog_costume'],
    'Saint Bernard Mascot': ['saint_bernard_mascot'],
    'Saint Louis University': ['saint_louis_university'],
    'Saint Madeleine Sophie Barat': ['saint_madeleine_sophie_barat'],
    'Saint Rose Philippine': ['saint_rose_philippine'],
    'Saint Rose Philippine Duchesne': ['saint_rose_philippine_duchesne'],
    'Saints': ['saints'],
    'Saints Athletic': ['saints_athletic'],
    'Saints Hall': ['saints_hall'],
    'Saints Nation Pride': ['saints_nation_pride'],
    'Satellite Location': ['satellite_location'],
    'Scale': ['scale'],
    'Scholar': ['scholar'],
    'Scholarship Fund': ['scholarship_fund'],
    'School': ['school'],
    'School Custom': ['school_custom'],
    'School Diploma': ['school_diploma'],
    'School Year': ['school_year'],
    'Science': ['science'],
    'Science Club': ['science_club'],
    'Science Department': ['science_department'],
    'Science Instrument': ['science_instrument'],
    'Scottish Rite Clinic': ['scottish_rite_clinic'],
    'Scottish Rite Masons': ['scottish_rite_masons'],
    'Search': ['search'],
    'Secret Planning Committee': ['secret_planning_committee'],
    'Select Faculty': ['select_faculty'],
    'Select Number': ['select_number'],
    'Sense': ['sense'],
    'Series': ['series'],
    'Service': ['service'],
    'Service Man': ['service_man'],
    'Session': ['session'],
    'Ship Rebecca': ['ship_rebecca'],
    'Short Year': ['short_year'],
    'Shortage': ['shortage'],
    'Significant Achievement': ['significant_achievement'],
    'Significant Enrollment Growth': ['significant_enrollment_growth'],
    'Simon': ['simon'],
    'Simon School': ['simon_school'],
    'Single Red Bird': ['single_red_bird'],
    'Sister Ann Webster': ['sister_ann_webster'],
    'Sister Harriet Ann Padberg': ['sister_harriet_ann_padberg'],
    'Sister Harriet Switzer': ['sister_harriet_switzer'],
    'Sister Hildegarde Hellmuth': ['sister_hildegarde_hellmuth'],
    'Sister Mary Robert Edwards': ['sister_mary_robert_edwards'],
    'Sister Mary Roch Rocklage': ['sister_mary_roch_rocklage'],
    'Sister Padberg': ['sister_padberg'],
    'Sister Rocklage': ['sister_rocklage'],
    'Sister Switzer': ['sister_switzer'],
    'Sister Webster': ['sister_webster'],
    'Site': ['site'],
    'Sixth President': ['sixth_president'],
    'Skill': ['skill'],
    'Skill Necessary': ['skill_necessary'],
    'Small Academy': ['small_academy'],
    'Small Apple': ['small_apple'],
    'Small Grant': ['small_grant'],
    'Small Personal Notebook': ['small_personal_notebook'],
    'Social Event': ['social_event'],
    'Societal More': ['societal_more'],
    'Soft Skill': ['soft_skill'],
    'Sophie Barat': ['sophie_barat'],
    'South County Location': ['south_county_location'],
    'South Wing': ['south_wing'],
    'Spain': ['spain'],
    'Spanish': ['spanish'],
    'Spanish Hospital': ['spanish_hospital'],
    'Speaker Series': ['speaker_series'],
    'Special Fundraising Event': ['special_fundraising_event'],
    'Special Holiday Edition': ['special_holiday_edition'],
    'Special Need': ['special_need'],
    'Specialist': ['specialist'],
    'Speech': ['speech'],
    'Sporadic Growth': ['sporadic_growth'],
    'Sport Business': ['sport_business'],
    'Stable Foundation': ['stable_foundation'],
    'Staff': ['staff'],
    'Staffing': ['staffing'],
    'Staffing Level': ['staffing_level'],
    'Staffing Shortage': ['staffing_shortage'],
    'Staircase': ['staircase'],
    'Standard': ['standard'],
    'Stanley Cup': ['stanley_cup'],
    'State Educational System': ['state_educational_system'],
    'State Mandate': ['state_mandate'],
    'Status': ['status'],
    'Stone Structure': ['stone_structure'],
    'Stone Terrace': ['stone_terrace'],
    'Story': ['story'],
    'Story Administration Building': ['story_administration_building'],
    'Story Dining Hall': ['story_dining_hall'],
    'Story Tall': ['story_tall'],
    'Strategic Plan': ['strategic_plan'],
    'Strike': ['strike'],
    'Strong Faith': ['strong_faith'],
    'Strong Footprint': ['strong_footprint'],
    'Structure': ['structure'],
    'Student': ['student'],
    'Student Apartment Building': ['student_apartment_building'],
    'Student Base': ['student_base'],
    'Student Body': ['student_body'],
    'Student Commons': ['student_commons'],
    'Student Enrollment': ['student_enrollment'],
    'Student Lounge': ['student_lounge'],
    'Student Master Course Material': ['student_master_course_material'],
    'Student Mental Health': ['student_mental_health'],
    'Student Outcome': ['student_outcome'],
    'Student Outreach': ['student_outreach'],
    'Student Profile': ['student_profile'],
    'Studio': ['studio'],
    'Study': ['study'],
    'Study Habit': ['study_habit'],
    'Style': ['style'],
    'Subsequent Year': ['subsequent_year'],
    'Subsidy': ['subsidy'],
    'Success': ['success'],
    'Successful Completion': ['successful_completion'],
    'Successful Stanley Cup': ['successful_stanley_cup'],
    'Successful Tenure': ['successful_tenure'],
    'Sufficient Number': ['sufficient_number'],
    'Suitable Course': ['suitable_course'],
    'Superior Class': ['superior_class'],
    'Support Line': ['support_line'],
    'Supportive Community Member': ['supportive_community_member'],
    'Surgeon': ['surgeon'],
    'Surgery': ['surgery'],
    'Switzer': ['switzer'],
    'Symbolizing Maryville': ['symbolizing_maryville'],
    'Symphony Hall': ['symphony_hall'],
    'System': ['system'],
    'Tall': ['tall'],
    'Taylor Morley Simon': ['taylor_morley_simon'],
    'Teaching Career': ['teaching_career'],
    'Team': ['team'],
    'Technology': ['technology'],
    'Telescope': ['telescope'],
    'Temporary': ['temporary'],
    'Tenure': ['tenure'],
    'Terrace': ['terrace'],
    'Therapy': ['therapy'],
    'Therapy Program': ['therapy_program'],
    'Therapy Session': ['therapy_session'],
    'Thought Leader': ['thought_leader'],
    'Time': ['time'],
    'Time Residential Student': ['time_residential_student'],
    'Time Student': ['time_student'],
    'Today': ['today'],
    'Tradition': ['tradition'],
    'Traditional College': ['traditional_college'],
    'Traditional Path': ['traditional_path'],
    'Traditional Undergraduate Student': ['traditional_undergraduate_student'],
    'Training': ['training'],
    'Training Event': ['training_event'],
    'Transformation': ['transformation'],
    'Transforming Business': ['transforming_business'],
    'Treatment Event': ['treatment_event'],
    'Trip': ['trip'],
    'Trip Downtown': ['trip_downtown'],
    'Tutorial Program': ['tutorial_program'],
    'Undergraduate': ['undergraduate'],
    'Undergraduate Student': ['undergraduate_student'],
    'Underprivileged Student': ['underprivileged_student'],
    'University': ['university'],
    'University Archives': ['university_archives'],
    'University Center': ['university_center'],
    'University Graduate Mother Marion Rose Bascom': [   'university_graduate_mother_marion_rose_bascom'],
    'University Logo': ['university_logo'],
    'University Status': ['university_status'],
    'Unprecedented Growth': ['unprecedented_growth'],
    'Urban Location': ['urban_location'],
    'Urgent Care': ['urgent_care'],
    'Valley Conference': ['valley_conference'],
    'Value': ['value'],
    'Varied Campus Constituency': ['varied_campus_constituency'],
    'Vice President': ['vice_president'],
    'Viele': ['viele'],
    'Villa Duchesne': ['villa_duchesne'],
    'Virtual Relaxation Room': ['virtual_relaxation_room'],
    'Volunteer Faculty Member': ['volunteer_faculty_member'],
    'Voyage': ['voyage'],
    'Walker Clinic Service': ['walker_clinic_service'],
    'Walker College': ['walker_college'],
    'Walker Hall': ['walker_hall'],
    'Walker Scottish Rite Clinic': ['walker_scottish_rite_clinic'],
    'War': ['war'],
    'War Ii': ['war_ii'],
    'War Relief': ['war_relief'],
    'Washington University': ['washington_university'],
    'Way': ['way'],
    'Webster': ['webster'],
    'Weekday Class Inconvenient': ['weekday_class_inconvenient'],
    'Weekend College Student': ['weekend_college_student'],
    'Weekly Dante Course': ['weekly_dante_course'],
    'Well Observer': ['well_observer'],
    'Wide Improvement Plan': ['wide_improvement_plan'],
    'Wide Main Staircase': ['wide_main_staircase'],
    'Wide Mental Health Service': ['wide_mental_health_service'],
    'Window': ['window'],
    'Wing': ['wing'],
    'Winner': ['winner'],
    'Wise Guidance Maryville': ['wise_guidance_maryville'],
    'Woman': ['woman'],
    'Wooden Display Cabinet': ['wooden_display_cabinet'],
    'Work of Art': ['work_of_art'],
    'World': ['world'],
    'World Leader': ['world_leader'],
    'World War Ii': ['world_war_ii'],
    'Year': ['year'],
    'Year Anniversary': ['year_anniversary'],
    'Year College': ['year_college'],
    'Year Degree': ['year_degree'],
    'Year Period': ['year_period'],
    'Young Candidate': ['young_candidate'],
    'Young College President': ['young_college_president'],
    'Young Woman': ['young_woman']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
