
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class MaryvilleLabels(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'MaryvilleLabels',
            'filename': 'maryville_labels',
            'queries': ['labels.sparql'],
            'reverse': True,
            'transformers': ['labels']},
 'source': 'maryville.owl',
 'time': '2022-05-17 11:15:54.178593'}

    __data = {
    'academic_building': ['Academic Building'],
    'academic_institution': ['Academic Institution'],
    'academic_offering': ['Academic Offering'],
    'academic_plan': ['Academic Plan'],
    'academic_program': ['Academic Program'],
    'academic_rigor': ['Academic Rigor'],
    'academic_standard': ['Academic Standard'],
    'academic_structure': ['Academic Structure'],
    'academy': ['Academy'],
    'access': ['Access'],
    'accreditation': ['Accreditation'],
    'achievement': ['Achievement'],
    'acre_campus_parcel': ['Acre Campus Parcel'],
    'acre_maryville_centre': ['Acre Maryville Centre'],
    'acre_parcel': ['Acre Parcel'],
    'acreage_adjacent': ['Acreage Adjacent'],
    'active_learning': ['Active Learning'],
    'active_learning_ecosystem': ['Active Learning Ecosystem'],
    'active_way': ['Active Way'],
    'activity': ['Activity'],
    'acute_care': ['Acute Care'],
    'additional_acreage_adjacent': ['Additional Acreage Adjacent'],
    'additional_campus_facility': ['Additional Campus Facility'],
    'additional_facility': ['Additional Facility'],
    'additional_physical_facility': ['Additional Physical Facility'],
    'additional_student_apartment_building': [   'Additional Student Apartment '
                                                 'Building'],
    'adept_real_estate_investor': ['Adept Real Estate Investor'],
    'adjacent': ['Adjacent'],
    'administration_building': ['Administration Building'],
    'administrative_responsibility': ['Administrative Responsibility'],
    'admission': ['Admission'],
    'adult_education_program': ['Adult Education Program'],
    'adult_student': ['Adult Student'],
    'advanced_practice_registered_nurse': [   'Advanced Practice Registered '
                                              'Nurse'],
    'advanced_training': ['Advanced Training'],
    'age': ['Age'],
    'agent': ['Agent'],
    'aid_training': ['Aid Training'],
    'airport': ['Airport'],
    'allied_health_program': ['Allied Health Program'],
    'alumnae': ['Alumnae'],
    'alumnae_association': ['Alumnae Association'],
    'alumnae_director': ['Alumnae Director'],
    'alumnae_office': ['Alumnae Office'],
    'american': ['American'],
    'american_association_of_colleges_of_nursing': [   'American Association '
                                                       'of Colleges of '
                                                       'Nursing'],
    'american_nurses_association': ['American Nurses Association'],
    'american_red_cross': ['American Red Cross'],
    'ann_padberg': ['Ann Padberg'],
    'ann_webster': ['Ann Webster'],
    'anniversary': ['Anniversary'],
    'annual_college_subsidy': ['Annual College Subsidy'],
    'annual_subsidy': ['Annual Subsidy'],
    'apartment_building': ['Apartment Building'],
    'aphasia_clinic': ['Aphasia Clinic'],
    'apothecary': ['Apothecary'],
    'app': ['App'],
    'archives': ['Archives'],
    'art_college': ['Art College'],
    'art_production_studio': ['Art Production Studio'],
    'art_structure': ['Art Structure'],
    'artifact': ['Artifact'],
    'ashlyn_cunningham': ['Ashlyn Cunningham'],
    'assistance': ['Assistance'],
    'associate_professor': ['Associate Professor'],
    'associates_degree': ["Associate's Degree"],
    'association': ['Association'],
    'astronomical_expansion': ['Astronomical Expansion'],
    'athletic': ['Athletic'],
    'athletic_center': ['Athletic Center'],
    'athletic_event': ['Athletic Event'],
    'athletic_field': ['Athletic Field'],
    'athletic_logo': ['Athletic Logo'],
    'athletic_team': ['Athletic Team'],
    'attention': ['Attention'],
    'audacious_mission': ['Audacious Mission'],
    'augustinian_academy': ['Augustinian Academy'],
    'bachelor_of_arts': ['Bachelor of Arts'],
    'bachelor_of_science': ['Bachelor of Science'],
    'bachelor_of_science_in_nursing': ['Bachelor of Science in Nursing'],
    'bachelors_degree': ["Bachelor's Degree"],
    'bank_building': ['Bank Building'],
    'barat': ['Barat'],
    'bascom': ['Bascom'],
    'bascom_honors_program': ['Bascom Honors Program'],
    'bascom_honors_scholarship_fund': ['Bascom Honors Scholarship Fund'],
    'base': ['Base'],
    'baur_commercial_development': ['Baur Commercial Development'],
    'belonging': ['Belonging'],
    'beloved_tradition': ['Beloved Tradition'],
    'benefactor': ['Benefactor'],
    'bernard_dog_costume': ['Bernard Dog Costume'],
    'bernard_mascot': ['Bernard Mascot'],
    'bias': ['Bias'],
    'big_red_m': ['Big Red M'],
    'bird': ['Bird'],
    'blish': ['Blish'],
    'blue_musical_note': ['Blue Musical Note'],
    'blues_successful_stanley_cup': ['Blues Successful Stanley Cup'],
    'board': ['Board'],
    'boarding_school': ['Boarding School'],
    'boarding_student': ['Boarding Student'],
    'body': ['Body'],
    'bold_logo': ['Bold Logo'],
    'books': ['Books'],
    'bosco': ['Bosco'],
    'brand_message': ['Brand Message'],
    'branding_initiative': ['Branding Initiative'],
    'brashear_telescope': ['Brashear Telescope'],
    'buder_family_student_commons': ['Buder Family Student Commons'],
    'building': ['Building', 'Building .'],
    'busch_hall': ['Busch Hall'],
    'business': ['Business'],
    'cabin': ['Cabin'],
    'cabinet': ['Cabinet'],
    'campaign': ['Campaign'],
    'campus': ['Campus'],
    'campus_activity': ['Campus Activity'],
    'campus_building': ['Campus Building'],
    'campus_chapter': ['Campus Chapter'],
    'campus_constituency': ['Campus Constituency'],
    'campus_construction': ['Campus Construction'],
    'campus_expansion': ['Campus Expansion'],
    'campus_facility': ['Campus Facility'],
    'campus_parcel': ['Campus Parcel'],
    'campus_population': ['Campus Population'],
    'campus_symbolizing_maryville': ['Campus Symbolizing Maryville'],
    'candidate': ['Candidate'],
    'cardinal': ['Cardinal'],
    'cardinals': ['Cardinals'],
    'care_event': ['Care Event'],
    'care_management': ['Care Management'],
    'career': ['Career'],
    'catholic_church': ['Catholic Church'],
    'celebration': ['Celebration'],
    'centennial_celebration': ['Centennial Celebration'],
    'center': ['Center'],
    'central_association': ['Central Association'],
    'centre': ['Centre'],
    'century': ['Century'],
    'certification': ['Certification'],
    'challenge': ['Challenge'],
    'challenging_study': ['Challenging Study'],
    'challenging_year': ['Challenging Year'],
    'chapel': ['Chapel'],
    'chapter': ['Chapter'],
    'charitable_entity': ['Charitable Entity'],
    'chemist': ['Chemist'],
    'child': ['Child'],
    'childhood_language_disorders': ['Childhood Language Disorders'],
    'church': ['Church'],
    'city': ['City'],
    'city_center': ['City Center'],
    'city_limit': ['City Limit'],
    'civil_rights_movement': ['Civil Rights Movement'],
    'civil_war': ['Civil War'],
    'class': ['Class'],
    'class_inconvenient': ['Class Inconvenient'],
    'class_neighborhood': ['Class Neighborhood'],
    'class_year': ['Class Year'],
    'classroom_duty': ['Classroom Duty'],
    'claude_pritchard': ['Claude Pritchard'],
    'clinic': ['Clinic'],
    'clinic_service': ['Clinic Service'],
    'clinical_competency': ['Clinical Competency'],
    'clinical_evaluation': ['Clinical Evaluation'],
    'clinical_outcome': ['Clinical Outcome'],
    'clinical_outcome_evaluation': ['Clinical Outcome Evaluation'],
    'clinical_training': ['Clinical Training'],
    'closure': ['Closure'],
    'club': ['Club'],
    'coach': ['Coach'],
    'college': ['College'],
    'college_credit': ['College Credit'],
    'college_degree': ['College Degree'],
    'college_enrollment': ['College Enrollment'],
    'college_physics_student': ['College Physics Student'],
    'college_presidency': ['College Presidency'],
    'college_president': ['College President'],
    'college_student': ['College Student'],
    'college_subsidy': ['College Subsidy'],
    'commercial_development': ['Commercial Development'],
    'committee': ['Committee'],
    'commons': ['Commons'],
    'communication_skill_necessary': ['Communication Skill Necessary'],
    'community': ['Community'],
    'community_center': ['Community Center'],
    'community_figure': ['Community Figure'],
    'community_member': ['Community Member'],
    'company': ['Company'],
    'competency': ['Competency'],
    'completion': ['Completion'],
    'component': ['Component'],
    'condition': ['Condition'],
    'conference': ['Conference'],
    'conference_room': ['Conference Room'],
    'confidential_plan': ['Confidential Plan'],
    'confine': ['Confine'],
    'constellation': ['Constellation'],
    'constituency': ['Constituency'],
    'construction': ['Construction'],
    'contemporary_dichotomy': ['Contemporary Dichotomy'],
    'contemporary_dress': ['Contemporary Dress'],
    'continent': ['Continent'],
    'continuous_learning': ['Continuous Learning'],
    'contract': ['Contract'],
    'convenient_highway_access': ['Convenient Highway Access'],
    'convenient_location': ['Convenient Location'],
    'convent': ['Convent'],
    'conway_road': ['Conway Road'],
    'corporate_college': ['Corporate College'],
    'costume': ['Costume'],
    'counseling': ['Counseling'],
    'counseling_center': ['Counseling Center'],
    'country': ['Country'],
    'county': ['County'],
    'county_campus': ['County Campus'],
    'county_location': ['County Location'],
    'county_parcel': ['County Parcel'],
    'county_site': ['County Site'],
    'course': ['Course'],
    'course_hour': ['Course Hour'],
    'course_material': ['Course Material'],
    'courtyard_hotel_adjacent': ['Courtyard Hotel Adjacent'],
    'coveted_bascom_honors_program': ['Coveted Bascom Honors Program'],
    'credit': ['Credit'],
    'cross': ['Cross'],
    'cultural_trip_downtown': ['Cultural Trip Downtown'],
    'cultural_value': ['Cultural Value'],
    'culture': ['Culture'],
    'cunningham': ['Cunningham'],
    'cup': ['Cup'],
    'cushion': ['Cushion'],
    'custom': ['Custom'],
    'dan_viele': ['Dan Viele'],
    'dante_course': ['Dante Course'],
    'date': ['Date'],
    'day_school': ['Day School'],
    'day_trip': ['Day Trip'],
    'day_voyage': ['Day Voyage'],
    'deal': ['Deal'],
    'decision': ['Decision'],
    'dedicated_alumnae': ['Dedicated Alumnae'],
    'dedicated_team': ['Dedicated Team'],
    'degree': ['Degree'],
    'degree_program': ['Degree Program'],
    'department': ['Department'],
    'depression': ['Depression'],
    'design': ['Design'],
    'design_building': ['Design Building'],
    'developer_taylor_morley_simon': ['Developer Taylor Morley Simon'],
    'development': ['Development'],
    'dichotomy': ['Dichotomy'],
    'different_academic_institution': ['Different Academic Institution'],
    'difficult_time': ['Difficult Time'],
    'difficulty': ['Difficulty'],
    'digital_age': ['Digital Age'],
    'digital_resource': ['Digital Resource'],
    'digital_world': ['Digital World'],
    'dii_conference': ['Dii Conference'],
    'dining_hall': ['Dining Hall'],
    'dining_room': ['Dining Room'],
    'diploma': ['Diploma'],
    'director': ['Director'],
    'disorders': ['Disorders'],
    'display_cabinet': ['Display Cabinet'],
    'distinguished_educational_institution': [   'Distinguished Educational '
                                                 'Institution'],
    'distinguished_scholar': ['Distinguished Scholar'],
    'diverse_program': ['Diverse Program'],
    'division_ii': ['Division Ii'],
    'doctoral_degree': ['Doctoral Degree'],
    'dog_costume': ['Dog Costume'],
    'dominant_brand_message': ['Dominant Brand Message'],
    'dominant_esport_team': ['Dominant Esport Team'],
    'donation': ['Donation'],
    'downtown': ['Downtown'],
    'dozen_year': ['Dozen Year'],
    'dress': ['Dress'],
    'duchesne': ['Duchesne'],
    'duchesne_hall': ['Duchesne Hall'],
    'duty': ['Duty'],
    'dynamic_academic_offering': ['Dynamic Academic Offering'],
    'dynamic_online_education_platform': ['Dynamic Online Education Platform'],
    'early_june': ['Early June'],
    'early_year': ['Early Year'],
    'ecosystem': ['Ecosystem'],
    'edge_university': ['Edge University'],
    'edition': ['Edition'],
    'education': ['Education'],
    'education_course': ['Education Course'],
    'education_dan_viele': ['Education Dan Viele'],
    'education_landscape': ['Education Landscape'],
    'education_leadership': ['Education Leadership'],
    'education_pin': ['Education Pin'],
    'education_platform': ['Education Platform'],
    'education_program': ['Education Program'],
    'educational_institution': ['Educational Institution'],
    'educational_opportunity': ['Educational Opportunity'],
    'educational_program': ['Educational Program'],
    'educational_reach': ['Educational Reach'],
    'educational_system': ['Educational System'],
    'educator': ['Educator'],
    'edwards': ['Edwards'],
    'effective_study_habit': ['Effective Study Habit'],
    'eighth_president': ['Eighth President'],
    'elapsed_time': ['Elapsed Time'],
    'elderly_patient': ['Elderly Patient'],
    'emergency_room': ['Emergency Room'],
    'empathy': ['Empathy'],
    'endowment_today': ['Endowment Today'],
    'english_language': ['English Language'],
    'enrollment': ['Enrollment'],
    'enrollment_growth': ['Enrollment Growth'],
    'entity': ['Entity'],
    'environment': ['Environment'],
    'episcopal_city': ['Episcopal City'],
    'era': ['Era'],
    'era_evoke_story': ['Era Evoke Story'],
    'esport_team': ['Esport Team'],
    'essential_value': ['Essential Value'],
    'estate_investor': ['Estate Investor'],
    'ethical_practice': ['Ethical Practice'],
    'europe': ['Europe'],
    'evaluation': ['Evaluation'],
    'evening_class': ['Evening Class'],
    'evening_college': ['Evening College'],
    'event': ['Event'],
    'evidence': ['Evidence'],
    'evoke_story': ['Evoke Story'],
    'existence_today': ['Existence Today'],
    'expansion': ['Expansion'],
    'experience': ['Experience'],
    'extensive_national_search': ['Extensive National Search'],
    'extensive_undergraduate': ['Extensive Undergraduate'],
    'extracurricular_activity': ['Extracurricular Activity'],
    'facility': ['Facility'],
    'facility_closure': ['Facility Closure'],
    'factor': ['Factor'],
    'faculty': ['Faculty'],
    'faculty_contract': ['Faculty Contract'],
    'faculty_lounge': ['Faculty Lounge'],
    'faculty_member': ['Faculty Member'],
    'fail_to_rescue_rate': ['Fail To Rescue Rate'],
    'fair_pay': ['Fair Pay'],
    'faith': ['Faith'],
    'famed_german_firm': ['Famed German Firm'],
    'family_home': ['Family Home'],
    'family_member': ['Family Member'],
    'family_nurse_practitioner': ['Family Nurse Practitioner'],
    'family_responsibility': ['Family Responsibility'],
    'family_student_commons': ['Family Student Commons'],
    'fashionable_office': ['Fashionable Office'],
    'favorite_tradition': ['Favorite Tradition'],
    'female_patient': ['Female Patient'],
    'field': ['Field'],
    'fifth_window': ['Fifth Window'],
    'figure': ['Figure'],
    'financial_assistance': ['Financial Assistance'],
    'financial_challenge': ['Financial Challenge'],
    'financial_cushion': ['Financial Cushion'],
    'financial_difficulty': ['Financial Difficulty'],
    'financial_predicament': ['Financial Predicament'],
    'financial_reason': ['Financial Reason'],
    'financial_resource': ['Financial Resource'],
    'financial_status': ['Financial Status'],
    'financial_success': ['Financial Success'],
    'firm': ['Firm'],
    'fledgling_campus': ['Fledgling Campus'],
    'florence_nightingale': ['Florence Nightingale'],
    'focus': ['Focus'],
    'following_year': ['Following Year'],
    'footprint': ['Footprint'],
    'fortune': ['Fortune'],
    'foundation': ['Foundation'],
    'foundation_grant': ['Foundation Grant'],
    'founders_hall': ['Founders Hall'],
    'fourth_president': ['Fourth President'],
    'fourth_time': ['Fourth Time'],
    'franklin_county': ['Franklin County'],
    'free_learning_app': ['Free Learning App'],
    'free_school': ['Free School'],
    'freshmen_student': ['Freshmen Student'],
    'full_potential': ['Full Potential'],
    'fund': ['Fund'],
    'fundraising_campaign': ['Fundraising Campaign'],
    'fundraising_event': ['Fundraising Event'],
    'gander': ['Gander'],
    'gander_hall': ['Gander Hall'],
    'gender_bias': ['Gender Bias'],
    'geographic_location': ['Geographic Location'],
    'geopolitical_entity': ['Geopolitical Entity'],
    'german_firm': ['German Firm'],
    'german_immigrant': ['German Immigrant'],
    'gidionsen': ['Gidionsen'],
    'glass_window': ['Glass Window'],
    'glee_club': ['Glee Club'],
    'good_fortune': ['Good Fortune'],
    'good_time': ['Good Time'],
    'good_way': ['Good Way'],
    'gothic_chapel': ['Gothic Chapel'],
    'graduate_level': ['Graduate Level'],
    'graduate_mother_marion_rose_bascom': [   'Graduate Mother Marion Rose '
                                              'Bascom'],
    'graduate_offering': ['Graduate Offering'],
    'graduate_program': ['Graduate Program'],
    'graduate_student': ['Graduate Student'],
    'grant': ['Grant'],
    'graphic_design': ['Graphic Design'],
    'gray_mcnally': ['Gray Mcnally'],
    'great_achievement': ['Great Achievement'],
    'great_books': ['Great Books'],
    'great_deal': ['Great Deal'],
    'great_depression': ['Great Depression'],
    'great_lakes_valley_conference': ['Great Lakes Valley Conference'],
    'great_peril': ['Great Peril'],
    'great_pioneer': ['Great Pioneer'],
    'great_sense': ['Great Sense'],
    'group': ['Group'],
    'group_therapy': ['Group Therapy'],
    'growth': ['Growth'],
    'growth_impact': ['Growth Impact'],
    'guidance_maryville': ['Guidance Maryville'],
    'gym_class': ['Gym Class'],
    'habit': ['Habit'],
    'hall': ['Hall'],
    'harriet_ann_padberg': ['Harriet Ann Padberg'],
    'harriet_switzer': ['Harriet Switzer'],
    'health': ['Health'],
    'health_care': ['Health Care'],
    'health_care_education': ['Health Care Education'],
    'health_care_management': ['Health Care Management'],
    'health_care_provider': ['Health Care Provider'],
    'health_care_quality': ['Health Care Quality'],
    'health_care_reform': ['Health Care Reform'],
    'health_care_specialist': ['Health Care Specialist'],
    'health_challenge': ['Health Challenge'],
    'health_department': ['Health Department'],
    'health_profession_education': ['Health Profession Education'],
    'health_program': ['Health Program'],
    'health_service': ['Health Service'],
    'heart_convent': ['Heart Convent'],
    'heart_era': ['Heart Era'],
    'heart_school': ['Heart School'],
    'hellmuth': ['Hellmuth'],
    'high': ['High'],
    'high_academic_standard': ['High Academic Standard'],
    'high_class': ['High Class'],
    'high_education_landscape': ['High Education Landscape'],
    'high_learning': ['High Learning'],
    'high_school': ['High School'],
    'highway_access': ['Highway Access'],
    'hildegarde_hellmuth': ['Hildegarde Hellmuth'],
    'historical_nursing': ['Historical Nursing'],
    'history': ['History'],
    'holiday_edition': ['Holiday Edition'],
    'holland_gidionsen': ['Holland Gidionsen'],
    'home': ['Home'],
    'honor_student': ['Honor Student'],
    'honors_program': ['Honors Program'],
    'honors_scholarship_fund': ['Honors Scholarship Fund'],
    'hospital': ['Hospital'],
    'hospital_conference_room': ['Hospital Conference Room'],
    'host_city': ['Host City'],
    'hotel_adjacent': ['Hotel Adjacent'],
    'hotel_facility': ['Hotel Facility'],
    'hour': ['Hour'],
    'house_production_specialist': ['House Production Specialist'],
    'huttig_chapel': ['Huttig Chapel'],
    'huttig_memorial_chapel': ['Huttig Memorial Chapel'],
    'ideal_institutional_foundation': ['Ideal Institutional Foundation'],
    'ii': ['Ii'],
    'immigrant': ['Immigrant'],
    'impact': ['Impact'],
    'important_component': ['Important Component'],
    'important_decision': ['Important Decision'],
    'important_factor': ['Important Factor'],
    'impressive_stone_structure': ['Impressive Stone Structure'],
    'improvement_plan': ['Improvement Plan'],
    'inconvenient': ['Inconvenient'],
    'independent_accreditation': ['Independent Accreditation'],
    'independent_charitable_entity': ['Independent Charitable Entity'],
    'individual_donation': ['Individual Donation'],
    'information': ['Information'],
    'initial_construction': ['Initial Construction'],
    'initial_degree': ['Initial Degree'],
    'initiative': ['Initiative'],
    'innovative_investment': ['Innovative Investment'],
    'innovative_leadership': ['Innovative Leadership'],
    'innovative_member': ['Innovative Member'],
    'innovative_technology': ['Innovative Technology'],
    'institute': ['Institute'],
    'institution': ['Institution'],
    'institutional_foundation': ['Institutional Foundation'],
    'instrument': ['Instrument'],
    'intellectual_life': ['Intellectual Life'],
    'interior_design': ['Interior Design'],
    'investment': ['Investment'],
    'investor': ['Investor'],
    'jefferson_county': ['Jefferson County'],
    'john_bosco': ['John Bosco'],
    'john_mullanphy': ['John Mullanphy'],
    'johnson_and_johnson': ['Johnson & Johnson'],
    'joseph_gander': ['Joseph Gander'],
    'journey': ['Journey'],
    'joyous_centennial_celebration': ['Joyous Centennial Celebration'],
    'june': ['June'],
    'junior_college': ['Junior College'],
    'kate_kline': ['Kate Kline'],
    'keith_lovin': ['Keith Lovin'],
    'kernaghan': ['Kernaghan'],
    'kernaghan_hall': ['Kernaghan Hall'],
    'key_role': ['Key Role'],
    'kline': ['Kline'],
    'labor_event': ['Labor Event'],
    'lakes_valley_conference': ['Lakes Valley Conference'],
    'landscape': ['Landscape'],
    'language': ['Language'],
    'language_disorders': ['Language Disorders'],
    'lapel_pin': ['Lapel Pin'],
    'large_site': ['Large Site'],
    'lay_board': ['Lay Board'],
    'lay_president': ['Lay President'],
    'leader': ['Leader'],
    'leadership': ['Leadership'],
    'leadership_fundraising_campaign': ['Leadership Fundraising Campaign'],
    'learning': ['Learning'],
    'learning_app': ['Learning App'],
    'learning_ecosystem': ['Learning Ecosystem'],
    'learning_environment': ['Learning Environment'],
    'learning_style': ['Learning Style'],
    'level': ['Level'],
    'level_speech': ['Level Speech'],
    'liberal_art_college': ['Liberal Art College'],
    'life': ['Life'],
    'life_coach': ['Life Coach'],
    'like_focus': ['Like Focus'],
    'limit': ['Limit'],
    'lincoln_county': ['Lincoln County'],
    'line': ['Line'],
    'little_ship_rebecca': ['Little Ship Rebecca'],
    'local_board': ['Local Board'],
    'location': ['Location'],
    'log_cabin': ['Log Cabin'],
    'logo': ['Logo'],
    'logo_design': ['Logo Design'],
    'lombardi': ['Lombardi'],
    'long_journey': ['Long Journey'],
    'long_term_health_care': ['Long Term Health Care'],
    'longtime_maryville_benefactor': ['Longtime Maryville Benefactor'],
    'louis_blues_successful_stanley_cup': [   'Louis Blues Successful Stanley '
                                              'Cup'],
    'louis_campus': ['Louis Campus'],
    'louis_cardinals': ['Louis Cardinals'],
    'louis_city_limit': ['Louis City Limit'],
    'louis_county_campus': ['Louis County Campus'],
    'louis_county_parcel': ['Louis County Parcel'],
    'louis_county_site': ['Louis County Site'],
    'louis_culture': ['Louis Culture'],
    'louis_landscape': ['Louis Landscape'],
    'louis_region': ['Louis Region'],
    'louis_scottish_rite_masons': ['Louis Scottish Rite Masons'],
    'louis_speaker_series': ['Louis Speaker Series'],
    'louis_university': ['Louis University'],
    'louise_padberg': ['Louise Padberg'],
    'lounge': ['Lounge'],
    'lovin': ['Lovin'],
    'low_level': ['Low Level'],
    'm': ['M'],
    'madeleine_sophie_barat': ['Madeleine Sophie Barat'],
    'main_campus_building': ['Main Campus Building'],
    'main_chapel': ['Main Chapel'],
    'main_staircase': ['Main Staircase'],
    'major': ['Major'],
    'male_leader': ['Male Leader'],
    'male_patient': ['Male Patient'],
    'male_student': ['Male Student'],
    'man': ['Man'],
    'management': ['Management'],
    'mandate': ['Mandate'],
    'marie_kernaghan': ['Marie Kernaghan'],
    'marie_louise_padberg': ['Marie Louise Padberg'],
    'marie_odeide_mouton': ['Marie Odeide Mouton'],
    'marion_bascom': ['Marion Bascom'],
    'marion_bascom_honors_scholarship_fund': [   'Marion Bascom Honors '
                                                 'Scholarship Fund'],
    'marion_rose_bascom': ['Marion Rose Bascom'],
    'mark_lombardi': ['Mark Lombardi'],
    'market': ['Market'],
    'marriott_courtyard_hotel_adjacent': ['Marriott Courtyard Hotel Adjacent'],
    'mary_blish': ['Mary Blish'],
    'mary_gray_mcnally': ['Mary Gray Mcnally'],
    'mary_robert_edwards': ['Mary Robert Edwards'],
    'mary_roch_rocklage': ['Mary Roch Rocklage'],
    'maryville': ['Maryville'],
    'maryville_academy': ['Maryville Academy'],
    'maryville_alumnae': ['Maryville Alumnae'],
    'maryville_benefactor': ['Maryville Benefactor'],
    'maryville_building': ['Maryville Building'],
    'maryville_career': ['Maryville Career'],
    'maryville_centre': ['Maryville Centre'],
    'maryville_college_physics_student': ['Maryville College Physics Student'],
    'maryville_community': ['Maryville Community'],
    'maryville_education': ['Maryville Education'],
    'maryville_faculty': ['Maryville Faculty'],
    'maryville_glee_club': ['Maryville Glee Club'],
    'maryville_saints': ['Maryville Saints'],
    'maryville_science_club': ['Maryville Science Club'],
    'maryville_university_archives': ['Maryville University Archives'],
    'mascot': ['Mascot'],
    'masons': ['Masons'],
    'master_course_material': ['Master Course Material'],
    'master_of_arts': ['Master of Arts'],
    'master_of_science': ['Master of Science'],
    'master_of_science_in_nursing': ['Master of Science in Nursing'],
    'masters_degree': ["Master's Degree"],
    'material': ['Material'],
    'mba_degree': ['Mba Degree'],
    'mcgarry': ['Mcgarry'],
    'mcnally': ['Mcnally'],
    'meaningful_online_learning': ['Meaningful Online Learning'],
    'medical_building': ['Medical Building'],
    'medical_facility_closure': ['Medical Facility Closure'],
    'member': ['Member'],
    'member_local_board': ['Member Local Board'],
    'memorial_chapel': ['Memorial Chapel'],
    'mental_health': ['Mental Health'],
    'mental_health_challenge': ['Mental Health Challenge'],
    'mental_health_service': ['Mental Health Service'],
    'mercy_department': ['Mercy Department'],
    'mercy_grant': ['Mercy Grant'],
    'mercy_hospital': ['Mercy Hospital'],
    'mercy_junior_college': ['Mercy Junior College'],
    'message': ['Message'],
    'mission': ['Mission'],
    'mississippi_river': ['Mississippi River'],
    'missouri_institute': ['Missouri Institute'],
    'missouri_river': ['Missouri River'],
    'mobile_access': ['Mobile Access'],
    'modern_high': ['Modern High'],
    'modern_nursing': ['Modern Nursing'],
    'money': ['Money'],
    'more': ['More'],
    'morley_simon': ['Morley Simon'],
    'mortality_rate': ['Mortality Rate'],
    'mother_bascom': ['Mother Bascom'],
    'mother_kernaghan': ['Mother Kernaghan'],
    'mother_marie_kernaghan': ['Mother Marie Kernaghan'],
    'mother_marie_odeide_mouton': ['Mother Marie Odeide Mouton'],
    'mother_marion_bascom': ['Mother Marion Bascom'],
    'mother_marion_bascom_honors_scholarship_fund': [   'Mother Marion Bascom '
                                                        'Honors Scholarship '
                                                        'Fund'],
    'mother_marion_rose_bascom': ['Mother Marion Rose Bascom'],
    'mother_mary_blish': ['Mother Mary Blish'],
    'mother_mary_gray_mcnally': ['Mother Mary Gray Mcnally'],
    'motivated_student': ['Motivated Student'],
    'mouton': ['Mouton'],
    'mouton_hall': ['Mouton Hall'],
    'movement': ['Movement'],
    'mullanphy': ['Mullanphy'],
    'multidimensional_leadership': ['Multidimensional Leadership'],
    'munich_style': ['Munich Style'],
    'music_therapy': ['Music Therapy'],
    'music_therapy_program': ['Music Therapy Program'],
    'musical_note': ['Musical Note'],
    'nation_pride': ['Nation Pride'],
    'national_attention': ['National Attention'],
    'national_certification': ['National Certification'],
    'national_institution': ['National Institution'],
    'national_scale': ['National Scale'],
    'national_search': ['National Search'],
    'national_student_base': ['National Student Base'],
    'national_university': ['National University'],
    'nationality': ['Nationality'],
    'ncaa_division_ii': ['Ncaa Division Ii'],
    'nearby_mississippi_river': ['Nearby Mississippi River'],
    'necessary': ['Necessary'],
    'need': ['Need'],
    'neighborhood': ['Neighborhood'],
    'new_athletic_logo': ['New Athletic Logo'],
    'new_branding_initiative': ['New Branding Initiative'],
    'new_building': ['New Building'],
    'new_campus': ['New Campus'],
    'new_constellation': ['New Constellation'],
    'new_family_member': ['New Family Member'],
    'new_home': ['New Home'],
    'new_initiative': ['New Initiative'],
    'new_market': ['New Market'],
    'new_mercy_department': ['New Mercy Department'],
    'new_official': ['New Official'],
    'new_phase': ['New Phase'],
    'new_property': ['New Property'],
    'new_religious': ['New Religious'],
    'new_residence_hall': ['New Residence Hall'],
    'new_school': ['New School'],
    'new_south_wing': ['New South Wing'],
    'new_structure': ['New Structure'],
    'noble_peace_prize_winner': ['Noble Peace Prize Winner'],
    'north_central_association': ['North Central Association'],
    'note': ['Note'],
    'notebook': ['Notebook'],
    'number': ['Number'],
    'nurse': ['Nurse'],
    'nurse_educator': ['Nurse Educator'],
    'nurse_practitioner': ['Nurse Practitioner'],
    'nursing': ['Nursing'],
    'nursing_diploma': ['Nursing Diploma'],
    'nursing_education': ['Nursing Education'],
    'nursing_home': ['Nursing Home'],
    'nursing_major': ['Nursing Major'],
    'nursing_program': ['Nursing Program'],
    'nursing_school': ['Nursing School'],
    'nursing_student': ['Nursing Student'],
    'oakwood_retirement_center': ['Oakwood Retirement Center'],
    'observer': ['Observer'],
    'occupational_therapy': ['Occupational Therapy'],
    'odeide_mouton': ['Odeide Mouton'],
    'offering': ['Offering'],
    'office': ['Office'],
    'official': ['Official'],
    'official_program': ['Official Program'],
    'old_campus': ['Old Campus'],
    'old_child': ['Old Child'],
    'old_institution': ['Old Institution'],
    'old_log_cabin': ['Old Log Cabin'],
    'old_maryville_building': ['Old Maryville Building'],
    'old_university_logo': ['Old University Logo'],
    'ongoing_training': ['Ongoing Training'],
    'online_degree_program': ['Online Degree Program'],
    'online_education_dan_viele': ['Online Education Dan Viele'],
    'online_education_platform': ['Online Education Platform'],
    'online_learning': ['Online Learning'],
    'open_field': ['Open Field'],
    'opportunity': ['Opportunity'],
    'opportunity_transforming_business': ['Opportunity Transforming Business'],
    'optimum_learning_style': ['Optimum Learning Style'],
    'order': ['Order'],
    'ordinal': ['Ordinal'],
    'organization': ['Organization'],
    'original_building': ['Original Building'],
    'original_campus': ['Original Campus'],
    'original_logo_design': ['Original Logo Design'],
    'ornate_student_lounge': ['Ornate Student Lounge'],
    'outcome': ['Outcome'],
    'outcome_evaluation': ['Outcome Evaluation'],
    'outreach': ['Outreach'],
    'outright_grant': ['Outright Grant'],
    'outstanding_team': ['Outstanding Team'],
    'oxford_university_graduate_mother_marion_rose_bascom': [   'Oxford '
                                                                'University '
                                                                'Graduate '
                                                                'Mother Marion '
                                                                'Rose Bascom'],
    'padberg': ['Padberg'],
    'padberg_mcgarry': ['Padberg Mcgarry'],
    'parcel': ['Parcel'],
    'parent_training': ['Parent Training'],
    'path': ['Path'],
    'patient': ['Patient'],
    'patient_care': ['Patient Care'],
    'patient_treatment': ['Patient Treatment'],
    'patient_treatment_plan': ['Patient Treatment Plan'],
    'pay': ['Pay'],
    'peace_prize_winner': ['Peace Prize Winner'],
    'pediactric_patient': ['Pediactric Patient'],
    'peer_review': ['Peer Review'],
    'peggy_padberg_mcgarry': ['Peggy Padberg Mcgarry'],
    'percent': ['Percent'],
    'peril': ['Peril'],
    'period': ['Period'],
    'permanent': ['Permanent'],
    'permanent_alumnae_office': ['Permanent Alumnae Office'],
    'person': ['Person'],
    'personal_belonging': ['Personal Belonging'],
    'personal_notebook': ['Personal Notebook'],
    'personal_quality': ['Personal Quality'],
    'personal_touch': ['Personal Touch'],
    'pharmacist': ['Pharmacist'],
    'pharmacy': ['Pharmacy'],
    'phase': ['Phase'],
    'philanthropist_john_mullanphy': ['Philanthropist John Mullanphy'],
    'philippine': ['Philippine'],
    'philippine_duchesne': ['Philippine Duchesne'],
    'physical_campus': ['Physical Campus'],
    'physical_education_course': ['Physical Education Course'],
    'physical_facility': ['Physical Facility'],
    'physical_site': ['Physical Site'],
    'physical_therapy': ['Physical Therapy'],
    'physical_transformation': ['Physical Transformation'],
    'physician': ['Physician'],
    'physics_student': ['Physics Student'],
    'pin': ['Pin'],
    'pioneer': ['Pioneer'],
    'pivotal_role': ['Pivotal Role'],
    'plan': ['Plan', 'Plan'],
    'planning_committee': ['Planning Committee'],
    'platform': ['Platform'],
    'platform_education': ['Platform Education'],
    'political_activity': ['Political Activity'],
    'political_group': ['Political Group'],
    'political_science': ['Political Science'],
    'population': ['Population'],
    'portable_brashear_telescope': ['Portable Brashear Telescope'],
    'postpandemic_era': ['Postpandemic Era'],
    'potential': ['Potential'],
    'potter_hall': ['Potter Hall'],
    'powell_symphony_hall': ['Powell Symphony Hall'],
    'practice': ['Practice'],
    'predicament': ['Predicament'],
    'preliminary_evidence': ['Preliminary Evidence'],
    'premier_dii_conference': ['Premier Dii Conference'],
    'presidency': ['Presidency'],
    'president': ['President'],
    'pride': ['Pride'],
    'primary_care': ['Primary Care'],
    'pritchard': ['Pritchard'],
    'private_high_school': ['Private High School'],
    'private_institution': ['Private Institution'],
    'prize_winner': ['Prize Winner'],
    'problem_mother_kernaghan': ['Problem Mother Kernaghan'],
    'product': ['Product'],
    'production_specialist': ['Production Specialist'],
    'production_studio': ['Production Studio'],
    'profession': ['Profession'],
    'profession_education': ['Profession Education'],
    'professional_career': ['Professional Career'],
    'professional_development': ['Professional Development'],
    'professor': ['Professor'],
    'profile': ['Profile'],
    'profile_information': ['Profile Information'],
    'program': ['Program'],
    'proper_training': ['Proper Training'],
    'property': ['Property'],
    'protestant_church': ['Protestant Church'],
    'provider': ['Provider'],
    'psychiatric_mental_health_nurse_practitioner': [   'Psychiatric Mental '
                                                        'Health Nurse '
                                                        'Practitioner'],
    'public_fundraising_campaign': ['Public Fundraising Campaign'],
    'public_health_department': ['Public Health Department'],
    'qualified_student': ['Qualified Student'],
    'quality': ['Quality'],
    'quantifiable_measurement': ['Quantifiable Measurement'],
    'quantity': ['Quantity'],
    'racial_bias': ['Racial Bias'],
    'range_strategic_plan': ['Range Strategic Plan'],
    'reach': ['Reach'],
    'readmission': ['Readmission'],
    'readmission_rate': ['Readmission Rate'],
    'real_estate_investor': ['Real Estate Investor'],
    'reason': ['Reason'],
    'rebecca': ['Rebecca'],
    'receiver': ['Receiver'],
    'red_bird': ['Red Bird'],
    'red_cross': ['Red Cross'],
    'red_m': ['Red M'],
    'reform': ['Reform'],
    'region': ['Region'],
    'registered_nurse': ['Registered Nurse'],
    'regulation': ['Regulation'],
    'rehabilitation_counseling': ['Rehabilitation Counseling'],
    'relaxation_room': ['Relaxation Room'],
    'relief': ['Relief'],
    'religious': ['Religious'],
    'religious_group': ['Religious Group'],
    'religious_order': ['Religious Order'],
    'remote_location': ['Remote Location'],
    'required_number': ['Required Number'],
    'residence_hall': ['Residence Hall'],
    'residential_campus_population': ['Residential Campus Population'],
    'residential_developer_taylor_morley_simon': [   'Residential Developer '
                                                     'Taylor Morley Simon'],
    'residential_student': ['Residential Student'],
    'resource': ['Resource'],
    'respected_faculty': ['Respected Faculty'],
    'responsibility': ['Responsibility'],
    'retirement_center': ['Retirement Center'],
    'retirement_year': ['Retirement Year'],
    'rich_experience': ['Rich Experience'],
    'rich_history': ['Rich History'],
    'rights_movement': ['Rights Movement'],
    'rigor': ['Rigor'],
    'risk_child': ['Risk Child'],
    'rite_clinic': ['Rite Clinic'],
    'rite_masons': ['Rite Masons'],
    'river': ['River'],
    'road': ['Road'],
    'robert_edwards': ['Robert Edwards'],
    'robust_expansion': ['Robust Expansion'],
    'robust_learning_environment': ['Robust Learning Environment'],
    'roch_rocklage': ['Roch Rocklage'],
    'rocklage': ['Rocklage'],
    'role': ['Role'],
    'roman_catholic_church': ['Roman Catholic Church'],
    'room': ['Room'],
    'room_adjacent': ['Room Adjacent'],
    'rose_bascom': ['Rose Bascom'],
    'rose_philippine': ['Rose Philippine'],
    'rose_philippine_duchesne': ['Rose Philippine Duchesne'],
    'rose_window': ['Rose Window'],
    'rosemary_holland_gidionsen': ['Rosemary Holland Gidionsen'],
    'round_window': ['Round Window'],
    'rule': ['Rule'],
    'rural_campus': ['Rural Campus'],
    'rural_community': ['Rural Community'],
    'rural_confine': ['Rural Confine'],
    'sacred_heart_convent': ['Sacred Heart Convent'],
    'sacred_heart_era': ['Sacred Heart Era'],
    'sacred_heart_school': ['Sacred Heart School'],
    'saint_bernard_dog_costume': ['Saint Bernard Dog Costume'],
    'saint_bernard_mascot': ['Saint Bernard Mascot'],
    'saint_louis_university': ['Saint Louis University'],
    'saint_madeleine_sophie_barat': ['Saint Madeleine Sophie Barat'],
    'saint_rose_philippine': ['Saint Rose Philippine'],
    'saint_rose_philippine_duchesne': ['Saint Rose Philippine Duchesne'],
    'saints': ['Saints'],
    'saints_athletic': ['Saints Athletic'],
    'saints_hall': ['Saints Hall'],
    'saints_nation_pride': ['Saints Nation Pride'],
    'satellite_location': ['Satellite Location'],
    'scale': ['Scale'],
    'scholar': ['Scholar'],
    'scholarship_fund': ['Scholarship Fund'],
    'school': ['School'],
    'school_custom': ['School Custom'],
    'school_diploma': ['School Diploma'],
    'school_year': ['School Year'],
    'science': ['Science'],
    'science_club': ['Science Club'],
    'science_department': ['Science Department'],
    'science_instrument': ['Science Instrument'],
    'scottish_rite_clinic': ['Scottish Rite Clinic'],
    'scottish_rite_masons': ['Scottish Rite Masons'],
    'search': ['Search'],
    'secret_planning_committee': ['Secret Planning Committee'],
    'select_faculty': ['Select Faculty'],
    'select_number': ['Select Number'],
    'sense': ['Sense'],
    'series': ['Series'],
    'service': ['Service'],
    'service_man': ['Service Man'],
    'session': ['Session'],
    'ship_rebecca': ['Ship Rebecca'],
    'short_year': ['Short Year'],
    'shortage': ['Shortage'],
    'significant_achievement': ['Significant Achievement'],
    'significant_enrollment_growth': ['Significant Enrollment Growth'],
    'simon': ['Simon'],
    'simon_school': ['Simon School'],
    'single_red_bird': ['Single Red Bird'],
    'sister_ann_webster': ['Sister Ann Webster'],
    'sister_harriet_ann_padberg': ['Sister Harriet Ann Padberg'],
    'sister_harriet_switzer': ['Sister Harriet Switzer'],
    'sister_hildegarde_hellmuth': ['Sister Hildegarde Hellmuth'],
    'sister_mary_robert_edwards': ['Sister Mary Robert Edwards'],
    'sister_mary_roch_rocklage': ['Sister Mary Roch Rocklage'],
    'sister_padberg': ['Sister Padberg'],
    'sister_rocklage': ['Sister Rocklage'],
    'sister_switzer': ['Sister Switzer'],
    'sister_webster': ['Sister Webster'],
    'site': ['Site'],
    'sixth_president': ['Sixth President'],
    'skill': ['Skill'],
    'skill_necessary': ['Skill Necessary'],
    'small_academy': ['Small Academy'],
    'small_apple': ['Small Apple'],
    'small_grant': ['Small Grant'],
    'small_personal_notebook': ['Small Personal Notebook'],
    'social_event': ['Social Event'],
    'societal_more': ['Societal More'],
    'soft_skill': ['Soft Skill'],
    'sophie_barat': ['Sophie Barat'],
    'south_county_location': ['South County Location'],
    'south_wing': ['South Wing'],
    'spain': ['Spain'],
    'spanish': ['Spanish'],
    'spanish_hospital': ['Spanish Hospital'],
    'speaker_series': ['Speaker Series'],
    'special_fundraising_event': ['Special Fundraising Event'],
    'special_holiday_edition': ['Special Holiday Edition'],
    'special_need': ['Special Need'],
    'specialist': ['Specialist'],
    'speech': ['Speech'],
    'sporadic_growth': ['Sporadic Growth'],
    'sport_business': ['Sport Business'],
    'stable_foundation': ['Stable Foundation'],
    'staff': ['Staff'],
    'staffing': ['Staffing'],
    'staffing_level': ['Staffing Level'],
    'staffing_shortage': ['Staffing Shortage'],
    'staircase': ['Staircase'],
    'standard': ['Standard'],
    'stanley_cup': ['Stanley Cup'],
    'state_educational_system': ['State Educational System'],
    'state_mandate': ['State Mandate'],
    'status': ['Status'],
    'stone_structure': ['Stone Structure'],
    'stone_terrace': ['Stone Terrace'],
    'story': ['Story'],
    'story_administration_building': ['Story Administration Building'],
    'story_dining_hall': ['Story Dining Hall'],
    'story_tall': ['Story Tall'],
    'strategic_plan': ['Strategic Plan'],
    'strike': ['Strike'],
    'strong_faith': ['Strong Faith'],
    'strong_footprint': ['Strong Footprint'],
    'structure': ['Structure'],
    'student': ['Student'],
    'student_apartment_building': ['Student Apartment Building'],
    'student_base': ['Student Base'],
    'student_body': ['Student Body'],
    'student_commons': ['Student Commons'],
    'student_enrollment': ['Student Enrollment'],
    'student_lounge': ['Student Lounge'],
    'student_master_course_material': ['Student Master Course Material'],
    'student_mental_health': ['Student Mental Health'],
    'student_outcome': ['Student Outcome'],
    'student_outreach': ['Student Outreach'],
    'student_profile': ['Student Profile'],
    'studio': ['Studio'],
    'study': ['Study'],
    'study_habit': ['Study Habit'],
    'style': ['Style'],
    'subsequent_year': ['Subsequent Year'],
    'subsidy': ['Subsidy'],
    'success': ['Success'],
    'successful_completion': ['Successful Completion'],
    'successful_stanley_cup': ['Successful Stanley Cup'],
    'successful_tenure': ['Successful Tenure'],
    'sufficient_number': ['Sufficient Number'],
    'suitable_course': ['Suitable Course'],
    'superior_class': ['Superior Class'],
    'support_line': ['Support Line'],
    'supportive_community_member': ['Supportive Community Member'],
    'surgeon': ['Surgeon'],
    'surgery': ['Surgery'],
    'switzer': ['Switzer'],
    'symbolizing_maryville': ['Symbolizing Maryville'],
    'symphony_hall': ['Symphony Hall'],
    'system': ['System'],
    'tall': ['Tall'],
    'taylor_morley_simon': ['Taylor Morley Simon'],
    'teaching_career': ['Teaching Career'],
    'team': ['Team'],
    'technology': ['Technology'],
    'telescope': ['Telescope'],
    'temporary': ['Temporary'],
    'tenure': ['Tenure'],
    'terrace': ['Terrace'],
    'therapy': ['Therapy'],
    'therapy_program': ['Therapy Program'],
    'therapy_session': ['Therapy Session'],
    'thought_leader': ['Thought Leader'],
    'time': ['Time'],
    'time_residential_student': ['Time Residential Student'],
    'time_student': ['Time Student'],
    'today': ['Today'],
    'tradition': ['Tradition'],
    'traditional_college': ['Traditional College'],
    'traditional_path': ['Traditional Path'],
    'traditional_undergraduate_student': ['Traditional Undergraduate Student'],
    'training': ['Training'],
    'training_event': ['Training Event'],
    'transformation': ['Transformation'],
    'transforming_business': ['Transforming Business'],
    'treatment_event': ['Treatment Event'],
    'trip': ['Trip'],
    'trip_downtown': ['Trip Downtown'],
    'tutorial_program': ['Tutorial Program'],
    'undergraduate': ['Undergraduate'],
    'undergraduate_student': ['Undergraduate Student'],
    'underprivileged_student': ['Underprivileged Student'],
    'university': ['University'],
    'university_archives': ['University Archives'],
    'university_center': ['University Center'],
    'university_graduate_mother_marion_rose_bascom': [   'University Graduate '
                                                         'Mother Marion Rose '
                                                         'Bascom'],
    'university_logo': ['University Logo'],
    'university_status': ['University Status'],
    'unprecedented_growth': ['Unprecedented Growth'],
    'urban_location': ['Urban Location'],
    'urgent_care': ['Urgent Care'],
    'valley_conference': ['Valley Conference'],
    'value': ['Value'],
    'varied_campus_constituency': ['Varied Campus Constituency'],
    'vice_president': ['Vice President'],
    'viele': ['Viele'],
    'villa_duchesne': ['Villa Duchesne'],
    'virtual_relaxation_room': ['Virtual Relaxation Room'],
    'volunteer_faculty_member': ['Volunteer Faculty Member'],
    'voyage': ['Voyage'],
    'walker_clinic_service': ['Walker Clinic Service'],
    'walker_college': ['Walker College'],
    'walker_hall': ['Walker Hall'],
    'walker_scottish_rite_clinic': ['Walker Scottish Rite Clinic'],
    'war': ['War'],
    'war_ii': ['War Ii'],
    'war_relief': ['War Relief'],
    'washington_university': ['Washington University'],
    'way': ['Way'],
    'webster': ['Webster'],
    'weekday_class_inconvenient': ['Weekday Class Inconvenient'],
    'weekend_college_student': ['Weekend College Student'],
    'weekly_dante_course': ['Weekly Dante Course'],
    'well_observer': ['Well Observer'],
    'wide_improvement_plan': ['Wide Improvement Plan'],
    'wide_main_staircase': ['Wide Main Staircase'],
    'wide_mental_health_service': ['Wide Mental Health Service'],
    'window': ['Window'],
    'wing': ['Wing'],
    'winner': ['Winner'],
    'wise_guidance_maryville': ['Wise Guidance Maryville'],
    'woman': ['Woman'],
    'wooden_display_cabinet': ['Wooden Display Cabinet'],
    'work_of_art': ['Work of Art'],
    'world': ['World'],
    'world_leader': ['World Leader'],
    'world_war_ii': ['World War Ii'],
    'year': ['Year'],
    'year_anniversary': ['Year Anniversary'],
    'year_college': ['Year College'],
    'year_degree': ['Year Degree'],
    'year_period': ['Year Period'],
    'young_candidate': ['Young Candidate'],
    'young_college_president': ['Young College President'],
    'young_woman': ['Young Woman']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
