from .autotaxo import *
from .mutato import *
from .normalize import *
from .portendo import *
from .segmenter import *
from .spacyparse import *
from .stemmer import *
from .tokenizer import *
from .graphviz import *
