
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class AppraisalTypesRev(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'AppraisalTypes',
            'filename': 'appraisal_types',
            'queries': ['subclass.sparql'],
            'reverse': True,
            'transformers': ['types']},
 'source': 'appraisal.owl',
 'time': '2022-04-27 21:15:16.362784'}

    __data = {
    'ability': ['intuitive_ability', 'cognitive_ability', 'persuasive_ability'],
    'acclaim': ['highly_acclaimed'],
    'accomplish': ['significant_accomplishments'],
    'account': ['personal_accountability', 'foremost_accountability'],
    'achieve': [   'strong_achiever',
                   'consistent_achiever',
                   'solid_achiever',
                   'substantial_achievement',
                   'goal_achiever',
                   'notable_achievement',
                   'greater_achievement',
                   'critical_achievement',
                   'high_achiever'],
    'action': [   'accelerate',
                  'corrective_actions',
                  'attract',
                  'decisive_action',
                  'concentrate',
                  'advice',
                  'disciplinary_action',
                  'accumulate',
                  'adapt',
                  'adhere',
                  'access',
                  'assist',
                  'assert',
                  'constructive_actions',
                  'positive_actions',
                  'advance',
                  'administer',
                  'accept',
                  'avoid',
                  'attain',
                  'accomplish',
                  'acquire',
                  'accelerate_change',
                  'stimulating_action',
                  'adjust',
                  'assess',
                  'approach',
                  'ask',
                  'affect',
                  'account',
                  'allocate'],
    'active': ['essential_activities'],
    'adapt': ['highly_adaptive'],
    'advance': ['technically_advanced'],
    'advantage': ['optimum_advantage'],
    'advice': ['practical_advice'],
    'alternative': ['creative_alternatives', 'strategic_alternatives'],
    'application': ['computer_application', 'practical_applications'],
    'approach': [   'planning_approaches',
                    'disciplined_approach',
                    'diversified_approaches',
                    'sound_approach',
                    'new_approaches',
                    'positive_approach',
                    'systematic_approach',
                    'realistic_approach'],
    'artefact': ['action_plans'],
    'articulate': ['highly_articulate'],
    'asset': ['valuable_asset'],
    'assign': [   'special_assignments',
                  'changing_assignments',
                  'concurrent_assignments'],
    'attain': ['goal_attainment'],
    'attention': ['meticulous_attention'],
    'attitude': ['positive_attitude', 'optimistic_attitude'],
    'attribute': [   'positive_attributes',
                     'aggressive',
                     'meticulous',
                     'clear',
                     'competitive',
                     'fresh'],
    'authority': ['preeminent_authority'],
    'background': ['solid_background'],
    'benefit': ['synergistic_benefit'],
    'build': ['team_building'],
    'capable': [   'highly_capable',
                   'electronic_capabilities',
                   'unique_capabilities',
                   'proven_capabilities',
                   'core_capabilities'],
    'category': ['review_category', 'closing_recommendation'],
    'cause': ['root_causes'],
    'challenge': [   'greater_challenge',
                     'key_challenges',
                     'future_challenges',
                     'formidable_challenges',
                     'unique_challenges',
                     'critical_challenges'],
    'change': ['implementing_change'],
    'characteristic': ['distinguishing_characteristics', 'key_characteristics'],
    'charisma': ['personal_charisma'],
    'combination': ['unique_combination'],
    'commit': [   'sustained_commitment',
                  'strongly_committed',
                  'dedicated_commitment',
                  'unwavering_commitment',
                  'verbal_commitments',
                  'personal_commitment',
                  'enthusiastic_commitment',
                  'powerful_commitment',
                  'highly_committed'],
    'communicate': [   'competent_communicator',
                       'skilled_communicator',
                       'open_communications'],
    'competent': [   'technical_competence',
                     'professional_competence',
                     'highly_competent',
                     'core_competencies'],
    'competitive': [   'competitive_advantage',
                       'competitive_edge',
                       'competitive_drive'],
    'complexity': ['complex_information'],
    'component': ['core_components'],
    'concept': ['new_concepts'],
    'conclusion': ['successful_conclusion', 'sound_conclusions'],
    'condition': ['changing_conditions'],
    'conduct': ['ethical_conduct'],
    'confident': ['continuing_confidence', 'self_confident'],
    'consciousness': [   'cost_conscious',
                         'time_conscious',
                         'quality_conscious',
                         'customer_conscious',
                         'profit_conscious',
                         'performance_conscious'],
    'consequence': ['unanticipated_consequences', 'unintended_consequences'],
    'considerable': ['sound_consideration'],
    'consideration': ['cost_considerations'],
    'consult': ['expert_consultation'],
    'contribute': [   'greater_contribution',
                      'maximum_contribution',
                      'substantial_contribution',
                      'significant_contribution'],
    'contributor': [   'important_contributor',
                       'major_contributor',
                       'solid_contributor',
                       'strong_contributor'],
    'control': [   'solid_control',
                   'damage_control',
                   'maintaining_control',
                   'cost_control',
                   'sound_controls'],
    'cooperate': ['productive_cooperation', 'close_cooperation'],
    'create': ['newly_created'],
    'creation': ['value_creation'],
    'credible': ['strong_credibility'],
    'creditable': ['highly_creditable'],
    'critical': ['constructive_criticism'],
    'culture': ['corporate_culture', 'organizational_culture'],
    'curve': ['learning_curve'],
    'decision': [   'sound_decisions',
                    'planning_decisions',
                    'independent_decisions'],
    'demand': ['multiple_demands'],
    'dependable': ['highly_dependable'],
    'desire': ['intense_desire'],
    'determine': ['priority_determinations'],
    'develop': ['innovative_developments', 'developing_solutions'],
    'development': [   'career_development',
                       'skill_development',
                       'self_development',
                       'sustained_development',
                       'formidable_development',
                       'professional_development'],
    'direct': ['positive_direction', 'solid_direction', 'self_direct'],
    'discipline': [   'constructive_discipline',
                      'financial_discipline',
                      'budget_discipline',
                      'self_discipline'],
    'document': ['solid_documentation', 'fully_documented'],
    'drive': [   'solution_driven',
                 'shared_drive',
                 'energy_drive',
                 'inner_drive',
                 'success_driven'],
    'dynamic': ['team_dynamics'],
    'edge': ['leading_edge'],
    'effect': ['cumulative_effects'],
    'effective': [   'personal_effectiveness',
                     'cost_effectiveness',
                     'highly_effective',
                     'maximum_effectiveness',
                     'management_effectiveness',
                     'professional_effectiveness',
                     'organizational_effectiveness',
                     'optimal_effectiveness'],
    'efficient': [   'maximum_efficiency',
                     'increasing_efficiency',
                     'time_efficient',
                     'peak_efficiency',
                     'management_efficiency'],
    'effort': [   'concentrated_effort',
                  'team_effort',
                  'extra_efforts',
                  'focused_efforts',
                  'determined_efforts',
                  'maximum_effort',
                  'strong_effort',
                  'continuing_efforts',
                  'unified_efforts'],
    'element': ['key_element', 'critical_elements'],
    'employee': ['key_employee'],
    'energy': ['renewed_energy', 'sustained_energy', 'highly_energized'],
    'enhance': ['quality_enhancement'],
    'enlarge': ['job_enlargement'],
    'enrich': ['job_enrichment'],
    'enthusiasm': [   'fresh_enthusiasm',
                      'marked_enthusiasm',
                      'committed_enthusiasm',
                      'high_enthusiasm'],
    'esteem': ['self_esteem', 'esteem'],
    'ethic': ['professional_ethics'],
    'excellence': [   'creative_excellence',
                      'operational_excellence',
                      'professional_excellence'],
    'expect': [   'clear_expectations',
                  'positive_expectations',
                  'organizational_expectations',
                  'meets_expectations',
                  'management_expectations',
                  'exceeds_expectations'],
    'expense': ['controlling_expenses'],
    'experience': ['solid_experience', 'learning_experience'],
    'expertise': ['unique_expertise', 'professional_expertise'],
    'facet': ['multi_facet'],
    'fact': ['documented_facts'],
    'factor': ['critical_factors'],
    'feedback': ['positive_feedback', 'constructive_feedback'],
    'flexible': ['considerable_flexibility'],
    'focus': [   'highly_focused',
                 'result_focus',
                 'dedicated_focus',
                 'strategically_focused',
                 'maintaining_focus',
                 'customer_focused'],
    'force': ['positive_force', 'driving_force'],
    'foundation': ['solid_foundation'],
    'generate': ['computer_generated'],
    'global': ['thinks_globally'],
    'goal': ['organizational_goals'],
    'grammatical_comparison': ['superlative'],
    'growth': [   'superior_growth',
                  'consistent_growth',
                  'sustainable_growth',
                  'personal_growth',
                  'solid_growth',
                  'steady_growth',
                  'strong_growth'],
    'high': ['consistently_high'],
    'honest': ['impeccable_honesty'],
    'horizon': ['intellectual_horizons'],
    'idea': ['constructive_ideas', 'fresh_ideas', 'conceptual_ideas'],
    'image': ['favorable_image', 'positive_image'],
    'impact': [   'productive_impact',
                  'robust_impact',
                  'profound_impact',
                  'positive_impact',
                  'personal_impact',
                  'significant_impact',
                  'strong_impact',
                  'performance_impact',
                  'high_impact',
                  'favorable_impact',
                  'maximum_impact'],
    'implication': ['cost_implications'],
    'important': ['critical_importance'],
    'impress': [   'dynamic_impressions',
                   'first_impressions',
                   'favorable_impression'],
    'improve': [   'creative_improvements',
                   'incremental_improvements',
                   'quality_improvement',
                   'continuous_improvement',
                   'exceptional_improvement'],
    'incident': ['critical_incidents'],
    'industry': ['extremely_industrious'],
    'inflation': ['rating_inflation'],
    'influence': ['positive_influence', 'stabilizing_influence'],
    'inform': ['well_informed'],
    'innovation': ['imaginative_innovation'],
    'insight': [   'fresh_insights',
                   'practical_insights',
                   'critical_insights',
                   'unique_insights',
                   'innovative_insight',
                   'powertul_insights'],
    'integrity': ['personal_integrity'],
    'interest': ['keen_interest'],
    'intervention': ['positive_intervention'],
    'involve': ['total_involvement'],
    'judgment': ['intuitive_judgments', 'sound_judgment'],
    'knowledge': [   'unique_knowledge',
                     'essential_knowledge',
                     'working_knowledge',
                     'operating_knowledge',
                     'shared_knowledge'],
    'leader': ['energetic_leader', 'opinion_leader'],
    'leadership': ['environmental_leadership', 'visionary_leadership'],
    'level': ['performance_levels', 'optimal_levels'],
    'look': ['forward_looking'],
    'magnetism': ['personal_magnetism'],
    'management': [   'crisis_management',
                      'management_skill',
                      'middle_management',
                      'top_management'],
    'manner': ['efficient_manner'],
    'measure': [   'corrective_measures',
                   'control_measures',
                   'prompt_measures',
                   'performance_measurement'],
    'method': ['unique_methods'],
    'mind': ['profit_mind', 'open_mind', 'serious_mind'],
    'momentum': [   'maintaining_momentum',
                    'high_momentum',
                    'enthusiastic_momentum'],
    'motive': ['team_motivator', 'self_motive', 'strong_motivator'],
    'mover': ['prime_mover'],
    'need': ['training_needs'],
    'objective': ['realistic_objectives'],
    'opportunity': [   'challenging_opportunities',
                       'learning_opportunities',
                       'unparalleled_opportunities',
                       'sales_opportunities',
                       'unique_opportunities',
                       'strategic_opportunities'],
    'orient': [   'customer_orientation',
                  'result_oriented',
                  'strategy_orient',
                  'success_orient',
                  'challenge_oriented',
                  'profit_oriented',
                  'future_oriented'],
    'outcome': ['optimal_outcomes', 'exceptional_outcomes'],
    'outlook': ['positive_outlook'],
    'output': ['high_output'],
    'pace': ['self_pacing'],
    'participant': [   'full_participation',
                       'fullest_participation',
                       'professional_participation'],
    'payoff': ['high_payoff'],
    'peak': ['performance_peak'],
    'perform': [   'dynamic_performance',
                   'proven_performer',
                   'enhanced_performance',
                   'team_performance',
                   'solid_performer',
                   'competent_performer',
                   'sustained_performance',
                   'strong_performer',
                   'consistent_performance',
                   'peak_performance',
                   'confident_performer',
                   'enterprising_performance',
                   'top_performer'],
    'persevere': ['strong_perseverance'],
    'perspective': [   'global_perspective',
                       'unique_perspective',
                       'proper_perspective',
                       'sound_perspectives',
                       'fresh_perspective',
                       'new_perspectives'],
    'plan': [   'innovative_planning',
                'crucial_planning',
                'contingency_plans',
                'strategic_plans'],
    'plateau': ['job_plateauing'],
    'position': [   'strategically_positioned',
                    'ideally_positioned',
                    'premier_position',
                    'well_positioned',
                    'uniquely_positioned'],
    'possible': ['innovative_possibilities'],
    'potential': [   'untapped_potential',
                     'growth_potential',
                     'true_potential',
                     'strong_potential',
                     'high_potential',
                     'hidden_potential'],
    'power': ['synergistic_power'],
    'prepare': ['fully_prepared'],
    'presentation': ['effective_presentations'],
    'prevent': ['crisis_prevention', 'problem_prevention'],
    'principle': ['core_principles', 'management_principles'],
    'priority': [   'task_priorities',
                    'competing_priorities',
                    'strategic_priorities',
                    'cost_priorities',
                    'highest_priority',
                    'changing_priorities'],
    'problem': ['challenging_problems', 'core_problems'],
    'producer': ['strong_producer', 'sales_producer', 'high_producer'],
    'product': ['expected_production'],
    'productive': ['optimum_productivity', 'maximum_productivity'],
    'professional': ['conveying_professionalism'],
    'proficient': ['highly_proficient', 'speech_proficiency'],
    'profile': ['high_profile'],
    'progress': [   'significant_progress',
                    'exceptional_progress',
                    'consistent_progress',
                    'tracking_progress',
                    'steady_progress'],
    'promote': ['highly_promotable'],
    'property': ['intellectual_property'],
    'punctual': ['consistently_punctual'],
    'qualify': [   'strongly_qualified',
                   'eminently_qualified',
                   'uniquely_qualified',
                   'well_qualified'],
    'quality': ['leadership_qualities', 'high_quality', 'improving_quality'],
    'quantity': ['zero'],
    'recognition': ['high_recognition'],
    'record': ['remarkable_record', 'proven_record', 'stellar_record'],
    'records_management': [   'operational_records_management',
                              'confidential_records_management'],
    'reduction': ['cost_reductions'],
    'regard': ['highly_regarded'],
    'reinforce': ['positive_reinforcement'],
    'relationship': ['supportive_relationships'],
    'reliable': ['self_reliant', 'extremely_reliable'],
    'reposition': ['strategic_repositioning'],
    'reputation': ['solid_reputation'],
    'resolution': ['conflict_resolution'],
    'resource': [   'extremely_resourceful',
                    'multiple_resources',
                    'valuable_resource',
                    'available_resources',
                    'maximizing_resources',
                    'organizational_resources',
                    'unique_resource'],
    'respect': ['highly_respected', 'most_respected'],
    'response': ['ultimate_responsibility', 'core_responsibility'],
    'result': [   'optimal_results',
                  'impressive_results',
                  'desired_results',
                  'systematic_results',
                  'significant_results',
                  'maximum_results',
                  'sustainable_results',
                  'measurable_results'],
    'return': ['greatest_return', 'maximum_return'],
    'review_category': [   'prioritize',
                           'leadership',
                           'budget',
                           'project_management',
                           'initative',
                           'cost_management',
                           'vendor',
                           'coaching_and_counseling',
                           'plan',
                           'artificial_intelligence',
                           'meet',
                           'potential',
                           'decision_making',
                           'feedback',
                           'quality',
                           'customer_service',
                           'management_skills_for_middle_management',
                           'development',
                           'resource',
                           'goals_and_objectives',
                           'mature',
                           'innovation',
                           'maintenance_management',
                           'versatile',
                           'risk_take',
                           'improve',
                           'cooperate',
                           'intellectual_property_management',
                           'safety_and_security',
                           'problem_solving',
                           'resilient',
                           'personal_quality',
                           'achieve',
                           'management_skills_for_top_management',
                           'knowledge',
                           'logistic',
                           'vision',
                           'records_management',
                           'motive',
                           'persuasiveness',
                           'multitasking',
                           'organize',
                           'delegating',
                           'global',
                           'tact',
                           'stress',
                           'accuracy',
                           'ethic',
                           'time_management',
                           'assign',
                           'professional',
                           'creative',
                           'sales_management',
                           'sell',
                           'expense_control',
                           'communication_skills',
                           'loyalty_and_dedication',
                           'environmental',
                           'dependable',
                           'administration',
                           'oral_expression',
                           'judgment',
                           'competency',
                           'response',
                           'coordinate',
                           'productive'],
    'risk': ['calculated_risks'],
    'role': [   'vital_role',
                'significant_role',
                'key_role',
                'important_role',
                'critical_role',
                'pivotal_role',
                'leadership_role'],
    'safety': ['safety_conscious'],
    'satisfy': ['customer_satisfaction'],
    'seeker': ['goal_seeker', 'solution_seeker'],
    'sequence': ['logical_sequence'],
    'service': ['support_services'],
    'situation': [   'stressful_situations',
                     'crisis_situations',
                     'demanding_situations',
                     'sensitive_situations',
                     'changing_situations'],
    'skill': [   'negotiating_skill',
                 'interpersonal_skill',
                 'learning_skill',
                 'team_skill',
                 'evaluation_skill',
                 'analytical_approach',
                 'supervisory_skill',
                 'technical_skill',
                 'recruiting_skill',
                 'practical_skills',
                 'presentation_skill',
                 'computer_skill',
                 'alternative_solutions',
                 'specialized_skills',
                 'analytical_reasoning',
                 'writing_skills',
                 'critical_skills',
                 'accurate_assessments',
                 'selling_skill',
                 'accurate_documentation',
                 'administrative_effectiveness',
                 'analytical_techniques',
                 'achieving_excellence',
                 'achieving_results',
                 'analytical_thinking',
                 'accepting_responsibility',
                 'professional_skills',
                 'accurate_predictions',
                 'essential_skill',
                 'supportive_skills',
                 'achievement_driven',
                 'articulate_communicator',
                 'analytical_qualities',
                 'achievement_oriented',
                 'solid_skills',
                 'administrative_support',
                 'accurate_evaluations',
                 'multiple_skills',
                 'empowerment_skills',
                 'administrative_competence',
                 'analytical_skill',
                 'operating_skills',
                 'cooperative_spirit',
                 'mental_skill',
                 'advanced_technologies',
                 'appropriate_measures',
                 'analytical_methods',
                 'active_participant',
                 'administrative_advancements',
                 'diversified_skills',
                 'accomplishing_results'],
    'solution': [   'stressful_solutions',
                    'critical_solutions',
                    'realistic_solutions',
                    'imaginative_solutions',
                    'simplified_solutions',
                    'practical_solutions',
                    'optional_solutions',
                    'viable_solutions',
                    'resourceful_solutions',
                    'planning_solutions',
                    'creative_solutions',
                    'initiating_solutions',
                    'innovative_solutions',
                    'satisfying_solutions'],
    'sophistication': ['highly_sophisticated'],
    'sound': ['strategically_sound'],
    'source': ['information_sources'],
    'speaker': ['confident_speaker'],
    'spirit': [   'enthusiastic_spirit',
                  'visionary_spirit',
                  'high_spirited',
                  'team_spirit'],
    'starter': ['self_starter'],
    'state': [   'appropriate_attention',
                 'complete',
                 'broadest_discretion',
                 'accumulated_knowledge',
                 'broad_mind',
                 'anticipated_performance',
                 'conventional_wisdom',
                 'complexity',
                 'broad_perspective',
                 'crisis',
                 'enthusiasm'],
    'strategy': [   'new_strategies',
                    'visionary_strategies',
                    'creative_strategies'],
    'strength': [   'individual_strengths',
                    'creative_strengths',
                    'hidden_strengths',
                    'basic_strengths',
                    'core_strengths',
                    'personal_strengths'],
    'success': [   'sustained_success',
                   'mutual_success',
                   'continued_success',
                   'maximum_success'],
    'superior': ['multiple_superiors'],
    'superlative': [   'strong',
                       'world_class',
                       'stellar',
                       'focus',
                       'maximum',
                       'high',
                       'great',
                       'ultimate',
                       'substantial'],
    'supervise': ['minimum_supervision'],
    'support': [   'fullest_support',
                   'highly_supportive',
                   'management_support',
                   'secretarial_support',
                   'organizational_support',
                   'loyal_support',
                   'creative_support'],
    'system': ['effective_systems'],
    'talent': [   'highly_talented',
                  'diverse_talents',
                  'unique_talents',
                  'creative_talent',
                  'hidden_talents'],
    'target': ['performance_targets', 'optimal_targets'],
    'task': ['routine_tasks'],
    'teamwork': ['promoting_teamwork'],
    'technique': [   'improving_techniques',
                     'creative_techniques',
                     'proven_techniques',
                     'solid_techniques',
                     'planning_techniques'],
    'technology': [   'emerging_technologies',
                      'computer_technologies',
                      'new_technologies'],
    'think': [   'fresh_thinking',
                 'innovative_thinking',
                 'practical_thinking',
                 'forward_thinking',
                 'creative_thinking',
                 'logical_thinking',
                 'heuristic_thinking',
                 'imaginative_thinking',
                 'critical_thinker',
                 'thinks_futuristically'],
    'thrust': ['strategic_thrust'],
    'tolerance': ['stress_tolerance', 'zero_tolerances'],
    'tone': ['positive_tone'],
    'tough': ['mental_toughness'],
    'trait': ['personal_traits'],
    'trajectory': ['growth_trajectory'],
    'transition': ['smooth_transition', 'organizational_transition'],
    'trend': ['emerging_trends', 'professional_trends', 'innovative_trends'],
    'utilize': ['resource_utilization'],
    'value': [   'individual_values',
                 'shared_values',
                 'highly_valuable',
                 'personal_values',
                 'key_values',
                 'core_values',
                 'unique_value',
                 'creating_value'],
    'variable': ['key_variables'],
    'visible': ['greater_visibility', 'personal_visibility'],
    'vision': ['shared_vision', 'strategic_vision'],
    'work': ['hard_work'],
    'writer': ['skilled_writer'],
    'zeal': ['impressive_zeal']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
