
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class AppraisalImpliesRev(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'AppraisalImplies',
            'filename': 'appraisal_implies',
            'queries': ['implies.sparql % $PREFIX=appraisal'],
            'reverse': True,
            'transformers': ['lowercase', 'implies']},
 'source': 'appraisal.owl',
 'time': '2022-04-27 21:15:17.723283'}

    __data = {
    'ability': ['cognitive_ability', 'intuitive_ability'],
    'accelerate': ['accelerate_change'],
    'accomplishings': ['accomplishing_results'],
    'accomplishments': ['significant_accomplishments'],
    'accountability': ['foremost_accountability'],
    'accumulated': ['accumulated_knowledge'],
    'accurateation': ['accurate_documentation'],
    'accurateions': ['accurate_predictions'],
    'accuratements': ['accurate_assessments'],
    'achievement': [   'critical_achievement',
                       'notable_achievement',
                       'substantial_achievement',
                       'achievement_driven'],
    'achievemented': ['achievement_oriented'],
    'achiever': [   'consistent_achiever',
                    'goal_achiever',
                    'high_achiever',
                    'solid_achiever',
                    'strong_achiever'],
    'achieving': ['achieving_excellence'],
    'achievinglence': ['achieving_excellence'],
    'achievings': ['achieving_results'],
    'actions': ['action_plans', 'constructive_actions', 'positive_actions'],
    'active': ['active_participant'],
    'activities': ['essential_activities'],
    'administrative': ['administrative_competence', 'administrative_support'],
    'administrativements': ['administrative_advancements'],
    'administrativeness': ['administrative_effectiveness'],
    'advancements': ['administrative_advancements'],
    'advantage': ['competitive_advantage', 'optimum_advantage'],
    'alternatives': ['alternative_solutions', 'creative_alternatives'],
    'analytical': ['analytical_approach', 'analytical_skill'],
    'analyticaling': ['analytical_reasoning', 'analytical_thinking'],
    'analyticals': ['analytical_methods', 'analytical_techniques'],
    'and_dedication': ['loyalty_and_dedication'],
    'and_security': ['safety_and_security'],
    'anticipatedance': ['anticipated_performance'],
    'application': ['computer_application'],
    'approach': [   'analytical_approach',
                    'positive_approach',
                    'realistic_approach',
                    'sound_approach',
                    'systematic_approach'],
    'approaches': ['new_approaches'],
    'appropriate': ['appropriate_attention'],
    'appropriates': ['appropriate_measures'],
    'assessments': ['accurate_assessments'],
    'asset': ['valuable_asset'],
    'assignments': ['concurrent_assignments', 'special_assignments'],
    'attainment': ['goal_attainment'],
    'attention': ['appropriate_attention', 'meticulous_attention'],
    'attitude': ['optimistic_attitude', 'positive_attitude'],
    'attributes': ['positive_attributes'],
    'authority': ['preeminent_authority'],
    'availables': ['available_resources'],
    'background': ['solid_background'],
    'basics': ['basic_strengths'],
    'benefit': ['synergistic_benefit'],
    'broad': ['broad_mind', 'broad_perspective'],
    'broadest': ['broadest_discretion'],
    'budget': ['budget_discipline'],
    'building': ['career_building', 'team_building'],
    'calculateds': ['calculated_risks'],
    'capabilities': [   'core_capabilities',
                        'electronic_capabilities',
                        'proven_capabilities',
                        'unique_capabilities'],
    'career': ['career_development'],
    'careering': ['career_building'],
    'causes': ['root_causes'],
    'challengeed': ['challenge_oriented'],
    'challenges': [   'critical_challenges',
                      'formidable_challenges',
                      'future_challenges',
                      'key_challenges',
                      'unique_challenges'],
    'challengings': ['challenging_problems'],
    'change': ['accelerate_change'],
    'changingments': ['changing_assignments'],
    'changings': ['changing_conditions', 'changing_situations'],
    'characteristics': ['key_characteristics'],
    'class': ['world_class'],
    'clearations': ['clear_expectations'],
    'coaching_anding': ['coaching_and_counseling'],
    'cognitive': ['cognitive_ability'],
    'combination': ['unique_combination'],
    'commitment': ['unwavering_commitment'],
    'commitments': ['verbal_commitments'],
    'committed': ['committed_enthusiasm'],
    'communications': ['open_communications', 'communication_skills'],
    'communicator': ['articulate_communicator', 'competent_communicator'],
    'competence': [   'administrative_competence',
                      'professional_competence',
                      'technical_competence'],
    'competencies': ['core_competencies'],
    'competenter': ['competent_performer'],
    'competitive': [   'competitive_advantage',
                       'competitive_drive',
                       'competitive_edge'],
    'complex': ['complex_information'],
    'complexation': ['complex_information'],
    'components': ['core_components'],
    'computer': ['computer_application', 'computer_skill'],
    'computerd': ['computer_generated'],
    'concentrated': ['concentrated_effort'],
    'concepts': ['new_concepts'],
    'conceptuals': ['conceptual_ideas'],
    'conclusions': ['sound_conclusions'],
    'concurrentments': ['concurrent_assignments'],
    'confident': ['confident_speaker', 'self_confident'],
    'confidenter': ['confident_performer'],
    'confidential_records': ['confidential_records_management'],
    'confidentials_management': ['confidential_records_management'],
    'conflict': ['conflict_resolution'],
    'conscious': [   'cost_conscious',
                     'customer_conscious',
                     'profit_conscious',
                     'quality_conscious',
                     'safety_conscious',
                     'time_conscious'],
    'consequences': ['unanticipated_consequences', 'unintended_consequences'],
    'consideration': ['sound_consideration'],
    'considerations': ['cost_considerations'],
    'consistent': ['consistent_growth', 'consistent_progress'],
    'consistentance': ['consistent_performance'],
    'consistently': ['consistently_high', 'consistently_punctual'],
    'consistentr': ['consistent_achiever'],
    'constructive': ['constructive_discipline', 'constructive_feedback'],
    'constructives': ['constructive_actions', 'constructive_ideas'],
    'consultation': ['expert_consultation'],
    'contingencys': ['contingency_plans'],
    'continued': ['continued_success'],
    'continuings': ['continuing_efforts'],
    'continuousment': ['continuous_improvement'],
    'contribution': [   'maximum_contribution',
                        'significant_contribution',
                        'substantial_contribution'],
    'contributor': [   'important_contributor',
                       'major_contributor',
                       'solid_contributor',
                       'strong_contributor'],
    'control': [   'cost_control',
                   'damage_control',
                   'expense_control',
                   'solid_control'],
    'controllings': ['controlling_expenses'],
    'controls': ['control_measures', 'sound_controls'],
    'conventional': ['conventional_wisdom'],
    'conveyingism': ['conveying_professionalism'],
    'cooperation': ['close_cooperation', 'productive_cooperation'],
    'cooperative': ['cooperative_spirit'],
    'cores': [   'core_components',
                 'core_principles',
                 'core_problems',
                 'core_strengths',
                 'core_values'],
    'corporate': ['corporate_culture'],
    'correctives': ['corrective_actions', 'corrective_measures'],
    'cost': ['cost_control', 'cost_management'],
    'costness': ['cost_effectiveness'],
    'costs': ['cost_considerations', 'cost_implications', 'cost_reductions'],
    'creating': ['creating_value'],
    'creation': ['value_creation'],
    'creative': ['creative_excellence', 'creative_support', 'creative_talent'],
    'creativeing': ['creative_thinking'],
    'creativements': ['creative_improvements'],
    'creatives': [   'creative_alternatives',
                     'creative_solutions',
                     'creative_strengths',
                     'creative_techniques'],
    'credibility': ['strong_credibility'],
    'crisis': ['crisis_management'],
    'crisision': ['crisis_prevention'],
    'crisiss': ['crisis_situations'],
    'critical': ['critical_role'],
    'criticaler': ['critical_thinker'],
    'criticalment': ['critical_achievement'],
    'criticals': [   'critical_challenges',
                     'critical_elements',
                     'critical_factors',
                     'critical_incidents',
                     'critical_insights',
                     'critical_skills',
                     'critical_solutions'],
    'criticism': ['constructive_criticism'],
    'crucialning': ['crucial_planning'],
    'culture': ['corporate_culture', 'organizational_culture'],
    'cumulatives': ['cumulative_effects'],
    'customer': ['customer_service'],
    'customeration': ['customer_orientation'],
    'customered': ['customer_focused'],
    'damage': ['damage_control'],
    'decisions': ['independent_decisions', 'sound_decisions'],
    'decisive': ['decisive_action'],
    'dedicated': ['dedicated_focus'],
    'dedicatedment': ['dedicated_commitment'],
    'demandings': ['demanding_situations'],
    'demands': ['multiple_demands'],
    'desire': ['intense_desire'],
    'desireds': ['desired_results'],
    'determinations': ['priority_determinations'],
    'determineds': ['determined_efforts'],
    'developings': ['developing_solutions'],
    'development': [   'career_development',
                       'formidable_development',
                       'professional_development',
                       'self_development',
                       'skill_development'],
    'direct': ['self_direct'],
    'direction': ['positive_direction', 'solid_direction'],
    'disciplinary': ['disciplinary_action'],
    'discipline': [   'budget_discipline',
                      'constructive_discipline',
                      'self_discipline'],
    'disciplined': ['disciplined_approach'],
    'distinguishings': ['distinguishing_characteristics'],
    'diverses': ['diverse_talents'],
    'diversifiedes': ['diversified_approaches'],
    'diversifieds': ['diversified_skills'],
    'documentation': ['accurate_documentation', 'solid_documentation'],
    'documenteds': ['documented_facts'],
    'drive': ['competitive_drive', 'energy_drive', 'inner_drive'],
    'driven': ['solution_driven', 'success_driven'],
    'driving': ['driving_force'],
    'dynamicance': ['dynamic_performance'],
    'dynamicions': ['dynamic_impressions'],
    'dynamics': ['team_dynamics'],
    'edge': ['competitive_edge'],
    'effectiveations': ['effective_presentations'],
    'effectiveness': [   'administrative_effectiveness',
                         'cost_effectiveness',
                         'management_effectiveness',
                         'maximum_effectiveness',
                         'optimal_effectiveness',
                         'organizational_effectiveness',
                         'professional_effectiveness'],
    'effectives': ['effective_presentations', 'effective_systems'],
    'effects': ['cumulative_effects'],
    'efficiency': [   'management_efficiency',
                      'maximum_efficiency',
                      'peak_efficiency'],
    'efficient': ['efficient_manner', 'time_efficient'],
    'effort': ['maximum_effort', 'strong_effort', 'team_effort'],
    'efforts': ['extra_efforts'],
    'element': ['key_element'],
    'elements': ['critical_elements'],
    'emergings': ['emerging_trends'],
    'employee': ['key_employee'],
    'empowerments': ['empowerment_skills'],
    'energetic': ['energetic_leader'],
    'energy': ['energy_drive'],
    'enhancedance': ['enhanced_performance'],
    'enhancement': ['quality_enhancement'],
    'enlargement': ['job_enlargement'],
    'enrichment': ['job_enrichment'],
    'enterprisingance': ['enterprising_performance'],
    'enthusiasm': ['fresh_enthusiasm', 'high_enthusiasm', 'marked_enthusiasm'],
    'enthusiastic': ['enthusiastic_momentum', 'enthusiastic_spirit'],
    'enthusiasticment': ['enthusiastic_commitment'],
    'environmental': ['environmental_leadership'],
    'essential': ['essential_knowledge', 'essential_skill'],
    'esteem': ['self_esteem'],
    'ethical': ['ethical_conduct'],
    'ethics': ['professional_ethics'],
    'evaluation': ['evaluation_skill'],
    'evaluations': ['accurate_evaluations'],
    'exceedsations': ['exceeds_expectations'],
    'excellence': ['creative_excellence', 'professional_excellence'],
    'exceptional': ['exceptional_progress'],
    'exceptionalment': ['exceptional_improvement'],
    'exceptionals': ['exceptional_outcomes'],
    'expectations': [   'clear_expectations',
                        'management_expectations',
                        'organizational_expectations',
                        'positive_expectations'],
    'expectedion': ['expected_production'],
    'expense': ['expense_control'],
    'experience': ['solid_experience'],
    'expertation': ['expert_consultation'],
    'expertise': ['professional_expertise', 'unique_expertise'],
    'expression': ['oral_expression'],
    'extras': ['extra_efforts'],
    'extremely': ['extremely_reliable'],
    'extremelyful': ['extremely_resourceful'],
    'facet': ['multi_facet'],
    'factors': ['critical_factors'],
    'fast': ['fast_pace'],
    'favorable': ['favorable_image', 'favorable_impact'],
    'favorableion': ['favorable_impression'],
    'feedback': ['constructive_feedback', 'positive_feedback'],
    'financial': ['financial_discipline'],
    'firstions': ['first_impressions'],
    'flexibility': ['considerable_flexibility'],
    'focus': ['result_focus'],
    'focused': ['customer_focused'],
    'focuseds': ['focused_efforts'],
    'force': ['positive_force'],
    'foremostability': ['foremost_accountability'],
    'formidable': ['formidable_development'],
    'formidables': ['formidable_challenges'],
    'forwarding': ['forward_looking', 'forward_thinking'],
    'foundation': ['solid_foundation'],
    'fresh': ['fresh_enthusiasm', 'fresh_perspective'],
    'freshing': ['fresh_thinking'],
    'freshs': ['fresh_ideas', 'fresh_insights'],
    'fullest': ['fullest_support'],
    'fullyd': ['fully_prepared'],
    'fullyed': ['fully_documented'],
    'futureed': ['future_oriented'],
    'futures': ['future_challenges'],
    'generated': ['computer_generated'],
    'global': ['global_perspective'],
    'goal': ['goal_seeker'],
    'goalment': ['goal_attainment'],
    'goalr': ['goal_achiever'],
    'goals': ['organizational_goals'],
    'goals_ands': ['goals_and_objectives'],
    'greater': ['greater_challenge'],
    'greaterment': ['greater_achievement'],
    'greatest': ['greatest_return'],
    'growth': [   'consistent_growth',
                  'growth_potential',
                  'growth_trajectory',
                  'solid_growth',
                  'steady_growth',
                  'strong_growth',
                  'superior_growth'],
    'hands': ['hands_on'],
    'heuristicing': ['heuristic_thinking'],
    'hidden': ['hidden_potential'],
    'hiddens': ['hidden_strengths', 'hidden_talents'],
    'high': [   'high_enthusiasm',
                'high_impact',
                'high_momentum',
                'high_output',
                'high_payoff',
                'high_potential',
                'high_producer',
                'high_profile',
                'high_quality',
                'high_recognition'],
    'highed': ['high_spirited'],
    'highest': ['highest_priority'],
    'highly': [   'highly_articulate',
                  'highly_capable',
                  'highly_competent',
                  'highly_creditable',
                  'highly_dependable',
                  'highly_effective',
                  'highly_proficient'],
    'highlyed': [   'highly_acclaimed',
                    'highly_focused',
                    'highly_regarded',
                    'highly_respected',
                    'highly_talented'],
    'highlyive': ['highly_adaptive', 'highly_supportive'],
    'highlyted': ['highly_committed'],
    'highr': ['high_achiever'],
    'horizons': ['intellectual_horizons'],
    'ideallyed': ['ideally_positioned'],
    'ideas': ['constructive_ideas', 'fresh_ideas'],
    'image': ['positive_image'],
    'imaginative': ['imaginative_innovation'],
    'imaginativeing': ['imaginative_thinking'],
    'imaginatives': ['imaginative_solutions'],
    'impact': [   'high_impact',
                  'maximum_impact',
                  'positive_impact',
                  'productive_impact',
                  'profound_impact',
                  'robust_impact',
                  'significant_impact',
                  'strong_impact'],
    'impeccabley': ['impeccable_honesty'],
    'implementing': ['implementing_change'],
    'implications': ['cost_implications'],
    'importance': ['critical_importance'],
    'important': ['important_contributor', 'important_role'],
    'impressions': ['dynamic_impressions', 'first_impressions'],
    'impressive': ['impressive_zeal'],
    'impressives': ['impressive_results'],
    'improvement': ['quality_improvement'],
    'improvements': ['creative_improvements'],
    'improving': ['improving_quality'],
    'improvings': ['improving_techniques'],
    'incidents': ['critical_incidents'],
    'incrementalments': ['incremental_improvements'],
    'independents': ['independent_decisions'],
    'individuals': ['individual_strengths', 'individual_values'],
    'inflation': ['rating_inflation'],
    'influence': ['positive_influence'],
    'information': ['complex_information'],
    'informations': ['information_sources'],
    'informed': ['well_informed'],
    'initiatings': ['initiating_solutions'],
    'inner': ['inner_drive'],
    'innovative': ['innovative_insight'],
    'innovativeing': ['innovative_thinking'],
    'innovativements': ['innovative_developments'],
    'innovativening': ['innovative_planning'],
    'innovatives': ['innovative_solutions', 'innovative_trends'],
    'insights': [   'critical_insights',
                    'fresh_insights',
                    'powertul_insights',
                    'unique_insights'],
    'intellectual': ['intellectual_property'],
    'intellectual_management': ['intellectual_property_management'],
    'intellectual_property': ['intellectual_property_management'],
    'intellectuals': ['intellectual_horizons'],
    'intelligence': ['artificial_intelligence'],
    'intense': ['intense_desire'],
    'interest': ['keen_interest'],
    'interpersonal': ['interpersonal_skill'],
    'intervention': ['positive_intervention'],
    'intuitive': ['intuitive_ability'],
    'intuitives': ['intuitive_judgments'],
    'involvement': ['total_involvement'],
    'jobing': ['job_plateauing'],
    'jobment': ['job_enlargement', 'job_enrichment'],
    'judgment': ['sound_judgment'],
    'judgments': ['intuitive_judgments'],
    'keen': ['keen_interest'],
    'key': ['key_element', 'key_employee', 'key_role'],
    'keys': [   'key_challenges',
                'key_characteristics',
                'key_values',
                'key_variables'],
    'knowledge': ['essential_knowledge', 'unique_knowledge'],
    'leader': ['opinion_leader'],
    'leadership': ['environmental_leadership', 'leadership_role'],
    'leading': ['leading_edge'],
    'learning': ['learning_curve', 'learning_experience', 'learning_skill'],
    'levels': ['optimal_levels'],
    'logical': ['logical_sequence'],
    'logicaling': ['logical_thinking'],
    'looking': ['forward_looking'],
    'loyal': ['loyal_support'],
    'maintaining': [   'maintaining_control',
                       'maintaining_focus',
                       'maintaining_momentum'],
    'maintenance': ['maintenance_management'],
    'major': ['major_contributor'],
    'making': ['decision_making'],
    'management': [   'cost_management',
                      'crisis_management',
                      'maintenance_management',
                      'management_skill',
                      'management_support',
                      'middle_management',
                      'project_management',
                      'sales_management',
                      'time_management',
                      'top_management'],
    'management_skills_for_management': [   'management_skills_for_middle_management',
                                            'management_skills_for_top_management'],
    'management_skills_middle_management': [   'management_skills_for_middle_management'],
    'management_skills_top_management': [   'management_skills_for_top_management'],
    'managementations': ['management_expectations'],
    'managementness': ['management_effectiveness'],
    'managements': ['management_principles'],
    'managements_for_middle_management': [   'management_skills_for_middle_management'],
    'managements_for_top_management': ['management_skills_for_top_management'],
    'manner': ['efficient_manner'],
    'marked': ['marked_enthusiasm'],
    'maximizings': ['maximizing_resources'],
    'maximum': [   'maximum_effort',
                   'maximum_impact',
                   'maximum_return',
                   'maximum_success'],
    'maximumness': ['maximum_effectiveness'],
    'maximums': ['maximum_results'],
    'measurables': ['measurable_results'],
    'measures': ['appropriate_measures', 'control_measures', 'prompt_measures'],
    'meetsations': ['meets_expectations'],
    'mental': ['mental_skill'],
    'mentalness': ['mental_toughness'],
    'methods': ['analytical_methods', 'unique_methods'],
    'meticulous': ['meticulous_attention'],
    'middle': ['middle_management'],
    'mind': ['broad_mind', 'open_mind', 'profit_mind', 'serious_mind'],
    'momentum': ['high_momentum'],
    'mosted': ['most_respected'],
    'motivator': ['strong_motivator', 'team_motivator'],
    'motive': ['self_motive'],
    'mover': ['prime_mover'],
    'multi': ['multi_facet', 'multi_task'],
    'multiples': [   'multiple_demands',
                     'multiple_resources',
                     'multiple_skills',
                     'multiple_superiors'],
    'mutual': ['mutual_success'],
    'negotiating': ['negotiating_skill'],
    'newes': ['new_approaches'],
    'newlyd': ['newly_created'],
    'news': ['new_concepts', 'new_perspectives'],
    'notablement': ['notable_achievement'],
    'objectives': ['realistic_objectives'],
    'on': ['hands_on'],
    'open': ['open_mind'],
    'operating': ['operating_knowledge'],
    'operatings': ['operating_skills'],
    'operational': ['operational_excellence'],
    'operational_records': ['operational_records_management'],
    'operationals_management': ['operational_records_management'],
    'opinion': ['opinion_leader'],
    'opportunities': [   'sales_opportunities',
                         'unique_opportunities',
                         'unparalleled_opportunities'],
    'optimalness': ['optimal_effectiveness'],
    'optimals': [   'optimal_levels',
                    'optimal_outcomes',
                    'optimal_results',
                    'optimal_targets'],
    'optimistic': ['optimistic_attitude'],
    'optimum': ['optimum_advantage'],
    'optionals': ['optional_solutions'],
    'oral': ['oral_expression'],
    'organizational': [   'organizational_culture',
                          'organizational_support',
                          'organizational_transition'],
    'organizationalations': ['organizational_expectations'],
    'organizationalness': ['organizational_effectiveness'],
    'organizationals': ['organizational_goals', 'organizational_resources'],
    'orient': ['strategy_orient', 'success_orient'],
    'orientation': ['customer_orientation'],
    'oriented': [   'challenge_oriented',
                    'future_oriented',
                    'profit_oriented',
                    'result_oriented'],
    'outcomes': ['optimal_outcomes'],
    'outlook': ['positive_outlook'],
    'output': ['high_output'],
    'pace': ['fast_pace'],
    'pacing': ['self_pacing'],
    'participant': ['active_participant'],
    'participation': ['full_participation', 'professional_participation'],
    'payoff': ['high_payoff'],
    'peakance': ['peak_performance'],
    'performance': [   'consistent_performance',
                       'dynamic_performance',
                       'performance_impact',
                       'peak_performance',
                       'performance_peak',
                       'team_performance'],
    'performancement': ['performance_measurement'],
    'performances': ['performance_levels', 'performance_targets'],
    'performer': [   'competent_performer',
                     'confident_performer',
                     'proven_performer',
                     'solid_performer',
                     'strong_performer',
                     'top_performer'],
    'perseverance': ['strong_perseverance'],
    'personal': [   'personal_charisma',
                    'personal_growth',
                    'personal_impact',
                    'personal_integrity',
                    'personal_magnetism',
                    'personal_quality',
                    'personal_traits'],
    'personalability': ['personal_accountability'],
    'personalment': ['personal_commitment'],
    'personalness': ['personal_effectiveness'],
    'personals': ['personal_strengths', 'personal_values'],
    'perspective': [   'broad_perspective',
                       'fresh_perspective',
                       'global_perspective',
                       'proper_perspective',
                       'unique_perspective'],
    'perspectives': ['new_perspectives', 'sound_perspectives'],
    'persuasive': ['persuasive_ability'],
    'pivotal': ['pivotal_role'],
    'planning': ['crucial_planning'],
    'planninges': ['planning_approaches'],
    'plannings': [   'planning_decisions',
                     'planning_solutions',
                     'planning_techniques'],
    'plans': ['action_plans'],
    'plateauing': ['job_plateauing'],
    'position': ['premier_position'],
    'positioned': ['well_positioned'],
    'positive': [   'positive_approach',
                    'positive_attitude',
                    'positive_feedback',
                    'positive_force',
                    'positive_image',
                    'positive_impact',
                    'positive_influence',
                    'positive_intervention',
                    'positive_outlook',
                    'positive_tone'],
    'positiveations': ['positive_expectations'],
    'positiveion': ['positive_direction'],
    'positivement': ['positive_reinforcement'],
    'positives': ['positive_actions', 'positive_attributes'],
    'potential': [   'growth_potential',
                     'hidden_potential',
                     'high_potential',
                     'strong_potential',
                     'true_potential',
                     'untapped_potential'],
    'power': ['synergistic_power'],
    'powerfulment': ['powerful_commitment'],
    'powertuls': ['powertul_insights'],
    'practical': ['practical_advice'],
    'practicaling': ['practical_thinking'],
    'practicals': [   'practical_applications',
                      'practical_insights',
                      'practical_skills',
                      'practical_solutions'],
    'predictions': ['accurate_predictions'],
    'preeminent': ['preeminent_authority'],
    'premier': ['premier_position'],
    'presentation': ['presentation_skill'],
    'presentations': ['effective_presentations'],
    'prevention': ['crisis_prevention', 'problem_prevention'],
    'prime': ['prime_mover'],
    'principles': ['core_principles', 'management_principles'],
    'priorities': ['cost_priorities', 'task_priorities'],
    'problemion': ['problem_prevention'],
    'problems': ['core_problems'],
    'producer': ['high_producer', 'sales_producer', 'strong_producer'],
    'productive': ['productive_impact'],
    'productivity': ['maximum_productivity', 'optimum_productivity'],
    'professional': [   'professional_development',
                        'professional_excellence',
                        'professional_expertise'],
    'professionalness': ['professional_effectiveness'],
    'professionals': [   'professional_ethics',
                         'professional_skills',
                         'professional_trends'],
    'proficiency': ['speech_proficiency'],
    'profile': ['high_profile'],
    'profit': ['profit_mind'],
    'profited': ['profit_oriented'],
    'profound': ['profound_impact'],
    'progress': [   'consistent_progress',
                    'significant_progress',
                    'steady_progress'],
    'project': ['project_management'],
    'promoting': ['promoting_teamwork'],
    'prompts': ['prompt_measures'],
    'proper': ['proper_perspective'],
    'property_management': ['intellectual_property_management'],
    'proven': ['proven_record'],
    'provener': ['proven_performer'],
    'provens': ['proven_techniques'],
    'qualified': ['well_qualified'],
    'qualities': ['analytical_qualities', 'leadership_qualities'],
    'quality': ['high_quality'],
    'qualityment': ['quality_enhancement', 'quality_improvement'],
    'rating': ['rating_inflation'],
    'realistic': ['realistic_approach'],
    'realistics': ['realistic_objectives', 'realistic_solutions'],
    'reasoning': ['analytical_reasoning'],
    'recognition': ['high_recognition'],
    'record': ['proven_record', 'stellar_record'],
    'records': ['records_management'],
    'records_management': ['confidential_records_management'],
    'recruiting': ['recruiting_skill'],
    'reductions': ['cost_reductions'],
    'reinforcement': ['positive_reinforcement'],
    'reliant': ['self_reliant'],
    'remarkable': ['remarkable_record'],
    'renewed': ['renewed_energy'],
    'reputation': ['solid_reputation'],
    'resolution': ['conflict_resolution'],
    'resource': ['unique_resource', 'valuable_resource'],
    'resourcefuls': ['resourceful_solutions'],
    'resources': [   'available_resources',
                     'maximizing_resources',
                     'multiple_resources',
                     'organizational_resources'],
    'respected': ['most_respected'],
    'responsibility': [   'accepting_responsibility',
                          'core_responsibility',
                          'ultimate_responsibility'],
    'result': ['result_focus'],
    'resulted': ['result_oriented'],
    'results': [   'maximum_results',
                   'optimal_results',
                   'significant_results',
                   'systematic_results'],
    'return': ['maximum_return'],
    'risk': ['risk_take'],
    'robust': ['robust_impact'],
    'role': [   'critical_role',
                'important_role',
                'key_role',
                'leadership_role',
                'pivotal_role',
                'significant_role',
                'vital_role'],
    'roots': ['root_causes'],
    'routines': ['routine_tasks'],
    'sales': ['sales_management', 'sales_producer'],
    'satisfaction': ['customer_satisfaction'],
    'satisfyings': ['satisfying_solutions'],
    'secretarial': ['secretarial_support'],
    'seeker': ['goal_seeker', 'solution_seeker'],
    'self': [   'self_confident',
                'self_development',
                'self_direct',
                'self_discipline',
                'self_esteem',
                'self_motive',
                'self_starter'],
    'selling': ['selling_skill'],
    'sensitives': ['sensitive_situations'],
    'serious': ['serious_mind'],
    'service': ['customer_service'],
    'services': ['support_services'],
    'setter': ['trend_setter'],
    'shared': ['shared_drive', 'shared_knowledge', 'shared_vision'],
    'shareds': ['shared_values'],
    'shooting': ['trouble_shooting'],
    'significant': [   'significant_impact',
                       'significant_progress',
                       'significant_role'],
    'significantments': ['significant_accomplishments'],
    'significants': ['significant_results'],
    'simplifieds': ['simplified_solutions'],
    'situations': ['crisis_situations', 'sensitive_situations'],
    'skill': [   'analytical_skill',
                 'computer_skill',
                 'skill_development',
                 'essential_skill',
                 'interpersonal_skill',
                 'management_skill',
                 'mental_skill',
                 'presentation_skill',
                 'supervisory_skill',
                 'team_skill',
                 'technical_skill'],
    'skilled': ['skilled_writer'],
    'skills': [   'critical_skills',
                  'empowerment_skills',
                  'multiple_skills',
                  'professional_skills',
                  'solid_skills'],
    'skills_for_middle_management': ['management_skills_for_middle_management'],
    'skills_for_top_management': ['management_skills_for_top_management'],
    'smooth': ['smooth_transition'],
    'solid': [   'solid_background',
                 'solid_contributor',
                 'solid_control',
                 'solid_experience',
                 'solid_foundation',
                 'solid_growth',
                 'solid_reputation'],
    'solidation': ['solid_documentation'],
    'solider': ['solid_performer'],
    'solidion': ['solid_direction'],
    'solidr': ['solid_achiever'],
    'solids': ['solid_skills', 'solid_techniques'],
    'solution': ['solution_seeker'],
    'solutionn': ['solution_driven'],
    'solutions': [   'alternative_solutions',
                     'creative_solutions',
                     'critical_solutions',
                     'realistic_solutions',
                     'viable_solutions'],
    'solving': ['problem_solving'],
    'sound': ['sound_approach', 'sound_judgment'],
    'sounds': [   'sound_conclusions',
                  'sound_controls',
                  'sound_decisions',
                  'sound_perspectives'],
    'speaker': ['confident_speaker'],
    'specializeds': ['specialized_skills'],
    'specialments': ['special_assignments'],
    'spirit': ['team_spirit'],
    'spirited': ['high_spirited'],
    'stabilizing': ['stabilizing_influence'],
    'starter': ['self_starter'],
    'steady': ['steady_growth', 'steady_progress'],
    'stellar': ['stellar_record'],
    'stimulating': ['stimulating_action'],
    'strategic': ['strategic_thrust', 'strategic_vision'],
    'strategically': ['strategically_sound'],
    'strategicallyed': ['strategically_focused', 'strategically_positioned'],
    'strategicing': ['strategic_repositioning'],
    'strategics': ['strategic_alternatives', 'strategic_plans'],
    'strategies': ['creative_strategies', 'new_strategies'],
    'strategy': ['strategy_orient'],
    'strengths': [   'basic_strengths',
                     'core_strengths',
                     'creative_strengths',
                     'individual_strengths'],
    'stress': ['stress_tolerance'],
    'stressfuls': ['stressful_situations', 'stressful_solutions'],
    'strong': [   'strong_contributor',
                  'strong_effort',
                  'strong_growth',
                  'strong_impact',
                  'strong_potential',
                  'strong_producer'],
    'stronger': ['strong_performer'],
    'stronglyted': ['strongly_committed'],
    'strongr': ['strong_achiever'],
    'substantialment': ['substantial_achievement'],
    'success': [   'success_driven',
                   'maximum_success',
                   'mutual_success',
                   'success_orient'],
    'successful': ['successful_conclusion'],
    'superior': ['superior_growth'],
    'superiors': ['multiple_superiors'],
    'supervisory': ['supervisory_skill'],
    'support': [   'administrative_support',
                   'creative_support',
                   'loyal_support',
                   'management_support',
                   'organizational_support',
                   'secretarial_support'],
    'supportives': ['supportive_relationships', 'supportive_skills'],
    'supports': ['support_services'],
    'sustainable': ['sustainable_growth'],
    'sustainables': ['sustainable_results'],
    'sustained': [   'sustained_development',
                     'sustained_energy',
                     'sustained_success'],
    'sustainedance': ['sustained_performance'],
    'sustainedment': ['sustained_commitment'],
    'synergistic': ['synergistic_benefit', 'synergistic_power'],
    'systematic': ['systematic_approach'],
    'systematics': ['systematic_results'],
    'systems': ['effective_systems'],
    'take': ['risk_take'],
    'talent': ['creative_talent'],
    'talents': ['diverse_talents', 'unique_talents'],
    'targets': ['optimal_targets'],
    'task': ['multi_task'],
    'tasks': ['routine_tasks'],
    'team': ['team_effort', 'team_skill', 'team_spirit'],
    'teamance': ['team_performance'],
    'teaming': ['team_building'],
    'teams': ['team_dynamics'],
    'technical': ['technical_skill'],
    'technicallyd': ['technically_advanced'],
    'techniques': [   'analytical_techniques',
                      'creative_techniques',
                      'proven_techniques',
                      'solid_techniques'],
    'technologies': ['computer_technologies', 'new_technologies'],
    'thinker': ['critical_thinker'],
    'thinking': [   'analytical_thinking',
                    'creative_thinking',
                    'forward_thinking',
                    'fresh_thinking',
                    'heuristic_thinking'],
    'thinksly': ['thinks_globally'],
    'time': ['time_efficient', 'time_management'],
    'tolerance': ['stress_tolerance'],
    'tolerances': ['zero_tolerances'],
    'tone': ['positive_tone'],
    'top': ['top_management'],
    'toper': ['top_performer'],
    'totalment': ['total_involvement'],
    'toughness': ['mental_toughness'],
    'tracking': ['tracking_progress'],
    'trainings': ['training_needs'],
    'trajectory': ['growth_trajectory'],
    'transition': ['organizational_transition', 'smooth_transition'],
    'trend': ['trend_setter'],
    'trends': ['professional_trends'],
    'trouble': ['trouble_shooting'],
    'true': ['true_potential'],
    'unanticipateds': ['unanticipated_consequences'],
    'unifieds': ['unified_efforts'],
    'unintendeds': ['unintended_consequences'],
    'unique': [   'unique_combination',
                  'unique_expertise',
                  'unique_knowledge',
                  'unique_perspective',
                  'unique_resource',
                  'unique_value'],
    'uniquelyed': ['uniquely_positioned'],
    'uniques': [   'unique_challenges',
                   'unique_insights',
                   'unique_methods',
                   'unique_talents'],
    'untapped': ['untapped_potential'],
    'unwaveringment': ['unwavering_commitment'],
    'utilization': ['resource_utilization'],
    'valuable': ['valuable_asset', 'valuable_resource'],
    'value': ['value_creation', 'unique_value'],
    'values': ['core_values', 'individual_values', 'key_values'],
    'variables': ['key_variables'],
    'verbalments': ['verbal_commitments'],
    'viables': ['viable_solutions'],
    'visionary': ['visionary_leadership', 'visionary_spirit'],
    'vital': ['vital_role'],
    'welled': ['well_informed', 'well_positioned'],
    'working': ['working_knowledge'],
    'world': ['world_class'],
    'writings': ['writing_skills'],
    'zeros': ['zero_tolerances']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
