
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class AppraisalImplies(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'AppraisalImplies',
            'filename': 'appraisal_implies',
            'queries': ['implies.sparql % $PREFIX=appraisal'],
            'reverse': True,
            'transformers': ['lowercase', 'implies']},
 'source': 'appraisal.owl',
 'time': '2022-04-27 21:15:17.715783'}

    __data = {
    'accelerate_change': ['accelerate', 'change'],
    'accepting_responsibility': ['responsibility'],
    'accomplishing_results': ['accomplishings'],
    'accumulated_knowledge': ['accumulated'],
    'accurate_assessments': ['accuratements', 'assessments'],
    'accurate_documentation': ['accurateation', 'documentation'],
    'accurate_evaluations': ['evaluations'],
    'accurate_predictions': ['accurateions', 'predictions'],
    'achievement_driven': ['achievement'],
    'achievement_oriented': ['achievemented'],
    'achieving_excellence': ['achievinglence', 'achieving'],
    'achieving_results': ['achievings'],
    'action_plans': ['actions', 'plans'],
    'active_participant': ['participant', 'active'],
    'administrative_advancements': ['administrativements', 'advancements'],
    'administrative_competence': ['administrative', 'competence'],
    'administrative_effectiveness': ['administrativeness', 'effectiveness'],
    'administrative_support': ['administrative', 'support'],
    'alternative_solutions': ['alternatives', 'solutions'],
    'analytical_approach': ['analytical', 'approach'],
    'analytical_methods': ['analyticals', 'methods'],
    'analytical_qualities': ['qualities'],
    'analytical_reasoning': ['analyticaling', 'reasoning'],
    'analytical_skill': ['analytical', 'skill'],
    'analytical_techniques': ['analyticals', 'techniques'],
    'analytical_thinking': ['analyticaling', 'thinking'],
    'anticipated_performance': ['anticipatedance'],
    'appropriate_attention': ['appropriate', 'attention'],
    'appropriate_measures': ['appropriates', 'measures'],
    'articulate_communicator': ['communicator'],
    'artificial_intelligence': ['intelligence'],
    'available_resources': ['availables', 'resources'],
    'basic_strengths': ['strengths', 'basics'],
    'broad_mind': ['broad', 'mind'],
    'broad_perspective': ['perspective', 'broad'],
    'broadest_discretion': ['broadest'],
    'budget_discipline': ['discipline', 'budget'],
    'calculated_risks': ['calculateds'],
    'career_building': ['careering', 'building'],
    'career_development': ['development', 'career'],
    'challenge_oriented': ['challengeed', 'oriented'],
    'challenging_problems': ['challengings'],
    'changing_assignments': ['changingments'],
    'changing_conditions': ['changings'],
    'changing_situations': ['changings'],
    'clear_expectations': ['expectations', 'clearations'],
    'close_cooperation': ['cooperation'],
    'coaching_and_counseling': ['coaching_anding'],
    'cognitive_ability': ['cognitive', 'ability'],
    'committed_enthusiasm': ['committed'],
    'communication_skills': ['communications'],
    'competent_communicator': ['communicator'],
    'competent_performer': ['competenter', 'performer'],
    'competitive_advantage': ['competitive', 'advantage'],
    'competitive_drive': ['competitive', 'drive'],
    'competitive_edge': ['competitive', 'edge'],
    'complex_information': ['complexation', 'information', 'complex'],
    'computer_application': ['application', 'computer'],
    'computer_generated': ['generated', 'computerd'],
    'computer_skill': ['computer', 'skill'],
    'computer_technologies': ['technologies'],
    'concentrated_effort': ['concentrated'],
    'conceptual_ideas': ['conceptuals'],
    'concurrent_assignments': ['concurrentments', 'assignments'],
    'confident_performer': ['confidenter', 'performer'],
    'confident_speaker': ['confident', 'speaker'],
    'confidential_records_management': [   'confidentials_management',
                                           'confidential_records',
                                           'records_management'],
    'conflict_resolution': ['resolution', 'conflict'],
    'considerable_flexibility': ['flexibility'],
    'consistent_achiever': ['consistentr', 'achiever'],
    'consistent_growth': ['consistent', 'growth'],
    'consistent_performance': ['consistentance', 'performance'],
    'consistent_progress': ['consistent', 'progress'],
    'consistently_high': ['consistently'],
    'consistently_punctual': ['consistently'],
    'constructive_actions': ['constructives', 'actions'],
    'constructive_criticism': ['criticism'],
    'constructive_discipline': ['constructive', 'discipline'],
    'constructive_feedback': ['constructive', 'feedback'],
    'constructive_ideas': ['constructives', 'ideas'],
    'contingency_plans': ['contingencys'],
    'continued_success': ['continued'],
    'continuing_efforts': ['continuings'],
    'continuous_improvement': ['continuousment'],
    'control_measures': ['measures', 'controls'],
    'controlling_expenses': ['controllings'],
    'conventional_wisdom': ['conventional'],
    'conveying_professionalism': ['conveyingism'],
    'cooperative_spirit': ['cooperative'],
    'core_capabilities': ['capabilities'],
    'core_competencies': ['competencies'],
    'core_components': ['components', 'cores'],
    'core_principles': ['principles', 'cores'],
    'core_problems': ['problems', 'cores'],
    'core_responsibility': ['responsibility'],
    'core_strengths': ['strengths', 'cores'],
    'core_values': ['values', 'cores'],
    'corporate_culture': ['corporate', 'culture'],
    'corrective_actions': ['correctives'],
    'corrective_measures': ['correctives'],
    'cost_conscious': ['conscious'],
    'cost_considerations': ['considerations', 'costs'],
    'cost_control': ['control', 'cost'],
    'cost_effectiveness': ['effectiveness', 'costness'],
    'cost_implications': ['implications', 'costs'],
    'cost_management': ['management', 'cost'],
    'cost_priorities': ['priorities'],
    'cost_reductions': ['reductions', 'costs'],
    'creating_value': ['creating'],
    'creative_alternatives': ['alternatives', 'creatives'],
    'creative_excellence': ['excellence', 'creative'],
    'creative_improvements': ['creativements', 'improvements'],
    'creative_solutions': ['creatives', 'solutions'],
    'creative_strategies': ['strategies'],
    'creative_strengths': ['creatives', 'strengths'],
    'creative_support': ['creative', 'support'],
    'creative_talent': ['creative', 'talent'],
    'creative_techniques': ['techniques', 'creatives'],
    'creative_thinking': ['creativeing', 'thinking'],
    'crisis_management': ['management', 'crisis'],
    'crisis_prevention': ['prevention', 'crisision'],
    'crisis_situations': ['situations', 'crisiss'],
    'critical_achievement': ['criticalment', 'achievement'],
    'critical_challenges': ['challenges', 'criticals'],
    'critical_elements': ['criticals', 'elements'],
    'critical_factors': ['criticals', 'factors'],
    'critical_importance': ['importance'],
    'critical_incidents': ['criticals', 'incidents'],
    'critical_insights': ['criticals', 'insights'],
    'critical_role': ['critical', 'role'],
    'critical_skills': ['criticals', 'skills'],
    'critical_solutions': ['solutions', 'criticals'],
    'critical_thinker': ['criticaler', 'thinker'],
    'crucial_planning': ['crucialning', 'planning'],
    'cumulative_effects': ['cumulatives', 'effects'],
    'customer_conscious': ['conscious'],
    'customer_focused': ['customered', 'focused'],
    'customer_orientation': ['customeration', 'orientation'],
    'customer_satisfaction': ['satisfaction'],
    'customer_service': ['customer', 'service'],
    'damage_control': ['control', 'damage'],
    'decision_making': ['making'],
    'decisive_action': ['decisive'],
    'dedicated_commitment': ['dedicatedment'],
    'dedicated_focus': ['dedicated'],
    'demanding_situations': ['demandings'],
    'desired_results': ['desireds'],
    'determined_efforts': ['determineds'],
    'developing_solutions': ['developings'],
    'disciplinary_action': ['disciplinary'],
    'disciplined_approach': ['disciplined'],
    'distinguishing_characteristics': ['distinguishings'],
    'diverse_talents': ['diverses', 'talents'],
    'diversified_approaches': ['diversifiedes'],
    'diversified_skills': ['diversifieds'],
    'documented_facts': ['documenteds'],
    'driving_force': ['driving'],
    'dynamic_impressions': ['dynamicions', 'impressions'],
    'dynamic_performance': ['performance', 'dynamicance'],
    'effective_presentations': [   'effectiveations',
                                   'presentations',
                                   'effectives'],
    'effective_systems': ['effectives', 'systems'],
    'efficient_manner': ['efficient', 'manner'],
    'electronic_capabilities': ['capabilities'],
    'emerging_trends': ['emergings'],
    'empowerment_skills': ['empowerments', 'skills'],
    'energetic_leader': ['energetic'],
    'energy_drive': ['energy', 'drive'],
    'enhanced_performance': ['enhancedance'],
    'enterprising_performance': ['enterprisingance'],
    'enthusiastic_commitment': ['enthusiasticment'],
    'enthusiastic_momentum': ['enthusiastic'],
    'enthusiastic_spirit': ['enthusiastic'],
    'environmental_leadership': ['environmental', 'leadership'],
    'essential_activities': ['activities'],
    'essential_knowledge': ['knowledge', 'essential'],
    'essential_skill': ['essential', 'skill'],
    'ethical_conduct': ['ethical'],
    'evaluation_skill': ['evaluation'],
    'exceeds_expectations': ['exceedsations'],
    'exceptional_improvement': ['exceptionalment'],
    'exceptional_outcomes': ['exceptionals'],
    'exceptional_progress': ['exceptional'],
    'expected_production': ['expectedion'],
    'expense_control': ['control', 'expense'],
    'expert_consultation': ['consultation', 'expertation'],
    'extra_efforts': ['efforts', 'extras'],
    'extremely_reliable': ['extremely'],
    'extremely_resourceful': ['extremelyful'],
    'fast_pace': ['fast', 'pace'],
    'favorable_image': ['favorable'],
    'favorable_impact': ['favorable'],
    'favorable_impression': ['favorableion'],
    'financial_discipline': ['financial'],
    'first_impressions': ['impressions', 'firstions'],
    'focused_efforts': ['focuseds'],
    'foremost_accountability': ['foremostability', 'accountability'],
    'formidable_challenges': ['formidables', 'challenges'],
    'formidable_development': ['development', 'formidable'],
    'forward_looking': ['forwarding', 'looking'],
    'forward_thinking': ['forwarding', 'thinking'],
    'fresh_enthusiasm': ['enthusiasm', 'fresh'],
    'fresh_ideas': ['freshs', 'ideas'],
    'fresh_insights': ['insights', 'freshs'],
    'fresh_perspective': ['perspective', 'fresh'],
    'fresh_thinking': ['freshing', 'thinking'],
    'full_participation': ['participation'],
    'fullest_support': ['fullest'],
    'fully_documented': ['fullyed'],
    'fully_prepared': ['fullyd'],
    'future_challenges': ['challenges', 'futures'],
    'future_oriented': ['oriented', 'futureed'],
    'global_perspective': ['perspective', 'global'],
    'goal_achiever': ['achiever', 'goalr'],
    'goal_attainment': ['attainment', 'goalment'],
    'goal_seeker': ['seeker', 'goal'],
    'goals_and_objectives': ['goals_ands'],
    'greater_achievement': ['greaterment'],
    'greater_challenge': ['greater'],
    'greatest_return': ['greatest'],
    'growth_potential': ['potential', 'growth'],
    'growth_trajectory': ['trajectory', 'growth'],
    'hands_on': ['hands', 'on'],
    'heuristic_thinking': ['heuristicing', 'thinking'],
    'hidden_potential': ['potential', 'hidden'],
    'hidden_strengths': ['hiddens'],
    'hidden_talents': ['hiddens'],
    'high_achiever': ['achiever', 'highr'],
    'high_enthusiasm': ['enthusiasm', 'high'],
    'high_impact': ['impact', 'high'],
    'high_momentum': ['momentum', 'high'],
    'high_output': ['output', 'high'],
    'high_payoff': ['payoff', 'high'],
    'high_potential': ['potential', 'high'],
    'high_producer': ['producer', 'high'],
    'high_profile': ['profile', 'high'],
    'high_quality': ['quality', 'high'],
    'high_recognition': ['recognition', 'high'],
    'high_spirited': ['spirited', 'highed'],
    'highest_priority': ['highest'],
    'highly_acclaimed': ['highlyed'],
    'highly_adaptive': ['highlyive'],
    'highly_articulate': ['highly'],
    'highly_capable': ['highly'],
    'highly_committed': ['highlyted'],
    'highly_competent': ['highly'],
    'highly_creditable': ['highly'],
    'highly_dependable': ['highly'],
    'highly_effective': ['highly'],
    'highly_focused': ['highlyed'],
    'highly_proficient': ['highly'],
    'highly_regarded': ['highlyed'],
    'highly_respected': ['highlyed'],
    'highly_supportive': ['highlyive'],
    'highly_talented': ['highlyed'],
    'ideally_positioned': ['ideallyed'],
    'imaginative_innovation': ['imaginative'],
    'imaginative_solutions': ['imaginatives'],
    'imaginative_thinking': ['imaginativeing'],
    'impeccable_honesty': ['impeccabley'],
    'implementing_change': ['implementing'],
    'important_contributor': ['contributor', 'important'],
    'important_role': ['important', 'role'],
    'impressive_results': ['impressives'],
    'impressive_zeal': ['impressive'],
    'improving_quality': ['improving'],
    'improving_techniques': ['improvings'],
    'incremental_improvements': ['incrementalments'],
    'independent_decisions': ['independents', 'decisions'],
    'individual_strengths': ['individuals', 'strengths'],
    'individual_values': ['individuals', 'values'],
    'information_sources': ['informations'],
    'initiating_solutions': ['initiatings'],
    'inner_drive': ['drive', 'inner'],
    'innovative_developments': ['innovativements'],
    'innovative_insight': ['innovative'],
    'innovative_planning': ['innovativening'],
    'innovative_solutions': ['innovatives'],
    'innovative_thinking': ['innovativeing'],
    'innovative_trends': ['innovatives'],
    'intellectual_horizons': ['intellectuals', 'horizons'],
    'intellectual_property': ['intellectual'],
    'intellectual_property_management': [   'intellectual_management',
                                            'intellectual_property',
                                            'property_management'],
    'intense_desire': ['intense', 'desire'],
    'interpersonal_skill': ['interpersonal', 'skill'],
    'intuitive_ability': ['intuitive', 'ability'],
    'intuitive_judgments': ['intuitives', 'judgments'],
    'job_enlargement': ['enlargement', 'jobment'],
    'job_enrichment': ['enrichment', 'jobment'],
    'job_plateauing': ['plateauing', 'jobing'],
    'keen_interest': ['interest', 'keen'],
    'key_challenges': ['challenges', 'keys'],
    'key_characteristics': ['characteristics', 'keys'],
    'key_element': ['element', 'key'],
    'key_employee': ['employee', 'key'],
    'key_role': ['role', 'key'],
    'key_values': ['values', 'keys'],
    'key_variables': ['variables', 'keys'],
    'leadership_qualities': ['qualities'],
    'leadership_role': ['leadership', 'role'],
    'leading_edge': ['leading'],
    'learning_curve': ['learning'],
    'learning_experience': ['learning'],
    'learning_skill': ['learning'],
    'logical_sequence': ['logical'],
    'logical_thinking': ['logicaling'],
    'loyal_support': ['support', 'loyal'],
    'loyalty_and_dedication': ['and_dedication'],
    'maintaining_control': ['maintaining'],
    'maintaining_focus': ['maintaining'],
    'maintaining_momentum': ['maintaining'],
    'maintenance_management': ['maintenance', 'management'],
    'major_contributor': ['contributor', 'major'],
    'management_effectiveness': ['managementness', 'effectiveness'],
    'management_efficiency': ['efficiency'],
    'management_expectations': ['managementations', 'expectations'],
    'management_principles': ['managements', 'principles'],
    'management_skill': ['management', 'skill'],
    'management_skills_for_middle_management': [   'management_skills_middle_management',
                                                   'managements_for_middle_management',
                                                   'management_skills_for_management',
                                                   'skills_for_middle_management'],
    'management_skills_for_top_management': [   'management_skills_top_management',
                                                'management_skills_for_management',
                                                'managements_for_top_management',
                                                'skills_for_top_management'],
    'management_support': ['management', 'support'],
    'marked_enthusiasm': ['enthusiasm', 'marked'],
    'maximizing_resources': ['maximizings', 'resources'],
    'maximum_contribution': ['contribution'],
    'maximum_effectiveness': ['effectiveness', 'maximumness'],
    'maximum_efficiency': ['efficiency'],
    'maximum_effort': ['maximum', 'effort'],
    'maximum_impact': ['maximum', 'impact'],
    'maximum_productivity': ['productivity'],
    'maximum_results': ['maximums', 'results'],
    'maximum_return': ['maximum', 'return'],
    'maximum_success': ['success', 'maximum'],
    'measurable_results': ['measurables'],
    'meets_expectations': ['meetsations'],
    'mental_skill': ['mental', 'skill'],
    'mental_toughness': ['mentalness', 'toughness'],
    'meticulous_attention': ['meticulous', 'attention'],
    'middle_management': ['management', 'middle'],
    'most_respected': ['respected', 'mosted'],
    'multi_facet': ['multi', 'facet'],
    'multi_task': ['multi', 'task'],
    'multiple_demands': ['multiples', 'demands'],
    'multiple_resources': ['multiples', 'resources'],
    'multiple_skills': ['multiples', 'skills'],
    'multiple_superiors': ['multiples', 'superiors'],
    'mutual_success': ['success', 'mutual'],
    'negotiating_skill': ['negotiating'],
    'new_approaches': ['approaches', 'newes'],
    'new_concepts': ['concepts', 'news'],
    'new_perspectives': ['perspectives', 'news'],
    'new_strategies': ['strategies'],
    'new_technologies': ['technologies'],
    'newly_created': ['newlyd'],
    'notable_achievement': ['achievement', 'notablement'],
    'open_communications': ['communications'],
    'open_mind': ['mind', 'open'],
    'operating_knowledge': ['operating'],
    'operating_skills': ['operatings'],
    'operational_excellence': ['operational'],
    'operational_records_management': [   'operationals_management',
                                          'operational_records'],
    'opinion_leader': ['opinion', 'leader'],
    'optimal_effectiveness': ['effectiveness', 'optimalness'],
    'optimal_levels': ['optimals', 'levels'],
    'optimal_outcomes': ['outcomes', 'optimals'],
    'optimal_results': ['optimals', 'results'],
    'optimal_targets': ['optimals', 'targets'],
    'optimistic_attitude': ['optimistic', 'attitude'],
    'optimum_advantage': ['advantage', 'optimum'],
    'optimum_productivity': ['productivity'],
    'optional_solutions': ['optionals'],
    'oral_expression': ['expression', 'oral'],
    'organizational_culture': ['organizational', 'culture'],
    'organizational_effectiveness': ['organizationalness', 'effectiveness'],
    'organizational_expectations': ['organizationalations', 'expectations'],
    'organizational_goals': ['organizationals', 'goals'],
    'organizational_resources': ['organizationals', 'resources'],
    'organizational_support': ['organizational', 'support'],
    'organizational_transition': ['organizational', 'transition'],
    'peak_efficiency': ['efficiency'],
    'peak_performance': ['performance', 'peakance'],
    'performance_impact': ['performance'],
    'performance_levels': ['performances'],
    'performance_measurement': ['performancement'],
    'performance_peak': ['performance'],
    'performance_targets': ['performances'],
    'personal_accountability': ['personalability'],
    'personal_charisma': ['personal'],
    'personal_commitment': ['personalment'],
    'personal_effectiveness': ['personalness'],
    'personal_growth': ['personal'],
    'personal_impact': ['personal'],
    'personal_integrity': ['personal'],
    'personal_magnetism': ['personal'],
    'personal_quality': ['personal'],
    'personal_strengths': ['personals'],
    'personal_traits': ['personal'],
    'personal_values': ['personals'],
    'persuasive_ability': ['persuasive'],
    'pivotal_role': ['pivotal', 'role'],
    'planning_approaches': ['planninges'],
    'planning_decisions': ['plannings'],
    'planning_solutions': ['plannings'],
    'planning_techniques': ['plannings'],
    'positive_actions': ['positives', 'actions'],
    'positive_approach': ['approach', 'positive'],
    'positive_attitude': ['positive', 'attitude'],
    'positive_attributes': ['attributes', 'positives'],
    'positive_direction': ['positiveion', 'direction'],
    'positive_expectations': ['positiveations', 'expectations'],
    'positive_feedback': ['feedback', 'positive'],
    'positive_force': ['positive', 'force'],
    'positive_image': ['positive', 'image'],
    'positive_impact': ['positive', 'impact'],
    'positive_influence': ['influence', 'positive'],
    'positive_intervention': ['intervention', 'positive'],
    'positive_outlook': ['positive', 'outlook'],
    'positive_reinforcement': ['reinforcement', 'positivement'],
    'positive_tone': ['positive', 'tone'],
    'powerful_commitment': ['powerfulment'],
    'powertul_insights': ['powertuls', 'insights'],
    'practical_advice': ['practical'],
    'practical_applications': ['practicals'],
    'practical_insights': ['practicals'],
    'practical_skills': ['practicals'],
    'practical_solutions': ['practicals'],
    'practical_thinking': ['practicaling'],
    'preeminent_authority': ['preeminent', 'authority'],
    'premier_position': ['position', 'premier'],
    'presentation_skill': ['presentation', 'skill'],
    'prime_mover': ['mover', 'prime'],
    'priority_determinations': ['determinations'],
    'problem_prevention': ['problemion', 'prevention'],
    'problem_solving': ['solving'],
    'productive_cooperation': ['cooperation'],
    'productive_impact': ['productive', 'impact'],
    'professional_competence': ['competence'],
    'professional_development': ['professional', 'development'],
    'professional_effectiveness': ['professionalness', 'effectiveness'],
    'professional_ethics': ['professionals', 'ethics'],
    'professional_excellence': ['professional', 'excellence'],
    'professional_expertise': ['professional', 'expertise'],
    'professional_participation': ['participation'],
    'professional_skills': ['professionals', 'skills'],
    'professional_trends': ['professionals', 'trends'],
    'profit_conscious': ['conscious'],
    'profit_mind': ['profit', 'mind'],
    'profit_oriented': ['profited', 'oriented'],
    'profound_impact': ['profound', 'impact'],
    'project_management': ['management', 'project'],
    'promoting_teamwork': ['promoting'],
    'prompt_measures': ['measures', 'prompts'],
    'proper_perspective': ['perspective', 'proper'],
    'proven_capabilities': ['capabilities'],
    'proven_performer': ['performer', 'provener'],
    'proven_record': ['proven', 'record'],
    'proven_techniques': ['techniques', 'provens'],
    'quality_conscious': ['conscious'],
    'quality_enhancement': ['qualityment', 'enhancement'],
    'quality_improvement': ['improvement', 'qualityment'],
    'rating_inflation': ['inflation', 'rating'],
    'realistic_approach': ['realistic', 'approach'],
    'realistic_objectives': ['objectives', 'realistics'],
    'realistic_solutions': ['realistics', 'solutions'],
    'records_management': ['records'],
    'recruiting_skill': ['recruiting'],
    'remarkable_record': ['remarkable'],
    'renewed_energy': ['renewed'],
    'resource_utilization': ['utilization'],
    'resourceful_solutions': ['resourcefuls'],
    'result_focus': ['result', 'focus'],
    'result_oriented': ['resulted', 'oriented'],
    'risk_take': ['risk', 'take'],
    'robust_impact': ['robust', 'impact'],
    'root_causes': ['causes', 'roots'],
    'routine_tasks': ['routines', 'tasks'],
    'safety_and_security': ['and_security'],
    'safety_conscious': ['conscious'],
    'sales_management': ['management', 'sales'],
    'sales_opportunities': ['opportunities'],
    'sales_producer': ['producer', 'sales'],
    'satisfying_solutions': ['satisfyings'],
    'secretarial_support': ['secretarial', 'support'],
    'self_confident': ['confident', 'self'],
    'self_development': ['development', 'self'],
    'self_direct': ['direct', 'self'],
    'self_discipline': ['discipline', 'self'],
    'self_esteem': ['esteem', 'self'],
    'self_motive': ['motive', 'self'],
    'self_pacing': ['pacing'],
    'self_reliant': ['reliant'],
    'self_starter': ['starter', 'self'],
    'selling_skill': ['selling'],
    'sensitive_situations': ['situations', 'sensitives'],
    'serious_mind': ['serious', 'mind'],
    'shared_drive': ['shared'],
    'shared_knowledge': ['shared'],
    'shared_values': ['shareds'],
    'shared_vision': ['shared'],
    'significant_accomplishments': ['significantments', 'accomplishments'],
    'significant_contribution': ['contribution'],
    'significant_impact': ['significant', 'impact'],
    'significant_progress': ['significant', 'progress'],
    'significant_results': ['significants', 'results'],
    'significant_role': ['significant', 'role'],
    'simplified_solutions': ['simplifieds'],
    'skill_development': ['development', 'skill'],
    'skilled_writer': ['skilled'],
    'smooth_transition': ['transition', 'smooth'],
    'solid_achiever': ['achiever', 'solidr'],
    'solid_background': ['background', 'solid'],
    'solid_contributor': ['contributor', 'solid'],
    'solid_control': ['control', 'solid'],
    'solid_direction': ['direction', 'solidion'],
    'solid_documentation': ['documentation', 'solidation'],
    'solid_experience': ['experience', 'solid'],
    'solid_foundation': ['foundation', 'solid'],
    'solid_growth': ['growth', 'solid'],
    'solid_performer': ['performer', 'solider'],
    'solid_reputation': ['reputation', 'solid'],
    'solid_skills': ['skills', 'solids'],
    'solid_techniques': ['techniques', 'solids'],
    'solution_driven': ['solutionn', 'driven'],
    'solution_seeker': ['solution', 'seeker'],
    'sound_approach': ['approach', 'sound'],
    'sound_conclusions': ['conclusions', 'sounds'],
    'sound_consideration': ['consideration'],
    'sound_controls': ['controls', 'sounds'],
    'sound_decisions': ['decisions', 'sounds'],
    'sound_judgment': ['judgment', 'sound'],
    'sound_perspectives': ['perspectives', 'sounds'],
    'special_assignments': ['specialments', 'assignments'],
    'specialized_skills': ['specializeds'],
    'speech_proficiency': ['proficiency'],
    'stabilizing_influence': ['stabilizing'],
    'steady_growth': ['growth', 'steady'],
    'steady_progress': ['progress', 'steady'],
    'stellar_record': ['stellar', 'record'],
    'stimulating_action': ['stimulating'],
    'strategic_alternatives': ['strategics'],
    'strategic_plans': ['strategics'],
    'strategic_repositioning': ['strategicing'],
    'strategic_thrust': ['strategic'],
    'strategic_vision': ['strategic'],
    'strategically_focused': ['strategicallyed'],
    'strategically_positioned': ['strategicallyed'],
    'strategically_sound': ['strategically'],
    'strategy_orient': ['strategy', 'orient'],
    'stress_tolerance': ['tolerance', 'stress'],
    'stressful_situations': ['stressfuls'],
    'stressful_solutions': ['stressfuls'],
    'strong_achiever': ['achiever', 'strongr'],
    'strong_contributor': ['contributor', 'strong'],
    'strong_credibility': ['credibility'],
    'strong_effort': ['strong', 'effort'],
    'strong_growth': ['strong', 'growth'],
    'strong_impact': ['strong', 'impact'],
    'strong_motivator': ['motivator'],
    'strong_performer': ['performer', 'stronger'],
    'strong_perseverance': ['perseverance'],
    'strong_potential': ['potential', 'strong'],
    'strong_producer': ['producer', 'strong'],
    'strongly_committed': ['stronglyted'],
    'substantial_achievement': ['substantialment', 'achievement'],
    'substantial_contribution': ['contribution'],
    'success_driven': ['success', 'driven'],
    'success_orient': ['success', 'orient'],
    'successful_conclusion': ['successful'],
    'superior_growth': ['superior', 'growth'],
    'supervisory_skill': ['supervisory', 'skill'],
    'support_services': ['services', 'supports'],
    'supportive_relationships': ['supportives'],
    'supportive_skills': ['supportives'],
    'sustainable_growth': ['sustainable'],
    'sustainable_results': ['sustainables'],
    'sustained_commitment': ['sustainedment'],
    'sustained_development': ['sustained'],
    'sustained_energy': ['sustained'],
    'sustained_performance': ['sustainedance'],
    'sustained_success': ['sustained'],
    'synergistic_benefit': ['synergistic', 'benefit'],
    'synergistic_power': ['synergistic', 'power'],
    'systematic_approach': ['systematic', 'approach'],
    'systematic_results': ['systematics', 'results'],
    'task_priorities': ['priorities'],
    'team_building': ['building', 'teaming'],
    'team_dynamics': ['dynamics', 'teams'],
    'team_effort': ['effort', 'team'],
    'team_motivator': ['motivator'],
    'team_performance': ['performance', 'teamance'],
    'team_skill': ['skill', 'team'],
    'team_spirit': ['spirit', 'team'],
    'technical_competence': ['competence'],
    'technical_skill': ['technical', 'skill'],
    'technically_advanced': ['technicallyd'],
    'thinks_globally': ['thinksly'],
    'time_conscious': ['conscious'],
    'time_efficient': ['efficient', 'time'],
    'time_management': ['management', 'time'],
    'top_management': ['management', 'top'],
    'top_performer': ['performer', 'toper'],
    'total_involvement': ['involvement', 'totalment'],
    'tracking_progress': ['tracking'],
    'training_needs': ['trainings'],
    'trend_setter': ['setter', 'trend'],
    'trouble_shooting': ['shooting', 'trouble'],
    'true_potential': ['potential', 'true'],
    'ultimate_responsibility': ['responsibility'],
    'unanticipated_consequences': ['unanticipateds', 'consequences'],
    'unified_efforts': ['unifieds'],
    'unintended_consequences': ['consequences', 'unintendeds'],
    'unique_capabilities': ['capabilities'],
    'unique_challenges': ['challenges', 'uniques'],
    'unique_combination': ['combination', 'unique'],
    'unique_expertise': ['expertise', 'unique'],
    'unique_insights': ['insights', 'uniques'],
    'unique_knowledge': ['knowledge', 'unique'],
    'unique_methods': ['uniques', 'methods'],
    'unique_opportunities': ['opportunities'],
    'unique_perspective': ['perspective', 'unique'],
    'unique_resource': ['resource', 'unique'],
    'unique_talents': ['uniques', 'talents'],
    'unique_value': ['unique', 'value'],
    'uniquely_positioned': ['uniquelyed'],
    'unparalleled_opportunities': ['opportunities'],
    'untapped_potential': ['potential', 'untapped'],
    'unwavering_commitment': ['unwaveringment', 'commitment'],
    'valuable_asset': ['valuable', 'asset'],
    'valuable_resource': ['resource', 'valuable'],
    'value_creation': ['creation', 'value'],
    'verbal_commitments': ['verbalments', 'commitments'],
    'viable_solutions': ['solutions', 'viables'],
    'visionary_leadership': ['visionary'],
    'visionary_spirit': ['visionary'],
    'vital_role': ['vital', 'role'],
    'well_informed': ['informed', 'welled'],
    'well_positioned': ['positioned', 'welled'],
    'well_qualified': ['qualified'],
    'working_knowledge': ['working'],
    'world_class': ['class', 'world'],
    'writing_skills': ['writings'],
    'zero_tolerances': ['tolerances', 'zeros']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
