
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class ChitchatSpans(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'ChitchatSpans',
            'filename': 'chitchat_spans',
            'queries': ['spans.sparql'],
            'transformers': ['spans']},
 'source': 'chitchat.owl',
 'time': '2022-04-27 21:17:15.156855'}

    __data = {
    '': [   {   'canon': 'sympathy_deflection',
                'content': {'happens,', 'like', "doesn't", 'mean', '...'},
                'distance': 3,
                'forward': True,
                'reverse': True}],
    'a': [   {   'canon': 'good_weather_response',
                 'content': {'fine', 'day!'},
                 'distance': 3,
                 'forward': True,
                 'reverse': True}],
    'ability': [   {   'canon': 'ability_action',
                       'content': {'action'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'adorkable': [   {   'canon': 'adorkable_response',
                         'content': {'response'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'agreeable': [   {   'canon': 'agreeable_deflection',
                         'content': {'deflection'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'animal': [   {   'canon': 'animal_slack_emoji',
                      'content': {'slack', 'emoji'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'are': [   {   'canon': 'free_state_action',
                   'content': {'free'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'free_state_action',
                   'content': {'right', 'anything', 'now?'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'busy_state_action',
                   'content': {'busy?'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'bad': [   {   'canon': 'bad_weather_response',
                   'content': {'response', 'weather'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'bad_weather',
                   'content': {'weather'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'better': [   {   'canon': 'friday_response',
                      'content': {'monday!'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'big': [   {   'canon': 'big_cat_slack_emoji',
                   'content': {'slack', 'emoji', 'cat'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'black': [   {   'canon': 'cat_slack_emoji',
                     'content': {'cat2'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'busy': [   {   'canon': 'busy_state_action',
                    'content': {'action', 'state'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'but': [   {   'canon': 'cliche_deflection',
                   'content': {'different'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'carousel': [   {   'canon': 'horse_slack_emoji',
                        'content': {'horse'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'cat': [   {   'canon': 'cat_slack_emoji',
                   'content': {'slack', 'emoji'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'cliche': [   {   'canon': 'cliche_deflection',
                      'content': {'deflection'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'conditional': [   {   'canon': 'conditional_state_deflection',
                           'content': {'deflection', 'state'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'crying': [   {   'canon': 'negative_slack_emoji',
                      'content': {'cat', 'face'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'deflection': [   {   'canon': 'deflection_response',
                          'content': {'response'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'disagreeable': [   {   'canon': 'disagreeable_deflection',
                            'content': {'deflection'},
                            'distance': 3,
                            'forward': True,
                            'reverse': True}],
    'dog': [   {   'canon': 'dog_slack_emoji',
                   'content': {'slack', 'emoji'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'doing': [   {   'canon': 'state_greeting_response',
                     'content': {'great'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'state_greeting_response',
                     'content': {'great'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'state_greeting_response',
                     'content': {'great', 'real'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'state_greeting_response',
                     'content': {'great', 'thank', '-', 'you!'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'dude': [   {   'canon': 'sympathy_deflection',
                    'content': {'feeling', "i'm"},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'sympathy_deflection',
                    'content': {'sorry', '...'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'face': [   {   'canon': 'insult_slack_emoji',
                    'content': {'raised', 'eyebrow'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'negative_slack_emoji',
                    'content': {'eyes', 'rolling'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'favorable': [   {   'canon': 'favorable_emotion',
                         'content': {'emotion'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'favorite': [   {   'canon': 'favorite_animal_response',
                        'content': {'response', 'animal'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'fine': [   {   'canon': 'good_weather',
                    'content': {'day'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'good_weather',
                    'content': {'weather'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'fine,': [   {   'canon': 'state_greeting_response',
                     'content': {'fine', 'fine.', '...'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'free': [   {   'canon': 'free_state_action',
                    'content': {'action', 'state'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'friday': [   {   'canon': 'friday_response',
                      'content': {'response'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'geez': [   {   'canon': 'sympathy_deflection',
                    'content': {'...'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'general': [   {   'canon': 'general_state_action',
                       'content': {'action', 'state'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'good': [   {   'canon': 'good_weather',
                    'content': {'weather'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'good_weather',
                    'content': {'day'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'state_greeting_response',
                    'content': {'thanks!'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'good_weather_response',
                    'content': {'response', 'weather'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'great': [   {   'canon': 'good_weather',
                     'content': {'day'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'good_weather',
                     'content': {'weather'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'state_greeting_response',
                     'content': {'man'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'greeting': [   {   'canon': 'greeting_slack_emoji',
                        'content': {'slack', 'emoji'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'greeting_response',
                        'content': {'response'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'greeting_action',
                        'content': {'action'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'guide': [   {   'canon': 'dog_slack_emoji',
                     'content': {'dog'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'hanging': [   {   'canon': 'state_greeting_response',
                       'content': {'there.'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'hello': [   {   'canon': 'hello_response',
                     'content': {'response'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'hello_response',
                     'content': {'there!'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'hey': [   {   'canon': 'state_greeting',
                   'content': {'whats'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'state_greeting',
                   'content': {'dude'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'horse': [   {   'canon': 'horse_slack_emoji',
                     'content': {'slack', 'emoji'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'horse_slack_emoji',
                     'content': {'racing'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'how': [   {   'canon': 'state_greeting',
                   'content': {'you?'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'state_greeting',
                   'content': {'ya'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'state_greeting',
                   'content': {'hangin'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'state_greeting',
                   'content': {'hanging'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'state_greeting',
                   'content': {'do?'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'state_greeting',
                   'content': {'been?'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'state_greeting',
                   'content': {'doin', 'ya'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'general_state_action',
                   'content': {'going', 'days?'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    "how's": [   {   'canon': 'state_greeting',
                     'content': {'hangin'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'state_greeting',
                     'content': {'hanging'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'general_state_action',
                     'content': {'going', 'days?'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'hows': [   {   'canon': 'state_greeting',
                    'content': {'hangin'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'state_greeting',
                    'content': {'hanging'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'howya': [   {   'canon': 'state_greeting',
                     'content': {'doin'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'how’s': [   {   'canon': 'general_state_action',
                     'content': {'days?\n', 'going'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'hugging': [   {   'canon': 'positive_slack_emoji',
                       'content': {'face'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'i': [   {   'canon': 'monday_response',
                 'content': {'mondays!', 'love'},
                 'distance': 3,
                 'forward': True,
                 'reverse': True},
             {   'canon': 'agreeable_deflection',
                 'content': {'agree'},
                 'distance': 3,
                 'forward': True,
                 'reverse': True},
             {   'canon': 'agreeable_deflection',
                 'content': {'agree', "can't"},
                 'distance': 3,
                 'forward': True,
                 'reverse': True},
             {   'canon': 'disagreeable_deflection',
                 'content': {'agree', "can't"},
                 'distance': 3,
                 'forward': True,
                 'reverse': True},
             {   'canon': 'sympathy_deflection',
                 'content': {'hear', 'ya', '...'},
                 'distance': 3,
                 'forward': True,
                 'reverse': True},
             {   'canon': 'sympathy_deflection',
                 'content': {'pain', 'feel'},
                 'distance': 3,
                 'forward': True,
                 'reverse': True},
             {   'canon': 'reverse_deflection',
                 'content': {'ask', 'that.'},
                 'distance': 3,
                 'forward': True,
                 'reverse': True},
             {   'canon': 'reverse_deflection',
                 'content': {'going', 'that.', 'say'},
                 'distance': 3,
                 'forward': True,
                 'reverse': True},
             {   'canon': 'favorite_animal_response',
                 'content': {'like', 'really', '{animal}'},
                 'distance': 3,
                 'forward': True,
                 'reverse': True}],
    "i'm": [   {   'canon': 'unknown_response',
                   'content': {'sure', 'say'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'bad_weather_response',
                   'content': {'glad', 'indoors', "i'm"},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'conditional_state_deflection',
                   'content': {'right', "you're", 'sure'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'sympathy_deflection',
                   'content': {'hear', 'sorry'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'good_weather_response',
                   'content': {'weather.', 'loving'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'good_weather_response',
                   'content': {'outside!', 'go', 'ready'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'good_weather_response',
                   'content': {'heading', 'outside', 'chat!'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    "i've": [   {   'canon': 'state_greeting_response',
                    'content': {'thanks!', 'well,'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'if': [   {   'canon': 'unknown_response',
                  'content': {'so.', 'say'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True},
              {   'canon': 'conditional_state_deflection',
                  'content': {'so!', 'say'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    'insult': [   {   'canon': 'insult_slack_emoji',
                      'content': {'slack', 'emoji'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'insult_response',
                      'content': {'response'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'interrogation': [   {   'canon': 'interrogation_response',
                             'content': {'response'},
                             'distance': 3,
                             'forward': True,
                             'reverse': True}],
    'is': [   {   'canon': 'friday_response',
                  'content': {'already?', 'friday'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    'it': [   {   'canon': 'meet_and_greet',
                  'content': {'you.', 'nice', 'meet'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    "it's": [   {   'canon': 'conditional_state_deflection',
                    'content': {'me.'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'disagreeable_deflection',
                    'content': {'old', 'story'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'i’m': [   {   'canon': 'location_response',
                   'content': {'always'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'joy': [   {   'canon': 'positive_slack_emoji',
                   'content': {'cat'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'just': [   {   'canon': 'state_greeting_response',
                    'content': {'great'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'late': [   {   'canon': 'late_transport',
                    'content': {'transport'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'late_transport_response',
                    'content': {'transport', 'response'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'like': [   {   'canon': 'like_animal',
                    'content': {'animal'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'location': [   {   'canon': 'location_response',
                        'content': {'response'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'location_question',
                        'content': {'question'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'long': [   {   'canon': 'time_greeting',
                    'content': {'see!\n', 'time'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'man': [   {   'canon': 'sympathy_deflection',
                   'content': {'sucks'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'neutral_slack_emoji',
                   'content': {'lotus', 'position'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'maybe': [   {   'canon': 'bad_weather_response',
                     'content': {'tomorrow', 'better'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'meet': [   {   'canon': 'meet_and_greet',
                    'content': {'greet'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'monday': [   {   'canon': 'monday_response',
                      'content': {'response'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'my': [   {   'canon': 'favorite_animal_response',
                  'content': {'{animal}', 'animal', 'favorite'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True},
              {   'canon': 'favorite_animal_response',
                  'content': {'{animal}', 'favorite'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    'negative': [   {   'canon': 'negative_slack_emoji',
                        'content': {'slack', 'emoji'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'negative_experience',
                        'content': {'experience'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'neutral': [   {   'canon': 'neutral_slack_emoji',
                       'content': {'slack', 'emoji'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'neutral_slack_emoji',
                       'content': {'face'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'nice': [   {   'canon': 'good_weather',
                    'content': {'day'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'good_weather',
                    'content': {"we're", 'weather'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'good_weather',
                    'content': {'weather'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'good_weather',
                    'content': {'today', 'day'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'good_weather',
                    'content': {'fishing', 'go', 'day'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'meet_and_greet',
                    'content': {'meet'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'no': [   {   'canon': 'disagreeable_deflection',
                  'content': {'way,', 'jose'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True},
              {   'canon': 'disagreeable_deflection',
                  'content': {'way'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    'oh': [   {   'canon': 'sympathy_deflection',
                  'content': {'geez'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    'otter': [   {   'canon': 'otter_slack_emoji',
                     'content': {'slack', 'emoji'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'packed': [   {   'canon': 'packed_transport',
                      'content': {'transport'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'pleading': [   {   'canon': 'negative_slack_emoji',
                        'content': {'persevere', 'face'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'pleased': [   {   'canon': 'meet_and_greet',
                       'content': {'meet'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'positive': [   {   'canon': 'positive_experience',
                        'content': {'experience'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'positive_slack_emoji',
                        'content': {'slack', 'emoji'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'pouting': [   {   'canon': 'negative_slack_emoji',
                       'content': {'cat'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'real': [   {   'canon': 'state_greeting_response',
                    'content': {'great', 'man'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'state_greeting_response',
                    'content': {'great'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'sympathy_deflection',
                    'content': {'hear', 'sorry'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'reverse': [   {   'canon': 'reverse_deflection',
                       'content': {'deflection'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'same': [   {   'canon': 'cliche_deflection',
                    'content': {'thing', 'old'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'cliche_deflection',
                    'content': {"o'"},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'service': [   {   'canon': 'dog_slack_emoji',
                       'content': {'dog'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'skull': [   {   'canon': 'negative_slack_emoji',
                     'content': {'crossbones'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'slack': [   {   'canon': 'slack_emoji',
                     'content': {'emoji'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'slightly': [   {   'canon': 'positive_slack_emoji',
                        'content': {'smiling', 'face'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'smile': [   {   'canon': 'cat_slack_emoji',
                     'content': {'cat'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'smiley': [   {   'canon': 'cat_slack_emoji',
                      'content': {'cat'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'smirk': [   {   'canon': 'cat_slack_emoji',
                     'content': {'cat'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'sorry': [   {   'canon': 'sympathy_deflection',
                     'content': {'hear'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'state': [   {   'canon': 'state_greeting_response',
                     'content': {'response', 'greeting'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'state_greeting',
                     'content': {'greeting'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'stuck': [   {   'canon': 'insult_slack_emoji',
                     'content': {'tongue'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'insult_slack_emoji',
                     'content': {'eye', 'winking', 'tongue'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'insult_slack_emoji',
                     'content': {'eye', 'tongue', 'closed'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'positive_slack_emoji',
                     'content': {'eyes', 'tongue', 'closed'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'sympathy': [   {   'canon': 'sympathy_deflection',
                        'content': {'deflection'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'that': [   {   'canon': 'sympathy_deflection',
                    'content': {'sucks'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'sympathy_deflection',
                    'content': {'sucks', 'kinda'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    "that's": [   {   'canon': 'conditional_state_deflection',
                      'content': {'suprising'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'disagreeable_deflection',
                      'content': {'true'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'the': [   {   'canon': 'cliche_deflection',
                   'content': {'things', 'change'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'cliche_deflection',
                   'content': {'stay'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'cliche_deflection',
                   'content': {'rigmarole', 'old'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'bad_weather_response',
                   'content': {'impact', "doesn't", 'weather'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'bad_weather_response',
                   'content': {'improve', 'weather'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'time': [   {   'canon': 'time_greeting',
                    'content': {'greeting'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'transport': [   {   'canon': 'transport_response',
                         'content': {'response'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'unknown': [   {   'canon': 'unknown_response',
                       'content': {'response'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'upside': [   {   'canon': 'positive_slack_emoji',
                      'content': {'face'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'weather': [   {   'canon': 'weather_response',
                       'content': {'response'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'what': [   {   'canon': 'free_state_action',
                    'content': {'right', 'now?\n'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'free_state_action',
                    'content': {'doing?\n'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'free_state_action',
                    'content': {'right', 'now?\n'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'ability_action',
                    'content': {'living?\n'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'ability_action',
                    'content': {'capabilities'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'ability_action',
                    'content': {'of?', 'capable'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'location_response',
                    'content': {'mean?'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'state_greeting',
                    'content': {'going'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'state_greeting',
                    'content': {'dawg\n'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'general_state_action',
                    'content': {'doing?'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'general_state_action',
                    'content': {'to?'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'general_state_action',
                    'content': {'lately?'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    "what's": [   {   'canon': 'state_greeting',
                      'content': {'going', 'on?'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'whatcha': [   {   'canon': 'general_state_action',
                       'content': {'doing?'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'general_state_action',
                       'content': {'doin’?'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'whats': [   {   'canon': 'state_greeting',
                     'content': {'going'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'state_greeting',
                     'content': {"goin'"},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'when': [   {   'canon': 'free_state_action',
                    'content': {'free?'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'where': [   {   'canon': 'location_question',
                     'content': {'you?'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'location_question',
                     'content': {'of?', 'based'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'location_question',
                     'content': {'of?', 'based'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'location_question',
                     'content': {'live?'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'woman': [   {   'canon': 'neutral_slack_emoji',
                     'content': {'lotus', 'position'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'wow': [   {   'canon': 'sympathy_deflection',
                   'content': {'sucks'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'yay': [   {   'canon': 'friday_response',
                   'content': {'friday!'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'yea': [   {   'canon': 'sympathy_deflection',
                   'content': {"that's", 'fun', '...'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'you': [   {   'canon': 'free_state_action',
                   'content': {'free?'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'cliche_deflection',
                   'content': {'twice\n', 'river', 'step', "can't"},
                   'distance': 3,
                   'forward': True,
                   'reverse': True},
               {   'canon': 'location_question',
                   'content': {'live', 'here?'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    "you're": [   {   'canon': 'agreeable_deflection',
                      'content': {'right'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'adorkable_response',
                      'content': {'adorkable'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'adorkable_response',
                      'content': {'pretty', 'adorkable'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'zany': [   {   'canon': 'insult_slack_emoji',
                    'content': {'face'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    '{transport}': [   {   'canon': 'packed_transport',
                           'content': {'packed'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True},
                       {   'canon': 'late_transport',
                           'content': {'late'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}]}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
