
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class ChitchatSynonyms(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'ChitchatSynonyms',
            'filename': 'chitchat_synonyms',
            'files': ['chitchat.txt'],
            'queries': ['synonyms.sparql'],
            'reverse': True,
            'transformers': ['lowercase', 'synonyms']},
 'source': 'chitchat.owl',
 'time': '2022-04-27 21:17:15.264355'}

    __data = {
    'ability_action': [   'tell me about what you can do',
                          'what do you do for a living?\n',
                          'what are your capabilities',
                          'what are you capable of?',
                          'what are you capable of',
                          'tell me what you can do',
                          'tell me about yourself',
                          'what can you do',
                          'ability action',
                          'what do you do'],
    'action': ['action'],
    'adorkable': ['adorkable'],
    'adorkable_response': [   "you're pretty adorkable yourself",
                              'adorkable response',
                              "you're adorkable"],
    'agreeable_deflection': [   'agreeable deflection',
                                "i can't agree more",
                                "you're so right",
                                'absolutely!',
                                'absolutely',
                                'i agree'],
    'animal': ['animal'],
    'animal_slack_emoji': ['animal slack emoji'],
    'bad_weather': ['bad weather'],
    'bad_weather_response': [   "the weather doesn't impact me",
                                'maybe tomorrow will be better',
                                'the weather will improve',
                                "i'm glad i'm indoors",
                                'bad weather response'],
    'big_cat_slack_emoji': [   'big cat slack emoji',
                               'leopard',
                               'tiger2',
                               'tiger'],
    'busy_state_action': [   'busy state action',
                             'are you busy?',
                             'are you busy',
                             'busy?',
                             'busy'],
    'cat': ['cats', 'cat'],
    'cat_slack_emoji': [   'cat slack emoji',
                           'smiley_cat',
                           'black_cat2',
                           'smirk_cat',
                           'smile_cat',
                           'tiger',
                           'cat2',
                           'cat'],
    'cliche_deflection': [   "you can't step in the same river twice\n",
                             'the more they stay the same',
                             'the same old rigmarole',
                             'the more things change',
                             'cliche deflection',
                             "same o' same o'",
                             'same old thing',
                             'but different',
                             'same same'],
    'conditional_state_deflection': [   'conditional state deflection',
                                        "it's all the same to me.",
                                        "it's all the same to me",
                                        "i'm sure you're right",
                                        "that's not suprising",
                                        'if you say so!',
                                        'if you say so',
                                        'okee-dokee'],
    'deflection_response': ['deflection response'],
    'disagreeable_deflection': [   'disagreeable deflection',
                                   "it's the same old story",
                                   "that's not true",
                                   "i can't agree",
                                   'no way, jose',
                                   'no way',
                                   'nopers',
                                   'nope',
                                   'nah',
                                   'no'],
    'dog': ['doggies', 'dogs', 'dog'],
    'dog_slack_emoji': [   'dog slack emoji',
                           'service_dog',
                           'guide_dog',
                           'hotdog',
                           'dog2',
                           'dog'],
    'early': ['early'],
    'emoji': ['emoji'],
    'emotion': ['emotion'],
    'experience': ['experience'],
    'favorable_emotion': ['favorable emotion'],
    'favorite_animal_response': [   'i like them all but i really like '
                                    '{animal}',
                                    'my favorite animal is {animal}',
                                    'favorite animal response',
                                    'my favorite are {animal}'],
    'free_state_action': [   'are you doing anything right now?',
                             'are you doing anything right now',
                             'what are you up to right now?\n',
                             'what are you doing right now?\n',
                             'when will you be free?',
                             'when will you be free',
                             'what are you doing?\n',
                             'free state action',
                             'are you free',
                             'you free?',
                             'you free',
                             'hey'],
    'friday': ['happy friday', 'friday'],
    'friday_response': [   'is it friday already?',
                           'is it friday already',
                           'better than monday!',
                           'better than monday',
                           'friday response',
                           'yay friday!',
                           'yay friday'],
    'general_state_action': [   'how’s it been going these days?\n',
                                'how is it going these days?',
                                'how is it going these days',
                                'what are you up to lately?',
                                "how's it going these days?",
                                'what are you up to lately',
                                "how's it going these days",
                                'general state action',
                                'what are you up to?',
                                'what are you doing?',
                                'what are you up to',
                                'what are you doing',
                                'whatcha doin’?',
                                'whatcha doing?',
                                'whatcha doin’',
                                'whatcha doing'],
    'good_weather': [   "nice weather we're having",
                        'nice day to go fishing',
                        'nice day today',
                        'great weather',
                        'good weather',
                        'fine weather',
                        'nice weather',
                        'great day',
                        'nice day',
                        'fine day',
                        'good day'],
    'good_weather_response': [   "i'm heading outside after this chat!",
                                 "i'm heading outside after this chat",
                                 "i'm loving this weather.",
                                 "i'm ready to go outside!",
                                 "i'm ready to go outside",
                                 "i'm loving this weather",
                                 'good weather response',
                                 'a fine day!',
                                 'a fine day',
                                 'yes'],
    'greeting': ['greeting'],
    'greeting_action': ['greeting action'],
    'greeting_response': ['greeting response'],
    'greeting_slack_emoji': ['greeting slack emoji', 'handshake', 'wave'],
    'hello': ['hi there', 'hello', 'hiya', 'hi'],
    'hello_response': [   'hello response',
                          'hello there!',
                          'hello there',
                          'hiya!',
                          'hiya',
                          'hi!',
                          'hi'],
    'horse': ['horsies', 'horses', 'horse'],
    'horse_slack_emoji': [   'horse slack emoji',
                             'carousel_horse',
                             'horse_racing',
                             'racehorse',
                             'horse'],
    'insult': ['insult'],
    'insult_response': ['insult response'],
    'insult_slack_emoji': [   'stuck_out_tongue_winking_eye',
                              'stuck_out_tongue_closed_eye',
                              'face_with_raised_eyebrow',
                              'insult slack emoji',
                              'stuck_out_tongue',
                              'zany_face'],
    'interrogation_response': ['interrogation response'],
    'kitten': ['kitties', 'kittens', 'kitten', 'kitty'],
    'late': ['late'],
    'late_transport': ['{transport} was late', 'late transport'],
    'late_transport_response': ['late transport response'],
    'like_animal': ['like animal'],
    'location_question': [   'where are you based out of?',
                             'where are you based out of',
                             'where you based out of?',
                             'where you based out of',
                             'where do you live?',
                             'where do you live',
                             'location question',
                             'you live here?',
                             'where are you?',
                             'you live here',
                             'where are you'],
    'location_response': [   'location response',
                             'what do you mean?',
                             'what do you mean',
                             'i’m always here'],
    'meet_and_greet': [   'it is nice to meet you.',
                          'it is nice to meet you',
                          'pleased to meet you',
                          'nice to meet you',
                          'meet and greet'],
    'monday': [   'mondays, am i right?',
                  'mondays, am i right',
                  'case of the mondays',
                  'happy monday',
                  'mondays',
                  'monday'],
    'monday_response': ['i love mondays!', 'monday response', 'i love mondays'],
    'negative_experience': ['negative experience'],
    'negative_slack_emoji': [   'pleading_face persevere',
                                'face_with_rolling_eyes',
                                'negative slack emoji',
                                'skull_and_crossbones',
                                'crying_cat_face',
                                'pouting_cat',
                                'persevere',
                                'scream',
                                'weary',
                                'skull',
                                'sweat',
                                'cry'],
    'neutral_slack_emoji': [   'woman_in_lotus_position',
                               'man_in_lotus_position',
                               'neutral slack emoji',
                               'expressionless',
                               'neutral_face',
                               'grimacing',
                               'shrug'],
    'ocelot': ['ocelots', 'ocelot'],
    'otter': ['otters', 'otter'],
    'otter_slack_emoji': ['otter slack emoji', 'otter'],
    'packed_transport': ['{transport} was packed', 'packed transport'],
    'positive_experience': ['positive experience'],
    'positive_slack_emoji': [   'stuck_out_tongue_closed_eyes',
                                'slightly_smiling_face',
                                'positive slack emoji',
                                'upside_down_face',
                                'hugging_face',
                                'joy_cat',
                                'wink',
                                'joy',
                                '100'],
    'pronoun': ['pronoun'],
    'puppy': ['puppies', 'puppy'],
    'response': ['response'],
    'reverse_deflection': [   'i was just about to ask you that.',
                              'i was just about to ask you that',
                              'i was going to say that.',
                              'i was going to say that',
                              'reverse deflection'],
    'slack_emoji': ['slack emoji'],
    'state': ['state'],
    'state_greeting': [   'how have you been?',
                          'what are you doing',
                          'how is it hanging',
                          'how have you been',
                          'how is it hangin',
                          "what's going on?",
                          "how's it hanging",
                          'what is going on',
                          'hows it hanging',
                          "how's it hangin",
                          "what's going on",
                          "whats goin' on",
                          'state greeting',
                          'hows it hangin',
                          'whats going on',
                          'how do you do?',
                          'what up dawg\n',
                          'how do you do',
                          'how are you?',
                          'how ya doing',
                          'hey whats up',
                          'howya doing',
                          'how ya doin',
                          'how are you',
                          'howya doin',
                          'howyadoing',
                          "what's up",
                          'hey dude',
                          'howdy',
                          'sup'],
    'state_greeting_response': [   'doing just great - thank you!',
                                   'doing just great - thank you',
                                   'state greeting response',
                                   "i've been well, thanks!",
                                   "i've been well, thanks",
                                   'fine, fine ... fine.',
                                   'fine, fine ... fine',
                                   'hanging in there.',
                                   'doing real great',
                                   'doing just great',
                                   'hanging in there',
                                   'real great man',
                                   'good thanks!',
                                   'doing great',
                                   'good thanks',
                                   'just great',
                                   'real great',
                                   'same same',
                                   'great man'],
    'sympathy_deflection': [   " i mean ... it happens, but that doesn't mean "
                               'we have to like it',
                               'i hear ya ... been there myself',
                               'real sorry to hear that',
                               "i'm sorry to hear that",
                               "dude i'm feeling that",
                               "yea ... that's no fun",
                               'sympathy deflection',
                               'sorry to hear that',
                               'i feel your pain',
                               'that kinda sucks',
                               'dude ... sorry',
                               'wow that sucks',
                               'man that sucks',
                               'that sucks',
                               'geez ...',
                               'oh geez',
                               'geez ..'],
    'time_greeting': ['long time no see!\n', 'time greeting'],
    'transport_response': ['transport response'],
    'unknown_response': [   "i'm not sure what to say",
                            'unknown response',
                            'if you say so.',
                            'if you say so',
                            'ok'],
    'weather': ['how is the weather', 'hows the weather'],
    'weather_response': ['weather response']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
