
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class ChitchatLookup(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'ChitchatLookup',
            'filename': 'chitchat_lookup',
            'files': ['chitchat.txt'],
            'queries': ['lookup.sparql'],
            'transformers': ['lowercase', 'lookup']},
 'source': 'chitchat.owl',
 'time': '2022-04-27 21:17:15.108357'}

    __data = {
    1: [   'expressionless',
           'absolutely!',
           'absolutely',
           'okee-dokee',
           'experience',
           'howyadoing',
           'persevere',
           'handshake',
           'racehorse',
           'grimacing',
           'adorkable',
           'response',
           'greeting',
           'doggies',
           'emotion',
           'mondays',
           'weather',
           'ocelots',
           'kittens',
           'leopard',
           'puppies',
           'horsies',
           'pronoun',
           'kitties',
           'hotdog',
           'otters',
           'nopers',
           'animal',
           'scream',
           'friday',
           'monday',
           'horses',
           'action',
           'ocelot',
           'tiger2',
           'insult',
           'kitten',
           'emoji',
           'early',
           'shrug',
           'puppy',
           'sweat',
           'otter',
           'hiya!',
           'weary',
           'howdy',
           'skull',
           'horse',
           'tiger',
           'hello',
           'kitty',
           'busy?',
           'state',
           'cats',
           'dogs',
           'wave',
           'hiya',
           'dog2',
           'nope',
           'wink',
           'cat2',
           'late',
           'busy',
           'cat',
           '100',
           'joy',
           'dog',
           'hey',
           'hi!',
           'cry',
           'nah',
           'sup',
           'yes',
           'no',
           'ok',
           'hi'],
    2: [   "i'm_heading_outside_after_this chat!",
           "i'm_heading_outside_after_this chat",
           'are_you_doing_anything_right now?',
           'are_you_doing_anything_right now',
           "you're_pretty_adorkable yourself",
           'how’s_it_been_going_these days?\n',
           'my_favorite_animal_is {animal}',
           'what_are_you_doing_right now?\n',
           'doing_just_great_-_thank you!',
           'maybe_tomorrow_will_be better',
           "the_weather_doesn't_impact me",
           'stuck_out_tongue_winking eye',
           'stuck_out_tongue_closed eyes',
           'doing_just_great_-_thank you',
           'conditional_state deflection',
           'where_are_you_based_out of?',
           'stuck_out_tongue_closed eye',
           'the_more_they_stay_the same',
           'how_is_it_going_these days?',
           'how_is_it_going_these days',
           "how's_it_going_these days?",
           'what_are_your capabilities',
           'where_are_you_based_out of',
           "how's_it_going_these days",
           "nice_weather_we're having",
           'face_with_raised eyebrow',
           'my_favorite_are {animal}',
           'the_weather_will improve',
           "i'm_loving_this weather.",
           'what_are_you_capable of?',
           'favorite_animal response',
           'tell_me_what_you_can do',
           'woman_in_lotus position',
           'state_greeting response',
           'disagreeable deflection',
           "i've_been_well, thanks!",
           "i'm_loving_this weather",
           'what_are_you_capable of',
           'late_transport response',
           'pleading_face persevere',
           'where_you_based_out of?',
           "it's_the_same_old story",
           "i've_been_well, thanks",
           'the_more_things change',
           'where_you_based_out of',
           '{transport}_was packed',
           'interrogation response',
           'when_will_you_be free?',
           'face_with_rolling eyes',
           'tell_me_about yourself',
           'the_same_old rigmarole',
           "i'm_sure_you're right",
           'when_will_you_be free',
           "yea_..._that's_no fun",
           'slightly_smiling face',
           "dude_i'm_feeling that",
           'is_it_friday already?',
           'good_weather response',
           'man_in_lotus position',
           'general_state action',
           'mondays,_am_i right?',
           'negative_slack emoji',
           'bad_weather response',
           'greeting_slack emoji',
           'is_it_friday already',
           'what_are_you doing?\n',
           "i'm_glad_i'm indoors",
           "that's_not suprising",
           '{transport}_was late',
           'fine,_fine_... fine.',
           'agreeable deflection',
           'positive_slack emoji',
           'neutral_slack emoji',
           'big_cat_slack emoji',
           'positive experience',
           'what_are_you_up to?',
           'mondays,_am_i right',
           'sympathy deflection',
           'fine,_fine_... fine',
           'deflection response',
           'negative experience',
           'what_are_you doing?',
           'better_than monday!',
           'what_are_you doing',
           'adorkable response',
           'insult_slack emoji',
           'transport response',
           'what_are_you_up to',
           'how_have_you been?',
           'where_do_you live?',
           'reverse deflection',
           'long_time_no see!\n',
           'animal_slack emoji',
           'better_than monday',
           "i_can't_agree more",
           'how_is_the weather',
           'horse_slack emoji',
           'cliche deflection',
           'location question',
           'busy_state action',
           'location response',
           'what_do_you mean?',
           'greeting response',
           'favorable emotion',
           'otter_slack emoji',
           'how_is_it hanging',
           'how_have_you been',
           'free_state action',
           'where_do_you live',
           'hanging_in there.',
           'weather response',
           "how's_it hanging",
           'doing_just great',
           'i_feel_your pain',
           "you're adorkable",
           'that_kinda sucks',
           "what's_going on?",
           'stuck_out tongue',
           'upside_down face',
           'hows_the weather',
           'doing_real great',
           'what_do_you mean',
           'packed transport',
           'unknown response',
           'doing real_great',
           'how_is_it hangin',
           'what_is_going on',
           'hanging_in there',
           "you're_so right",
           'dog_slack emoji',
           "same_o'_same o'",
           "that's_not true",
           'monday response',
           'crying_cat face',
           'hows_it hanging',
           'i_love mondays!',
           "what's_going on",
           'greeting action',
           'what_can_you do',
           'i’m_always here',
           'friday response',
           'insult response',
           'cat_slack emoji',
           "how's_it hangin",
           'how_do_you do?',
           'whats_going on',
           'whatcha doing?',
           'state greeting',
           "whats_goin' on",
           'if_you_say so!',
           'hows_it hangin',
           'where_are you?',
           'carousel horse',
           'what_do_you do',
           'where are_you?',
           'you_live here?',
           'same_old thing',
           'i_love mondays',
           'if_you_say so.',
           'hello response',
           'nice_day today',
           'late transport',
           'real_great man',
           'ability action',
           'whatcha doin’?',
           'dude_... sorry',
           'man_that sucks',
           'wow_that sucks',
           'you_live here',
           "i_can't agree",
           'where are_you',
           'where_are you',
           'if_you_say so',
           'are_you busy?',
           'what_up dawg\n',
           'great weather',
           'how_do_you do',
           'time greeting',
           'whatcha doin’',
           'but different',
           'whatcha doing',
           'no_way, jose',
           'are_you busy',
           'hugging face',
           'are_you free',
           'neutral face',
           'good weather',
           'good thanks!',
           'happy monday',
           'happy friday',
           'hello there!',
           'how_ya doing',
           'how are_you?',
           'how_are you?',
           'hey_whats up',
           'horse racing',
           'fine weather',
           'nice weather',
           'doing great',
           'like animal',
           'howya doing',
           'slack emoji',
           'hello there',
           'how_ya doin',
           'service dog',
           'how are_you',
           'how_are you',
           'pouting cat',
           'yay friday!',
           'good thanks',
           'a_fine day!',
           'bad weather',
           'yay friday',
           'real great',
           'black cat2',
           'that sucks',
           'just great',
           'a_fine day',
           'howya doin',
           'smiley cat',
           'guide dog',
           'zany face',
           'smile cat',
           'same same',
           "what's up",
           'great man',
           'smirk cat',
           'great day',
           'you free?',
           'hi there',
           'geez ...',
           'fine day',
           'nice day',
           'good day',
           'you free',
           'hey dude',
           'geez ..',
           'joy cat',
           'oh geez',
           'i agree',
           'no way'],
    3: [   'conditional state deflection',
           'favorite animal response',
           'pleading face persevere',
           'late transport response',
           'state greeting response',
           '{transport} was packed',
           'slightly smiling face',
           'good weather response',
           'negative slack emoji',
           'general state action',
           'positive slack emoji',
           '{transport} was late',
           'bad weather response',
           'skull and crossbones',
           "that's not suprising",
           'greeting slack emoji',
           'neutral slack emoji',
           'better than monday!',
           'animal slack emoji',
           'insult slack emoji',
           'better than monday',
           'free state action',
           'hanging in there.',
           'horse slack emoji',
           'otter slack emoji',
           'busy state action',
           'stuck out tongue',
           "how's it hanging",
           'that kinda sucks',
           'doing real great',
           'doing just great',
           "what's going on?",
           'hows the weather',
           'hanging in there',
           'upside down face',
           "that's not true",
           'hows it hanging',
           "how's it hangin",
           'cat slack emoji',
           "what's going on",
           'i love mondays!',
           'crying cat face',
           'i’m always here',
           "you're so right",
           'dog slack emoji',
           'you live here?',
           'where are you?',
           'dude ... sorry',
           'whats going on',
           'real great man',
           "whats goin' on",
           'meet and greet',
           'hows it hangin',
           'i love mondays',
           'same old thing',
           'man that sucks',
           'wow that sucks',
           'nice day today',
           'are you busy?',
           "i can't agree",
           'where are you',
           'what up dawg\n',
           'you live here',
           'how are you?',
           'how ya doing',
           'are you free',
           'hey whats up',
           'are you busy',
           'no way, jose',
           'how ya doin',
           'a fine day!',
           'how are you',
           'a fine day'],
    4: [   "you're pretty adorkable yourself",
           'what are your capabilities',
           "nice weather we're having",
           'my favorite are {animal}',
           "i'm loving this weather.",
           'the weather will improve',
           'face with raised eyebrow',
           'woman in lotus position',
           "i've been well, thanks!",
           "i'm loving this weather",
           'the same old rigmarole',
           'tell me about yourself',
           'face with rolling eyes',
           'the more things change',
           "i've been well, thanks",
           'man in lotus position',
           'is it friday already?',
           "i'm sure you're right",
           "dude i'm feeling that",
           'what are you doing?\n',
           "i'm glad i'm indoors",
           'is it friday already',
           'mondays, am i right?',
           'fine, fine ... fine.',
           'what are you doing?',
           'mondays, am i right',
           'big cat slack emoji',
           'case of the mondays',
           'pleased to meet you',
           'fine, fine ... fine',
           'long time no see!\n',
           'how is the weather',
           'how have you been?',
           "i can't agree more",
           'sorry to hear that',
           'what are you doing',
           'where do you live?',
           'how is it hanging',
           'what do you mean?',
           'where do you live',
           'how have you been',
           'how is it hangin',
           'nice to meet you',
           'what do you mean',
           'i feel your pain',
           'what is going on',
           'what can you do',
           "same o' same o'",
           'if you say so!',
           'what do you do',
           'if you say so.',
           'how do you do?',
           'if you say so',
           'how do you do'],
    5: [   'my favorite animal is {animal}',
           "the weather doesn't impact me",
           'maybe tomorrow will be better',
           'stuck out tongue winking eye',
           'stuck out tongue closed eyes',
           'stuck out tongue closed eye',
           "how's it going these days?",
           "how's it going these days",
           "i'm ready to go outside!",
           'what are you capable of?',
           'where you based out of?',
           "it's the same old story",
           "i'm ready to go outside",
           'what are you capable of',
           'real sorry to hear that',
           'where you based out of',
           'when will you be free?',
           "i'm sorry to hear that",
           'nice day to go fishing',
           "yea ... that's no fun",
           'when will you be free',
           'what are you up to?',
           'what are you up to'],
    6: [   "i'm heading outside after this chat!",
           "i'm heading outside after this chat",
           'are you doing anything right now?',
           'are you doing anything right now',
           'how’s it been going these days?\n',
           'what are you doing right now?\n',
           'doing just great - thank you!',
           'doing just great - thank you',
           'the more they stay the same',
           'where are you based out of?',
           'how is it going these days?',
           'how is it going these days',
           'where are you based out of',
           'what are you up to lately?',
           'what are you up to lately',
           "it's all the same to me.",
           'i was going to say that.',
           "i'm not sure what to say",
           'it is nice to meet you.',
           'tell me what you can do',
           'i was going to say that',
           "it's all the same to me",
           'it is nice to meet you'],
    7: [   'i hear ya ... been there myself',
           'what are you up to right now?\n',
           'what do you do for a living?\n',
           'tell me about what you can do'],
    8: [   "you can't step in the same river twice\n",
           'i was just about to ask you that.',
           'i was just about to ask you that'],
    9: ['i like them all but i really like {animal}'],
    15: [" i mean ... it happens, but that doesn't mean we have to like it"]}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
