
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class ChitchatInferByRequires(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'ChitchatInferByRequires',
            'filename': 'chitchat_infer_by_requires',
            'queries': ['infer_by_requires.sparql % $PREFIX=chitchat'],
            'transformers': ['infer_by_requires']},
 'source': 'chitchat.owl',
 'time': '2022-04-27 21:17:15.131855'}

    __data = {
    'adorkable_response': [   {   'context': ['insult'],
                                  'id': '15a180ff-c6aa-11ec-ad4a-4c1d96716627',
                                  'replace': 'insult',
                                  'with': 'adorkable'}],
    'agreeable_deflection': [   {   'context': ['deflection_response'],
                                    'id': '15a180f3-c6aa-11ec-854c-4c1d96716627',
                                    'replace': 'deflection_response',
                                    'with': 'conditional_state_deflection'},
                                {   'context': ['deflection_response'],
                                    'id': '15a180f7-c6aa-11ec-a9f4-4c1d96716627',
                                    'replace': 'deflection_response',
                                    'with': 'disagreeable_deflection'},
                                {   'context': ['weather_response'],
                                    'id': '15a180fb-c6aa-11ec-a7cc-4c1d96716627',
                                    'replace': 'weather_response',
                                    'with': 'good_weather_response'},
                                {   'context': ['insult'],
                                    'id': '15a18100-c6aa-11ec-ab3c-4c1d96716627',
                                    'replace': 'insult',
                                    'with': 'adorkable'}],
    'bad_weather_response': [   {   'context': ['negative_experience'],
                                    'id': '15a180fe-c6aa-11ec-97ad-4c1d96716627',
                                    'replace': 'negative_experience',
                                    'with': 'bad_weather'}],
    'cliche_deflection': [   {   'context': ['greeting_response'],
                                 'id': '15a180ef-c6aa-11ec-9480-4c1d96716627',
                                 'replace': 'greeting_response',
                                 'with': 'monday_response'},
                             {   'context': ['transport_response'],
                                 'id': '15a180f9-c6aa-11ec-b9fc-4c1d96716627',
                                 'replace': 'transport_response',
                                 'with': 'late_transport_response'}],
    'conditional_state_deflection': [   {   'context': ['deflection_response'],
                                            'id': '15a180e9-c6aa-11ec-aa21-4c1d96716627',
                                            'replace': 'deflection_response',
                                            'with': 'unknown_response'},
                                        {   'context': ['weather_response'],
                                            'id': '15a180ed-c6aa-11ec-b754-4c1d96716627',
                                            'replace': 'weather_response',
                                            'with': 'bad_weather_response'},
                                        {   'context': ['greeting_response'],
                                            'id': '15a180ee-c6aa-11ec-9af3-4c1d96716627',
                                            'replace': 'greeting_response',
                                            'with': 'monday_response'},
                                        {   'context': ['greeting_response'],
                                            'id': '15a180f8-c6aa-11ec-9a88-4c1d96716627',
                                            'replace': 'greeting_response',
                                            'with': 'state_greeting_response'},
                                        {   'context': ['greeting_response'],
                                            'id': '15a180fd-c6aa-11ec-9085-4c1d96716627',
                                            'replace': 'greeting_response',
                                            'with': 'weather_response'}],
    'deflection_response': [   {   'context': ['conditional_state_deflection'],
                                   'id': '15a180e9-c6aa-11ec-aa21-4c1d96716627',
                                   'replace': 'deflection_response',
                                   'with': 'unknown_response'},
                               {   'context': ['agreeable_deflection'],
                                   'id': '15a180f3-c6aa-11ec-854c-4c1d96716627',
                                   'replace': 'deflection_response',
                                   'with': 'conditional_state_deflection'},
                               {   'context': ['disagreeable_deflection'],
                                   'id': '15a180f6-c6aa-11ec-b17d-4c1d96716627',
                                   'replace': 'deflection_response',
                                   'with': 'agreeable_deflection'},
                               {   'context': ['agreeable_deflection'],
                                   'id': '15a180f7-c6aa-11ec-a9f4-4c1d96716627',
                                   'replace': 'deflection_response',
                                   'with': 'disagreeable_deflection'}],
    'disagreeable_deflection': [   {   'context': ['deflection_response'],
                                       'id': '15a180f6-c6aa-11ec-b17d-4c1d96716627',
                                       'replace': 'deflection_response',
                                       'with': 'agreeable_deflection'}],
    'friday_response': [   {   'context': ['weekday'],
                               'id': '15a180ea-c6aa-11ec-b98b-4c1d96716627',
                               'replace': 'weekday',
                               'with': 'friday'}],
    'good_weather_response': [   {   'context': ['weather'],
                                     'id': '15a180eb-c6aa-11ec-805e-4c1d96716627',
                                     'replace': 'weather',
                                     'with': 'good_weather'}],
    'greeting': [   {   'context': ['state_greeting'],
                        'id': '15a180f4-c6aa-11ec-a500-4c1d96716627',
                        'replace': 'greeting',
                        'with': 'meet_and_greet'},
                    {   'context': ['hello_response'],
                        'id': '15a180f5-c6aa-11ec-9ec0-4c1d96716627',
                        'replace': 'greeting',
                        'with': 'hello'},
                    {   'context': ['state_greeting_response'],
                        'id': '15a180fc-c6aa-11ec-9b7b-4c1d96716627',
                        'replace': 'greeting',
                        'with': 'state_greeting'}],
    'greeting_response': [   {   'context': ['conditional_state_deflection'],
                                 'id': '15a180ee-c6aa-11ec-9af3-4c1d96716627',
                                 'replace': 'greeting_response',
                                 'with': 'monday_response'},
                             {   'context': ['cliche_deflection'],
                                 'id': '15a180ef-c6aa-11ec-9480-4c1d96716627',
                                 'replace': 'greeting_response',
                                 'with': 'monday_response'},
                             {   'context': ['monday'],
                                 'id': '15a180f0-c6aa-11ec-97e2-4c1d96716627',
                                 'replace': 'greeting_response',
                                 'with': 'monday_response'},
                             {   'context': ['meet_and_greet'],
                                 'id': '15a180f1-c6aa-11ec-8198-4c1d96716627',
                                 'replace': 'greeting_response',
                                 'with': 'hello_response'},
                             {   'context': ['conditional_state_deflection'],
                                 'id': '15a180f8-c6aa-11ec-9a88-4c1d96716627',
                                 'replace': 'greeting_response',
                                 'with': 'state_greeting_response'},
                             {   'context': ['conditional_state_deflection'],
                                 'id': '15a180fd-c6aa-11ec-9085-4c1d96716627',
                                 'replace': 'greeting_response',
                                 'with': 'weather_response'}],
    'hello_response': [   {   'context': ['greeting'],
                              'id': '15a180f5-c6aa-11ec-9ec0-4c1d96716627',
                              'replace': 'greeting',
                              'with': 'hello'}],
    'insult': [   {   'context': ['adorkable_response'],
                      'id': '15a180ff-c6aa-11ec-ad4a-4c1d96716627',
                      'replace': 'insult',
                      'with': 'adorkable'},
                  {   'context': ['agreeable_deflection'],
                      'id': '15a18100-c6aa-11ec-ab3c-4c1d96716627',
                      'replace': 'insult',
                      'with': 'adorkable'}],
    'late_transport_response': [   {   'context': ['traffic'],
                                       'id': '15a180f2-c6aa-11ec-9568-4c1d96716627',
                                       'replace': 'traffic',
                                       'with': 'late_transport'}],
    'meet_and_greet': [   {   'context': ['greeting_response'],
                              'id': '15a180f1-c6aa-11ec-8198-4c1d96716627',
                              'replace': 'greeting_response',
                              'with': 'hello_response'}],
    'monday': [   {   'context': ['greeting_response'],
                      'id': '15a180f0-c6aa-11ec-97e2-4c1d96716627',
                      'replace': 'greeting_response',
                      'with': 'monday_response'}],
    'monday_response': [   {   'context': ['weekday'],
                               'id': '15a180ec-c6aa-11ec-8eb0-4c1d96716627',
                               'replace': 'weekday',
                               'with': 'monday'}],
    'negative_experience': [   {   'context': ['bad_weather_response'],
                                   'id': '15a180fe-c6aa-11ec-97ad-4c1d96716627',
                                   'replace': 'negative_experience',
                                   'with': 'bad_weather'}],
    'state_greeting': [   {   'context': ['greeting'],
                              'id': '15a180f4-c6aa-11ec-a500-4c1d96716627',
                              'replace': 'greeting',
                              'with': 'meet_and_greet'}],
    'state_greeting_response': [   {   'context': ['greeting'],
                                       'id': '15a180fc-c6aa-11ec-9b7b-4c1d96716627',
                                       'replace': 'greeting',
                                       'with': 'state_greeting'}],
    'sympathy_deflection': [   {   'context': ['transport_response'],
                                   'id': '15a180fa-c6aa-11ec-8a04-4c1d96716627',
                                   'replace': 'transport_response',
                                   'with': 'late_transport_response'}],
    'traffic': [   {   'context': ['late_transport_response'],
                       'id': '15a180f2-c6aa-11ec-9568-4c1d96716627',
                       'replace': 'traffic',
                       'with': 'late_transport'}],
    'transport_response': [   {   'context': ['cliche_deflection'],
                                  'id': '15a180f9-c6aa-11ec-b9fc-4c1d96716627',
                                  'replace': 'transport_response',
                                  'with': 'late_transport_response'},
                              {   'context': ['sympathy_deflection'],
                                  'id': '15a180fa-c6aa-11ec-8a04-4c1d96716627',
                                  'replace': 'transport_response',
                                  'with': 'late_transport_response'}],
    'weather': [   {   'context': ['good_weather_response'],
                       'id': '15a180eb-c6aa-11ec-805e-4c1d96716627',
                       'replace': 'weather',
                       'with': 'good_weather'}],
    'weather_response': [   {   'context': ['conditional_state_deflection'],
                                'id': '15a180ed-c6aa-11ec-b754-4c1d96716627',
                                'replace': 'weather_response',
                                'with': 'bad_weather_response'},
                            {   'context': ['agreeable_deflection'],
                                'id': '15a180fb-c6aa-11ec-a7cc-4c1d96716627',
                                'replace': 'weather_response',
                                'with': 'good_weather_response'}],
    'weekday': [   {   'context': ['friday_response'],
                       'id': '15a180ea-c6aa-11ec-b98b-4c1d96716627',
                       'replace': 'weekday',
                       'with': 'friday'},
                   {   'context': ['monday_response'],
                       'id': '15a180ec-c6aa-11ec-8eb0-4c1d96716627',
                       'replace': 'weekday',
                       'with': 'monday'}]}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
