
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

d_emoji_set_rev_provenance = {
 'action': ['router.py',
            'plac_core.py',
            'csv2py_orchestrator.py',
            'emojis2py.py',
            'emoji_dict_writer.py',
            'common_utils.py'],
 'source': 'resources/data/csv/emojis.xlsx',
 'time': '2022-05-17 17:00:32.971457'}

d_emoji_set_rev = {
    '8ball': [-1, -1],
    'Objects': [-1],
    'ab': [8],
    'abc': [8],
    'abcd': [8],
    'accept': [8],
    'adult': [1],
    'alarm_clock': [-1],
    'alien': [1],
    'angel': [1],
    'angry': [1],
    'anguished': [1],
    'ant': [4],
    'apple': [-1, -1],
    'aquarius': [8],
    'aries': [8],
    'arrow_backward': [8],
    'arrow_double_down': [8],
    'arrow_double_up': [8],
    'arrow_down': [8],
    'arrow_down_small': [8],
    'arrow_forward': [8],
    'arrow_heading_down': [8],
    'arrow_heading_up': [8],
    'arrow_left': [8],
    'arrow_lower_left': [8],
    'arrow_lower_right': [8],
    'arrow_right': [8],
    'arrow_right_hook': [8],
    'arrow_up': [8],
    'arrow_up_down': [8],
    'arrow_up_small': [8],
    'arrow_upper_left': [8],
    'arrow_upper_right': [8],
    'arrows_clockwise': [8],
    'arrows_counterclockwise': [8],
    'art': [-1, -1],
    'astonished': [1],
    'baby': [1],
    'baby_bottle': [-1, -1],
    'baby_chick': [4],
    'baby_symbol': [8],
    'back': [8],
    'baggage_claim': [8],
    'balloon': [5, -1],
    'ballot_box_with_check': [8],
    'bamboo': [-1],
    'banana': [-1, -1],
    'bangbang': [8],
    'bank': [7],
    'bar_chart': [-1, -1],
    'baseball': [-1, -1],
    'basketball': [-1, -1],
    'bath': [-1, -1],
    'bathtub': [-1, -1],
    'battery': [-1, -1],
    'bear': [4],
    'bearded_person': [1],
    'beer': [-1, -1],
    'beers': [-1, -1],
    'beetle': [4],
    'bell': [5, -1],
    'bento': [-1, -1],
    'bicyclist': [-1, -1],
    'bikini': [-1, -1],
    'bird': [4],
    'birthday': [-1, -1],
    'black_circle': [8],
    'black_joker': [-1, -1],
    'black_large_square': [8],
    'black_medium_small_square': [8],
    'black_medium_square': [8],
    'black_nib': [-1, -1],
    'black_small_square': [8],
    'black_square_button': [8],
    'blond_haired_man': [1],
    'blond_haired_woman': [1],
    'blossom': [-1],
    'blue_book': [-1, -1],
    'blush': [1],
    'boar': [4],
    'boat': [6],
    'bomb': [-1, -1],
    'book': [-1, -1],
    'bookmark': [-1, -1],
    'bookmark_tabs': [-1, -1],
    'books': [-1, -1],
    'boot': [-1, -1],
    'bowling': [-1, -1],
    'boy': [1],
    'bread': [-1, -1],
    'breast_feeding': [1],
    'bride_with_veil': [1],
    'bridge_at_night': [7],
    'briefcase': [-1, -1],
    'bug': [4],
    'bulb': [2, -1, -1],
    'cactus': [-1],
    'cake': [-1, -1],
    'calendar': [-1, -1],
    'calling': [-1, -1],
    'camel': [4],
    'camera': [5, -1],
    'cancer': [8],
    'candy': [-1, -1],
    'capital_abcd': [8],
    'capricorn': [8],
    'card_index': [-1, -1],
    'carousel_horse': [7],
    'cat': [4],
    'cd': [5, -1],
    'chart': [8],
    'chart_with_downwards_trend': [-1, -1],
    'chart_with_upwards_trend': [-1, -1],
    'cherries': [-1, -1],
    'chestnut': [-1],
    'chicken': [4],
    'child': [1],
    'children_crossing': [8],
    'chocolate_bar': [-1, -1],
    'christmas_tree': [5, -1],
    'church': [7],
    'cinema': [8],
    'cl': [8],
    'clap': [2],
    'clapper': [-1, -1],
    'clipboard': [-1, -1],
    'clock1': [8],
    'clock10': [8],
    'clock1030': [8],
    'clock11': [8],
    'clock1130': [8],
    'clock12': [8],
    'clock1230': [8],
    'clock130': [8],
    'clock2': [8],
    'clock230': [8],
    'clock3': [8],
    'clock330': [8],
    'clock4': [8],
    'clock430': [8],
    'clock5': [8],
    'clock530': [8],
    'clock6': [8],
    'clock630': [8],
    'clock7': [8],
    'clock730': [8],
    'clock8': [8],
    'clock830': [8],
    'clock9': [8],
    'clock930': [8],
    'closed_book': [-1, -1],
    'closed_lock_with_key': [-1, -1],
    'closed_umbrella': [-1, -1],
    'cloud': [3],
    'clown_face': [1],
    'clubs': [-1, -1],
    'cocktail': [-1, -1],
    'coffee': [-1, -1],
    'cold_sweat': [1],
    'computer': [5, -1],
    'confetti_ball': [5, -1],
    'confounded': [1],
    'confused': [1],
    'congratulations': [8],
    'convenience_store': [7],
    'cookie': [-1, -1],
    'cool': [8],
    'copyright': [8],
    'corn': [-1, -1],
    'cow': [4],
    'credit_card': [-1, -1],
    'crescent_moon': [-1],
    'crown': [-1, -1],
    'cry': [1],
    'crying_cat_face': [1],
    'crystal_ball': [5, -1],
    'curly_loop': [8],
    'currency_exchange': [8],
    'curry': [-1, -1],
    'custard': [-1, -1],
    'customs': [8],
    'cyclone': [3],
    'dancer': [1],
    'dango': [-1, -1],
    'dart': [2, -1, -1],
    'date': [-1, -1],
    'deciduous_tree': [-1],
    'department_store': [7],
    'diamond_shape_with_a_dot_inside': [8],
    'diamonds': [-1, -1],
    'disappointed': [1],
    'disappointed_relieved': [1],
    'dizzy_face': [1],
    'do_not_litter': [8],
    'dog': [4],
    'dollar': [-1, -1],
    'dolls': [5, -1],
    'dolphin': [4],
    'door': [-1, -1],
    'doughnut': [-1, -1],
    'dress': [-1, -1],
    'drooling_face': [1],
    'dvd': [5, -1],
    'e-mail': [-1, -1],
    'ear_of_rice': [-1],
    'earth_africa': [-1],
    'earth_americas': [-1],
    'earth_asia': [-1],
    'egg': [-1, -1],
    'eggplant': [-1, -1],
    'eight': [8],
    'eight_pointed_black_star': [8],
    'eight_spoked_asterisk': [8],
    'electric_plug': [-1, -1],
    'elephant': [4],
    'email': [-1, -1],
    'end': [8],
    'envelope': [-1, -1],
    'euro': [-1, -1],
    'evergreen_tree': [-1],
    'exploding_head': [1],
    'expressionless': [1],
    'eyeglasses': [-1, -1],
    'eyes': [2],
    'face_vomiting': [1],
    'face_with_cowboy_hat': [1],
    'face_with_hand_over_mouth': [1],
    'face_with_head_bandage': [1],
    'face_with_monocle': [1],
    'face_with_raised_eyebrow': [1],
    'face_with_rolling_eyes': [1],
    'face_with_symbols_on_mouth': [1],
    'face_with_thermometer': [1],
    'factory': [7],
    'fallen_leaf': [-1],
    'fast_forward': [8],
    'fax': [5, -1],
    'fearful': [1],
    'female_artist': [1],
    'female_astronaut': [1],
    'female_construction_worker': [1],
    'female_cook': [1],
    'female_detective': [1],
    'female_doctor': [1],
    'female_elf': [1],
    'female_factory_worker': [1],
    'female_fairy': [1],
    'female_farmer': [1],
    'female_firefighter': [1],
    'female_genie': [1],
    'female_guard': [1],
    'female_judge': [1],
    'female_mage': [1],
    'female_mechanic': [1],
    'female_office_worker': [1],
    'female_pilot': [1],
    'female_police_officer': [1],
    'female_scientist': [1],
    'female_singer': [1],
    'female_student': [1],
    'female_teacher': [1],
    'female_technologist': [1],
    'female_vampire': [1],
    'female_zombie': [1],
    'ferris_wheel': [6],
    'file_folder': [-1, -1],
    'fireworks': [5, -1],
    'first_quarter_moon': [-1],
    'first_quarter_moon_with_face': [-1],
    'fish': [4],
    'fish_cake': [-1, -1],
    'fishing_pole_and_fish': [-1, -1],
    'five': [8],
    'flags': [5, -1],
    'flashlight': [-1, -1],
    'floppy_disk': [5, -1],
    'flower_playing_cards': [-1, -1],
    'flushed': [1],
    'foggy': [3],
    'football': [-1, -1],
    'fork_and_knife': [-1, -1],
    'fountain': [6],
    'four': [8],
    'free': [8],
    'fried_shrimp': [-1, -1],
    'fries': [-1, -1],
    'frog': [4],
    'frowning': [1],
    'full_moon': [-1],
    'full_moon_with_face': [-1],
    'game_die': [-1, -1],
    'gem': [-1, -1],
    'gemini': [8],
    'ghost': [1, 5, -1],
    'gift': [5, -1],
    'gift_heart': [5, -1],
    'girl': [1],
    'globe_with_meridians': [-1],
    'golf': [-1, -1],
    'grapes': [-1, -1],
    'green_apple': [-1, -1],
    'green_book': [-1, -1],
    'grimacing': [1],
    'guitar': [-1, -1],
    'gun': [-1, -1],
    'hamburger': [-1, -1],
    'hammer': [-1, -1],
    'hamster': [4],
    'handbag': [-1, -1],
    'hankey': [1],
    'hash': [8],
    'hatched_chick': [4],
    'headphones': [-1, -1],
    'hear_no_evil': [1],
    'heart_decoration': [8],
    'heart_eyes': [1],
    'heart_eyes_cat': [1],
    'hearts': [-1, -1],
    'heavy_check_mark': [8],
    'heavy_division_sign': [8],
    'heavy_dollar_sign': [8],
    'heavy_exclamation_mark': [8],
    'heavy_minus_sign': [8],
    'heavy_multiplication_x': [8],
    'heavy_plus_sign': [2, 8],
    'herb': [-1],
    'hibiscus': [-1],
    'high_brightness': [-1, -1],
    'high_heel': [-1, -1],
    'hocho': [-1, -1],
    'honey_pot': [-1, -1],
    'honeybee': [4],
    'horse': [4],
    'horse_racing': [-1, -1],
    'hospital': [7],
    'hotel': [7],
    'hourglass': [-1],
    'hourglass_flowing_sand': [-1],
    'house': [7],
    'house_with_garden': [7],
    'hugging_face': [1],
    'hushed': [1],
    'ice_cream': [-1, -1],
    'icecream': [-1, -1],
    'id': [8],
    'ideograph_advantage': [8],
    'imp': [1],
    'inbox_tray': [-1, -1],
    'incoming_envelope': [-1, -1],
    'information_source': [8],
    'innocent': [1],
    'interrobang': [8],
    'iphone': [-1],
    'jack_o_lantern': [5, -1],
    'japan': [7],
    'japanese_goblin': [1],
    'japanese_ogre': [1],
    'jeans': [-1, -1],
    'joy': [1],
    'joy_cat': [1],
    'key': [-1, -1],
    'keycap_ten': [8],
    'kimono': [-1, -1],
    'kissing': [1],
    'kissing_cat': [1],
    'kissing_closed_eyes': [1],
    'kissing_heart': [1],
    'kissing_smiling_eyes': [1],
    'koala': [4],
    'koko': [8],
    'large_blue_circle': [2, 8],
    'large_blue_diamond': [8],
    'large_orange_diamond': [8],
    'last_quarter_moon': [-1],
    'last_quarter_moon_with_face': [-1],
    'leaves': [-1],
    'ledger': [-1, -1],
    'left_luggage': [8],
    'left_right_arrow': [8],
    'leftwards_arrow_with_hook': [8],
    'lemon': [-1, -1],
    'leo': [8],
    'libra': [8],
    'link': [8],
    'lipstick': [-1, -1],
    'lock': [-1, -1],
    'lock_with_ink_pen': [-1, -1],
    'lollipop': [-1, -1],
    'loop': [-1, -1],
    'loudspeaker': [-1],
    'low_brightness': [-1, -1],
    'lying_face': [1],
    'mag': [-1, -1],
    'mag_right': [-1, -1],
    'mahjong': [-1, -1],
    'mailbox': [-1, -1],
    'mailbox_closed': [-1, -1],
    'mailbox_with_mail': [-1, -1],
    'mailbox_with_no_mail': [-1, -1],
    'male_artist': [1],
    'male_astronaut': [1],
    'male_construction_worker': [1],
    'male_cook': [1],
    'male_detective': [1],
    'male_doctor': [1],
    'male_elf': [1],
    'male_factory_worker': [1],
    'male_fairy': [1],
    'male_farmer': [1],
    'male_firefighter': [1],
    'male_genie': [1],
    'male_guard': [1],
    'male_judge': [1],
    'male_mage': [1],
    'male_mechanic': [1],
    'male_office_worker': [1],
    'male_pilot': [1],
    'male_police_officer': [1],
    'male_scientist': [1],
    'male_singer': [1],
    'male_student': [1],
    'male_teacher': [1],
    'male_technologist': [1],
    'male_vampire': [1],
    'male_zombie': [1],
    'man': [1],
    'man_bowing': [1],
    'man_climbing': [1],
    'man_dancing': [1],
    'man_facepalming': [1],
    'man_frowning': [1],
    'man_gesturing_no': [1],
    'man_gesturing_ok': [1],
    'man_getting_haircut': [1],
    'man_getting_massage': [1],
    'man_in_lotus_position': [1],
    'man_in_steamy_room': [1],
    'man_in_tuxedo': [1],
    'man_pouting': [1],
    'man_raising_hand': [1],
    'man_running': [1],
    'man_shrugging': [1],
    'man_tipping_hand': [1],
    'man_walking': [1],
    'man_wearing_turban': [1],
    'man_with_bunny_ears_partying': [1],
    'man_with_gua_pi_mao': [1],
    'mans_shoe': [-1, -1],
    'maple_leaf': [-1],
    'mask': [1],
    'meat_on_bone': [-1, -1],
    'mega': [2, -1],
    'melon': [-1, -1],
    'memo': [-1, -1],
    'mens': [8],
    'mermaid': [1],
    'merman': [1],
    'metro': [8],
    'microphone': [-1, -1],
    'microscope': [-1, -1],
    'milky_way': [-1],
    'minidisc': [5, -1],
    'mobile_phone_off': [8],
    'money_mouth_face': [1],
    'money_with_wings': [-1, -1],
    'moneybag': [-1, -1],
    'monkey': [4],
    'monkey_face': [4],
    'mortar_board': [5, -1],
    'mount_fuji': [7],
    'mountain_bicyclist': [-1, -1],
    'mouse': [4],
    'movie_camera': [5, -1],
    'mrs_claus': [1],
    'mushroom': [-1],
    'musical_keyboard': [-1, -1],
    'musical_score': [-1, -1],
    'mute': [-1],
    'name_badge': [-1, -1],
    'nauseated_face': [1],
    'necktie': [-1, -1],
    'negative_squared_cross_mark': [8],
    'nerd_face': [1],
    'neutral_face': [1],
    'new': [8],
    'new_moon': [-1],
    'new_moon_with_face': [-1],
    'newspaper': [-1, -1],
    'ng': [8],
    'nine': [8],
    'no_bell': [5, -1],
    'no_bicycles': [8],
    'no_entry': [8],
    'no_entry_sign': [8],
    'no_mobile_phones': [8],
    'no_mouth': [1],
    'no_pedestrians': [8],
    'no_smoking': [8],
    'non-potable_water': [8],
    'notebook': [-1, -1],
    'notebook_with_decorative_cover': [-1, -1],
    'nut_and_bolt': [-1, -1],
    'o2': [8],
    'ocean': [3],
    'octocat': [-1],
    'octopus': [4],
    'oden': [-1, -1],
    'office': [7],
    'ok': [8],
    'older_adult': [1],
    'older_man': [1],
    'older_woman': [1],
    'on': [8],
    'one': [8],
    'open_file_folder': [-1, -1],
    'open_mouth': [1],
    'ophiuchus': [8],
    'orange_book': [-1, -1],
    'outbox_tray': [-1, -1],
    'package': [-1, -1],
    'page_facing_up': [-1, -1],
    'page_with_curl': [-1, -1],
    'pager': [5, -1],
    'palm_tree': [-1],
    'panda_face': [4],
    'paperclip': [-1, -1],
    'parking': [8],
    'part_alternation_mark': [8],
    'partly_sunny': [-1],
    'passport_control': [8],
    'peach': [-1, -1],
    'pear': [-1, -1],
    'pencil': [-1, -1],
    'pencil2': [-1, -1],
    'penguin': [4],
    'pensive': [1],
    'persevere': [1],
    'person_with_headscarf': [1],
    'phone': [5, -1],
    'pig': [4],
    'pig_nose': [4],
    'pill': [-1, -1],
    'pineapple': [-1, -1],
    'pisces': [8],
    'pizza': [-1, -1],
    'post_office': [7],
    'postal_horn': [-1, -1],
    'postbox': [-1, -1],
    'potable_water': [8],
    'pouch': [-1, -1],
    'poultry_leg': [-1, -1],
    'pound': [-1, -1],
    'pouting_cat': [1],
    'pray': [2],
    'pregnant_woman': [1],
    'prince': [1],
    'princess': [1],
    'purse': [-1, -1],
    'pushpin': [-1, -1],
    'put_litter_in_its_place': [8],
    'rabbit': [4],
    'racehorse': [4],
    'radio': [-1],
    'radio_button': [8],
    'rage': [1],
    'rainbow': [7],
    'raised_hands': [2],
    'ramen': [-1, -1],
    'recycle': [8],
    'red_circle': [2, 8],
    'registered': [8],
    'relaxed': [1],
    'relieved': [1],
    'repeat': [8],
    'repeat_one': [8],
    'restroom': [8],
    'rewind': [8],
    'ribbon': [-1, -1],
    'rice': [-1, -1],
    'rice_ball': [-1, -1],
    'rice_cracker': [-1, -1],
    'rice_scene': [-1],
    'ring': [-1, -1],
    'robot_face': [1],
    'roller_coaster': [6],
    'rolling_on_the_floor_laughing': [1],
    'rugby_football': [-1, -1],
    'running_shirt_with_sash': [-1, -1],
    'sa': [8],
    'sagittarius': [8],
    'sailboat': [6],
    'sake': [-1, -1],
    'sandal': [-1, -1],
    'santa': [1, 5, -1],
    'satellite': [-1],
    'saxophone': [-1, -1],
    'school': [7],
    'school_satchel': [5, -1],
    'scissors': [-1, -1],
    'scorpius': [8],
    'scream': [1],
    'scream_cat': [1],
    'scroll': [-1, -1],
    'seat': [-1, -1],
    'secret': [8],
    'see_no_evil': [1],
    'seedling': [-1],
    'seven': [8],
    'shaved_ice': [-1, -1],
    'sheep': [4],
    'shell': [-1],
    'ship': [6],
    'shipit': [8],
    'shirt': [-1, -1],
    'shoe': [-1, -1],
    'shower': [-1, -1],
    'shushing_face': [1],
    'signal_strength': [8],
    'six': [8],
    'six_pointed_star': [8],
    'ski': [-1, -1],
    'skull': [1],
    'skull_and_crossbones': [1],
    'sleeping': [1],
    'sleepy': [1],
    'slightly_frowning_face': [1],
    'slightly_smiling_face': [1],
    'small_blue_diamond': [8],
    'small_orange_diamond': [8],
    'small_red_triangle': [8],
    'small_red_triangle_down': [8],
    'smile': [1],
    'smile_cat': [1],
    'smiley': [1],
    'smiley_cat': [1],
    'smiling_imp': [1],
    'smirk': [1],
    'smirk_cat': [1],
    'smoking': [-1, -1],
    'snail': [4],
    'snake': [4],
    'sneezing_face': [1],
    'snowboarder': [-1, -1],
    'snowflake': [3],
    'snowman': [3],
    'sob': [1],
    'soccer': [-1, -1],
    'soon': [8],
    'sos': [8],
    'sound': [-1],
    'space_invader': [1, -1, -1],
    'spades': [-1, -1],
    'spaghetti': [-1, -1],
    'sparkle': [8],
    'sparkler': [5, -1],
    'speak_no_evil': [1],
    'speaker': [-1],
    'speedboat': [6],
    'squirrel': [-1],
    'star_struck': [1],
    'statue_of_liberty': [7],
    'stew': [-1, -1],
    'straight_ruler': [-1, -1],
    'strawberry': [-1, -1],
    'stuck_out_tongue': [1],
    'stuck_out_tongue_closed_eyes': [1],
    'stuck_out_tongue_winking_eye': [1],
    'sun_with_face': [-1],
    'sunglasses': [1],
    'sunny': [3],
    'sunrise': [7],
    'sunrise_over_mountains': [7],
    'surfer': [-1, -1],
    'sushi': [-1, -1],
    'sweat': [1],
    'sweat_smile': [1],
    'sweet_potato': [-1, -1],
    'swimmer': [-1, -1],
    'symbols': [8],
    'syringe': [-1, -1],
    'tada': [2, 5, -1],
    'tanabata_tree': [5, -1],
    'tangerine': [-1, -1],
    'taurus': [8],
    'tea': [-1, -1],
    'telephone': [5, -1],
    'telephone_receiver': [5, -1],
    'telescope': [-1, -1],
    'tennis': [-1, -1],
    'tent': [7],
    'thinking_face': [1],
    'three': [8],
    'thumbsup': [2],
    'tiger': [4],
    'tired_face': [1],
    'tm': [8],
    'toilet': [-1, -1],
    'tokyo_tower': [7],
    'tomato': [-1, -1],
    'top': [8],
    'tophat': [-1, -1],
    'triangular_ruler': [-1, -1],
    'trident': [8],
    'triumph': [1],
    'trophy': [-1, -1],
    'tropical_drink': [-1, -1],
    'tropical_fish': [4],
    'trumpet': [-1, -1],
    'tshirt': [-1, -1],
    'turtle': [4],
    'tv': [5, -1],
    'twisted_rightwards_arrows': [8],
    'two': [8],
    'u5272': [8],
    'u5408': [8],
    'u55b6': [8],
    'u6307': [8],
    'u6708': [8],
    'u6709': [8],
    'u6e80': [8],
    'u7121': [8],
    'u7533': [8],
    'u7981': [8],
    'u7a7a': [8],
    'umbrella': [3],
    'unamused': [1],
    'underage': [8],
    'unlock': [-1, -1],
    'up': [8],
    'upside_down_face': [1],
    'vhs': [5, -1],
    'vibration_mode': [8],
    'video_camera': [5, -1],
    'video_game': [-1, -1],
    'violin': [-1, -1],
    'virgo': [8],
    'volcano': [-1],
    'vs': [8],
    'waning_crescent_moon': [-1],
    'waning_gibbous_moon': [-1],
    'watch': [-1],
    'watermelon': [-1, -1],
    'wave': [2],
    'wavy_dash': [8],
    'waxing_crescent_moon': [-1],
    'waxing_gibbous_moon': [-1],
    'wc': [8],
    'weary': [1],
    'wedding': [7],
    'whale': [4],
    'wheelchair': [8],
    'white_check_mark': [8],
    'white_circle': [2, 8],
    'white_flower': [8],
    'white_frowning_face': [1],
    'white_large_square': [8],
    'white_medium_small_square': [8],
    'white_medium_square': [8],
    'white_small_square': [8],
    'white_square_button': [8],
    'wind_chime': [5, -1],
    'wine_glass': [-1, -1],
    'wink': [1],
    'wolf': [4],
    'woman': [1],
    'woman_bowing': [1],
    'woman_climbing': [1],
    'woman_facepalming': [1],
    'woman_frowning': [1],
    'woman_gesturing_no': [1],
    'woman_gesturing_ok': [1],
    'woman_getting_haircut': [1],
    'woman_getting_massage': [1],
    'woman_in_lotus_position': [1],
    'woman_in_steamy_room': [1],
    'woman_pouting': [1],
    'woman_raising_hand': [1],
    'woman_running': [1],
    'woman_shrugging': [1],
    'woman_tipping_hand': [1],
    'woman_walking': [1],
    'woman_wearing_turban': [1],
    'woman_with_bunny_ears_partying': [1],
    'womans_clothes': [-1, -1],
    'womans_hat': [-1, -1],
    'womens': [8],
    'worried': [1],
    'wrench': [-1, -1],
    'yen': [-1, -1],
    'yum': [1],
    'zany_face': [1],
    'zap': [3],
    'zero': [8],
    'zipper_mouth_face': [1]}
