
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

d_emoji_creature_rev_provenance = {
 'action': ['router.py',
            'plac_core.py',
            'csv2py_orchestrator.py',
            'emojis2py.py',
            'emoji_dict_writer.py',
            'common_utils.py'],
 'source': 'resources/data/csv/emojis.xlsx',
 'time': '2022-05-17 17:00:33.021958'}

d_emoji_creature_rev = {
    'adult': ['person'],
    'alien': ['alien'],
    'angel': ['angel'],
    'baby': ['baby'],
    'bear': ['bear'],
    'bearded_person': ['person'],
    'blond_haired_man': ['person'],
    'blond_haired_woman': ['person'],
    'boar': ['boar'],
    'boy': ['child'],
    'breast_feeding': ['person'],
    'bride_with_veil': ['person'],
    'camel': ['camel'],
    'cat': ['cat'],
    'child': ['child'],
    'cow': ['cow'],
    'crying_cat_face': ['cat'],
    'dancer': ['person'],
    'dog': ['dog'],
    'female_artist': ['person'],
    'female_astronaut': ['person'],
    'female_construction_worker': ['person'],
    'female_cook': ['person'],
    'female_detective': ['person'],
    'female_doctor': ['person'],
    'female_elf': ['elf'],
    'female_factory_worker': ['person'],
    'female_fairy': ['fairy'],
    'female_farmer': ['person'],
    'female_firefighter': ['person'],
    'female_genie': ['genie'],
    'female_guard': ['person'],
    'female_judge': ['person'],
    'female_mage': ['wizard'],
    'female_mechanic': ['person'],
    'female_office_worker': ['person'],
    'female_pilot': ['person'],
    'female_police_officer': ['person'],
    'female_scientist': ['person'],
    'female_singer': ['person'],
    'female_student': ['person'],
    'female_teacher': ['person'],
    'female_technologist': ['person'],
    'female_vampire': ['vampire'],
    'female_zombie': ['zombie'],
    'frog': ['frog'],
    'ghost': ['ghost'],
    'girl': ['child'],
    'hamster': ['hamster'],
    'hear_no_evil': ['monkey'],
    'heart_eyes_cat': ['cat'],
    'horse': ['horse'],
    'imp': ['imp'],
    'japanese_goblin': ['goblin'],
    'japanese_ogre': ['ogre'],
    'joy_cat': ['cat'],
    'kissing_cat': ['cat'],
    'koala': ['koala'],
    'male_artist': ['person'],
    'male_astronaut': ['person'],
    'male_construction_worker': ['person'],
    'male_cook': ['person'],
    'male_detective': ['person'],
    'male_doctor': ['person'],
    'male_elf': ['elf'],
    'male_factory_worker': ['person'],
    'male_fairy': ['fairy'],
    'male_farmer': ['person'],
    'male_firefighter': ['person'],
    'male_genie': ['genie'],
    'male_guard': ['person'],
    'male_judge': ['person'],
    'male_mage': ['wizard'],
    'male_mechanic': ['person'],
    'male_office_worker': ['person'],
    'male_pilot': ['person'],
    'male_police_officer': ['person'],
    'male_scientist': ['person'],
    'male_singer': ['person'],
    'male_student': ['person'],
    'male_teacher': ['person'],
    'male_technologist': ['person'],
    'male_vampire': ['vampire'],
    'male_zombie': ['zombie'],
    'man': ['person'],
    'man_bowing': ['person'],
    'man_climbing': ['person'],
    'man_dancing': ['person'],
    'man_facepalming': ['person'],
    'man_frowning': ['person'],
    'man_gesturing_no': ['person'],
    'man_gesturing_ok': ['person'],
    'man_getting_haircut': ['person'],
    'man_getting_massage': ['person'],
    'man_in_lotus_position': ['person'],
    'man_in_steamy_room': ['person'],
    'man_in_tuxedo': ['person'],
    'man_pouting': ['person'],
    'man_raising_hand': ['person'],
    'man_running': ['person'],
    'man_shrugging': ['person'],
    'man_tipping_hand': ['person'],
    'man_walking': ['person'],
    'man_wearing_turban': ['person'],
    'man_with_bunny_ears_partying': ['person'],
    'man_with_gua_pi_mao': ['person'],
    'mermaid': ['mermaid'],
    'merman': ['mermaid'],
    'monkey': ['monkey'],
    'monkey_face': ['monkey'],
    'mouse': ['mouse'],
    'mrs_claus': ['santa claus'],
    'older_adult': ['person'],
    'older_man': ['person'],
    'older_woman': ['person'],
    'person_with_headscarf': ['person'],
    'pig': ['pig'],
    'pig_nose': ['pig'],
    'pouting_cat': ['cat'],
    'pregnant_woman': ['person'],
    'prince': ['person'],
    'princess': ['person'],
    'rabbit': ['rabbit'],
    'racehorse': ['horse'],
    'robot_face': ['robot'],
    'santa': ['santa claus'],
    'scream_cat': ['cat'],
    'see_no_evil': ['monkey'],
    'sheep': ['sheep'],
    'skull': ['skull'],
    'skull_and_crossbones': ['skull'],
    'smile_cat': ['cat'],
    'smiley_cat': ['cat'],
    'smiling_imp': ['imp'],
    'smirk_cat': ['cat'],
    'space_invader': ['alien'],
    'speak_no_evil': ['monkey'],
    'tiger': ['tiger'],
    'wolf': ['wolf'],
    'woman': ['person'],
    'woman_bowing': ['person'],
    'woman_climbing': ['person'],
    'woman_facepalming': ['person'],
    'woman_frowning': ['person'],
    'woman_gesturing_no': ['person'],
    'woman_gesturing_ok': ['person'],
    'woman_getting_haircut': ['person'],
    'woman_getting_massage': ['person'],
    'woman_in_lotus_position': ['person'],
    'woman_in_steamy_room': ['person'],
    'woman_pouting': ['person'],
    'woman_raising_hand': ['person'],
    'woman_running': ['person'],
    'woman_shrugging': ['person'],
    'woman_tipping_hand': ['person'],
    'woman_walking': ['person'],
    'woman_wearing_turban': ['person'],
    'woman_with_bunny_ears_partying': ['person']}
