
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

d_emoji_tags_rev_provenance = {
 'action': ['router.py',
            'plac_core.py',
            'csv2py_orchestrator.py',
            'emojis2py.py',
            'emoji_dict_writer.py',
            'common_utils.py'],
 'source': 'resources/data/csv/emojis.xlsx',
 'time': '2022-05-17 17:00:33.109957'}

d_emoji_tags_rev = {
    '8ball': ['8ball', '8ball'],
    'ab': ['ab'],
    'abc': ['abc'],
    'abcd': ['abcd'],
    'accept': ['accept'],
    'adult': ['adult'],
    'alarm_clock': ['alarm', 'clock'],
    'alien': ['alien'],
    'angel': ['angel'],
    'angry': ['angry', 'angri'],
    'anguished': ['anguish', 'anguished'],
    'ant': ['ant'],
    'apple': ['appl', 'appl', 'apple', 'apple'],
    'aquarius': ['aquariu', 'aquarius'],
    'aries': ['ari', 'aries'],
    'arrow_backward': ['arrow', 'backward'],
    'arrow_double_down': ['down', 'arrow', 'doubl', 'double'],
    'arrow_double_up': ['arrow', 'up', 'doubl', 'double'],
    'arrow_down': ['down', 'arrow'],
    'arrow_down_small': ['down', 'arrow', 'small'],
    'arrow_forward': ['arrow', 'forward'],
    'arrow_heading_down': ['down', 'head', 'arrow', 'heading'],
    'arrow_heading_up': ['head', 'arrow', 'up', 'heading'],
    'arrow_left': ['arrow', 'left'],
    'arrow_lower_left': ['arrow', 'left', 'lower'],
    'arrow_lower_right': ['arrow', 'lower', 'right'],
    'arrow_right': ['arrow', 'right'],
    'arrow_right_hook': ['arrow', 'right', 'hook'],
    'arrow_up': ['arrow', 'up'],
    'arrow_up_down': ['down', 'arrow', 'up'],
    'arrow_up_small': ['arrow', 'up', 'small'],
    'arrow_upper_left': ['arrow', 'left', 'upper'],
    'arrow_upper_right': ['arrow', 'right', 'upper'],
    'arrows_clockwise': ['arrow', 'arrows', 'clockwis', 'clockwise'],
    'arrows_counterclockwise': [   'arrow',
                                   'arrows',
                                   'counterclockwis',
                                   'counterclockwise'],
    'art': ['art', 'art'],
    'astonished': ['astonish', 'astonished'],
    'baby': ['baby', 'babi'],
    'baby_bottle': [   'baby',
                       'baby',
                       'babi',
                       'babi',
                       'bottl',
                       'bottl',
                       'bottle',
                       'bottle'],
    'baby_chick': ['baby', 'babi', 'chick'],
    'baby_symbol': ['symbol', 'baby', 'babi'],
    'back': ['back'],
    'baggage_claim': ['claim', 'baggag', 'baggage'],
    'balloon': ['balloon', 'balloon'],
    'ballot_box_with_check': ['check', 'box', 'ballot'],
    'bamboo': ['bamboo'],
    'banana': ['banana', 'banana'],
    'bangbang': ['bangbang'],
    'bank': ['bank'],
    'bar_chart': ['chart', 'chart', 'bar', 'bar'],
    'baseball': ['basebal', 'basebal', 'baseball', 'baseball'],
    'basketball': ['basketbal', 'basketbal', 'basketball', 'basketball'],
    'bath': ['bath', 'bath'],
    'bathtub': ['bathtub', 'bathtub'],
    'battery': ['batteri', 'batteri', 'battery', 'battery'],
    'bear': ['bear'],
    'bearded_person': ['person', 'beard', 'bearded'],
    'beer': ['beer', 'beer'],
    'beers': ['beer', 'beer', 'beers', 'beers'],
    'beetle': ['beetl', 'beetle'],
    'bell': ['bell', 'bell'],
    'bento': ['bento', 'bento'],
    'bicyclist': ['bicyclist', 'bicyclist'],
    'bikini': ['bikini', 'bikini'],
    'bird': ['bird'],
    'birthday': ['birthday', 'birthday'],
    'black_circle': ['circl', 'circle', 'black'],
    'black_joker': ['black', 'black', 'joker', 'joker'],
    'black_large_square': ['larg', 'large', 'black', 'squar', 'square'],
    'black_medium_small_square': [   'small',
                                     'black',
                                     'squar',
                                     'square',
                                     'medium'],
    'black_medium_square': ['black', 'squar', 'square', 'medium'],
    'black_nib': ['black', 'black', 'nib', 'nib'],
    'black_small_square': ['small', 'black', 'squar', 'square'],
    'black_square_button': ['black', 'squar', 'button', 'square'],
    'blond_haired_man': ['man', 'hair', 'blond', 'haired'],
    'blond_haired_woman': ['woman', 'hair', 'blond', 'haired'],
    'blossom': ['blossom'],
    'blue_book': ['blue', 'blue', 'book', 'book'],
    'blush': ['blush'],
    'boar': ['boar'],
    'boat': ['boat'],
    'bomb': ['bomb', 'bomb'],
    'book': ['book', 'book'],
    'bookmark': ['bookmark', 'bookmark'],
    'bookmark_tabs': ['tab', 'tab', 'tabs', 'tabs', 'bookmark', 'bookmark'],
    'books': ['book', 'book', 'books', 'books'],
    'boot': ['boot', 'boot'],
    'bowling': ['bowl', 'bowl', 'bowling', 'bowling'],
    'boy': ['boy'],
    'bread': ['bread', 'bread'],
    'breast_feeding': ['feed', 'breast', 'feeding', 'breast fe', 'breast feed'],
    'bride_with_veil': ['veil', 'bride'],
    'bridge_at_night': ['bridg', 'night', 'bridge'],
    'briefcase': ['briefcas', 'briefcas', 'briefcase', 'briefcase'],
    'bug': ['bug'],
    'bulb': ['bulb', 'bulb', 'bulb'],
    'cactus': ['cactu', 'cactus'],
    'cake': ['cake', 'cake'],
    'calendar': ['calendar', 'calendar'],
    'calling': ['call', 'call', 'calling', 'calling'],
    'camel': ['camel'],
    'camera': ['camera', 'camera'],
    'cancer': ['cancer'],
    'candy': ['candi', 'candi', 'candy', 'candy'],
    'capital_abcd': ['abcd', 'capit', 'capital'],
    'capricorn': ['capricorn'],
    'card_index': ['card', 'card', 'index', 'index'],
    'carousel_horse': ['hors', 'horse', 'carousel'],
    'cat': ['cat'],
    'cd': ['cd', 'cd'],
    'chart': ['chart'],
    'chart_with_downwards_trend': [   'chart',
                                      'chart',
                                      'trend',
                                      'trend',
                                      'downward',
                                      'downward',
                                      'downwards',
                                      'downwards'],
    'chart_with_upwards_trend': [   'chart',
                                    'chart',
                                    'trend',
                                    'trend',
                                    'upward',
                                    'upward',
                                    'upwards',
                                    'upwards'],
    'cherries': ['cherri', 'cherri', 'cherries', 'cherries'],
    'chestnut': ['chestnut'],
    'chicken': ['chicken'],
    'child': ['child'],
    'children_crossing': ['cross', 'crossing', 'children'],
    'chocolate_bar': [   'bar',
                         'bar',
                         'chocol',
                         'chocol',
                         'chocolate',
                         'chocolate'],
    'christmas_tree': [   'tree',
                          'tree',
                          'christma',
                          'christma',
                          'christmas',
                          'christmas'],
    'church': ['church'],
    'cinema': ['cinema'],
    'cl': ['cl'],
    'clap': ['clap'],
    'clapper': ['clapper', 'clapper'],
    'clipboard': ['clipboard', 'clipboard'],
    'clock1': ['clock1'],
    'clock10': ['clock10'],
    'clock1030': ['clock1030'],
    'clock11': ['clock11'],
    'clock1130': ['clock1130'],
    'clock12': ['clock12'],
    'clock1230': ['clock1230'],
    'clock130': ['clock130'],
    'clock2': ['clock2'],
    'clock230': ['clock230'],
    'clock3': ['clock3'],
    'clock330': ['clock330'],
    'clock4': ['clock4'],
    'clock430': ['clock430'],
    'clock5': ['clock5'],
    'clock530': ['clock530'],
    'clock6': ['clock6'],
    'clock630': ['clock630'],
    'clock7': ['clock7'],
    'clock730': ['clock730'],
    'clock8': ['clock8'],
    'clock830': ['clock830'],
    'clock9': ['clock9'],
    'clock930': ['clock930'],
    'closed_book': ['close', 'close', 'closed', 'closed', 'book', 'book'],
    'closed_lock_with_key': [   'close',
                                'close',
                                'closed',
                                'closed',
                                'lock',
                                'lock',
                                'key',
                                'key'],
    'closed_umbrella': [   'close',
                           'close',
                           'closed',
                           'closed',
                           'umbrella',
                           'umbrella'],
    'cloud': ['cloud'],
    'clown_face': ['face', 'clown'],
    'clubs': ['club', 'club', 'clubs', 'clubs'],
    'cocktail': ['cocktail', 'cocktail'],
    'coffee': ['coffe', 'coffe', 'coffee', 'coffee'],
    'cold_sweat': ['sweat', 'cold'],
    'computer': ['comput', 'comput', 'computer', 'computer'],
    'confetti_ball': ['ball', 'ball', 'confetti', 'confetti'],
    'confounded': ['confound', 'confounded'],
    'confused': ['confus', 'confused'],
    'congratulations': ['congratul', 'congratulations'],
    'convenience_store': ['store', 'conveni', 'convenience'],
    'cookie': ['cooki', 'cooki', 'cookie', 'cookie'],
    'cool': ['cool'],
    'copyright': ['copyright'],
    'corn': ['corn', 'corn'],
    'cow': ['cow'],
    'credit_card': ['card', 'card', 'credit', 'credit'],
    'crescent_moon': ['moon', 'crescent'],
    'crown': ['crown', 'crown'],
    'cry': ['cry', 'cri'],
    'crying_cat_face': ['face', 'cri', 'cat', 'crying'],
    'crystal_ball': ['ball', 'ball', 'crystal', 'crystal'],
    'curly_loop': ['loop', 'curly', 'curli'],
    'currency_exchange': ['exchang', 'currenc', 'currency', 'exchange'],
    'curry': ['curry', 'curry', 'curri', 'curri'],
    'custard': ['custard', 'custard'],
    'customs': ['custom', 'customs'],
    'cyclone': ['cyclon', 'cyclone'],
    'dancer': ['party', 'parti', 'dancer'],
    'dango': ['dango', 'dango'],
    'dart': ['dart', 'dart', 'dart'],
    'date': ['date', 'date'],
    'deciduous_tree': ['tree', 'decidu', 'deciduous'],
    'department_store': ['store', 'depart', 'department'],
    'diamond_shape_with_a_dot_inside': [   'a',
                                           'dot',
                                           'insid',
                                           'shape',
                                           'inside',
                                           'diamond'],
    'diamonds': ['diamond', 'diamond', 'diamonds', 'diamonds'],
    'disappointed': ['disappoint', 'disappointed'],
    'disappointed_relieved': [   'reliev',
                                 'relieved',
                                 'disappoint',
                                 'disappointed'],
    'dizzy_face': ['face', 'dizzi', 'dizzy'],
    'do_not_litter': ['litter', 'do', 'not'],
    'dog': ['dog'],
    'dollar': ['dollar', 'dollar'],
    'dolls': ['doll', 'doll', 'dolls', 'dolls'],
    'dolphin': ['dolphin'],
    'door': ['door', 'door'],
    'doughnut': ['doughnut', 'doughnut'],
    'dress': ['dress', 'dress'],
    'drooling_face': ['face', 'drool', 'drooling'],
    'dvd': ['dvd', 'dvd'],
    'e-mail': ['e-mail', 'e-mail'],
    'ear_of_rice': ['ear', 'rice'],
    'earth_africa': ['earth', 'africa'],
    'earth_americas': ['earth', 'america', 'americas'],
    'earth_asia': ['earth', 'asia'],
    'egg': ['egg', 'egg'],
    'eggplant': ['eggplant', 'eggplant'],
    'eight': ['eight'],
    'eight_pointed_black_star': ['star', 'eight', 'black', 'point', 'pointed'],
    'eight_spoked_asterisk': ['eight', 'spoke', 'spoked', 'asterisk'],
    'electric_plug': [   'plug',
                         'plug',
                         'electr',
                         'electr',
                         'electric',
                         'electric'],
    'elephant': ['eleph', 'elephant'],
    'email': ['email', 'email'],
    'end': ['end'],
    'envelope': ['envelop', 'envelop', 'envelope', 'envelope'],
    'euro': ['euro', 'euro'],
    'evergreen_tree': ['tree', 'evergreen'],
    'exploding_head': ['head', 'explod', 'exploding'],
    'expressionless': ['expressionless'],
    'eyeglasses': ['eyeglass', 'eyeglass', 'eyeglasses', 'eyeglasses'],
    'eyes': ['eye', 'eyes'],
    'face_vomiting': ['face', 'vomit', 'vomiting'],
    'face_with_cowboy_hat': ['face', 'hat', 'cowboy'],
    'face_with_hand_over_mouth': ['face', 'mouth', 'hand', 'over'],
    'face_with_head_bandage': ['face', 'head', 'bandag', 'bandage'],
    'face_with_monocle': ['face', 'monocl', 'monocle'],
    'face_with_raised_eyebrow': ['face', 'rais', 'raised', 'eyebrow'],
    'face_with_rolling_eyes': ['roll', 'rolling', 'eye', 'eyes', 'face'],
    'face_with_symbols_on_mouth': ['face', 'mouth', 'symbol', 'symbols'],
    'face_with_thermometer': ['face', 'thermomet', 'thermometer'],
    'factory': ['factory', 'factori'],
    'fallen_leaf': ['leaf', 'fallen'],
    'fast_forward': ['forward', 'fast'],
    'fax': ['fax', 'fax'],
    'fearful': ['fear', 'fearful'],
    'female_artist': ['femal', 'female', 'artist'],
    'female_astronaut': ['femal', 'female', 'astronaut'],
    'female_construction_worker': [   'femal',
                                      'female',
                                      'worker',
                                      'construct',
                                      'construction'],
    'female_cook': ['femal', 'female', 'cook'],
    'female_detective': ['femal', 'female', 'detect', 'detective'],
    'female_doctor': ['doctor', 'femal', 'female'],
    'female_elf': ['femal', 'female', 'elf'],
    'female_factory_worker': [   'femal',
                                 'female',
                                 'worker',
                                 'factory',
                                 'factori'],
    'female_fairy': ['femal', 'female', 'fairy', 'fairi'],
    'female_farmer': ['femal', 'female', 'farmer'],
    'female_firefighter': ['femal', 'female', 'firefight', 'firefighter'],
    'female_genie': ['femal', 'female', 'geni', 'genie'],
    'female_guard': ['femal', 'female', 'guard'],
    'female_judge': ['femal', 'female', 'judg', 'judge'],
    'female_mage': ['femal', 'female', 'mage'],
    'female_mechanic': ['femal', 'female', 'mechan', 'mechanic'],
    'female_office_worker': [   'femal',
                                'female',
                                'worker',
                                'offic',
                                'clerk',
                                'office'],
    'female_pilot': ['femal', 'female', 'pilot'],
    'female_police_officer': [   'femal',
                                 'female',
                                 'offic',
                                 'polic',
                                 'police',
                                 'officer'],
    'female_scientist': ['femal', 'female', 'scientist'],
    'female_singer': ['femal', 'female', 'singer'],
    'female_student': ['femal', 'female', 'student'],
    'female_teacher': ['femal', 'female', 'teacher'],
    'female_technologist': ['nerd', 'femal', 'female', 'technologist'],
    'female_vampire': ['femal', 'female', 'vampir', 'vampire'],
    'female_zombie': ['femal', 'female', 'zombi', 'zombie'],
    'ferris_wheel': ['ferri', 'wheel', 'ferris'],
    'file_folder': ['file', 'file', 'folder', 'folder'],
    'fireworks': ['firework', 'firework', 'fireworks', 'fireworks'],
    'first_quarter_moon': ['moon', 'first', 'quarter'],
    'first_quarter_moon_with_face': ['face', 'moon', 'first', 'quarter'],
    'fish': ['fish'],
    'fish_cake': ['fish', 'fish', 'cake', 'cake'],
    'fishing_pole_and_fish': [   'and',
                                 'and',
                                 'fish',
                                 'fish',
                                 'pole',
                                 'pole',
                                 'fishing',
                                 'fishing'],
    'five': ['five'],
    'flags': ['flag', 'flag', 'flags', 'flags'],
    'flashlight': ['flashlight', 'flashlight'],
    'floppy_disk': ['disk', 'disk', 'floppi', 'floppi', 'floppy', 'floppy'],
    'flower_playing_cards': [   'flower',
                                'flower',
                                'card',
                                'card',
                                'play',
                                'play',
                                'cards',
                                'cards',
                                'playing',
                                'playing'],
    'flushed': ['flush', 'flushed'],
    'foggy': ['foggy', 'foggi'],
    'football': ['footbal', 'footbal', 'football', 'football'],
    'fork_and_knife': ['and', 'and', 'fork', 'fork', 'knife', 'knife'],
    'fountain': ['fountain'],
    'four': ['four'],
    'free': ['free'],
    'fried_shrimp': ['fri', 'fri', 'fried', 'fried', 'shrimp', 'shrimp'],
    'fries': ['fri', 'fri', 'fries', 'fries'],
    'frog': ['frog'],
    'frowning': ['frown', 'frowning'],
    'full_moon': ['full', 'moon'],
    'full_moon_with_face': ['face', 'full', 'moon'],
    'game_die': ['game', 'game', 'die', 'die'],
    'gem': ['gem', 'gem'],
    'gemini': ['gemini'],
    'ghost': ['ghost', 'ghost', 'ghost'],
    'gift': ['gift', 'gift'],
    'gift_heart': ['heart', 'heart', 'gift', 'gift'],
    'girl': ['girl'],
    'globe_with_meridians': ['globe', 'meridian', 'meridians'],
    'golf': ['golf', 'golf'],
    'grapes': ['grape', 'grape', 'grapes', 'grapes'],
    'green_apple': ['green', 'green', 'appl', 'appl', 'apple', 'apple'],
    'green_book': ['book', 'book', 'green', 'green'],
    'grimacing': ['grimac', 'grimacing'],
    'guitar': ['guitar', 'guitar'],
    'gun': ['gun', 'gun'],
    'hamburger': ['hamburg', 'hamburg', 'hamburger', 'hamburger'],
    'hammer': ['hammer', 'hammer'],
    'hamster': ['hamster'],
    'handbag': ['handbag', 'handbag'],
    'hankey': ['hankey'],
    'hash': ['hash'],
    'hatched_chick': ['chick', 'hatch', 'hatched'],
    'headphones': ['headphon', 'headphon', 'headphones', 'headphones'],
    'hear_no_evil': ['no', 'evil', 'hear'],
    'heart_decoration': ['heart', 'decor', 'decoration'],
    'heart_eyes': ['eye', 'eyes', 'heart'],
    'heart_eyes_cat': ['eye', 'eyes', 'heart', 'cat'],
    'hearts': ['heart', 'heart', 'hearts', 'hearts'],
    'heavy_check_mark': ['heavy', 'heavi', 'mark', 'check'],
    'heavy_division_sign': ['sign', 'heavy', 'heavi', 'divis', 'division'],
    'heavy_dollar_sign': ['sign', 'heavy', 'heavi', 'dollar'],
    'heavy_exclamation_mark': [   'heavy',
                                  'heavi',
                                  'mark',
                                  'exclam',
                                  'exclamation'],
    'heavy_minus_sign': ['sign', 'heavy', 'heavi', 'minu', 'minus'],
    'heavy_multiplication_x': [   'heavy',
                                  'heavi',
                                  'x',
                                  'multipl',
                                  'multiplication'],
    'heavy_plus_sign': [   'plu',
                           'plu',
                           'sign',
                           'sign',
                           'plus',
                           'plus',
                           'heavy',
                           'heavy',
                           'heavi',
                           'heavi'],
    'herb': ['herb'],
    'hibiscus': ['hibiscu', 'hibiscus'],
    'high_brightness': [   'high',
                           'high',
                           'bright',
                           'bright',
                           'brightness',
                           'brightness'],
    'high_heel': ['high', 'high', 'heel', 'heel'],
    'hocho': ['hocho', 'hocho'],
    'honey_pot': ['pot', 'pot', 'honey', 'honey'],
    'honeybee': ['honeybe', 'honeybee'],
    'horse': ['hors', 'horse'],
    'horse_racing': [   'hors',
                        'hors',
                        'horse',
                        'horse',
                        'race',
                        'race',
                        'racing',
                        'racing'],
    'hospital': ['hospit', 'hospital'],
    'hotel': ['hotel'],
    'hourglass': ['hourglass'],
    'hourglass_flowing_sand': ['hourglass', 'flow', 'sand', 'flowing'],
    'house': ['hous', 'house'],
    'house_with_garden': ['hous', 'house', 'garden'],
    'hugging_face': ['face', 'hug', 'hugging'],
    'hushed': ['hush', 'hushed'],
    'ice_cream': ['ice', 'ice', 'cream', 'cream'],
    'icecream': ['icecream', 'icecream'],
    'id': ['id'],
    'ideograph_advantage': ['advantag', 'ideograph', 'advantage'],
    'imp': ['imp'],
    'inbox_tray': ['tray', 'tray', 'inbox', 'inbox'],
    'incoming_envelope': [   'envelop',
                             'envelop',
                             'envelope',
                             'envelope',
                             'incom',
                             'incom',
                             'incoming',
                             'incoming'],
    'information_source': ['sourc', 'inform', 'source', 'information'],
    'innocent': ['innoc', 'innocent'],
    'interrobang': ['interrobang'],
    'iphone': ['iphon', 'iphone'],
    'jack_o_lantern': ['o', 'o', 'jack', 'jack', 'lantern', 'lantern'],
    'japan': ['japan'],
    'japanese_goblin': ['japanes', 'japanese', 'goblin'],
    'japanese_ogre': ['ogr', 'ogre', 'japanes', 'japanese'],
    'jeans': ['jean', 'jean', 'jeans', 'jeans'],
    'joy': ['joy'],
    'joy_cat': ['joy', 'cat'],
    'key': ['key', 'key'],
    'keycap_ten': ['ten', 'keycap'],
    'kimono': ['kimono', 'kimono'],
    'kissing': ['kiss', 'kissing'],
    'kissing_cat': ['kiss', 'kissing', 'cat'],
    'kissing_closed_eyes': [   'eye',
                               'eyes',
                               'kiss',
                               'kissing',
                               'close',
                               'closed'],
    'kissing_heart': ['heart', 'kiss', 'kissing'],
    'kissing_smiling_eyes': [   'smile',
                                'eye',
                                'eyes',
                                'kiss',
                                'kissing',
                                'smiling'],
    'koala': ['koala'],
    'koko': ['koko'],
    'large_blue_circle': [   'circl',
                             'circl',
                             'circle',
                             'circle',
                             'larg',
                             'larg',
                             'blue',
                             'blue',
                             'large',
                             'large'],
    'large_blue_diamond': ['larg', 'blue', 'large', 'diamond'],
    'large_orange_diamond': ['larg', 'large', 'diamond', 'orang', 'orange'],
    'last_quarter_moon': ['moon', 'quarter', 'last'],
    'last_quarter_moon_with_face': ['face', 'moon', 'quarter', 'last'],
    'leaves': ['leav', 'leaves'],
    'ledger': ['ledger', 'ledger'],
    'left_luggage': ['left', 'luggag', 'luggage'],
    'left_right_arrow': ['arrow', 'left', 'right'],
    'leftwards_arrow_with_hook': ['arrow', 'hook', 'leftward', 'leftwards'],
    'lemon': ['lemon', 'lemon'],
    'leo': ['leo'],
    'libra': ['libra'],
    'link': ['link'],
    'lipstick': ['lipstick', 'lipstick'],
    'lock': ['lock', 'lock'],
    'lock_with_ink_pen': ['lock', 'lock', 'pen', 'pen', 'ink', 'ink'],
    'lollipop': ['lollipop', 'lollipop'],
    'loop': ['loop', 'loop'],
    'loudspeaker': ['loudspeak', 'loudspeaker'],
    'low_brightness': [   'bright',
                          'bright',
                          'brightness',
                          'brightness',
                          'low',
                          'low'],
    'lying_face': ['face', 'lie', 'lying'],
    'mag': ['mag', 'mag'],
    'mag_right': ['right', 'right', 'mag', 'mag'],
    'mahjong': ['mahjong', 'mahjong'],
    'mailbox': ['mailbox', 'mailbox'],
    'mailbox_closed': [   'close',
                          'close',
                          'closed',
                          'closed',
                          'mailbox',
                          'mailbox'],
    'mailbox_with_mail': ['mailbox', 'mailbox', 'mail', 'mail'],
    'mailbox_with_no_mail': ['no', 'no', 'mailbox', 'mailbox', 'mail', 'mail'],
    'male_artist': ['male', 'artist'],
    'male_astronaut': ['male', 'astronaut'],
    'male_construction_worker': ['male', 'worker', 'construct', 'construction'],
    'male_cook': ['male', 'cook'],
    'male_detective': ['male', 'detect', 'detective'],
    'male_doctor': ['male', 'doctor'],
    'male_elf': ['male', 'elf'],
    'male_factory_worker': ['male', 'worker', 'factory', 'factori'],
    'male_fairy': ['male', 'fairy', 'fairi'],
    'male_farmer': ['male', 'farmer'],
    'male_firefighter': ['male', 'firefight', 'firefighter'],
    'male_genie': ['male', 'geni', 'genie'],
    'male_guard': ['male', 'guard'],
    'male_judge': ['male', 'judg', 'judge'],
    'male_mage': ['male', 'mage'],
    'male_mechanic': ['male', 'mechan', 'mechanic'],
    'male_office_worker': ['male', 'worker', 'offic', 'clerk', 'office'],
    'male_pilot': ['male', 'pilot'],
    'male_police_officer': ['male', 'offic', 'polic', 'police', 'officer'],
    'male_scientist': ['male', 'scientist'],
    'male_singer': ['male', 'singer'],
    'male_student': ['male', 'student'],
    'male_teacher': ['male', 'teacher'],
    'male_technologist': ['nerd', 'male', 'technologist'],
    'male_vampire': ['male', 'vampir', 'vampire'],
    'male_zombie': ['male', 'zombi', 'zombie'],
    'man': ['man'],
    'man_bowing': ['man', 'bow', 'bowing'],
    'man_climbing': ['man', 'exercis', 'exercise', 'climb', 'climbing'],
    'man_dancing': ['man', 'party', 'parti', 'danc', 'dancing'],
    'man_facepalming': ['man', 'facepalm', 'face palm', 'facepalming'],
    'man_frowning': ['frown', 'frowning', 'man'],
    'man_gesturing_no': ['no', 'man', 'gestur', 'gesturing'],
    'man_gesturing_ok': ['man', 'gestur', 'gesturing', 'ok'],
    'man_getting_haircut': ['man', 'get', 'getting', 'haircut'],
    'man_getting_massage': [   'relax',
                               'man',
                               'get',
                               'massag',
                               'massage',
                               'getting'],
    'man_in_lotus_position': [   'man',
                                 'lotu',
                                 'yoga',
                                 'lotus',
                                 'posit',
                                 'position'],
    'man_in_steamy_room': ['relax', 'man', 'room', 'steamy', 'steami'],
    'man_in_tuxedo': ['man', 'groom', 'tuxedo'],
    'man_pouting': ['pout', 'pouting', 'man'],
    'man_raising_hand': ['rais', 'hand', 'man', 'raising', 'raise hand'],
    'man_running': ['man', 'exercis', 'exercise', 'run', 'running'],
    'man_shrugging': ['man', 'shrug', 'shrugging'],
    'man_tipping_hand': ['hand', 'man', 'tip', 'tipping', 'tip hand'],
    'man_walking': ['man', 'walk', 'walking', 'exercis', 'exercise'],
    'man_wearing_turban': ['man', 'wear', 'turban', 'wearing'],
    'man_with_bunny_ears_partying': [   'man',
                                        'party',
                                        'parti',
                                        'ear',
                                        'ears',
                                        'bunni',
                                        'bunny',
                                        'partying'],
    'man_with_gua_pi_mao': ['man', 'pi', 'mao', 'gua', 'gua pi mao'],
    'mans_shoe': ['man', 'man', 'shoe', 'shoe', 'mans', 'mans'],
    'maple_leaf': ['leaf', 'mapl', 'maple'],
    'mask': ['mask'],
    'meat_on_bone': ['meat', 'meat', 'bone', 'bone'],
    'mega': ['mega', 'mega'],
    'melon': ['melon', 'melon'],
    'memo': ['memo', 'memo'],
    'mens': ['men', 'mens'],
    'mermaid': ['mermaid'],
    'merman': ['merman'],
    'metro': ['metro'],
    'microphone': ['microphon', 'microphon', 'microphone', 'microphone'],
    'microscope': ['microscop', 'microscop', 'microscope', 'microscope'],
    'milky_way': ['way', 'milki', 'milky'],
    'minidisc': ['minidisc', 'minidisc'],
    'mobile_phone_off': ['phone', 'mobil', 'mobile', 'off'],
    'money_mouth_face': ['face', 'mouth', 'money'],
    'money_with_wings': ['money', 'money', 'wing', 'wing', 'wings', 'wings'],
    'moneybag': ['moneybag', 'moneybag'],
    'monkey': ['monkey'],
    'monkey_face': ['face', 'monkey'],
    'mortar_board': ['board', 'board', 'mortar', 'mortar'],
    'mount_fuji': ['fuji', 'mount'],
    'mountain_bicyclist': ['mountain', 'mountain', 'bicyclist', 'bicyclist'],
    'mouse': ['mous', 'mouse'],
    'movie_camera': ['camera', 'camera', 'movi', 'movi', 'movie', 'movie'],
    'mrs_claus': ['mr', 'mrs', 'clau', 'claus'],
    'mushroom': ['mushroom'],
    'musical_keyboard': [   'music',
                            'music',
                            'musical',
                            'musical',
                            'keyboard',
                            'keyboard'],
    'musical_score': ['score', 'score', 'music', 'music', 'musical', 'musical'],
    'mute': ['mute'],
    'name_badge': ['badg', 'badg', 'name', 'name', 'badge', 'badge'],
    'nauseated_face': ['face', 'nauseat', 'nauseated'],
    'necktie': ['neckti', 'neckti', 'necktie', 'necktie'],
    'negative_squared_cross_mark': [   'cross',
                                       'neg',
                                       'mark',
                                       'squar',
                                       'squared',
                                       'negative'],
    'nerd_face': ['face', 'nerd'],
    'neutral_face': ['face', 'neutral'],
    'new': ['new'],
    'new_moon': ['new', 'moon'],
    'new_moon_with_face': ['face', 'new', 'moon'],
    'newspaper': ['newspap', 'newspap', 'newspaper', 'newspaper'],
    'ng': ['ng'],
    'nine': ['nine'],
    'no_bell': ['no', 'no', 'bell', 'bell'],
    'no_bicycles': ['no', 'bicycl', 'bicycles'],
    'no_entry': ['no', 'entry', 'entri'],
    'no_entry_sign': ['no', 'sign', 'entry', 'entri'],
    'no_mobile_phones': ['no', 'phone', 'mobil', 'mobile', 'phones'],
    'no_mouth': ['no', 'mouth'],
    'no_pedestrians': ['no', 'pedestrian', 'pedestrians'],
    'no_smoking': ['no', 'smoke', 'smoking'],
    'non-potable_water': ['water', 'non-pot', 'non-potable'],
    'notebook': ['notebook', 'notebook'],
    'notebook_with_decorative_cover': [   'decor',
                                          'decor',
                                          'notebook',
                                          'notebook',
                                          'cover',
                                          'cover',
                                          'decorative',
                                          'decorative'],
    'nut_and_bolt': ['and', 'and', 'nut', 'nut', 'bolt', 'bolt'],
    'o2': ['o2'],
    'objects': ['object', 'objects'],
    'ocean': ['ocean'],
    'octocat': ['octocat'],
    'octopus': ['octopu', 'octopus'],
    'oden': ['oden', 'oden'],
    'office': ['offic', 'office'],
    'ok': ['ok'],
    'older_adult': ['adult', 'older'],
    'older_man': ['man', 'older'],
    'older_woman': ['woman', 'older'],
    'one': ['one'],
    'open_file_folder': ['open', 'open', 'file', 'file', 'folder', 'folder'],
    'open_mouth': ['mouth', 'open'],
    'ophiuchus': ['ophiuchu', 'ophiuchus'],
    'orange_book': ['orang', 'orang', 'orange', 'orange', 'book', 'book'],
    'outbox_tray': ['tray', 'tray', 'outbox', 'outbox'],
    'package': ['packag', 'packag', 'package', 'package'],
    'page_facing_up': [   'face',
                          'face',
                          'up',
                          'up',
                          'page',
                          'page',
                          'facing',
                          'facing'],
    'page_with_curl': ['page', 'page', 'curl', 'curl'],
    'pager': ['pager', 'pager'],
    'palm_tree': ['tree', 'palm'],
    'panda_face': ['face', 'panda'],
    'paperclip': ['paperclip', 'paperclip'],
    'parking': ['park', 'parking'],
    'part_alternation_mark': ['mark', 'part', 'altern', 'alternation'],
    'partly_sunny': ['sunny', 'sunni', 'partli', 'partly'],
    'passport_control': ['control', 'passport'],
    'peach': ['peach', 'peach'],
    'pear': ['pear', 'pear'],
    'pencil': ['pencil', 'pencil'],
    'pencil2': ['pencil2', 'pencil2'],
    'penguin': ['penguin'],
    'pensive': ['pensiv', 'pensive'],
    'persevere': ['persever', 'persevere'],
    'person_with_headscarf': ['person', 'headscarf', 'head scarf'],
    'phone': ['phone', 'phone'],
    'pig': ['pig'],
    'pig_nose': ['pig', 'nose'],
    'pill': ['pill', 'pill'],
    'pineapple': ['pineappl', 'pineappl', 'pineapple', 'pineapple'],
    'pisces': ['pisc', 'pisces'],
    'pizza': ['pizza', 'pizza'],
    'post_office': ['offic', 'office', 'post'],
    'postal_horn': ['horn', 'horn', 'postal', 'postal'],
    'postbox': ['postbox', 'postbox'],
    'potable_water': ['water', 'potabl', 'potable'],
    'pouch': ['pouch', 'pouch'],
    'poultry_leg': ['leg', 'leg', 'poultry', 'poultry', 'poultri', 'poultri'],
    'pound': ['pound', 'pound'],
    'pouting_cat': ['cat', 'pout', 'pouting'],
    'pray': ['pray'],
    'pregnant_woman': ['woman', 'pregnant'],
    'prince': ['princ', 'prince'],
    'princess': ['princess'],
    'purse': ['purs', 'purs', 'purse', 'purse'],
    'pushpin': ['pushpin', 'pushpin'],
    'put_litter_in_its_place': ['it', 'its', 'put', 'place', 'litter'],
    'rabbit': ['rabbit'],
    'racehorse': ['racehors', 'racehorse'],
    'radio': ['radio'],
    'radio_button': ['radio', 'button'],
    'rage': ['rage'],
    'rainbow': ['rainbow'],
    'raised_hands': ['rais', 'raised', 'hand', 'hands'],
    'ramen': ['ramen', 'ramen'],
    'recycle': ['recycl', 'recycle'],
    'red_circle': ['circl', 'circl', 'circle', 'circle', 'red', 'red'],
    'registered': ['regist', 'registered'],
    'relaxed': ['relax', 'relaxed'],
    'relieved': ['reliev', 'relieved'],
    'repeat': ['repeat'],
    'repeat_one': ['one', 'repeat'],
    'restroom': ['restroom'],
    'rewind': ['rewind'],
    'ribbon': ['ribbon', 'ribbon'],
    'rice': ['rice', 'rice'],
    'rice_ball': ['ball', 'ball', 'rice', 'rice'],
    'rice_cracker': ['rice', 'rice', 'cracker', 'cracker'],
    'rice_scene': ['rice', 'scene'],
    'ring': ['ring', 'ring'],
    'robot_face': ['face', 'robot'],
    'roller_coaster': ['roller', 'coaster'],
    'rolling_on_the_floor_laughing': [   'roll',
                                         'laugh',
                                         'floor',
                                         'rolling',
                                         'laughing'],
    'rugby_football': [   'footbal',
                          'footbal',
                          'football',
                          'football',
                          'rugby',
                          'rugby',
                          'rugbi',
                          'rugbi'],
    'running_shirt_with_sash': [   'run',
                                   'run',
                                   'running',
                                   'running',
                                   'shirt',
                                   'shirt',
                                   'sash',
                                   'sash'],
    'sa': ['sa'],
    'sagittarius': ['sagittariu', 'sagittarius'],
    'sailboat': ['sailboat'],
    'sake': ['sake', 'sake'],
    'sandal': ['sandal', 'sandal'],
    'santa': ['santa', 'santa', 'santa'],
    'satellite': ['satellit', 'satellite'],
    'saxophone': ['saxophon', 'saxophon', 'saxophone', 'saxophone'],
    'school': ['school'],
    'school_satchel': ['school', 'school', 'satchel', 'satchel'],
    'scissors': ['scissor', 'scissor', 'scissors', 'scissors'],
    'scorpius': ['scorpiu', 'scorpius'],
    'scream': ['scream'],
    'scream_cat': ['scream', 'cat'],
    'scroll': ['scroll', 'scroll'],
    'seat': ['seat', 'seat'],
    'secret': ['secret'],
    'see_no_evil': ['no', 'see', 'evil'],
    'seedling': ['seedl', 'seedling'],
    'seven': ['seven'],
    'shaved_ice': ['ice', 'ice', 'shave', 'shave', 'shaved', 'shaved'],
    'sheep': ['sheep'],
    'shell': ['shell'],
    'ship': ['ship'],
    'shipit': ['shipit'],
    'shirt': ['shirt', 'shirt'],
    'shoe': ['shoe', 'shoe'],
    'shower': ['shower', 'shower'],
    'shushing_face': ['face', 'shush', 'shushing'],
    'signal_strength': ['signal', 'strength'],
    'six': ['six'],
    'six_pointed_star': ['star', 'six', 'point', 'pointed'],
    'ski': ['ski', 'ski'],
    'skull': ['skull'],
    'skull_and_crossbones': ['skull', 'and', 'crossbon', 'crossbones'],
    'sleeping': ['sleep', 'sleeping'],
    'sleepy': ['sleepy', 'sleepi'],
    'slightly_frowning_face': [   'face',
                                  'slightli',
                                  'slightly',
                                  'frown',
                                  'frowning'],
    'slightly_smiling_face': [   'smile',
                                 'smiling',
                                 'face',
                                 'slightli',
                                 'slightly'],
    'small_blue_diamond': ['blue', 'small', 'diamond'],
    'small_orange_diamond': ['small', 'diamond', 'orang', 'orange'],
    'small_red_triangle': ['red', 'small', 'triangl', 'triangle'],
    'small_red_triangle_down': ['down', 'red', 'small', 'triangl', 'triangle'],
    'smile': ['smile'],
    'smile_cat': ['smile', 'cat'],
    'smiley': ['smiley'],
    'smiley_cat': ['smiley', 'cat'],
    'smiling_imp': ['smile', 'smiling', 'imp'],
    'smirk': ['smirk'],
    'smirk_cat': ['smirk', 'cat'],
    'smoking': ['smoke', 'smoke', 'smoking', 'smoking'],
    'snail': ['snail'],
    'snake': ['snake'],
    'sneezing_face': ['face', 'sneez', 'sneezing'],
    'snowboarder': ['snowboard', 'snowboard', 'snowboarder', 'snowboarder'],
    'snowflake': ['snowflak', 'snowflake'],
    'snowman': ['snowman'],
    'sob': ['sob'],
    'soccer': ['soccer', 'soccer'],
    'soon': ['soon'],
    'sos': ['so', 'sos'],
    'sound': ['sound'],
    'space_invader': [   'space',
                         'space',
                         'space',
                         'invad',
                         'invad',
                         'invad',
                         'invader',
                         'invader',
                         'invader'],
    'spades': ['spade', 'spade', 'spades', 'spades'],
    'spaghetti': ['spaghetti', 'spaghetti'],
    'sparkle': ['sparkl', 'sparkle'],
    'sparkler': ['sparkler', 'sparkler'],
    'speak_no_evil': ['no', 'evil', 'speak'],
    'speaker': ['speaker'],
    'speedboat': ['speedboat'],
    'squirrel': ['squirrel'],
    'star_struck': ['star', 'galaxy', 'struck', 'galaxi', 'solar system'],
    'statue_of_liberty': ['statu', 'statue', 'liberti', 'liberty'],
    'stew': ['stew', 'stew'],
    'straight_ruler': ['ruler', 'ruler', 'straight', 'straight'],
    'strawberry': ['strawberry', 'strawberry', 'strawberri', 'strawberri'],
    'stuck_out_tongue': ['out', 'stuck', 'tongu', 'tongue'],
    'stuck_out_tongue_closed_eyes': [   'eye',
                                        'eyes',
                                        'close',
                                        'closed',
                                        'out',
                                        'stuck',
                                        'tongu',
                                        'tongue'],
    'stuck_out_tongue_winking_eye': [   'wink',
                                        'eye',
                                        'out',
                                        'stuck',
                                        'tongu',
                                        'tongue',
                                        'winking'],
    'sun_with_face': ['face', 'sun'],
    'sunglasses': ['sunglass', 'sunglasses'],
    'sunny': ['sunny', 'sunni'],
    'sunrise': ['sunris', 'sunrise'],
    'sunrise_over_mountains': [   'over',
                                  'sunris',
                                  'sunrise',
                                  'mountain',
                                  'mountains'],
    'surfer': ['surfer', 'surfer'],
    'sushi': ['sushi', 'sushi'],
    'sweat': ['sweat'],
    'sweat_smile': ['smile', 'sweat'],
    'sweet_potato': ['sweet', 'sweet', 'potato', 'potato'],
    'swimmer': ['swimmer', 'swimmer'],
    'symbols': ['symbol', 'symbols'],
    'syringe': ['syring', 'syring', 'syringe', 'syringe'],
    'tada': ['tada', 'tada', 'tada'],
    'tanabata_tree': ['tree', 'tree', 'tanabata', 'tanabata'],
    'tangerine': ['tangerin', 'tangerin', 'tangerine', 'tangerine'],
    'taurus': ['tauru', 'taurus'],
    'tea': ['tea', 'tea'],
    'telephone': ['telephon', 'telephon', 'telephone', 'telephone'],
    'telephone_receiver': [   'telephon',
                              'telephon',
                              'telephone',
                              'telephone',
                              'receiv',
                              'receiv',
                              'receiver',
                              'receiver'],
    'telescope': ['telescop', 'telescop', 'telescope', 'telescope'],
    'tennis': ['tenni', 'tenni', 'tennis', 'tennis'],
    'tent': ['tent'],
    'thinking_face': ['face', 'think', 'thinking'],
    'three': ['three'],
    'thumbsup': ['thumbsup'],
    'tiger': ['tiger'],
    'tired_face': ['face', 'tire', 'tired'],
    'tm': ['tm'],
    'toilet': ['toilet', 'toilet'],
    'tokyo_tower': ['tower', 'tokyo'],
    'tomato': ['tomato', 'tomato'],
    'top': ['top'],
    'tophat': ['tophat', 'tophat'],
    'triangular_ruler': ['ruler', 'ruler', 'triangular', 'triangular'],
    'trident': ['trident'],
    'triumph': ['triumph'],
    'trophy': ['trophi', 'trophi', 'trophy', 'trophy'],
    'tropical_drink': [   'tropic',
                          'tropic',
                          'tropical',
                          'tropical',
                          'drink',
                          'drink'],
    'tropical_fish': ['fish', 'tropic', 'tropical'],
    'trumpet': ['trumpet', 'trumpet'],
    'tshirt': ['tshirt', 'tshirt'],
    'turtle': ['turtl', 'turtle'],
    'tv': ['tv', 'tv'],
    'twisted_rightwards_arrows': [   'arrow',
                                     'arrows',
                                     'twist',
                                     'twisted',
                                     'rightward',
                                     'rightwards'],
    'two': ['two'],
    'u5272': ['u5272'],
    'u5408': ['u5408'],
    'u55b6': ['u55b6'],
    'u6307': ['u6307'],
    'u6708': ['u6708'],
    'u6709': ['u6709'],
    'u6e80': ['u6e80'],
    'u7121': ['u7121'],
    'u7533': ['u7533'],
    'u7981': ['u7981'],
    'u7a7a': ['u7a7a'],
    'umbrella': ['umbrella'],
    'unamused': ['unamus', 'unamused'],
    'underage': ['underag', 'underage'],
    'unlock': ['unlock', 'unlock'],
    'up': ['up'],
    'upside_down_face': ['face', 'down', 'upsid', 'upside'],
    'vhs': ['vh', 'vh', 'vhs', 'vhs'],
    'vibration_mode': ['mode', 'vibrat', 'vibration'],
    'video_camera': ['camera', 'camera', 'video', 'video'],
    'video_game': ['video', 'video', 'game', 'game'],
    'violin': ['violin', 'violin'],
    'virgo': ['virgo'],
    'volcano': ['volcano'],
    'vs': ['vs'],
    'waning_crescent_moon': ['moon', 'crescent', 'wane', 'waning'],
    'waning_gibbous_moon': ['moon', 'gibbou', 'gibbous', 'wane', 'waning'],
    'watch': ['watch'],
    'watermelon': ['watermelon', 'watermelon'],
    'wave': ['wave'],
    'wavy_dash': ['wavy', 'dash', 'wavi'],
    'waxing_crescent_moon': ['moon', 'wax', 'waxing', 'crescent'],
    'waxing_gibbous_moon': ['moon', 'wax', 'waxing', 'gibbou', 'gibbous'],
    'wc': ['wc'],
    'weary': ['weary', 'weari'],
    'wedding': ['wed', 'wedding'],
    'whale': ['whale'],
    'wheelchair': ['wheelchair'],
    'white_check_mark': ['white', 'mark', 'check'],
    'white_circle': ['white', 'white', 'circl', 'circl', 'circle', 'circle'],
    'white_flower': ['white', 'flower'],
    'white_frowning_face': ['face', 'white', 'frown', 'frowning'],
    'white_large_square': ['white', 'larg', 'large', 'squar', 'square'],
    'white_medium_small_square': [   'white',
                                     'small',
                                     'squar',
                                     'square',
                                     'medium'],
    'white_medium_square': ['white', 'squar', 'square', 'medium'],
    'white_small_square': ['white', 'small', 'squar', 'square'],
    'white_square_button': ['white', 'squar', 'button', 'square'],
    'wind_chime': ['wind', 'wind', 'chime', 'chime'],
    'wine_glass': ['wine', 'wine', 'glass', 'glass'],
    'wink': ['wink'],
    'wolf': ['wolf'],
    'woman': ['woman'],
    'woman_bowing': ['woman', 'bow', 'bowing'],
    'woman_climbing': ['woman', 'exercis', 'exercise', 'climb', 'climbing'],
    'woman_facepalming': ['woman', 'facepalm', 'face palm', 'facepalming'],
    'woman_frowning': ['frown', 'frowning', 'woman'],
    'woman_gesturing_no': ['no', 'woman', 'gestur', 'gesturing'],
    'woman_gesturing_ok': ['woman', 'gestur', 'gesturing', 'ok'],
    'woman_getting_haircut': ['woman', 'get', 'getting', 'haircut'],
    'woman_getting_massage': [   'relax',
                                 'woman',
                                 'get',
                                 'massag',
                                 'massage',
                                 'getting'],
    'woman_in_lotus_position': [   'woman',
                                   'lotu',
                                   'yoga',
                                   'lotus',
                                   'posit',
                                   'position'],
    'woman_in_steamy_room': ['relax', 'woman', 'room', 'steamy', 'steami'],
    'woman_pouting': ['pout', 'pouting', 'woman'],
    'woman_raising_hand': ['rais', 'hand', 'woman', 'raising', 'raise hand'],
    'woman_running': ['woman', 'exercis', 'exercise', 'run', 'running'],
    'woman_shrugging': ['woman', 'shrug', 'shrugging'],
    'woman_tipping_hand': ['hand', 'woman', 'tip', 'tipping', 'tip hand'],
    'woman_walking': ['woman', 'walk', 'walking', 'exercis', 'exercise'],
    'woman_wearing_turban': ['woman', 'wear', 'turban', 'wearing'],
    'woman_with_bunny_ears_partying': [   'woman',
                                          'party',
                                          'parti',
                                          'ear',
                                          'ears',
                                          'bunni',
                                          'bunny',
                                          'partying'],
    'womans_clothes': [   'woman',
                          'woman',
                          'cloth',
                          'cloth',
                          'womans',
                          'womans',
                          'clothes',
                          'clothes'],
    'womans_hat': ['hat', 'hat', 'woman', 'woman', 'womans', 'womans'],
    'womens': ['women', 'womens'],
    'worried': ['worri', 'worried'],
    'wrench': ['wrench', 'wrench'],
    'yen': ['yen', 'yen'],
    'yum': ['yum'],
    'zany_face': ['face', 'zany', 'zani'],
    'zap': ['zap'],
    'zero': ['zero'],
    'zipper_mouth_face': ['face', 'mouth', 'zipper']}
