
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

d_emoji_creature_fwd_provenance = {
 'action': ['router.py',
            'plac_core.py',
            'csv2py_orchestrator.py',
            'emojis2py.py',
            'emoji_dict_writer.py',
            'common_utils.py'],
 'source': 'resources/data/csv/emojis.xlsx',
 'time': '2022-05-17 17:00:33.019957'}

d_emoji_creature_fwd = {
    'alien': ['alien', 'space_invader'],
    'angel': ['angel'],
    'baby': ['baby'],
    'bear': ['bear'],
    'boar': ['boar'],
    'camel': ['camel'],
    'cat': [   'smiley_cat',
               'smile_cat',
               'joy_cat',
               'heart_eyes_cat',
               'smirk_cat',
               'kissing_cat',
               'scream_cat',
               'crying_cat_face',
               'pouting_cat',
               'cat'],
    'child': ['child', 'boy', 'girl'],
    'cow': ['cow'],
    'dog': ['dog'],
    'elf': ['female_elf', 'male_elf'],
    'fairy': ['female_fairy', 'male_fairy'],
    'frog': ['frog'],
    'genie': ['female_genie', 'male_genie'],
    'ghost': ['ghost'],
    'goblin': ['japanese_goblin'],
    'hamster': ['hamster'],
    'horse': ['horse', 'racehorse'],
    'imp': ['smiling_imp', 'imp'],
    'koala': ['koala'],
    'mermaid': ['mermaid', 'merman'],
    'monkey': [   'see_no_evil',
                  'hear_no_evil',
                  'speak_no_evil',
                  'monkey_face',
                  'monkey'],
    'mouse': ['mouse'],
    'ogre': ['japanese_ogre'],
    'person': [   'adult',
                  'man',
                  'woman',
                  'older_adult',
                  'older_man',
                  'older_woman',
                  'male_doctor',
                  'female_doctor',
                  'male_student',
                  'female_student',
                  'male_teacher',
                  'female_teacher',
                  'male_judge',
                  'female_judge',
                  'male_farmer',
                  'female_farmer',
                  'male_cook',
                  'female_cook',
                  'male_mechanic',
                  'female_mechanic',
                  'male_factory_worker',
                  'female_factory_worker',
                  'male_office_worker',
                  'female_office_worker',
                  'male_scientist',
                  'female_scientist',
                  'male_technologist',
                  'female_technologist',
                  'male_singer',
                  'female_singer',
                  'male_artist',
                  'female_artist',
                  'male_pilot',
                  'female_pilot',
                  'male_astronaut',
                  'female_astronaut',
                  'male_firefighter',
                  'female_firefighter',
                  'male_police_officer',
                  'female_police_officer',
                  'male_detective',
                  'female_detective',
                  'male_guard',
                  'female_guard',
                  'male_construction_worker',
                  'female_construction_worker',
                  'prince',
                  'princess',
                  'man_wearing_turban',
                  'woman_wearing_turban',
                  'man_with_gua_pi_mao',
                  'person_with_headscarf',
                  'bearded_person',
                  'blond_haired_man',
                  'blond_haired_woman',
                  'man_in_tuxedo',
                  'bride_with_veil',
                  'pregnant_woman',
                  'breast_feeding',
                  'man_frowning',
                  'woman_frowning',
                  'man_pouting',
                  'woman_pouting',
                  'man_gesturing_no',
                  'woman_gesturing_no',
                  'man_gesturing_ok',
                  'woman_gesturing_ok',
                  'man_tipping_hand',
                  'woman_tipping_hand',
                  'man_raising_hand',
                  'woman_raising_hand',
                  'man_bowing',
                  'woman_bowing',
                  'man_facepalming',
                  'woman_facepalming',
                  'man_shrugging',
                  'woman_shrugging',
                  'man_getting_massage',
                  'woman_getting_massage',
                  'man_getting_haircut',
                  'woman_getting_haircut',
                  'man_walking',
                  'woman_walking',
                  'man_running',
                  'woman_running',
                  'dancer',
                  'man_dancing',
                  'man_with_bunny_ears_partying',
                  'woman_with_bunny_ears_partying',
                  'woman_in_steamy_room',
                  'man_in_steamy_room',
                  'woman_climbing',
                  'man_climbing',
                  'woman_in_lotus_position',
                  'man_in_lotus_position'],
    'pig': ['pig', 'pig_nose'],
    'rabbit': ['rabbit'],
    'robot': ['robot_face'],
    'santa claus': ['santa', 'mrs_claus'],
    'sheep': ['sheep'],
    'skull': ['skull', 'skull_and_crossbones'],
    'tiger': ['tiger'],
    'vampire': ['female_vampire', 'male_vampire'],
    'wizard': ['female_mage', 'male_mage'],
    'wolf': ['wolf'],
    'zombie': ['female_zombie', 'male_zombie']}
