
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

d_emoji_gender_rev_provenance = {
 'action': ['router.py',
            'plac_core.py',
            'csv2py_orchestrator.py',
            'emojis2py.py',
            'emoji_dict_writer.py',
            'common_utils.py'],
 'source': 'resources/data/csv/emojis.xlsx',
 'time': '2022-05-17 17:00:33.017957'}

d_emoji_gender_rev = {
    '8ball': ['u', 'u'],
    'ab': ['u'],
    'abc': ['u'],
    'abcd': ['u'],
    'accept': ['u'],
    'adult': ['m'],
    'alarm_clock': ['u'],
    'alien': ['u'],
    'angel': ['u'],
    'angry': ['u'],
    'anguished': ['u'],
    'ant': ['u'],
    'apple': ['u', 'u'],
    'aquarius': ['u'],
    'aries': ['u'],
    'arrow_backward': ['u'],
    'arrow_double_down': ['u'],
    'arrow_double_up': ['u'],
    'arrow_down': ['u'],
    'arrow_down_small': ['u'],
    'arrow_forward': ['u'],
    'arrow_heading_down': ['u'],
    'arrow_heading_up': ['u'],
    'arrow_left': ['u'],
    'arrow_lower_left': ['u'],
    'arrow_lower_right': ['u'],
    'arrow_right': ['u'],
    'arrow_right_hook': ['u'],
    'arrow_up': ['u'],
    'arrow_up_down': ['u'],
    'arrow_up_small': ['u'],
    'arrow_upper_left': ['u'],
    'arrow_upper_right': ['u'],
    'arrows_clockwise': ['u'],
    'arrows_counterclockwise': ['u'],
    'art': ['u', 'u'],
    'astonished': ['u'],
    'baby': ['u'],
    'baby_bottle': ['u', 'u'],
    'baby_chick': ['u'],
    'baby_symbol': ['u'],
    'back': ['u'],
    'baggage_claim': ['u'],
    'balloon': ['u', 'u'],
    'ballot_box_with_check': ['u'],
    'bamboo': ['u'],
    'banana': ['u', 'u'],
    'bangbang': ['u'],
    'bank': ['u'],
    'bar_chart': ['u', 'u'],
    'baseball': ['u', 'u'],
    'basketball': ['u', 'u'],
    'bath': ['u', 'u'],
    'bathtub': ['u', 'u'],
    'battery': ['u', 'u'],
    'bear': ['u'],
    'bearded_person': ['m'],
    'beer': ['u', 'u'],
    'beers': ['u', 'u'],
    'beetle': ['u'],
    'bell': ['u', 'u'],
    'bento': ['u', 'u'],
    'bicyclist': ['u', 'u'],
    'bikini': ['u', 'u'],
    'bird': ['u'],
    'birthday': ['u', 'u'],
    'black_circle': ['u'],
    'black_joker': ['u', 'u'],
    'black_large_square': ['u'],
    'black_medium_small_square': ['u'],
    'black_medium_square': ['u'],
    'black_nib': ['u', 'u'],
    'black_small_square': ['u'],
    'black_square_button': ['u'],
    'blond_haired_man': ['m'],
    'blond_haired_woman': ['u'],
    'blossom': ['u'],
    'blue_book': ['u', 'u'],
    'blush': ['u'],
    'boar': ['u'],
    'boat': ['u'],
    'bomb': ['u', 'u'],
    'book': ['u', 'u'],
    'bookmark': ['u', 'u'],
    'bookmark_tabs': ['u', 'u'],
    'books': ['u', 'u'],
    'boot': ['u', 'u'],
    'bowling': ['u', 'u'],
    'boy': ['m'],
    'bread': ['u', 'u'],
    'breast_feeding': ['u'],
    'bride_with_veil': ['u'],
    'bridge_at_night': ['u'],
    'briefcase': ['u', 'u'],
    'bug': ['u'],
    'bulb': ['u', 'u', 'u'],
    'cactus': ['u'],
    'cake': ['u', 'u'],
    'calendar': ['u', 'u'],
    'calling': ['u', 'u'],
    'camel': ['u'],
    'camera': ['u', 'u'],
    'cancer': ['u'],
    'candy': ['u', 'u'],
    'capital_abcd': ['u'],
    'capricorn': ['u'],
    'card_index': ['u', 'u'],
    'carousel_horse': ['u'],
    'cat': ['u'],
    'cd': ['u', 'u'],
    'chart': ['u'],
    'chart_with_downwards_trend': ['u', 'u'],
    'chart_with_upwards_trend': ['u', 'u'],
    'cherries': ['u', 'u'],
    'chestnut': ['u'],
    'chicken': ['u'],
    'child': ['m'],
    'children_crossing': ['u'],
    'chocolate_bar': ['u', 'u'],
    'christmas_tree': ['u', 'u'],
    'church': ['u'],
    'cinema': ['u'],
    'cl': ['u'],
    'clap': ['u'],
    'clapper': ['u', 'u'],
    'clipboard': ['u', 'u'],
    'clock1': ['u'],
    'clock10': ['u'],
    'clock1030': ['u'],
    'clock11': ['u'],
    'clock1130': ['u'],
    'clock12': ['u'],
    'clock1230': ['u'],
    'clock130': ['u'],
    'clock2': ['u'],
    'clock230': ['u'],
    'clock3': ['u'],
    'clock330': ['u'],
    'clock4': ['u'],
    'clock430': ['u'],
    'clock5': ['u'],
    'clock530': ['u'],
    'clock6': ['u'],
    'clock630': ['u'],
    'clock7': ['u'],
    'clock730': ['u'],
    'clock8': ['u'],
    'clock830': ['u'],
    'clock9': ['u'],
    'clock930': ['u'],
    'closed_book': ['u', 'u'],
    'closed_lock_with_key': ['u', 'u'],
    'closed_umbrella': ['u', 'u'],
    'cloud': ['u'],
    'clown_face': ['u'],
    'clubs': ['u', 'u'],
    'cocktail': ['u', 'u'],
    'coffee': ['u', 'u'],
    'cold_sweat': ['u'],
    'computer': ['u', 'u'],
    'confetti_ball': ['u', 'u'],
    'confounded': ['u'],
    'confused': ['u'],
    'congratulations': ['u'],
    'convenience_store': ['u'],
    'cookie': ['u', 'u'],
    'cool': ['u'],
    'copyright': ['u'],
    'corn': ['u', 'u'],
    'cow': ['u'],
    'credit_card': ['u', 'u'],
    'crescent_moon': ['u'],
    'crown': ['u', 'u'],
    'cry': ['u'],
    'crying_cat_face': ['u'],
    'crystal_ball': ['u', 'u'],
    'curly_loop': ['u'],
    'currency_exchange': ['u'],
    'curry': ['u', 'u'],
    'custard': ['u', 'u'],
    'customs': ['u'],
    'cyclone': ['u'],
    'dancer': ['m'],
    'dango': ['u', 'u'],
    'dart': ['u', 'u', 'u'],
    'date': ['u', 'u'],
    'deciduous_tree': ['u'],
    'department_store': ['u'],
    'diamond_shape_with_a_dot_inside': ['u'],
    'diamonds': ['u', 'u'],
    'disappointed': ['u'],
    'disappointed_relieved': ['u'],
    'dizzy_face': ['u'],
    'do_not_litter': ['u'],
    'dog': ['u'],
    'dollar': ['u', 'u'],
    'dolls': ['u', 'u'],
    'dolphin': ['u'],
    'door': ['u', 'u'],
    'doughnut': ['u', 'u'],
    'dress': ['u', 'u'],
    'drooling_face': ['u'],
    'dvd': ['u', 'u'],
    'e-mail': ['u', 'u'],
    'ear_of_rice': ['u'],
    'earth_africa': ['u'],
    'earth_americas': ['u'],
    'earth_asia': ['u'],
    'egg': ['u', 'u'],
    'eggplant': ['u', 'u'],
    'eight': ['u'],
    'eight_pointed_black_star': ['u'],
    'eight_spoked_asterisk': ['u'],
    'electric_plug': ['u', 'u'],
    'elephant': ['u'],
    'email': ['u', 'u'],
    'end': ['u'],
    'envelope': ['u', 'u'],
    'euro': ['u', 'u'],
    'evergreen_tree': ['u'],
    'exploding_head': ['u'],
    'expressionless': ['u'],
    'eyeglasses': ['u', 'u'],
    'eyes': ['u'],
    'face_vomiting': ['u'],
    'face_with_cowboy_hat': ['u'],
    'face_with_hand_over_mouth': ['u'],
    'face_with_head_bandage': ['u'],
    'face_with_monocle': ['u'],
    'face_with_raised_eyebrow': ['u'],
    'face_with_rolling_eyes': ['u'],
    'face_with_symbols_on_mouth': ['u'],
    'face_with_thermometer': ['u'],
    'factory': ['u'],
    'fallen_leaf': ['u'],
    'fast_forward': ['u'],
    'fax': ['u', 'u'],
    'fearful': ['u'],
    'female_artist': ['f'],
    'female_astronaut': ['f'],
    'female_construction_worker': ['f'],
    'female_cook': ['f'],
    'female_detective': ['f'],
    'female_doctor': ['f'],
    'female_elf': ['u'],
    'female_factory_worker': ['f'],
    'female_fairy': ['u'],
    'female_farmer': ['f'],
    'female_firefighter': ['f'],
    'female_genie': ['u'],
    'female_guard': ['f'],
    'female_judge': ['f'],
    'female_mage': ['u'],
    'female_mechanic': ['f'],
    'female_office_worker': ['f'],
    'female_pilot': ['f'],
    'female_police_officer': ['f'],
    'female_scientist': ['f'],
    'female_singer': ['f'],
    'female_student': ['f'],
    'female_teacher': ['f'],
    'female_technologist': ['f'],
    'female_vampire': ['u'],
    'female_zombie': ['u'],
    'ferris_wheel': ['u'],
    'file_folder': ['u', 'u'],
    'fireworks': ['u', 'u'],
    'first_quarter_moon': ['u'],
    'first_quarter_moon_with_face': ['u'],
    'fish': ['u'],
    'fish_cake': ['u', 'u'],
    'fishing_pole_and_fish': ['u', 'u'],
    'five': ['u'],
    'flags': ['u', 'u'],
    'flashlight': ['u', 'u'],
    'floppy_disk': ['u', 'u'],
    'flower_playing_cards': ['u', 'u'],
    'flushed': ['u'],
    'foggy': ['u'],
    'football': ['u', 'u'],
    'fork_and_knife': ['u', 'u'],
    'fountain': ['u'],
    'four': ['u'],
    'free': ['u'],
    'fried_shrimp': ['u', 'u'],
    'fries': ['u', 'u'],
    'frog': ['u'],
    'frowning': ['u'],
    'full_moon': ['u'],
    'full_moon_with_face': ['u'],
    'game_die': ['u', 'u'],
    'gem': ['u', 'u'],
    'gemini': ['u'],
    'ghost': ['u', 'u', 'u'],
    'gift': ['u', 'u'],
    'gift_heart': ['u', 'u'],
    'girl': ['f'],
    'globe_with_meridians': ['u'],
    'golf': ['u', 'u'],
    'grapes': ['u', 'u'],
    'green_apple': ['u', 'u'],
    'green_book': ['u', 'u'],
    'grimacing': ['u'],
    'guitar': ['u', 'u'],
    'gun': ['u', 'u'],
    'hamburger': ['u', 'u'],
    'hammer': ['u', 'u'],
    'hamster': ['u'],
    'handbag': ['u', 'u'],
    'hankey': ['u'],
    'hash': ['u'],
    'hatched_chick': ['u'],
    'headphones': ['u', 'u'],
    'hear_no_evil': ['u'],
    'heart_decoration': ['u'],
    'heart_eyes': ['u'],
    'heart_eyes_cat': ['u'],
    'hearts': ['u', 'u'],
    'heavy_check_mark': ['u'],
    'heavy_division_sign': ['u'],
    'heavy_dollar_sign': ['u'],
    'heavy_exclamation_mark': ['u'],
    'heavy_minus_sign': ['u'],
    'heavy_multiplication_x': ['u'],
    'heavy_plus_sign': ['u', 'u'],
    'herb': ['u'],
    'hibiscus': ['u'],
    'high_brightness': ['u', 'u'],
    'high_heel': ['u', 'u'],
    'hocho': ['u', 'u'],
    'honey_pot': ['u', 'u'],
    'honeybee': ['u'],
    'horse': ['u'],
    'horse_racing': ['u', 'u'],
    'hospital': ['u'],
    'hotel': ['u'],
    'hourglass': ['u'],
    'hourglass_flowing_sand': ['u'],
    'house': ['u'],
    'house_with_garden': ['u'],
    'hugging_face': ['u'],
    'hushed': ['u'],
    'ice_cream': ['u', 'u'],
    'icecream': ['u', 'u'],
    'id': ['u'],
    'ideograph_advantage': ['u'],
    'imp': ['u'],
    'inbox_tray': ['u', 'u'],
    'incoming_envelope': ['u', 'u'],
    'information_source': ['u'],
    'innocent': ['u'],
    'interrobang': ['u'],
    'iphone': ['u'],
    'jack_o_lantern': ['u', 'u'],
    'japan': ['u'],
    'japanese_goblin': ['u'],
    'japanese_ogre': ['u'],
    'jeans': ['u', 'u'],
    'joy': ['u'],
    'joy_cat': ['u'],
    'key': ['u', 'u'],
    'keycap_ten': ['u'],
    'kimono': ['u', 'u'],
    'kissing': ['u'],
    'kissing_cat': ['u'],
    'kissing_closed_eyes': ['u'],
    'kissing_heart': ['u'],
    'kissing_smiling_eyes': ['u'],
    'koala': ['u'],
    'koko': ['u'],
    'large_blue_circle': ['u', 'u'],
    'large_blue_diamond': ['u'],
    'large_orange_diamond': ['u'],
    'last_quarter_moon': ['u'],
    'last_quarter_moon_with_face': ['u'],
    'leaves': ['u'],
    'ledger': ['u', 'u'],
    'left_luggage': ['u'],
    'left_right_arrow': ['u'],
    'leftwards_arrow_with_hook': ['u'],
    'lemon': ['u', 'u'],
    'leo': ['u'],
    'libra': ['u'],
    'link': ['u'],
    'lipstick': ['u', 'u'],
    'lock': ['u', 'u'],
    'lock_with_ink_pen': ['u', 'u'],
    'lollipop': ['u', 'u'],
    'loop': ['u', 'u'],
    'loudspeaker': ['u'],
    'low_brightness': ['u', 'u'],
    'lying_face': ['u'],
    'mag': ['u', 'u'],
    'mag_right': ['u', 'u'],
    'mahjong': ['u', 'u'],
    'mailbox': ['u', 'u'],
    'mailbox_closed': ['u', 'u'],
    'mailbox_with_mail': ['u', 'u'],
    'mailbox_with_no_mail': ['u', 'u'],
    'male_artist': ['m'],
    'male_astronaut': ['m'],
    'male_construction_worker': ['m'],
    'male_cook': ['m'],
    'male_detective': ['m'],
    'male_doctor': ['m'],
    'male_elf': ['m'],
    'male_factory_worker': ['m'],
    'male_fairy': ['m'],
    'male_farmer': ['m'],
    'male_firefighter': ['m'],
    'male_genie': ['m'],
    'male_guard': ['m'],
    'male_judge': ['m'],
    'male_mage': ['m'],
    'male_mechanic': ['m'],
    'male_office_worker': ['m'],
    'male_pilot': ['m'],
    'male_police_officer': ['m'],
    'male_scientist': ['m'],
    'male_singer': ['m'],
    'male_student': ['m'],
    'male_teacher': ['m'],
    'male_technologist': ['m'],
    'male_vampire': ['m'],
    'male_zombie': ['m'],
    'man': ['m'],
    'man_bowing': ['m'],
    'man_climbing': ['m'],
    'man_dancing': ['u'],
    'man_facepalming': ['m'],
    'man_frowning': ['u'],
    'man_gesturing_no': ['m'],
    'man_gesturing_ok': ['m'],
    'man_getting_haircut': ['m'],
    'man_getting_massage': ['m'],
    'man_in_lotus_position': ['m'],
    'man_in_steamy_room': ['m'],
    'man_in_tuxedo': ['m'],
    'man_pouting': ['u'],
    'man_raising_hand': ['m'],
    'man_running': ['m'],
    'man_shrugging': ['m'],
    'man_tipping_hand': ['m'],
    'man_walking': ['m'],
    'man_wearing_turban': ['m'],
    'man_with_bunny_ears_partying': ['m'],
    'man_with_gua_pi_mao': ['m'],
    'mans_shoe': ['u', 'u'],
    'maple_leaf': ['u'],
    'mask': ['u'],
    'meat_on_bone': ['u', 'u'],
    'mega': ['u', 'u'],
    'melon': ['u', 'u'],
    'memo': ['u', 'u'],
    'mens': ['u'],
    'mermaid': ['u'],
    'merman': ['m'],
    'metro': ['u'],
    'microphone': ['u', 'u'],
    'microscope': ['u', 'u'],
    'milky_way': ['u'],
    'minidisc': ['u', 'u'],
    'mobile_phone_off': ['u'],
    'money_mouth_face': ['u'],
    'money_with_wings': ['u', 'u'],
    'moneybag': ['u', 'u'],
    'monkey': ['u'],
    'monkey_face': ['u'],
    'mortar_board': ['u', 'u'],
    'mount_fuji': ['u'],
    'mountain_bicyclist': ['u', 'u'],
    'mouse': ['u'],
    'movie_camera': ['u', 'u'],
    'mrs_claus': ['u'],
    'mushroom': ['u'],
    'musical_keyboard': ['u', 'u'],
    'musical_score': ['u', 'u'],
    'mute': ['u'],
    'name_badge': ['u', 'u'],
    'nauseated_face': ['u'],
    'necktie': ['u', 'u'],
    'negative_squared_cross_mark': ['u'],
    'nerd_face': ['u'],
    'neutral_face': ['u'],
    'new': ['u'],
    'new_moon': ['u'],
    'new_moon_with_face': ['u'],
    'newspaper': ['u', 'u'],
    'ng': ['u'],
    'nine': ['u'],
    'no_bell': ['u', 'u'],
    'no_bicycles': ['u'],
    'no_entry': ['u'],
    'no_entry_sign': ['u'],
    'no_mobile_phones': ['u'],
    'no_mouth': ['u'],
    'no_pedestrians': ['u'],
    'no_smoking': ['u'],
    'non-potable_water': ['u'],
    'notebook': ['u', 'u'],
    'notebook_with_decorative_cover': ['u', 'u'],
    'nut_and_bolt': ['u', 'u'],
    'o2': ['u'],
    'objects': ['u'],
    'ocean': ['u'],
    'octocat': ['u'],
    'octopus': ['u'],
    'oden': ['u', 'u'],
    'office': ['u'],
    'ok': ['u'],
    'older_adult': ['m'],
    'older_man': ['m'],
    'older_woman': ['f'],
    'on': ['u'],
    'one': ['u'],
    'open_file_folder': ['u', 'u'],
    'open_mouth': ['u'],
    'ophiuchus': ['u'],
    'orange_book': ['u', 'u'],
    'outbox_tray': ['u', 'u'],
    'package': ['u', 'u'],
    'page_facing_up': ['u', 'u'],
    'page_with_curl': ['u', 'u'],
    'pager': ['u', 'u'],
    'palm_tree': ['u'],
    'panda_face': ['u'],
    'paperclip': ['u', 'u'],
    'parking': ['u'],
    'part_alternation_mark': ['u'],
    'partly_sunny': ['u'],
    'passport_control': ['u'],
    'peach': ['u', 'u'],
    'pear': ['u', 'u'],
    'pencil': ['u', 'u'],
    'pencil2': ['u', 'u'],
    'penguin': ['u'],
    'pensive': ['u'],
    'persevere': ['u'],
    'person_with_headscarf': ['f'],
    'phone': ['u', 'u'],
    'pig': ['u'],
    'pig_nose': ['u'],
    'pill': ['u', 'u'],
    'pineapple': ['u', 'u'],
    'pisces': ['u'],
    'pizza': ['u', 'u'],
    'post_office': ['u'],
    'postal_horn': ['u', 'u'],
    'postbox': ['u', 'u'],
    'potable_water': ['u'],
    'pouch': ['u', 'u'],
    'poultry_leg': ['u', 'u'],
    'pound': ['u', 'u'],
    'pouting_cat': ['u'],
    'pray': ['u'],
    'pregnant_woman': ['u'],
    'prince': ['m'],
    'princess': ['f'],
    'purse': ['u', 'u'],
    'pushpin': ['u', 'u'],
    'put_litter_in_its_place': ['u'],
    'rabbit': ['u'],
    'racehorse': ['u'],
    'radio': ['u'],
    'radio_button': ['u'],
    'rage': ['u'],
    'rainbow': ['u'],
    'raised_hands': ['u'],
    'ramen': ['u', 'u'],
    'recycle': ['u'],
    'red_circle': ['u', 'u'],
    'registered': ['u'],
    'relaxed': ['u'],
    'relieved': ['u'],
    'repeat': ['u'],
    'repeat_one': ['u'],
    'restroom': ['u'],
    'rewind': ['u'],
    'ribbon': ['u', 'u'],
    'rice': ['u', 'u'],
    'rice_ball': ['u', 'u'],
    'rice_cracker': ['u', 'u'],
    'rice_scene': ['u'],
    'ring': ['u', 'u'],
    'robot_face': ['u'],
    'roller_coaster': ['u'],
    'rolling_on_the_floor_laughing': ['u'],
    'rugby_football': ['u', 'u'],
    'running_shirt_with_sash': ['u', 'u'],
    'sa': ['u'],
    'sagittarius': ['u'],
    'sailboat': ['u'],
    'sake': ['u', 'u'],
    'sandal': ['u', 'u'],
    'santa': ['u', 'u', 'm'],
    'satellite': ['u'],
    'saxophone': ['u', 'u'],
    'school': ['u'],
    'school_satchel': ['u', 'u'],
    'scissors': ['u', 'u'],
    'scorpius': ['u'],
    'scream': ['u'],
    'scream_cat': ['u'],
    'scroll': ['u', 'u'],
    'seat': ['u', 'u'],
    'secret': ['u'],
    'see_no_evil': ['u'],
    'seedling': ['u'],
    'seven': ['u'],
    'shaved_ice': ['u', 'u'],
    'sheep': ['u'],
    'shell': ['u'],
    'ship': ['u'],
    'shipit': ['u'],
    'shirt': ['u', 'u'],
    'shoe': ['u', 'u'],
    'shower': ['u', 'u'],
    'shushing_face': ['u'],
    'signal_strength': ['u'],
    'six': ['u'],
    'six_pointed_star': ['u'],
    'ski': ['u', 'u'],
    'skull': ['u'],
    'skull_and_crossbones': ['u'],
    'sleeping': ['u'],
    'sleepy': ['u'],
    'slightly_frowning_face': ['u'],
    'slightly_smiling_face': ['u'],
    'small_blue_diamond': ['u'],
    'small_orange_diamond': ['u'],
    'small_red_triangle': ['u'],
    'small_red_triangle_down': ['u'],
    'smile': ['u'],
    'smile_cat': ['u'],
    'smiley': ['u'],
    'smiley_cat': ['u'],
    'smiling_imp': ['u'],
    'smirk': ['u'],
    'smirk_cat': ['u'],
    'smoking': ['u', 'u'],
    'snail': ['u'],
    'snake': ['u'],
    'sneezing_face': ['u'],
    'snowboarder': ['u', 'u'],
    'snowflake': ['u'],
    'snowman': ['u'],
    'sob': ['u'],
    'soccer': ['u', 'u'],
    'soon': ['u'],
    'sos': ['u'],
    'sound': ['u'],
    'space_invader': ['u', 'u', 'u'],
    'spades': ['u', 'u'],
    'spaghetti': ['u', 'u'],
    'sparkle': ['u'],
    'sparkler': ['u', 'u'],
    'speak_no_evil': ['u'],
    'speaker': ['u'],
    'speedboat': ['u'],
    'squirrel': ['u'],
    'star_struck': ['u'],
    'statue_of_liberty': ['u'],
    'stew': ['u', 'u'],
    'straight_ruler': ['u', 'u'],
    'strawberry': ['u', 'u'],
    'stuck_out_tongue': ['u'],
    'stuck_out_tongue_closed_eyes': ['u'],
    'stuck_out_tongue_winking_eye': ['u'],
    'sun_with_face': ['u'],
    'sunglasses': ['u'],
    'sunny': ['u'],
    'sunrise': ['u'],
    'sunrise_over_mountains': ['u'],
    'surfer': ['u', 'u'],
    'sushi': ['u', 'u'],
    'sweat': ['u'],
    'sweat_smile': ['u'],
    'sweet_potato': ['u', 'u'],
    'swimmer': ['u', 'u'],
    'symbols': ['u'],
    'syringe': ['u', 'u'],
    'tada': ['u', 'u', 'u'],
    'tanabata_tree': ['u', 'u'],
    'tangerine': ['u', 'u'],
    'taurus': ['u'],
    'tea': ['u', 'u'],
    'telephone': ['u', 'u'],
    'telephone_receiver': ['u', 'u'],
    'telescope': ['u', 'u'],
    'tennis': ['u', 'u'],
    'tent': ['u'],
    'thinking_face': ['u'],
    'three': ['u'],
    'thumbsup': ['u'],
    'tiger': ['u'],
    'tired_face': ['u'],
    'tm': ['u'],
    'toilet': ['u', 'u'],
    'tokyo_tower': ['u'],
    'tomato': ['u', 'u'],
    'top': ['u'],
    'tophat': ['u', 'u'],
    'triangular_ruler': ['u', 'u'],
    'trident': ['u'],
    'triumph': ['u'],
    'trophy': ['u', 'u'],
    'tropical_drink': ['u', 'u'],
    'tropical_fish': ['u'],
    'trumpet': ['u', 'u'],
    'tshirt': ['u', 'u'],
    'turtle': ['u'],
    'tv': ['u', 'u'],
    'twisted_rightwards_arrows': ['u'],
    'two': ['u'],
    'u5272': ['u'],
    'u5408': ['u'],
    'u55b6': ['u'],
    'u6307': ['u'],
    'u6708': ['u'],
    'u6709': ['u'],
    'u6e80': ['u'],
    'u7121': ['u'],
    'u7533': ['u'],
    'u7981': ['u'],
    'u7a7a': ['u'],
    'umbrella': ['u'],
    'unamused': ['u'],
    'underage': ['u'],
    'unlock': ['u', 'u'],
    'up': ['u'],
    'upside_down_face': ['u'],
    'vhs': ['u', 'u'],
    'vibration_mode': ['u'],
    'video_camera': ['u', 'u'],
    'video_game': ['u', 'u'],
    'violin': ['u', 'u'],
    'virgo': ['u'],
    'volcano': ['u'],
    'vs': ['u'],
    'waning_crescent_moon': ['u'],
    'waning_gibbous_moon': ['u'],
    'watch': ['u'],
    'watermelon': ['u', 'u'],
    'wave': ['u'],
    'wavy_dash': ['u'],
    'waxing_crescent_moon': ['u'],
    'waxing_gibbous_moon': ['u'],
    'wc': ['u'],
    'weary': ['u'],
    'wedding': ['u'],
    'whale': ['u'],
    'wheelchair': ['u'],
    'white_check_mark': ['u'],
    'white_circle': ['u', 'u'],
    'white_flower': ['u'],
    'white_frowning_face': ['u'],
    'white_large_square': ['u'],
    'white_medium_small_square': ['u'],
    'white_medium_square': ['u'],
    'white_small_square': ['u'],
    'white_square_button': ['u'],
    'wind_chime': ['u', 'u'],
    'wine_glass': ['u', 'u'],
    'wink': ['u'],
    'wolf': ['u'],
    'woman': ['f'],
    'woman_bowing': ['u'],
    'woman_climbing': ['u'],
    'woman_facepalming': ['u'],
    'woman_frowning': ['m'],
    'woman_gesturing_no': ['u'],
    'woman_gesturing_ok': ['u'],
    'woman_getting_haircut': ['u'],
    'woman_getting_massage': ['u'],
    'woman_in_lotus_position': ['u'],
    'woman_in_steamy_room': ['u'],
    'woman_pouting': ['u'],
    'woman_raising_hand': ['u'],
    'woman_running': ['u'],
    'woman_shrugging': ['u'],
    'woman_tipping_hand': ['u'],
    'woman_walking': ['u'],
    'woman_wearing_turban': ['f'],
    'woman_with_bunny_ears_partying': ['u'],
    'womans_clothes': ['u', 'u'],
    'womans_hat': ['u', 'u'],
    'womens': ['u'],
    'worried': ['u'],
    'wrench': ['u', 'u'],
    'yen': ['u', 'u'],
    'yum': ['u'],
    'zany_face': ['u'],
    'zap': ['u'],
    'zero': ['u'],
    'zipper_mouth_face': ['u']}
