
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

d_emoji_tags_fwd_provenance = {
 'action': ['router.py',
            'plac_core.py',
            'csv2py_orchestrator.py',
            'emojis2py.py',
            'emoji_dict_writer.py',
            'common_utils.py'],
 'source': 'resources/data/csv/emojis.xlsx',
 'time': '2022-05-17 17:00:33.036457'}

d_emoji_tags_fwd = {
    '8ball': ['8ball', '8ball'],
    'a': ['diamond_shape_with_a_dot_inside'],
    'ab': ['ab'],
    'abc': ['abc'],
    'abcd': ['capital_abcd', 'abcd'],
    'accept': ['accept'],
    'adult': ['adult', 'older_adult'],
    'advantag': ['ideograph_advantage'],
    'advantage': ['ideograph_advantage'],
    'africa': ['earth_africa'],
    'alarm': ['alarm_clock'],
    'alien': ['alien'],
    'altern': ['part_alternation_mark'],
    'alternation': ['part_alternation_mark'],
    'america': ['earth_americas'],
    'americas': ['earth_americas'],
    'and': [   'skull_and_crossbones',
               'nut_and_bolt',
               'fishing_pole_and_fish',
               'fork_and_knife',
               'nut_and_bolt',
               'fishing_pole_and_fish',
               'fork_and_knife'],
    'angel': ['angel'],
    'angri': ['angry'],
    'angry': ['angry'],
    'anguish': ['anguished'],
    'anguished': ['anguished'],
    'ant': ['ant'],
    'appl': ['apple', 'green_apple', 'apple', 'green_apple'],
    'apple': ['apple', 'green_apple', 'apple', 'green_apple'],
    'aquariu': ['aquarius'],
    'aquarius': ['aquarius'],
    'ari': ['aries'],
    'aries': ['aries'],
    'arrow': [   'arrow_backward',
                 'arrow_down',
                 'arrow_forward',
                 'arrow_left',
                 'arrow_lower_left',
                 'arrow_lower_right',
                 'arrow_right',
                 'arrow_up',
                 'arrow_upper_left',
                 'arrow_upper_right',
                 'arrow_double_down',
                 'arrow_double_up',
                 'arrow_down_small',
                 'arrow_heading_down',
                 'arrow_heading_up',
                 'leftwards_arrow_with_hook',
                 'arrow_right_hook',
                 'left_right_arrow',
                 'arrow_up_down',
                 'arrow_up_small',
                 'arrows_clockwise',
                 'arrows_counterclockwise',
                 'twisted_rightwards_arrows'],
    'arrows': [   'arrows_clockwise',
                  'arrows_counterclockwise',
                  'twisted_rightwards_arrows'],
    'art': ['art', 'art'],
    'artist': ['male_artist', 'female_artist'],
    'asia': ['earth_asia'],
    'asterisk': ['eight_spoked_asterisk'],
    'astonish': ['astonished'],
    'astonished': ['astonished'],
    'astronaut': ['male_astronaut', 'female_astronaut'],
    'babi': ['baby', 'baby_chick', 'baby_symbol', 'baby_bottle', 'baby_bottle'],
    'baby': ['baby', 'baby_chick', 'baby_symbol', 'baby_bottle', 'baby_bottle'],
    'back': ['back'],
    'backward': ['arrow_backward'],
    'badg': ['name_badge', 'name_badge'],
    'badge': ['name_badge', 'name_badge'],
    'baggag': ['baggage_claim'],
    'baggage': ['baggage_claim'],
    'ball': [   'confetti_ball',
                'crystal_ball',
                'rice_ball',
                'confetti_ball',
                'crystal_ball',
                'rice_ball'],
    'balloon': ['balloon', 'balloon'],
    'ballot': ['ballot_box_with_check'],
    'bamboo': ['bamboo'],
    'banana': ['banana', 'banana'],
    'bandag': ['face_with_head_bandage'],
    'bandage': ['face_with_head_bandage'],
    'bangbang': ['bangbang'],
    'bank': ['bank'],
    'bar': ['bar_chart', 'chocolate_bar', 'bar_chart', 'chocolate_bar'],
    'basebal': ['baseball', 'baseball'],
    'baseball': ['baseball', 'baseball'],
    'basketbal': ['basketball', 'basketball'],
    'basketball': ['basketball', 'basketball'],
    'bath': ['bath', 'bath'],
    'bathtub': ['bathtub', 'bathtub'],
    'batteri': ['battery', 'battery'],
    'battery': ['battery', 'battery'],
    'bear': ['bear'],
    'beard': ['bearded_person'],
    'bearded': ['bearded_person'],
    'beer': ['beer', 'beers', 'beer', 'beers'],
    'beers': ['beers', 'beers'],
    'beetl': ['beetle'],
    'beetle': ['beetle'],
    'bell': ['bell', 'no_bell', 'bell', 'no_bell'],
    'bento': ['bento', 'bento'],
    'bicycl': ['no_bicycles'],
    'bicycles': ['no_bicycles'],
    'bicyclist': [   'mountain_bicyclist',
                     'bicyclist',
                     'mountain_bicyclist',
                     'bicyclist'],
    'bikini': ['bikini', 'bikini'],
    'bird': ['bird'],
    'birthday': ['birthday', 'birthday'],
    'black': [   'eight_pointed_black_star',
                 'black_small_square',
                 'black_medium_small_square',
                 'black_medium_square',
                 'black_large_square',
                 'black_square_button',
                 'black_circle',
                 'black_nib',
                 'black_joker',
                 'black_nib',
                 'black_joker'],
    'blond': ['blond_haired_man', 'blond_haired_woman'],
    'blossom': ['blossom'],
    'blue': [   'large_blue_circle',
                'large_blue_circle',
                'large_blue_diamond',
                'small_blue_diamond',
                'blue_book',
                'blue_book'],
    'blush': ['blush'],
    'boar': ['boar'],
    'board': ['mortar_board', 'mortar_board'],
    'boat': ['boat'],
    'bolt': ['nut_and_bolt', 'nut_and_bolt'],
    'bomb': ['bomb', 'bomb'],
    'bone': ['meat_on_bone', 'meat_on_bone'],
    'book': [   'closed_book',
                'green_book',
                'blue_book',
                'orange_book',
                'books',
                'book',
                'closed_book',
                'green_book',
                'blue_book',
                'orange_book',
                'books',
                'book'],
    'bookmark': ['bookmark_tabs', 'bookmark', 'bookmark_tabs', 'bookmark'],
    'books': ['books', 'books'],
    'boot': ['boot', 'boot'],
    'bottl': ['baby_bottle', 'baby_bottle'],
    'bottle': ['baby_bottle', 'baby_bottle'],
    'bow': ['man_bowing', 'woman_bowing'],
    'bowing': ['man_bowing', 'woman_bowing'],
    'bowl': ['bowling', 'bowling'],
    'bowling': ['bowling', 'bowling'],
    'box': ['ballot_box_with_check'],
    'boy': ['boy'],
    'bread': ['bread', 'bread'],
    'breast': ['breast_feeding'],
    'breast fe': ['breast_feeding'],
    'breast feed': ['breast_feeding'],
    'bride': ['bride_with_veil'],
    'bridg': ['bridge_at_night'],
    'bridge': ['bridge_at_night'],
    'briefcas': ['briefcase', 'briefcase'],
    'briefcase': ['briefcase', 'briefcase'],
    'bright': [   'high_brightness',
                  'low_brightness',
                  'high_brightness',
                  'low_brightness'],
    'brightness': [   'high_brightness',
                      'low_brightness',
                      'high_brightness',
                      'low_brightness'],
    'bug': ['bug'],
    'bulb': ['bulb', 'bulb', 'bulb'],
    'bunni': ['man_with_bunny_ears_partying', 'woman_with_bunny_ears_partying'],
    'bunny': ['man_with_bunny_ears_partying', 'woman_with_bunny_ears_partying'],
    'button': ['radio_button', 'black_square_button', 'white_square_button'],
    'cactu': ['cactus'],
    'cactus': ['cactus'],
    'cake': ['fish_cake', 'cake', 'fish_cake', 'cake'],
    'calendar': ['calendar', 'calendar'],
    'call': ['calling', 'calling'],
    'calling': ['calling', 'calling'],
    'camel': ['camel'],
    'camera': [   'camera',
                  'video_camera',
                  'movie_camera',
                  'camera',
                  'video_camera',
                  'movie_camera'],
    'cancer': ['cancer'],
    'candi': ['candy', 'candy'],
    'candy': ['candy', 'candy'],
    'capit': ['capital_abcd'],
    'capital': ['capital_abcd'],
    'capricorn': ['capricorn'],
    'card': [   'credit_card',
                'card_index',
                'flower_playing_cards',
                'credit_card',
                'card_index',
                'flower_playing_cards'],
    'cards': ['flower_playing_cards', 'flower_playing_cards'],
    'carousel': ['carousel_horse'],
    'cat': [   'smiley_cat',
               'smile_cat',
               'joy_cat',
               'heart_eyes_cat',
               'smirk_cat',
               'kissing_cat',
               'scream_cat',
               'crying_cat_face',
               'pouting_cat',
               'cat'],
    'cd': ['cd', 'cd'],
    'chart': [   'chart',
                 'bar_chart',
                 'chart_with_upwards_trend',
                 'chart_with_downwards_trend',
                 'bar_chart',
                 'chart_with_upwards_trend',
                 'chart_with_downwards_trend'],
    'check': ['heavy_check_mark', 'ballot_box_with_check', 'white_check_mark'],
    'cherri': ['cherries', 'cherries'],
    'cherries': ['cherries', 'cherries'],
    'chestnut': ['chestnut'],
    'chick': ['baby_chick', 'hatched_chick'],
    'chicken': ['chicken'],
    'child': ['child'],
    'children': ['children_crossing'],
    'chime': ['wind_chime', 'wind_chime'],
    'chocol': ['chocolate_bar', 'chocolate_bar'],
    'chocolate': ['chocolate_bar', 'chocolate_bar'],
    'christma': ['christmas_tree', 'christmas_tree'],
    'christmas': ['christmas_tree', 'christmas_tree'],
    'church': ['church'],
    'cinema': ['cinema'],
    'circl': [   'white_circle',
                 'large_blue_circle',
                 'red_circle',
                 'black_circle',
                 'white_circle',
                 'red_circle',
                 'large_blue_circle'],
    'circle': [   'white_circle',
                  'large_blue_circle',
                  'red_circle',
                  'black_circle',
                  'white_circle',
                  'red_circle',
                  'large_blue_circle'],
    'cl': ['cl'],
    'claim': ['baggage_claim'],
    'clap': ['clap'],
    'clapper': ['clapper', 'clapper'],
    'clau': ['mrs_claus'],
    'claus': ['mrs_claus'],
    'clerk': ['male_office_worker', 'female_office_worker'],
    'climb': ['woman_climbing', 'man_climbing'],
    'climbing': ['woman_climbing', 'man_climbing'],
    'clipboard': ['clipboard', 'clipboard'],
    'clock': ['alarm_clock'],
    'clock1': ['clock1'],
    'clock10': ['clock10'],
    'clock1030': ['clock1030'],
    'clock11': ['clock11'],
    'clock1130': ['clock1130'],
    'clock12': ['clock12'],
    'clock1230': ['clock1230'],
    'clock130': ['clock130'],
    'clock2': ['clock2'],
    'clock230': ['clock230'],
    'clock3': ['clock3'],
    'clock330': ['clock330'],
    'clock4': ['clock4'],
    'clock430': ['clock430'],
    'clock5': ['clock5'],
    'clock530': ['clock530'],
    'clock6': ['clock6'],
    'clock630': ['clock630'],
    'clock7': ['clock7'],
    'clock730': ['clock730'],
    'clock8': ['clock8'],
    'clock830': ['clock830'],
    'clock9': ['clock9'],
    'clock930': ['clock930'],
    'clockwis': ['arrows_clockwise'],
    'clockwise': ['arrows_clockwise'],
    'close': [   'kissing_closed_eyes',
                 'stuck_out_tongue_closed_eyes',
                 'closed_lock_with_key',
                 'mailbox_closed',
                 'closed_book',
                 'closed_umbrella',
                 'closed_lock_with_key',
                 'mailbox_closed',
                 'closed_book',
                 'closed_umbrella'],
    'closed': [   'kissing_closed_eyes',
                  'stuck_out_tongue_closed_eyes',
                  'closed_lock_with_key',
                  'mailbox_closed',
                  'closed_book',
                  'closed_umbrella',
                  'closed_lock_with_key',
                  'mailbox_closed',
                  'closed_book',
                  'closed_umbrella'],
    'cloth': ['womans_clothes', 'womans_clothes'],
    'clothes': ['womans_clothes', 'womans_clothes'],
    'cloud': ['cloud'],
    'clown': ['clown_face'],
    'club': ['clubs', 'clubs'],
    'clubs': ['clubs', 'clubs'],
    'coaster': ['roller_coaster'],
    'cocktail': ['cocktail', 'cocktail'],
    'coffe': ['coffee', 'coffee'],
    'coffee': ['coffee', 'coffee'],
    'cold': ['cold_sweat'],
    'comput': ['computer', 'computer'],
    'computer': ['computer', 'computer'],
    'confetti': ['confetti_ball', 'confetti_ball'],
    'confound': ['confounded'],
    'confounded': ['confounded'],
    'confus': ['confused'],
    'confused': ['confused'],
    'congratul': ['congratulations'],
    'congratulations': ['congratulations'],
    'construct': ['male_construction_worker', 'female_construction_worker'],
    'construction': ['male_construction_worker', 'female_construction_worker'],
    'control': ['passport_control'],
    'conveni': ['convenience_store'],
    'convenience': ['convenience_store'],
    'cook': ['male_cook', 'female_cook'],
    'cooki': ['cookie', 'cookie'],
    'cookie': ['cookie', 'cookie'],
    'cool': ['cool'],
    'copyright': ['copyright'],
    'corn': ['corn', 'corn'],
    'counterclockwis': ['arrows_counterclockwise'],
    'counterclockwise': ['arrows_counterclockwise'],
    'cover': [   'notebook_with_decorative_cover',
                 'notebook_with_decorative_cover'],
    'cow': ['cow'],
    'cowboy': ['face_with_cowboy_hat'],
    'cracker': ['rice_cracker', 'rice_cracker'],
    'cream': ['ice_cream', 'ice_cream'],
    'credit': ['credit_card', 'credit_card'],
    'crescent': [   'waxing_crescent_moon',
                    'waning_crescent_moon',
                    'crescent_moon'],
    'cri': ['cry', 'crying_cat_face'],
    'cross': ['children_crossing', 'negative_squared_cross_mark'],
    'crossbon': ['skull_and_crossbones'],
    'crossbones': ['skull_and_crossbones'],
    'crossing': ['children_crossing'],
    'crown': ['crown', 'crown'],
    'cry': ['cry'],
    'crying': ['crying_cat_face'],
    'crystal': ['crystal_ball', 'crystal_ball'],
    'curl': ['page_with_curl', 'page_with_curl'],
    'curli': ['curly_loop'],
    'curly': ['curly_loop'],
    'currenc': ['currency_exchange'],
    'currency': ['currency_exchange'],
    'curri': ['curry', 'curry'],
    'curry': ['curry', 'curry'],
    'custard': ['custard', 'custard'],
    'custom': ['customs'],
    'customs': ['customs'],
    'cyclon': ['cyclone'],
    'cyclone': ['cyclone'],
    'danc': ['man_dancing'],
    'dancer': ['dancer'],
    'dancing': ['man_dancing'],
    'dango': ['dango', 'dango'],
    'dart': ['dart', 'dart', 'dart'],
    'dash': ['wavy_dash'],
    'date': ['date', 'date'],
    'decidu': ['deciduous_tree'],
    'deciduous': ['deciduous_tree'],
    'decor': [   'heart_decoration',
                 'notebook_with_decorative_cover',
                 'notebook_with_decorative_cover'],
    'decoration': ['heart_decoration'],
    'decorative': [   'notebook_with_decorative_cover',
                      'notebook_with_decorative_cover'],
    'depart': ['department_store'],
    'department': ['department_store'],
    'detect': ['male_detective', 'female_detective'],
    'detective': ['male_detective', 'female_detective'],
    'diamond': [   'diamond_shape_with_a_dot_inside',
                   'large_blue_diamond',
                   'large_orange_diamond',
                   'small_blue_diamond',
                   'small_orange_diamond',
                   'diamonds',
                   'diamonds'],
    'diamonds': ['diamonds', 'diamonds'],
    'die': ['game_die', 'game_die'],
    'disappoint': ['disappointed_relieved', 'disappointed'],
    'disappointed': ['disappointed_relieved', 'disappointed'],
    'disk': ['floppy_disk', 'floppy_disk'],
    'divis': ['heavy_division_sign'],
    'division': ['heavy_division_sign'],
    'dizzi': ['dizzy_face'],
    'dizzy': ['dizzy_face'],
    'do': ['do_not_litter'],
    'doctor': ['male_doctor', 'female_doctor'],
    'dog': ['dog'],
    'doll': ['dolls', 'dolls'],
    'dollar': ['heavy_dollar_sign', 'dollar', 'dollar'],
    'dolls': ['dolls', 'dolls'],
    'dolphin': ['dolphin'],
    'door': ['door', 'door'],
    'dot': ['diamond_shape_with_a_dot_inside'],
    'doubl': ['arrow_double_down', 'arrow_double_up'],
    'double': ['arrow_double_down', 'arrow_double_up'],
    'doughnut': ['doughnut', 'doughnut'],
    'down': [   'upside_down_face',
                'arrow_down',
                'arrow_double_down',
                'arrow_down_small',
                'arrow_heading_down',
                'arrow_up_down',
                'small_red_triangle_down'],
    'downward': ['chart_with_downwards_trend', 'chart_with_downwards_trend'],
    'downwards': ['chart_with_downwards_trend', 'chart_with_downwards_trend'],
    'dress': ['dress', 'dress'],
    'drink': ['tropical_drink', 'tropical_drink'],
    'drool': ['drooling_face'],
    'drooling': ['drooling_face'],
    'dvd': ['dvd', 'dvd'],
    'e-mail': ['e-mail', 'e-mail'],
    'ear': [   'man_with_bunny_ears_partying',
               'woman_with_bunny_ears_partying',
               'ear_of_rice'],
    'ears': ['man_with_bunny_ears_partying', 'woman_with_bunny_ears_partying'],
    'earth': ['earth_africa', 'earth_americas', 'earth_asia'],
    'egg': ['egg', 'egg'],
    'eggplant': ['eggplant', 'eggplant'],
    'eight': ['eight', 'eight_spoked_asterisk', 'eight_pointed_black_star'],
    'electr': ['electric_plug', 'electric_plug'],
    'electric': ['electric_plug', 'electric_plug'],
    'eleph': ['elephant'],
    'elephant': ['elephant'],
    'elf': ['female_elf', 'male_elf'],
    'email': ['email', 'email'],
    'end': ['end'],
    'entri': ['no_entry_sign', 'no_entry'],
    'entry': ['no_entry_sign', 'no_entry'],
    'envelop': [   'envelope',
                   'incoming_envelope',
                   'envelope',
                   'incoming_envelope'],
    'envelope': [   'envelope',
                    'incoming_envelope',
                    'envelope',
                    'incoming_envelope'],
    'euro': ['euro', 'euro'],
    'evergreen': ['evergreen_tree'],
    'evil': ['see_no_evil', 'hear_no_evil', 'speak_no_evil'],
    'exchang': ['currency_exchange'],
    'exchange': ['currency_exchange'],
    'exclam': ['heavy_exclamation_mark'],
    'exclamation': ['heavy_exclamation_mark'],
    'exercis': [   'man_walking',
                   'woman_walking',
                   'man_running',
                   'woman_running',
                   'woman_climbing',
                   'man_climbing'],
    'exercise': [   'man_walking',
                    'woman_walking',
                    'man_running',
                    'woman_running',
                    'woman_climbing',
                    'man_climbing'],
    'explod': ['exploding_head'],
    'exploding': ['exploding_head'],
    'expressionless': ['expressionless'],
    'eye': [   'heart_eyes',
               'kissing_smiling_eyes',
               'kissing_closed_eyes',
               'face_with_rolling_eyes',
               'stuck_out_tongue_winking_eye',
               'stuck_out_tongue_closed_eyes',
               'heart_eyes_cat',
               'eyes'],
    'eyebrow': ['face_with_raised_eyebrow'],
    'eyeglass': ['eyeglasses', 'eyeglasses'],
    'eyeglasses': ['eyeglasses', 'eyeglasses'],
    'eyes': [   'heart_eyes',
                'kissing_smiling_eyes',
                'kissing_closed_eyes',
                'face_with_rolling_eyes',
                'stuck_out_tongue_closed_eyes',
                'heart_eyes_cat',
                'eyes'],
    'face': [   'slightly_smiling_face',
                'hugging_face',
                'thinking_face',
                'face_with_raised_eyebrow',
                'neutral_face',
                'face_with_rolling_eyes',
                'zipper_mouth_face',
                'tired_face',
                'drooling_face',
                'upside_down_face',
                'money_mouth_face',
                'white_frowning_face',
                'slightly_frowning_face',
                'zany_face',
                'dizzy_face',
                'face_with_symbols_on_mouth',
                'face_with_thermometer',
                'face_with_head_bandage',
                'nauseated_face',
                'face_vomiting',
                'sneezing_face',
                'face_with_cowboy_hat',
                'clown_face',
                'lying_face',
                'shushing_face',
                'face_with_hand_over_mouth',
                'face_with_monocle',
                'nerd_face',
                'robot_face',
                'crying_cat_face',
                'monkey_face',
                'panda_face',
                'page_facing_up',
                'sun_with_face',
                'full_moon_with_face',
                'new_moon_with_face',
                'last_quarter_moon_with_face',
                'first_quarter_moon_with_face',
                'page_facing_up'],
    'face palm': ['man_facepalming', 'woman_facepalming'],
    'facepalm': ['man_facepalming', 'woman_facepalming'],
    'facepalming': ['man_facepalming', 'woman_facepalming'],
    'facing': ['page_facing_up', 'page_facing_up'],
    'factori': ['male_factory_worker', 'female_factory_worker', 'factory'],
    'factory': ['male_factory_worker', 'female_factory_worker', 'factory'],
    'fairi': ['female_fairy', 'male_fairy'],
    'fairy': ['female_fairy', 'male_fairy'],
    'fallen': ['fallen_leaf'],
    'farmer': ['male_farmer', 'female_farmer'],
    'fast': ['fast_forward'],
    'fax': ['fax', 'fax'],
    'fear': ['fearful'],
    'fearful': ['fearful'],
    'feed': ['breast_feeding'],
    'feeding': ['breast_feeding'],
    'femal': [   'female_doctor',
                 'female_student',
                 'female_teacher',
                 'female_judge',
                 'female_farmer',
                 'female_cook',
                 'female_mechanic',
                 'female_factory_worker',
                 'female_office_worker',
                 'female_scientist',
                 'female_technologist',
                 'female_singer',
                 'female_artist',
                 'female_pilot',
                 'female_astronaut',
                 'female_firefighter',
                 'female_police_officer',
                 'female_detective',
                 'female_guard',
                 'female_construction_worker',
                 'female_mage',
                 'female_fairy',
                 'female_vampire',
                 'female_elf',
                 'female_genie',
                 'female_zombie'],
    'female': [   'female_doctor',
                  'female_student',
                  'female_teacher',
                  'female_judge',
                  'female_farmer',
                  'female_cook',
                  'female_mechanic',
                  'female_factory_worker',
                  'female_office_worker',
                  'female_scientist',
                  'female_technologist',
                  'female_singer',
                  'female_artist',
                  'female_pilot',
                  'female_astronaut',
                  'female_firefighter',
                  'female_police_officer',
                  'female_detective',
                  'female_guard',
                  'female_construction_worker',
                  'female_mage',
                  'female_fairy',
                  'female_vampire',
                  'female_elf',
                  'female_genie',
                  'female_zombie'],
    'ferri': ['ferris_wheel'],
    'ferris': ['ferris_wheel'],
    'file': [   'file_folder',
                'open_file_folder',
                'file_folder',
                'open_file_folder'],
    'firefight': ['male_firefighter', 'female_firefighter'],
    'firefighter': ['male_firefighter', 'female_firefighter'],
    'firework': ['fireworks', 'fireworks'],
    'fireworks': ['fireworks', 'fireworks'],
    'first': ['first_quarter_moon', 'first_quarter_moon_with_face'],
    'fish': [   'tropical_fish',
                'fish',
                'fishing_pole_and_fish',
                'fish_cake',
                'fishing_pole_and_fish',
                'fish_cake'],
    'fishing': ['fishing_pole_and_fish', 'fishing_pole_and_fish'],
    'five': ['five'],
    'flag': ['flags', 'flags'],
    'flags': ['flags', 'flags'],
    'flashlight': ['flashlight', 'flashlight'],
    'floor': ['rolling_on_the_floor_laughing'],
    'floppi': ['floppy_disk', 'floppy_disk'],
    'floppy': ['floppy_disk', 'floppy_disk'],
    'flow': ['hourglass_flowing_sand'],
    'flower': ['white_flower', 'flower_playing_cards', 'flower_playing_cards'],
    'flowing': ['hourglass_flowing_sand'],
    'flush': ['flushed'],
    'flushed': ['flushed'],
    'foggi': ['foggy'],
    'foggy': ['foggy'],
    'folder': [   'file_folder',
                  'open_file_folder',
                  'file_folder',
                  'open_file_folder'],
    'footbal': ['football', 'rugby_football', 'football', 'rugby_football'],
    'football': ['football', 'rugby_football', 'football', 'rugby_football'],
    'fork': ['fork_and_knife', 'fork_and_knife'],
    'forward': ['arrow_forward', 'fast_forward'],
    'fountain': ['fountain'],
    'four': ['four'],
    'free': ['free'],
    'fri': ['fries', 'fried_shrimp', 'fries', 'fried_shrimp'],
    'fried': ['fried_shrimp', 'fried_shrimp'],
    'fries': ['fries', 'fries'],
    'frog': ['frog'],
    'frown': [   'white_frowning_face',
                 'slightly_frowning_face',
                 'frowning',
                 'man_frowning',
                 'woman_frowning'],
    'frowning': [   'white_frowning_face',
                    'slightly_frowning_face',
                    'frowning',
                    'man_frowning',
                    'woman_frowning'],
    'fuji': ['mount_fuji'],
    'full': ['full_moon_with_face', 'full_moon'],
    'galaxi': ['star_struck'],
    'galaxy': ['star_struck'],
    'game': ['video_game', 'game_die', 'video_game', 'game_die'],
    'garden': ['house_with_garden'],
    'gem': ['gem', 'gem'],
    'gemini': ['gemini'],
    'geni': ['female_genie', 'male_genie'],
    'genie': ['female_genie', 'male_genie'],
    'gestur': [   'man_gesturing_no',
                  'woman_gesturing_no',
                  'man_gesturing_ok',
                  'woman_gesturing_ok'],
    'gesturing': [   'man_gesturing_no',
                     'woman_gesturing_no',
                     'man_gesturing_ok',
                     'woman_gesturing_ok'],
    'get': [   'man_getting_massage',
               'woman_getting_massage',
               'man_getting_haircut',
               'woman_getting_haircut'],
    'getting': [   'man_getting_massage',
                   'woman_getting_massage',
                   'man_getting_haircut',
                   'woman_getting_haircut'],
    'ghost': ['ghost', 'ghost', 'ghost'],
    'gibbou': ['waxing_gibbous_moon', 'waning_gibbous_moon'],
    'gibbous': ['waxing_gibbous_moon', 'waning_gibbous_moon'],
    'gift': ['gift_heart', 'gift', 'gift_heart', 'gift'],
    'girl': ['girl'],
    'glass': ['wine_glass', 'wine_glass'],
    'globe': ['globe_with_meridians'],
    'goblin': ['japanese_goblin'],
    'golf': ['golf', 'golf'],
    'grape': ['grapes', 'grapes'],
    'grapes': ['grapes', 'grapes'],
    'green': ['green_book', 'green_apple', 'green_book', 'green_apple'],
    'grimac': ['grimacing'],
    'grimacing': ['grimacing'],
    'groom': ['man_in_tuxedo'],
    'gua': ['man_with_gua_pi_mao'],
    'gua pi mao': ['man_with_gua_pi_mao'],
    'guard': ['male_guard', 'female_guard'],
    'guitar': ['guitar', 'guitar'],
    'gun': ['gun', 'gun'],
    'hair': ['blond_haired_man', 'blond_haired_woman'],
    'haircut': ['man_getting_haircut', 'woman_getting_haircut'],
    'haired': ['blond_haired_man', 'blond_haired_woman'],
    'hamburg': ['hamburger', 'hamburger'],
    'hamburger': ['hamburger', 'hamburger'],
    'hammer': ['hammer', 'hammer'],
    'hamster': ['hamster'],
    'hand': [   'face_with_hand_over_mouth',
                'man_tipping_hand',
                'woman_tipping_hand',
                'man_raising_hand',
                'woman_raising_hand',
                'raised_hands'],
    'handbag': ['handbag', 'handbag'],
    'hands': ['raised_hands'],
    'hankey': ['hankey'],
    'hash': ['hash'],
    'hat': ['face_with_cowboy_hat', 'womans_hat', 'womans_hat'],
    'hatch': ['hatched_chick'],
    'hatched': ['hatched_chick'],
    'head': [   'exploding_head',
                'face_with_head_bandage',
                'arrow_heading_down',
                'arrow_heading_up'],
    'head scarf': ['person_with_headscarf'],
    'heading': ['arrow_heading_down', 'arrow_heading_up'],
    'headphon': ['headphones', 'headphones'],
    'headphones': ['headphones', 'headphones'],
    'headscarf': ['person_with_headscarf'],
    'hear': ['hear_no_evil'],
    'heart': [   'heart_eyes',
                 'kissing_heart',
                 'heart_eyes_cat',
                 'gift_heart',
                 'heart_decoration',
                 'hearts',
                 'gift_heart',
                 'hearts'],
    'hearts': ['hearts', 'hearts'],
    'heavi': [   'heavy_plus_sign',
                 'heavy_dollar_sign',
                 'heavy_exclamation_mark',
                 'heavy_multiplication_x',
                 'heavy_plus_sign',
                 'heavy_minus_sign',
                 'heavy_division_sign',
                 'heavy_check_mark'],
    'heavy': [   'heavy_plus_sign',
                 'heavy_dollar_sign',
                 'heavy_exclamation_mark',
                 'heavy_multiplication_x',
                 'heavy_plus_sign',
                 'heavy_minus_sign',
                 'heavy_division_sign',
                 'heavy_check_mark'],
    'heel': ['high_heel', 'high_heel'],
    'herb': ['herb'],
    'hibiscu': ['hibiscus'],
    'hibiscus': ['hibiscus'],
    'high': ['high_brightness', 'high_heel', 'high_brightness', 'high_heel'],
    'hocho': ['hocho', 'hocho'],
    'honey': ['honey_pot', 'honey_pot'],
    'honeybe': ['honeybee'],
    'honeybee': ['honeybee'],
    'hook': ['leftwards_arrow_with_hook', 'arrow_right_hook'],
    'horn': ['postal_horn', 'postal_horn'],
    'hors': ['horse', 'carousel_horse', 'horse_racing', 'horse_racing'],
    'horse': ['horse', 'carousel_horse', 'horse_racing', 'horse_racing'],
    'hospit': ['hospital'],
    'hospital': ['hospital'],
    'hotel': ['hotel'],
    'hourglass': ['hourglass', 'hourglass_flowing_sand'],
    'hous': ['house', 'house_with_garden'],
    'house': ['house', 'house_with_garden'],
    'hug': ['hugging_face'],
    'hugging': ['hugging_face'],
    'hush': ['hushed'],
    'hushed': ['hushed'],
    'ice': ['ice_cream', 'shaved_ice', 'ice_cream', 'shaved_ice'],
    'icecream': ['icecream', 'icecream'],
    'id': ['id'],
    'ideograph': ['ideograph_advantage'],
    'imp': ['smiling_imp', 'imp'],
    'inbox': ['inbox_tray', 'inbox_tray'],
    'incom': ['incoming_envelope', 'incoming_envelope'],
    'incoming': ['incoming_envelope', 'incoming_envelope'],
    'index': ['card_index', 'card_index'],
    'inform': ['information_source'],
    'information': ['information_source'],
    'ink': ['lock_with_ink_pen', 'lock_with_ink_pen'],
    'innoc': ['innocent'],
    'innocent': ['innocent'],
    'insid': ['diamond_shape_with_a_dot_inside'],
    'inside': ['diamond_shape_with_a_dot_inside'],
    'interrobang': ['interrobang'],
    'invad': ['space_invader', 'space_invader', 'space_invader'],
    'invader': ['space_invader', 'space_invader', 'space_invader'],
    'iphon': ['iphone'],
    'iphone': ['iphone'],
    'it': ['put_litter_in_its_place'],
    'its': ['put_litter_in_its_place'],
    'jack': ['jack_o_lantern', 'jack_o_lantern'],
    'japan': ['japan'],
    'japanes': ['japanese_ogre', 'japanese_goblin'],
    'japanese': ['japanese_ogre', 'japanese_goblin'],
    'jean': ['jeans', 'jeans'],
    'jeans': ['jeans', 'jeans'],
    'joker': ['black_joker', 'black_joker'],
    'joy': ['joy', 'joy_cat'],
    'judg': ['male_judge', 'female_judge'],
    'judge': ['male_judge', 'female_judge'],
    'key': ['closed_lock_with_key', 'key', 'closed_lock_with_key', 'key'],
    'keyboard': ['musical_keyboard', 'musical_keyboard'],
    'keycap': ['keycap_ten'],
    'kimono': ['kimono', 'kimono'],
    'kiss': [   'kissing_heart',
                'kissing',
                'kissing_smiling_eyes',
                'kissing_closed_eyes',
                'kissing_cat'],
    'kissing': [   'kissing_heart',
                   'kissing',
                   'kissing_smiling_eyes',
                   'kissing_closed_eyes',
                   'kissing_cat'],
    'knife': ['fork_and_knife', 'fork_and_knife'],
    'koala': ['koala'],
    'koko': ['koko'],
    'lantern': ['jack_o_lantern', 'jack_o_lantern'],
    'larg': [   'large_blue_circle',
                'black_large_square',
                'white_large_square',
                'large_blue_circle',
                'large_blue_diamond',
                'large_orange_diamond'],
    'large': [   'large_blue_circle',
                 'black_large_square',
                 'white_large_square',
                 'large_blue_circle',
                 'large_blue_diamond',
                 'large_orange_diamond'],
    'last': ['last_quarter_moon', 'last_quarter_moon_with_face'],
    'laugh': ['rolling_on_the_floor_laughing'],
    'laughing': ['rolling_on_the_floor_laughing'],
    'leaf': ['maple_leaf', 'fallen_leaf'],
    'leav': ['leaves'],
    'leaves': ['leaves'],
    'ledger': ['ledger', 'ledger'],
    'left': [   'arrow_left',
                'arrow_lower_left',
                'arrow_upper_left',
                'left_right_arrow',
                'left_luggage'],
    'leftward': ['leftwards_arrow_with_hook'],
    'leftwards': ['leftwards_arrow_with_hook'],
    'leg': ['poultry_leg', 'poultry_leg'],
    'lemon': ['lemon', 'lemon'],
    'leo': ['leo'],
    'liberti': ['statue_of_liberty'],
    'liberty': ['statue_of_liberty'],
    'libra': ['libra'],
    'lie': ['lying_face'],
    'link': ['link'],
    'lipstick': ['lipstick', 'lipstick'],
    'litter': ['put_litter_in_its_place', 'do_not_litter'],
    'lock': [   'lock',
                'lock_with_ink_pen',
                'closed_lock_with_key',
                'lock',
                'lock_with_ink_pen',
                'closed_lock_with_key'],
    'lollipop': ['lollipop', 'lollipop'],
    'loop': ['curly_loop', 'loop', 'loop'],
    'lotu': ['woman_in_lotus_position', 'man_in_lotus_position'],
    'lotus': ['woman_in_lotus_position', 'man_in_lotus_position'],
    'loudspeak': ['loudspeaker'],
    'loudspeaker': ['loudspeaker'],
    'low': ['low_brightness', 'low_brightness'],
    'lower': ['arrow_lower_left', 'arrow_lower_right'],
    'luggag': ['left_luggage'],
    'luggage': ['left_luggage'],
    'lying': ['lying_face'],
    'mag': ['mag', 'mag_right', 'mag', 'mag_right'],
    'mage': ['female_mage', 'male_mage'],
    'mahjong': ['mahjong', 'mahjong'],
    'mail': [   'mailbox_with_mail',
                'mailbox_with_no_mail',
                'mailbox_with_mail',
                'mailbox_with_no_mail'],
    'mailbox': [   'mailbox',
                   'mailbox_closed',
                   'mailbox_with_mail',
                   'mailbox_with_no_mail',
                   'mailbox',
                   'mailbox_closed',
                   'mailbox_with_mail',
                   'mailbox_with_no_mail'],
    'male': [   'male_doctor',
                'male_student',
                'male_teacher',
                'male_judge',
                'male_farmer',
                'male_cook',
                'male_mechanic',
                'male_factory_worker',
                'male_office_worker',
                'male_scientist',
                'male_technologist',
                'male_singer',
                'male_artist',
                'male_pilot',
                'male_astronaut',
                'male_firefighter',
                'male_police_officer',
                'male_detective',
                'male_guard',
                'male_construction_worker',
                'male_mage',
                'male_fairy',
                'male_vampire',
                'male_elf',
                'male_genie',
                'male_zombie'],
    'man': [   'man',
               'older_man',
               'man_wearing_turban',
               'man_with_gua_pi_mao',
               'blond_haired_man',
               'man_in_tuxedo',
               'man_frowning',
               'man_pouting',
               'man_gesturing_no',
               'man_gesturing_ok',
               'man_tipping_hand',
               'man_raising_hand',
               'man_bowing',
               'man_facepalming',
               'man_shrugging',
               'man_getting_massage',
               'man_getting_haircut',
               'man_walking',
               'man_running',
               'man_dancing',
               'man_with_bunny_ears_partying',
               'man_in_steamy_room',
               'man_climbing',
               'man_in_lotus_position',
               'mans_shoe',
               'mans_shoe'],
    'mans': ['mans_shoe', 'mans_shoe'],
    'mao': ['man_with_gua_pi_mao'],
    'mapl': ['maple_leaf'],
    'maple': ['maple_leaf'],
    'mark': [   'negative_squared_cross_mark',
                'heavy_exclamation_mark',
                'heavy_check_mark',
                'part_alternation_mark',
                'white_check_mark'],
    'mask': ['mask'],
    'massag': ['man_getting_massage', 'woman_getting_massage'],
    'massage': ['man_getting_massage', 'woman_getting_massage'],
    'meat': ['meat_on_bone', 'meat_on_bone'],
    'mechan': ['male_mechanic', 'female_mechanic'],
    'mechanic': ['male_mechanic', 'female_mechanic'],
    'medium': [   'black_medium_small_square',
                  'white_medium_small_square',
                  'black_medium_square',
                  'white_medium_square'],
    'mega': ['mega', 'mega'],
    'melon': ['melon', 'melon'],
    'memo': ['memo', 'memo'],
    'men': ['mens'],
    'mens': ['mens'],
    'meridian': ['globe_with_meridians'],
    'meridians': ['globe_with_meridians'],
    'mermaid': ['mermaid'],
    'merman': ['merman'],
    'metro': ['metro'],
    'microphon': ['microphone', 'microphone'],
    'microphone': ['microphone', 'microphone'],
    'microscop': ['microscope', 'microscope'],
    'microscope': ['microscope', 'microscope'],
    'milki': ['milky_way'],
    'milky': ['milky_way'],
    'minidisc': ['minidisc', 'minidisc'],
    'minu': ['heavy_minus_sign'],
    'minus': ['heavy_minus_sign'],
    'mobil': ['no_mobile_phones', 'mobile_phone_off'],
    'mobile': ['no_mobile_phones', 'mobile_phone_off'],
    'mode': ['vibration_mode'],
    'money': ['money_mouth_face', 'money_with_wings', 'money_with_wings'],
    'moneybag': ['moneybag', 'moneybag'],
    'monkey': ['monkey_face', 'monkey'],
    'monocl': ['face_with_monocle'],
    'monocle': ['face_with_monocle'],
    'moon': [   'full_moon_with_face',
                'new_moon_with_face',
                'new_moon',
                'waxing_crescent_moon',
                'first_quarter_moon',
                'waxing_gibbous_moon',
                'full_moon',
                'waning_gibbous_moon',
                'last_quarter_moon',
                'waning_crescent_moon',
                'last_quarter_moon_with_face',
                'first_quarter_moon_with_face',
                'crescent_moon'],
    'mortar': ['mortar_board', 'mortar_board'],
    'mount': ['mount_fuji'],
    'mountain': [   'sunrise_over_mountains',
                    'mountain_bicyclist',
                    'mountain_bicyclist'],
    'mountains': ['sunrise_over_mountains'],
    'mous': ['mouse'],
    'mouse': ['mouse'],
    'mouth': [   'no_mouth',
                 'open_mouth',
                 'zipper_mouth_face',
                 'money_mouth_face',
                 'face_with_symbols_on_mouth',
                 'face_with_hand_over_mouth'],
    'movi': ['movie_camera', 'movie_camera'],
    'movie': ['movie_camera', 'movie_camera'],
    'mr': ['mrs_claus'],
    'mrs': ['mrs_claus'],
    'multipl': ['heavy_multiplication_x'],
    'multiplication': ['heavy_multiplication_x'],
    'mushroom': ['mushroom'],
    'music': [   'musical_score',
                 'musical_keyboard',
                 'musical_score',
                 'musical_keyboard'],
    'musical': [   'musical_score',
                   'musical_keyboard',
                   'musical_score',
                   'musical_keyboard'],
    'mute': ['mute'],
    'name': ['name_badge', 'name_badge'],
    'nauseat': ['nauseated_face'],
    'nauseated': ['nauseated_face'],
    'neckti': ['necktie', 'necktie'],
    'necktie': ['necktie', 'necktie'],
    'neg': ['negative_squared_cross_mark'],
    'negative': ['negative_squared_cross_mark'],
    'nerd': ['nerd_face', 'male_technologist', 'female_technologist'],
    'neutral': ['neutral_face'],
    'new': ['new', 'new_moon_with_face', 'new_moon'],
    'newspap': ['newspaper', 'newspaper'],
    'newspaper': ['newspaper', 'newspaper'],
    'ng': ['ng'],
    'nib': ['black_nib', 'black_nib'],
    'night': ['bridge_at_night'],
    'nine': ['nine'],
    'no': [   'no_mouth',
              'see_no_evil',
              'hear_no_evil',
              'speak_no_evil',
              'man_gesturing_no',
              'woman_gesturing_no',
              'no_bell',
              'no_smoking',
              'no_entry_sign',
              'no_mobile_phones',
              'no_bicycles',
              'no_pedestrians',
              'no_entry',
              'mailbox_with_no_mail',
              'no_bell',
              'mailbox_with_no_mail'],
    'non-pot': ['non-potable_water'],
    'non-potable': ['non-potable_water'],
    'nose': ['pig_nose'],
    'not': ['do_not_litter'],
    'notebook': [   'notebook',
                    'notebook_with_decorative_cover',
                    'notebook',
                    'notebook_with_decorative_cover'],
    'nut': ['nut_and_bolt', 'nut_and_bolt'],
    'o': ['jack_o_lantern', 'jack_o_lantern'],
    'o2': ['o2'],
    'object': ['objects'],
    'objects': ['objects'],
    'ocean': ['ocean'],
    'octocat': ['octocat'],
    'octopu': ['octopus'],
    'octopus': ['octopus'],
    'oden': ['oden', 'oden'],
    'off': ['mobile_phone_off'],
    'offic': [   'male_office_worker',
                 'female_office_worker',
                 'male_police_officer',
                 'female_police_officer',
                 'office',
                 'post_office'],
    'office': [   'male_office_worker',
                  'female_office_worker',
                  'office',
                  'post_office'],
    'officer': ['male_police_officer', 'female_police_officer'],
    'ogr': ['japanese_ogre'],
    'ogre': ['japanese_ogre'],
    'ok': ['man_gesturing_ok', 'woman_gesturing_ok', 'ok'],
    'older': ['older_adult', 'older_man', 'older_woman'],
    'one': ['one', 'repeat_one'],
    'open': ['open_mouth', 'open_file_folder', 'open_file_folder'],
    'ophiuchu': ['ophiuchus'],
    'ophiuchus': ['ophiuchus'],
    'orang': [   'large_orange_diamond',
                 'small_orange_diamond',
                 'orange_book',
                 'orange_book'],
    'orange': [   'large_orange_diamond',
                  'small_orange_diamond',
                  'orange_book',
                  'orange_book'],
    'out': [   'stuck_out_tongue',
               'stuck_out_tongue_winking_eye',
               'stuck_out_tongue_closed_eyes'],
    'outbox': ['outbox_tray', 'outbox_tray'],
    'over': ['face_with_hand_over_mouth', 'sunrise_over_mountains'],
    'packag': ['package', 'package'],
    'package': ['package', 'package'],
    'page': [   'page_facing_up',
                'page_with_curl',
                'page_facing_up',
                'page_with_curl'],
    'pager': ['pager', 'pager'],
    'palm': ['palm_tree'],
    'panda': ['panda_face'],
    'paperclip': ['paperclip', 'paperclip'],
    'park': ['parking'],
    'parking': ['parking'],
    'part': ['part_alternation_mark'],
    'parti': [   'dancer',
                 'man_dancing',
                 'man_with_bunny_ears_partying',
                 'woman_with_bunny_ears_partying'],
    'partli': ['partly_sunny'],
    'partly': ['partly_sunny'],
    'party': [   'dancer',
                 'man_dancing',
                 'man_with_bunny_ears_partying',
                 'woman_with_bunny_ears_partying'],
    'partying': [   'man_with_bunny_ears_partying',
                    'woman_with_bunny_ears_partying'],
    'passport': ['passport_control'],
    'peach': ['peach', 'peach'],
    'pear': ['pear', 'pear'],
    'pedestrian': ['no_pedestrians'],
    'pedestrians': ['no_pedestrians'],
    'pen': ['lock_with_ink_pen', 'lock_with_ink_pen'],
    'pencil': ['pencil', 'pencil'],
    'pencil2': ['pencil2', 'pencil2'],
    'penguin': ['penguin'],
    'pensiv': ['pensive'],
    'pensive': ['pensive'],
    'persever': ['persevere'],
    'persevere': ['persevere'],
    'person': ['person_with_headscarf', 'bearded_person'],
    'phone': ['phone', 'no_mobile_phones', 'mobile_phone_off', 'phone'],
    'phones': ['no_mobile_phones'],
    'pi': ['man_with_gua_pi_mao'],
    'pig': ['pig', 'pig_nose'],
    'pill': ['pill', 'pill'],
    'pilot': ['male_pilot', 'female_pilot'],
    'pineappl': ['pineapple', 'pineapple'],
    'pineapple': ['pineapple', 'pineapple'],
    'pisc': ['pisces'],
    'pisces': ['pisces'],
    'pizza': ['pizza', 'pizza'],
    'place': ['put_litter_in_its_place'],
    'play': ['flower_playing_cards', 'flower_playing_cards'],
    'playing': ['flower_playing_cards', 'flower_playing_cards'],
    'plu': ['heavy_plus_sign', 'heavy_plus_sign'],
    'plug': ['electric_plug', 'electric_plug'],
    'plus': ['heavy_plus_sign', 'heavy_plus_sign'],
    'point': ['eight_pointed_black_star', 'six_pointed_star'],
    'pointed': ['eight_pointed_black_star', 'six_pointed_star'],
    'pole': ['fishing_pole_and_fish', 'fishing_pole_and_fish'],
    'polic': ['male_police_officer', 'female_police_officer'],
    'police': ['male_police_officer', 'female_police_officer'],
    'posit': ['woman_in_lotus_position', 'man_in_lotus_position'],
    'position': ['woman_in_lotus_position', 'man_in_lotus_position'],
    'post': ['post_office'],
    'postal': ['postal_horn', 'postal_horn'],
    'postbox': ['postbox', 'postbox'],
    'pot': ['honey_pot', 'honey_pot'],
    'potabl': ['potable_water'],
    'potable': ['potable_water'],
    'potato': ['sweet_potato', 'sweet_potato'],
    'pouch': ['pouch', 'pouch'],
    'poultri': ['poultry_leg', 'poultry_leg'],
    'poultry': ['poultry_leg', 'poultry_leg'],
    'pound': ['pound', 'pound'],
    'pout': ['pouting_cat', 'man_pouting', 'woman_pouting'],
    'pouting': ['pouting_cat', 'man_pouting', 'woman_pouting'],
    'pray': ['pray'],
    'pregnant': ['pregnant_woman'],
    'princ': ['prince'],
    'prince': ['prince'],
    'princess': ['princess'],
    'purs': ['purse', 'purse'],
    'purse': ['purse', 'purse'],
    'pushpin': ['pushpin', 'pushpin'],
    'put': ['put_litter_in_its_place'],
    'quarter': [   'first_quarter_moon',
                   'last_quarter_moon',
                   'last_quarter_moon_with_face',
                   'first_quarter_moon_with_face'],
    'rabbit': ['rabbit'],
    'race': ['horse_racing', 'horse_racing'],
    'racehors': ['racehorse'],
    'racehorse': ['racehorse'],
    'racing': ['horse_racing', 'horse_racing'],
    'radio': ['radio_button', 'radio'],
    'rage': ['rage'],
    'rainbow': ['rainbow'],
    'rais': [   'face_with_raised_eyebrow',
                'man_raising_hand',
                'woman_raising_hand',
                'raised_hands'],
    'raise hand': ['man_raising_hand', 'woman_raising_hand'],
    'raised': ['face_with_raised_eyebrow', 'raised_hands'],
    'raising': ['man_raising_hand', 'woman_raising_hand'],
    'ramen': ['ramen', 'ramen'],
    'receiv': ['telephone_receiver', 'telephone_receiver'],
    'receiver': ['telephone_receiver', 'telephone_receiver'],
    'recycl': ['recycle'],
    'recycle': ['recycle'],
    'red': [   'red_circle',
               'red_circle',
               'small_red_triangle',
               'small_red_triangle_down'],
    'regist': ['registered'],
    'registered': ['registered'],
    'relax': [   'relaxed',
                 'man_getting_massage',
                 'woman_getting_massage',
                 'woman_in_steamy_room',
                 'man_in_steamy_room'],
    'relaxed': ['relaxed'],
    'reliev': ['disappointed_relieved', 'relieved'],
    'relieved': ['disappointed_relieved', 'relieved'],
    'repeat': ['repeat', 'repeat_one'],
    'restroom': ['restroom'],
    'rewind': ['rewind'],
    'ribbon': ['ribbon', 'ribbon'],
    'rice': [   'rice_ball',
                'rice_cracker',
                'rice',
                'ear_of_rice',
                'rice_scene',
                'rice_ball',
                'rice_cracker',
                'rice'],
    'right': [   'arrow_lower_right',
                 'arrow_right',
                 'arrow_upper_right',
                 'arrow_right_hook',
                 'left_right_arrow',
                 'mag_right',
                 'mag_right'],
    'rightward': ['twisted_rightwards_arrows'],
    'rightwards': ['twisted_rightwards_arrows'],
    'ring': ['ring', 'ring'],
    'robot': ['robot_face'],
    'roll': ['rolling_on_the_floor_laughing', 'face_with_rolling_eyes'],
    'roller': ['roller_coaster'],
    'rolling': ['rolling_on_the_floor_laughing', 'face_with_rolling_eyes'],
    'room': ['woman_in_steamy_room', 'man_in_steamy_room'],
    'rugbi': ['rugby_football', 'rugby_football'],
    'rugby': ['rugby_football', 'rugby_football'],
    'ruler': [   'straight_ruler',
                 'triangular_ruler',
                 'straight_ruler',
                 'triangular_ruler'],
    'run': [   'man_running',
               'woman_running',
               'running_shirt_with_sash',
               'running_shirt_with_sash'],
    'running': [   'man_running',
                   'woman_running',
                   'running_shirt_with_sash',
                   'running_shirt_with_sash'],
    'sa': ['sa'],
    'sagittariu': ['sagittarius'],
    'sagittarius': ['sagittarius'],
    'sailboat': ['sailboat'],
    'sake': ['sake', 'sake'],
    'sand': ['hourglass_flowing_sand'],
    'sandal': ['sandal', 'sandal'],
    'santa': ['santa', 'santa', 'santa'],
    'sash': ['running_shirt_with_sash', 'running_shirt_with_sash'],
    'satchel': ['school_satchel', 'school_satchel'],
    'satellit': ['satellite'],
    'satellite': ['satellite'],
    'saxophon': ['saxophone', 'saxophone'],
    'saxophone': ['saxophone', 'saxophone'],
    'scene': ['rice_scene'],
    'school': ['school_satchel', 'school', 'school_satchel'],
    'scientist': ['male_scientist', 'female_scientist'],
    'scissor': ['scissors', 'scissors'],
    'scissors': ['scissors', 'scissors'],
    'score': ['musical_score', 'musical_score'],
    'scorpiu': ['scorpius'],
    'scorpius': ['scorpius'],
    'scream': ['scream', 'scream_cat'],
    'scroll': ['scroll', 'scroll'],
    'seat': ['seat', 'seat'],
    'secret': ['secret'],
    'see': ['see_no_evil'],
    'seedl': ['seedling'],
    'seedling': ['seedling'],
    'seven': ['seven'],
    'shape': ['diamond_shape_with_a_dot_inside'],
    'shave': ['shaved_ice', 'shaved_ice'],
    'shaved': ['shaved_ice', 'shaved_ice'],
    'sheep': ['sheep'],
    'shell': ['shell'],
    'ship': ['ship'],
    'shipit': ['shipit'],
    'shirt': [   'shirt',
                 'running_shirt_with_sash',
                 'shirt',
                 'running_shirt_with_sash'],
    'shoe': ['shoe', 'mans_shoe', 'shoe', 'mans_shoe'],
    'shower': ['shower', 'shower'],
    'shrimp': ['fried_shrimp', 'fried_shrimp'],
    'shrug': ['man_shrugging', 'woman_shrugging'],
    'shrugging': ['man_shrugging', 'woman_shrugging'],
    'shush': ['shushing_face'],
    'shushing': ['shushing_face'],
    'sign': [   'heavy_plus_sign',
                'no_entry_sign',
                'heavy_dollar_sign',
                'heavy_plus_sign',
                'heavy_minus_sign',
                'heavy_division_sign'],
    'signal': ['signal_strength'],
    'singer': ['male_singer', 'female_singer'],
    'six': ['six', 'six_pointed_star'],
    'ski': ['ski', 'ski'],
    'skull': ['skull', 'skull_and_crossbones'],
    'sleep': ['sleeping'],
    'sleepi': ['sleepy'],
    'sleeping': ['sleeping'],
    'sleepy': ['sleepy'],
    'slightli': ['slightly_smiling_face', 'slightly_frowning_face'],
    'slightly': ['slightly_smiling_face', 'slightly_frowning_face'],
    'small': [   'arrow_down_small',
                 'arrow_up_small',
                 'black_small_square',
                 'white_small_square',
                 'black_medium_small_square',
                 'white_medium_small_square',
                 'small_blue_diamond',
                 'small_orange_diamond',
                 'small_red_triangle',
                 'small_red_triangle_down'],
    'smile': [   'smile',
                 'sweat_smile',
                 'kissing_smiling_eyes',
                 'slightly_smiling_face',
                 'smiling_imp',
                 'smile_cat'],
    'smiley': ['smiley', 'smiley_cat'],
    'smiling': ['kissing_smiling_eyes', 'slightly_smiling_face', 'smiling_imp'],
    'smirk': ['smirk', 'smirk_cat'],
    'smoke': ['no_smoking', 'smoking', 'smoking'],
    'smoking': ['no_smoking', 'smoking', 'smoking'],
    'snail': ['snail'],
    'snake': ['snake'],
    'sneez': ['sneezing_face'],
    'sneezing': ['sneezing_face'],
    'snowboard': ['snowboarder', 'snowboarder'],
    'snowboarder': ['snowboarder', 'snowboarder'],
    'snowflak': ['snowflake'],
    'snowflake': ['snowflake'],
    'snowman': ['snowman'],
    'so': ['sos'],
    'sob': ['sob'],
    'soccer': ['soccer', 'soccer'],
    'solar system': ['star_struck'],
    'soon': ['soon'],
    'sos': ['sos'],
    'sound': ['sound'],
    'sourc': ['information_source'],
    'source': ['information_source'],
    'space': ['space_invader', 'space_invader', 'space_invader'],
    'spade': ['spades', 'spades'],
    'spades': ['spades', 'spades'],
    'spaghetti': ['spaghetti', 'spaghetti'],
    'sparkl': ['sparkle'],
    'sparkle': ['sparkle'],
    'sparkler': ['sparkler', 'sparkler'],
    'speak': ['speak_no_evil'],
    'speaker': ['speaker'],
    'speedboat': ['speedboat'],
    'spoke': ['eight_spoked_asterisk'],
    'spoked': ['eight_spoked_asterisk'],
    'squar': [   'negative_squared_cross_mark',
                 'black_small_square',
                 'white_small_square',
                 'black_medium_small_square',
                 'white_medium_small_square',
                 'black_medium_square',
                 'white_medium_square',
                 'black_large_square',
                 'white_large_square',
                 'black_square_button',
                 'white_square_button'],
    'square': [   'black_small_square',
                  'white_small_square',
                  'black_medium_small_square',
                  'white_medium_small_square',
                  'black_medium_square',
                  'white_medium_square',
                  'black_large_square',
                  'white_large_square',
                  'black_square_button',
                  'white_square_button'],
    'squared': ['negative_squared_cross_mark'],
    'squirrel': ['squirrel'],
    'star': ['star_struck', 'eight_pointed_black_star', 'six_pointed_star'],
    'statu': ['statue_of_liberty'],
    'statue': ['statue_of_liberty'],
    'steami': ['woman_in_steamy_room', 'man_in_steamy_room'],
    'steamy': ['woman_in_steamy_room', 'man_in_steamy_room'],
    'stew': ['stew', 'stew'],
    'store': ['convenience_store', 'department_store'],
    'straight': ['straight_ruler', 'straight_ruler'],
    'strawberri': ['strawberry', 'strawberry'],
    'strawberry': ['strawberry', 'strawberry'],
    'strength': ['signal_strength'],
    'struck': ['star_struck'],
    'stuck': [   'stuck_out_tongue',
                 'stuck_out_tongue_winking_eye',
                 'stuck_out_tongue_closed_eyes'],
    'student': ['male_student', 'female_student'],
    'sun': ['sun_with_face'],
    'sunglass': ['sunglasses'],
    'sunglasses': ['sunglasses'],
    'sunni': ['sunny', 'partly_sunny'],
    'sunny': ['sunny', 'partly_sunny'],
    'sunris': ['sunrise_over_mountains', 'sunrise'],
    'sunrise': ['sunrise_over_mountains', 'sunrise'],
    'surfer': ['surfer', 'surfer'],
    'sushi': ['sushi', 'sushi'],
    'sweat': ['sweat_smile', 'sweat', 'cold_sweat'],
    'sweet': ['sweet_potato', 'sweet_potato'],
    'swimmer': ['swimmer', 'swimmer'],
    'symbol': ['face_with_symbols_on_mouth', 'symbols', 'baby_symbol'],
    'symbols': ['face_with_symbols_on_mouth', 'symbols'],
    'syring': ['syringe', 'syringe'],
    'syringe': ['syringe', 'syringe'],
    'tab': ['bookmark_tabs', 'bookmark_tabs'],
    'tabs': ['bookmark_tabs', 'bookmark_tabs'],
    'tada': ['tada', 'tada', 'tada'],
    'tanabata': ['tanabata_tree', 'tanabata_tree'],
    'tangerin': ['tangerine', 'tangerine'],
    'tangerine': ['tangerine', 'tangerine'],
    'tauru': ['taurus'],
    'taurus': ['taurus'],
    'tea': ['tea', 'tea'],
    'teacher': ['male_teacher', 'female_teacher'],
    'technologist': ['male_technologist', 'female_technologist'],
    'telephon': [   'telephone',
                    'telephone_receiver',
                    'telephone',
                    'telephone_receiver'],
    'telephone': [   'telephone',
                     'telephone_receiver',
                     'telephone',
                     'telephone_receiver'],
    'telescop': ['telescope', 'telescope'],
    'telescope': ['telescope', 'telescope'],
    'ten': ['keycap_ten'],
    'tenni': ['tennis', 'tennis'],
    'tennis': ['tennis', 'tennis'],
    'tent': ['tent'],
    'thermomet': ['face_with_thermometer'],
    'thermometer': ['face_with_thermometer'],
    'think': ['thinking_face'],
    'thinking': ['thinking_face'],
    'three': ['three'],
    'thumbsup': ['thumbsup'],
    'tiger': ['tiger'],
    'tip': ['man_tipping_hand', 'woman_tipping_hand'],
    'tip hand': ['man_tipping_hand', 'woman_tipping_hand'],
    'tipping': ['man_tipping_hand', 'woman_tipping_hand'],
    'tire': ['tired_face'],
    'tired': ['tired_face'],
    'tm': ['tm'],
    'toilet': ['toilet', 'toilet'],
    'tokyo': ['tokyo_tower'],
    'tomato': ['tomato', 'tomato'],
    'tongu': [   'stuck_out_tongue',
                 'stuck_out_tongue_winking_eye',
                 'stuck_out_tongue_closed_eyes'],
    'tongue': [   'stuck_out_tongue',
                  'stuck_out_tongue_winking_eye',
                  'stuck_out_tongue_closed_eyes'],
    'top': ['top'],
    'tophat': ['tophat', 'tophat'],
    'tower': ['tokyo_tower'],
    'tray': ['inbox_tray', 'outbox_tray', 'inbox_tray', 'outbox_tray'],
    'tree': [   'christmas_tree',
                'tanabata_tree',
                'palm_tree',
                'evergreen_tree',
                'deciduous_tree',
                'christmas_tree',
                'tanabata_tree'],
    'trend': [   'chart_with_upwards_trend',
                 'chart_with_downwards_trend',
                 'chart_with_upwards_trend',
                 'chart_with_downwards_trend'],
    'triangl': ['small_red_triangle', 'small_red_triangle_down'],
    'triangle': ['small_red_triangle', 'small_red_triangle_down'],
    'triangular': ['triangular_ruler', 'triangular_ruler'],
    'trident': ['trident'],
    'triumph': ['triumph'],
    'trophi': ['trophy', 'trophy'],
    'trophy': ['trophy', 'trophy'],
    'tropic': ['tropical_fish', 'tropical_drink', 'tropical_drink'],
    'tropical': ['tropical_fish', 'tropical_drink', 'tropical_drink'],
    'trumpet': ['trumpet', 'trumpet'],
    'tshirt': ['tshirt', 'tshirt'],
    'turban': ['man_wearing_turban', 'woman_wearing_turban'],
    'turtl': ['turtle'],
    'turtle': ['turtle'],
    'tuxedo': ['man_in_tuxedo'],
    'tv': ['tv', 'tv'],
    'twist': ['twisted_rightwards_arrows'],
    'twisted': ['twisted_rightwards_arrows'],
    'two': ['two'],
    'u5272': ['u5272'],
    'u5408': ['u5408'],
    'u55b6': ['u55b6'],
    'u6307': ['u6307'],
    'u6708': ['u6708'],
    'u6709': ['u6709'],
    'u6e80': ['u6e80'],
    'u7121': ['u7121'],
    'u7533': ['u7533'],
    'u7981': ['u7981'],
    'u7a7a': ['u7a7a'],
    'umbrella': ['umbrella', 'closed_umbrella', 'closed_umbrella'],
    'unamus': ['unamused'],
    'unamused': ['unamused'],
    'underag': ['underage'],
    'underage': ['underage'],
    'unlock': ['unlock', 'unlock'],
    'up': [   'arrow_up',
              'arrow_double_up',
              'arrow_heading_up',
              'arrow_up_down',
              'arrow_up_small',
              'up',
              'page_facing_up',
              'page_facing_up'],
    'upper': ['arrow_upper_left', 'arrow_upper_right'],
    'upsid': ['upside_down_face'],
    'upside': ['upside_down_face'],
    'upward': ['chart_with_upwards_trend', 'chart_with_upwards_trend'],
    'upwards': ['chart_with_upwards_trend', 'chart_with_upwards_trend'],
    'vampir': ['female_vampire', 'male_vampire'],
    'vampire': ['female_vampire', 'male_vampire'],
    'veil': ['bride_with_veil'],
    'vh': ['vhs', 'vhs'],
    'vhs': ['vhs', 'vhs'],
    'vibrat': ['vibration_mode'],
    'vibration': ['vibration_mode'],
    'video': ['video_camera', 'video_game', 'video_camera', 'video_game'],
    'violin': ['violin', 'violin'],
    'virgo': ['virgo'],
    'volcano': ['volcano'],
    'vomit': ['face_vomiting'],
    'vomiting': ['face_vomiting'],
    'vs': ['vs'],
    'walk': ['man_walking', 'woman_walking'],
    'walking': ['man_walking', 'woman_walking'],
    'wane': ['waning_gibbous_moon', 'waning_crescent_moon'],
    'waning': ['waning_gibbous_moon', 'waning_crescent_moon'],
    'watch': ['watch'],
    'water': ['potable_water', 'non-potable_water'],
    'watermelon': ['watermelon', 'watermelon'],
    'wave': ['wave'],
    'wavi': ['wavy_dash'],
    'wavy': ['wavy_dash'],
    'wax': ['waxing_crescent_moon', 'waxing_gibbous_moon'],
    'waxing': ['waxing_crescent_moon', 'waxing_gibbous_moon'],
    'way': ['milky_way'],
    'wc': ['wc'],
    'wear': ['man_wearing_turban', 'woman_wearing_turban'],
    'weari': ['weary'],
    'wearing': ['man_wearing_turban', 'woman_wearing_turban'],
    'weary': ['weary'],
    'wed': ['wedding'],
    'wedding': ['wedding'],
    'whale': ['whale'],
    'wheel': ['ferris_wheel'],
    'wheelchair': ['wheelchair'],
    'white': [   'white_frowning_face',
                 'white_circle',
                 'white_flower',
                 'white_small_square',
                 'white_medium_small_square',
                 'white_medium_square',
                 'white_large_square',
                 'white_check_mark',
                 'white_square_button',
                 'white_circle'],
    'wind': ['wind_chime', 'wind_chime'],
    'wine': ['wine_glass', 'wine_glass'],
    'wing': ['money_with_wings', 'money_with_wings'],
    'wings': ['money_with_wings', 'money_with_wings'],
    'wink': ['wink', 'stuck_out_tongue_winking_eye'],
    'winking': ['stuck_out_tongue_winking_eye'],
    'wolf': ['wolf'],
    'woman': [   'woman',
                 'older_woman',
                 'woman_wearing_turban',
                 'blond_haired_woman',
                 'pregnant_woman',
                 'woman_frowning',
                 'woman_pouting',
                 'woman_gesturing_no',
                 'woman_gesturing_ok',
                 'woman_tipping_hand',
                 'woman_raising_hand',
                 'woman_bowing',
                 'woman_facepalming',
                 'woman_shrugging',
                 'woman_getting_massage',
                 'woman_getting_haircut',
                 'woman_walking',
                 'woman_running',
                 'woman_with_bunny_ears_partying',
                 'woman_in_steamy_room',
                 'woman_climbing',
                 'woman_in_lotus_position',
                 'womans_clothes',
                 'womans_hat',
                 'womans_clothes',
                 'womans_hat'],
    'womans': ['womans_clothes', 'womans_hat', 'womans_clothes', 'womans_hat'],
    'women': ['womens'],
    'womens': ['womens'],
    'worker': [   'male_factory_worker',
                  'female_factory_worker',
                  'male_office_worker',
                  'female_office_worker',
                  'male_construction_worker',
                  'female_construction_worker'],
    'worri': ['worried'],
    'worried': ['worried'],
    'wrench': ['wrench', 'wrench'],
    'x': ['heavy_multiplication_x'],
    'yen': ['yen', 'yen'],
    'yoga': ['woman_in_lotus_position', 'man_in_lotus_position'],
    'yum': ['yum'],
    'zani': ['zany_face'],
    'zany': ['zany_face'],
    'zap': ['zap'],
    'zero': ['zero'],
    'zipper': ['zipper_mouth_face'],
    'zombi': ['female_zombie', 'male_zombie'],
    'zombie': ['female_zombie', 'male_zombie']}
