
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

d_emoji_cluster_rev_provenance = {
 'action': ['router.py',
            'plac_core.py',
            'csv2py_orchestrator.py',
            'emojis2py.py',
            'emoji_dict_writer.py',
            'common_utils.py'],
 'source': 'resources/data/csv/emojis.xlsx',
 'time': '2022-05-17 17:00:32.993957'}

d_emoji_cluster_rev = {
    '8ball': [-1, -1],
    'Objects': [-1],
    'ab': [-1],
    'abc': [-1],
    'abcd': [-1],
    'accept': [-1],
    'adult': [7],
    'alarm_clock': [-1],
    'angel': [9],
    'ant': [-1],
    'apple': [-1, -1],
    'aquarius': [-1],
    'aries': [-1],
    'arrow_backward': [-1],
    'arrow_double_down': [-1],
    'arrow_double_up': [-1],
    'arrow_down': [-1],
    'arrow_down_small': [-1],
    'arrow_forward': [-1],
    'arrow_heading_down': [-1],
    'arrow_heading_up': [-1],
    'arrow_left': [-1],
    'arrow_lower_left': [-1],
    'arrow_lower_right': [-1],
    'arrow_right': [-1],
    'arrow_right_hook': [-1],
    'arrow_up': [-1],
    'arrow_up_down': [-1],
    'arrow_up_small': [-1],
    'arrow_upper_left': [-1],
    'arrow_upper_right': [-1],
    'arrows_clockwise': [-1],
    'arrows_counterclockwise': [-1],
    'art': [-1, -1],
    'baby': [7],
    'baby_bottle': [-1, -1],
    'baby_chick': [-1],
    'baby_symbol': [-1],
    'back': [-1],
    'baggage_claim': [-1],
    'balloon': [-1, -1],
    'ballot_box_with_check': [-1],
    'bamboo': [-1],
    'banana': [-1, -1],
    'bangbang': [-1],
    'bank': [-1],
    'bar_chart': [-1, -1],
    'baseball': [-1, -1],
    'basketball': [-1, -1],
    'bath': [-1, -1],
    'bathtub': [-1, -1],
    'battery': [-1, -1],
    'bear': [-1],
    'bearded_person': [-1],
    'beer': [-1, -1],
    'beers': [-1, -1],
    'beetle': [-1],
    'bell': [-1, -1],
    'bento': [-1, -1],
    'bicyclist': [-1, -1],
    'bikini': [-1, -1],
    'bird': [-1],
    'birthday': [-1, -1],
    'black_circle': [-1],
    'black_joker': [-1, -1],
    'black_large_square': [-1],
    'black_medium_small_square': [-1],
    'black_medium_square': [-1],
    'black_nib': [-1, -1],
    'black_small_square': [-1],
    'black_square_button': [-1],
    'blond_haired_man': [-1],
    'blond_haired_woman': [-1],
    'blossom': [-1],
    'blue_book': [-1, -1],
    'boar': [-1],
    'boat': [-1],
    'bomb': [-1, -1],
    'book': [-1, -1],
    'bookmark': [-1, -1],
    'bookmark_tabs': [-1, -1],
    'books': [-1, -1],
    'boot': [-1, -1],
    'bowling': [-1, -1],
    'boy': [7],
    'bread': [-1, -1],
    'breast_feeding': [-1],
    'bride_with_veil': [-1],
    'bridge_at_night': [-1],
    'briefcase': [-1, -1],
    'bug': [-1],
    'bulb': [-1, -1, -1],
    'cactus': [-1],
    'cake': [-1, -1],
    'calendar': [-1, -1],
    'calling': [-1, -1],
    'camel': [-1],
    'camera': [-1, -1],
    'cancer': [-1],
    'candy': [-1, -1],
    'capital_abcd': [-1],
    'capricorn': [-1],
    'card_index': [-1, -1],
    'carousel_horse': [-1],
    'cat': [-1],
    'cd': [-1, -1],
    'chart': [-1],
    'chart_with_downwards_trend': [-1, -1],
    'chart_with_upwards_trend': [-1, -1],
    'cherries': [-1, -1],
    'chestnut': [-1],
    'chicken': [-1],
    'child': [7],
    'children_crossing': [-1],
    'chocolate_bar': [-1, -1],
    'christmas_tree': [-1, -1],
    'church': [-1],
    'cinema': [-1],
    'cl': [-1],
    'clap': [-1],
    'clapper': [-1, -1],
    'clipboard': [-1, -1],
    'clock1': [-1],
    'clock10': [-1],
    'clock1030': [-1],
    'clock11': [-1],
    'clock1130': [-1],
    'clock12': [-1],
    'clock1230': [-1],
    'clock130': [-1],
    'clock2': [-1],
    'clock230': [-1],
    'clock3': [-1],
    'clock330': [-1],
    'clock4': [-1],
    'clock430': [-1],
    'clock5': [-1],
    'clock530': [-1],
    'clock6': [-1],
    'clock630': [-1],
    'clock7': [-1],
    'clock730': [-1],
    'clock8': [-1],
    'clock830': [-1],
    'clock9': [-1],
    'clock930': [-1],
    'closed_book': [-1, -1],
    'closed_lock_with_key': [-1, -1],
    'closed_umbrella': [-1, -1],
    'cloud': [-1],
    'clubs': [-1, -1],
    'cocktail': [-1, -1],
    'coffee': [-1, -1],
    'computer': [-1, -1],
    'confetti_ball': [-1, -1],
    'congratulations': [-1],
    'convenience_store': [-1],
    'cookie': [-1, -1],
    'cool': [-1],
    'copyright': [-1],
    'corn': [-1, -1],
    'cow': [-1],
    'credit_card': [-1, -1],
    'crescent_moon': [-1],
    'crown': [-1, -1],
    'crying_cat_face': [5],
    'crystal_ball': [-1, -1],
    'curly_loop': [-1],
    'currency_exchange': [-1],
    'curry': [-1, -1],
    'custard': [-1, -1],
    'customs': [-1],
    'cyclone': [-1],
    'dancer': [10],
    'dango': [-1, -1],
    'dart': [-1, -1, -1],
    'date': [-1, -1],
    'deciduous_tree': [-1],
    'department_store': [-1],
    'diamond_shape_with_a_dot_inside': [-1],
    'diamonds': [-1, -1],
    'do_not_litter': [-1],
    'dog': [-1],
    'dollar': [-1, -1],
    'dolls': [-1, -1],
    'dolphin': [-1],
    'door': [-1, -1],
    'doughnut': [-1, -1],
    'dress': [-1, -1],
    'dvd': [-1, -1],
    'e-mail': [-1, -1],
    'ear_of_rice': [-1],
    'earth_africa': [-1],
    'earth_americas': [-1],
    'earth_asia': [-1],
    'egg': [-1, -1],
    'eggplant': [-1, -1],
    'eight': [-1],
    'eight_pointed_black_star': [-1],
    'eight_spoked_asterisk': [-1],
    'electric_plug': [-1, -1],
    'elephant': [-1],
    'email': [-1, -1],
    'end': [-1],
    'envelope': [-1, -1],
    'euro': [-1, -1],
    'evergreen_tree': [-1],
    'eyeglasses': [-1, -1],
    'eyes': [-1],
    'factory': [-1],
    'fallen_leaf': [-1],
    'fast_forward': [-1],
    'fax': [-1, -1],
    'female_artist': [8],
    'female_astronaut': [8],
    'female_construction_worker': [8],
    'female_cook': [8],
    'female_detective': [8],
    'female_doctor': [8],
    'female_elf': [9],
    'female_factory_worker': [8],
    'female_fairy': [9],
    'female_farmer': [8],
    'female_firefighter': [8],
    'female_genie': [9],
    'female_guard': [8],
    'female_judge': [8],
    'female_mage': [9],
    'female_mechanic': [8],
    'female_office_worker': [8],
    'female_pilot': [8],
    'female_police_officer': [8],
    'female_scientist': [8],
    'female_singer': [8],
    'female_student': [8],
    'female_teacher': [8],
    'female_technologist': [8],
    'female_vampire': [9],
    'female_zombie': [9],
    'ferris_wheel': [-1],
    'file_folder': [-1, -1],
    'fireworks': [-1, -1],
    'first_quarter_moon': [-1],
    'first_quarter_moon_with_face': [-1],
    'fish': [-1],
    'fish_cake': [-1, -1],
    'fishing_pole_and_fish': [-1, -1],
    'five': [-1],
    'flags': [-1, -1],
    'flashlight': [-1, -1],
    'floppy_disk': [-1, -1],
    'flower_playing_cards': [-1, -1],
    'foggy': [-1],
    'football': [-1, -1],
    'fork_and_knife': [-1, -1],
    'fountain': [-1],
    'four': [-1],
    'free': [-1],
    'fried_shrimp': [-1, -1],
    'fries': [-1, -1],
    'frog': [-1],
    'full_moon': [-1],
    'full_moon_with_face': [-1],
    'game_die': [-1, -1],
    'gem': [-1, -1],
    'gemini': [-1],
    'ghost': [-1, -1],
    'gift': [-1, -1],
    'gift_heart': [-1, -1],
    'girl': [7],
    'globe_with_meridians': [-1],
    'golf': [-1, -1],
    'grapes': [-1, -1],
    'green_apple': [-1, -1],
    'green_book': [-1, -1],
    'guitar': [-1, -1],
    'gun': [-1, -1],
    'hamburger': [-1, -1],
    'hammer': [-1, -1],
    'hamster': [-1],
    'handbag': [-1, -1],
    'hash': [-1],
    'hatched_chick': [-1],
    'headphones': [-1, -1],
    'hear_no_evil': [6],
    'heart_decoration': [-1],
    'heart_eyes_cat': [5],
    'hearts': [-1, -1],
    'heavy_check_mark': [-1],
    'heavy_division_sign': [-1],
    'heavy_dollar_sign': [-1],
    'heavy_exclamation_mark': [-1],
    'heavy_minus_sign': [-1],
    'heavy_multiplication_x': [-1],
    'heavy_plus_sign': [-1, -1],
    'herb': [-1],
    'hibiscus': [-1],
    'high_brightness': [-1, -1],
    'high_heel': [-1, -1],
    'hocho': [-1, -1],
    'honey_pot': [-1, -1],
    'honeybee': [-1],
    'horse': [-1],
    'horse_racing': [-1, -1],
    'hospital': [-1],
    'hotel': [-1],
    'hourglass': [-1],
    'hourglass_flowing_sand': [-1],
    'house': [-1],
    'house_with_garden': [-1],
    'ice_cream': [-1, -1],
    'icecream': [-1, -1],
    'id': [-1],
    'ideograph_advantage': [-1],
    'inbox_tray': [-1, -1],
    'incoming_envelope': [-1, -1],
    'information_source': [-1],
    'interrobang': [-1],
    'iphone': [-1],
    'jack_o_lantern': [-1, -1],
    'japan': [-1],
    'jeans': [-1, -1],
    'joy_cat': [5],
    'key': [-1, -1],
    'keycap_ten': [-1],
    'kimono': [-1, -1],
    'kissing_cat': [5],
    'koala': [-1],
    'koko': [-1],
    'large_blue_circle': [-1, -1],
    'large_blue_diamond': [-1],
    'large_orange_diamond': [-1],
    'last_quarter_moon': [-1],
    'last_quarter_moon_with_face': [-1],
    'leaves': [-1],
    'ledger': [-1, -1],
    'left_luggage': [-1],
    'left_right_arrow': [-1],
    'leftwards_arrow_with_hook': [-1],
    'lemon': [-1, -1],
    'leo': [-1],
    'libra': [-1],
    'link': [-1],
    'lipstick': [-1, -1],
    'lock': [-1, -1],
    'lock_with_ink_pen': [-1, -1],
    'lollipop': [-1, -1],
    'loop': [-1, -1],
    'loudspeaker': [-1],
    'low_brightness': [-1, -1],
    'mag': [-1, -1],
    'mag_right': [-1, -1],
    'mahjong': [-1, -1],
    'mailbox': [-1, -1],
    'mailbox_closed': [-1, -1],
    'mailbox_with_mail': [-1, -1],
    'mailbox_with_no_mail': [-1, -1],
    'male_artist': [8],
    'male_astronaut': [8],
    'male_construction_worker': [8],
    'male_cook': [8],
    'male_detective': [8],
    'male_doctor': [8],
    'male_elf': [9],
    'male_factory_worker': [8],
    'male_fairy': [9],
    'male_farmer': [8],
    'male_firefighter': [8],
    'male_genie': [9],
    'male_guard': [8],
    'male_judge': [8],
    'male_mage': [9],
    'male_mechanic': [8],
    'male_office_worker': [8],
    'male_pilot': [8],
    'male_police_officer': [8],
    'male_scientist': [8],
    'male_singer': [8],
    'male_student': [8],
    'male_teacher': [8],
    'male_technologist': [8],
    'male_vampire': [9],
    'male_zombie': [9],
    'man': [7],
    'man_bowing': [10],
    'man_climbing': [10],
    'man_dancing': [10],
    'man_facepalming': [10],
    'man_frowning': [10],
    'man_gesturing_no': [10],
    'man_gesturing_ok': [10],
    'man_getting_haircut': [10],
    'man_getting_massage': [10],
    'man_in_lotus_position': [10],
    'man_in_steamy_room': [10],
    'man_in_tuxedo': [-1],
    'man_pouting': [10],
    'man_raising_hand': [10],
    'man_running': [10],
    'man_shrugging': [10],
    'man_tipping_hand': [10],
    'man_walking': [10],
    'man_wearing_turban': [-1],
    'man_with_bunny_ears_partying': [10],
    'man_with_gua_pi_mao': [-1],
    'mans_shoe': [-1, -1],
    'maple_leaf': [-1],
    'meat_on_bone': [-1, -1],
    'mega': [-1, -1],
    'melon': [-1, -1],
    'memo': [-1, -1],
    'mens': [-1],
    'mermaid': [9],
    'merman': [9],
    'metro': [-1],
    'microphone': [-1, -1],
    'microscope': [-1, -1],
    'milky_way': [-1],
    'minidisc': [-1, -1],
    'mobile_phone_off': [-1],
    'money_with_wings': [-1, -1],
    'moneybag': [-1, -1],
    'monkey': [-1],
    'monkey_face': [-1],
    'mortar_board': [-1, -1],
    'mount_fuji': [-1],
    'mountain_bicyclist': [-1, -1],
    'mouse': [-1],
    'movie_camera': [-1, -1],
    'mrs_claus': [9],
    'mushroom': [-1],
    'musical_keyboard': [-1, -1],
    'musical_score': [-1, -1],
    'mute': [-1],
    'name_badge': [-1, -1],
    'necktie': [-1, -1],
    'negative_squared_cross_mark': [-1],
    'new': [-1],
    'new_moon': [-1],
    'new_moon_with_face': [-1],
    'newspaper': [-1, -1],
    'ng': [-1],
    'nine': [-1],
    'no_bell': [-1, -1],
    'no_bicycles': [-1],
    'no_entry': [-1],
    'no_entry_sign': [-1],
    'no_mobile_phones': [-1],
    'no_pedestrians': [-1],
    'no_smoking': [-1],
    'non-potable_water': [-1],
    'notebook': [-1, -1],
    'notebook_with_decorative_cover': [-1, -1],
    'nut_and_bolt': [-1, -1],
    'o2': [-1],
    'ocean': [-1],
    'octocat': [-1],
    'octopus': [-1],
    'oden': [-1, -1],
    'office': [-1],
    'ok': [-1],
    'older_adult': [7],
    'older_man': [7],
    'older_woman': [7],
    'on': [-1],
    'one': [-1],
    'open_file_folder': [-1, -1],
    'ophiuchus': [-1],
    'orange_book': [-1, -1],
    'outbox_tray': [-1, -1],
    'package': [-1, -1],
    'page_facing_up': [-1, -1],
    'page_with_curl': [-1, -1],
    'pager': [-1, -1],
    'palm_tree': [-1],
    'panda_face': [-1],
    'paperclip': [-1, -1],
    'parking': [-1],
    'part_alternation_mark': [-1],
    'partly_sunny': [-1],
    'passport_control': [-1],
    'peach': [-1, -1],
    'pear': [-1, -1],
    'pencil': [-1, -1],
    'pencil2': [-1, -1],
    'penguin': [-1],
    'person_with_headscarf': [-1],
    'phone': [-1, -1],
    'pig': [-1],
    'pig_nose': [-1],
    'pill': [-1, -1],
    'pineapple': [-1, -1],
    'pisces': [-1],
    'pizza': [-1, -1],
    'post_office': [-1],
    'postal_horn': [-1, -1],
    'postbox': [-1, -1],
    'potable_water': [-1],
    'pouch': [-1, -1],
    'poultry_leg': [-1, -1],
    'pound': [-1, -1],
    'pouting_cat': [5],
    'pray': [-1],
    'pregnant_woman': [-1],
    'prince': [9],
    'princess': [9],
    'purse': [-1, -1],
    'pushpin': [-1, -1],
    'put_litter_in_its_place': [-1],
    'rabbit': [-1],
    'racehorse': [-1],
    'radio': [-1],
    'radio_button': [-1],
    'rainbow': [-1],
    'raised_hands': [-1],
    'ramen': [-1, -1],
    'recycle': [-1],
    'red_circle': [-1, -1],
    'registered': [-1],
    'repeat': [-1],
    'repeat_one': [-1],
    'restroom': [-1],
    'rewind': [-1],
    'ribbon': [-1, -1],
    'rice': [-1, -1],
    'rice_ball': [-1, -1],
    'rice_cracker': [-1, -1],
    'rice_scene': [-1],
    'ring': [-1, -1],
    'roller_coaster': [-1],
    'rugby_football': [-1, -1],
    'running_shirt_with_sash': [-1, -1],
    'sa': [-1],
    'sagittarius': [-1],
    'sailboat': [-1],
    'sake': [-1, -1],
    'sandal': [-1, -1],
    'santa': [9, -1, -1],
    'satellite': [-1],
    'saxophone': [-1, -1],
    'school': [-1],
    'school_satchel': [-1, -1],
    'scissors': [-1, -1],
    'scorpius': [-1],
    'scream_cat': [5],
    'scroll': [-1, -1],
    'seat': [-1, -1],
    'secret': [-1],
    'see_no_evil': [6],
    'seedling': [-1],
    'seven': [-1],
    'shaved_ice': [-1, -1],
    'sheep': [-1],
    'shell': [-1],
    'ship': [-1],
    'shipit': [-1],
    'shirt': [-1, -1],
    'shoe': [-1, -1],
    'shower': [-1, -1],
    'signal_strength': [-1],
    'six': [-1],
    'six_pointed_star': [-1],
    'ski': [-1, -1],
    'small_blue_diamond': [-1],
    'small_orange_diamond': [-1],
    'small_red_triangle': [-1],
    'small_red_triangle_down': [-1],
    'smile_cat': [5],
    'smiley_cat': [5],
    'smirk_cat': [5],
    'smoking': [-1, -1],
    'snail': [-1],
    'snake': [-1],
    'snowboarder': [-1, -1],
    'snowflake': [-1],
    'snowman': [-1],
    'soccer': [-1, -1],
    'soon': [-1],
    'sos': [-1],
    'sound': [-1],
    'space_invader': [-1, -1],
    'spades': [-1, -1],
    'spaghetti': [-1, -1],
    'sparkle': [-1],
    'sparkler': [-1, -1],
    'speak_no_evil': [6],
    'speaker': [-1],
    'speedboat': [-1],
    'squirrel': [-1],
    'statue_of_liberty': [-1],
    'stew': [-1, -1],
    'straight_ruler': [-1, -1],
    'strawberry': [-1, -1],
    'sun_with_face': [-1],
    'sunny': [-1],
    'sunrise': [-1],
    'sunrise_over_mountains': [-1],
    'surfer': [-1, -1],
    'sushi': [-1, -1],
    'sweet_potato': [-1, -1],
    'swimmer': [-1, -1],
    'symbols': [-1],
    'syringe': [-1, -1],
    'tada': [-1, -1, -1],
    'tanabata_tree': [-1, -1],
    'tangerine': [-1, -1],
    'taurus': [-1],
    'tea': [-1, -1],
    'telephone': [-1, -1],
    'telephone_receiver': [-1, -1],
    'telescope': [-1, -1],
    'tennis': [-1, -1],
    'tent': [-1],
    'three': [-1],
    'thumbsup': [-1],
    'tiger': [-1],
    'tm': [-1],
    'toilet': [-1, -1],
    'tokyo_tower': [-1],
    'tomato': [-1, -1],
    'top': [-1],
    'tophat': [-1, -1],
    'triangular_ruler': [-1, -1],
    'trident': [-1],
    'trophy': [-1, -1],
    'tropical_drink': [-1, -1],
    'tropical_fish': [-1],
    'trumpet': [-1, -1],
    'tshirt': [-1, -1],
    'turtle': [-1],
    'tv': [-1, -1],
    'twisted_rightwards_arrows': [-1],
    'two': [-1],
    'u5272': [-1],
    'u5408': [-1],
    'u55b6': [-1],
    'u6307': [-1],
    'u6708': [-1],
    'u6709': [-1],
    'u6e80': [-1],
    'u7121': [-1],
    'u7533': [-1],
    'u7981': [-1],
    'u7a7a': [-1],
    'umbrella': [-1],
    'underage': [-1],
    'unlock': [-1, -1],
    'up': [-1],
    'vhs': [-1, -1],
    'vibration_mode': [-1],
    'video_camera': [-1, -1],
    'video_game': [-1, -1],
    'violin': [-1, -1],
    'virgo': [-1],
    'volcano': [-1],
    'vs': [-1],
    'waning_crescent_moon': [-1],
    'waning_gibbous_moon': [-1],
    'watch': [-1],
    'watermelon': [-1, -1],
    'wave': [-1],
    'wavy_dash': [-1],
    'waxing_crescent_moon': [-1],
    'waxing_gibbous_moon': [-1],
    'wc': [-1],
    'wedding': [-1],
    'whale': [-1],
    'wheelchair': [-1],
    'white_check_mark': [-1],
    'white_circle': [-1, -1],
    'white_flower': [-1],
    'white_large_square': [-1],
    'white_medium_small_square': [-1],
    'white_medium_square': [-1],
    'white_small_square': [-1],
    'white_square_button': [-1],
    'wind_chime': [-1, -1],
    'wine_glass': [-1, -1],
    'wolf': [-1],
    'woman': [7],
    'woman_bowing': [10],
    'woman_climbing': [10],
    'woman_facepalming': [10],
    'woman_frowning': [10],
    'woman_gesturing_no': [10],
    'woman_gesturing_ok': [10],
    'woman_getting_haircut': [10],
    'woman_getting_massage': [10],
    'woman_in_lotus_position': [10],
    'woman_in_steamy_room': [10],
    'woman_pouting': [10],
    'woman_raising_hand': [10],
    'woman_running': [10],
    'woman_shrugging': [10],
    'woman_tipping_hand': [10],
    'woman_walking': [10],
    'woman_wearing_turban': [-1],
    'woman_with_bunny_ears_partying': [10],
    'womans_clothes': [-1, -1],
    'womans_hat': [-1, -1],
    'womens': [-1],
    'wrench': [-1, -1],
    'yen': [-1, -1],
    'zap': [-1],
    'zero': [-1]}
