
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class MedicalSpans(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'MedicalSpans',
            'filename': 'medical_spans',
            'queries': ['spans.sparql'],
            'transformers': ['spans']},
 'source': 'medical.owl',
 'time': '2022-04-27 21:15:55.865856'}

    __data = {
    'adrenal': [   {   'canon': 'adrenal_gland',
                       'content': {'gland'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'age': [   {   'canon': 'age_bucket',
                   'content': {'bucket'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'blood': [   {   'canon': 'blood_transfusion',
                     'content': {'transfusion'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'bodily': [   {   'canon': 'bodily_event',
                      'content': {'event'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'body': [   {   'canon': 'fluid_discharge',
                    'content': {'fluid'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'breast': [   {   'canon': 'breast_milk',
                      'content': {'milk'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'congenital': [   {   'canon': 'congenital_cytomegalovirus',
                          'content': {'cytomegalovirus'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'emotional': [   {   'canon': 'emotional_condition',
                         'content': {'condition'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True},
                     {   'canon': 'emotional_condition',
                         'content': {'state'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'fluid': [   {   'canon': 'fluid_discharge',
                     'content': {'discharge'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'health': [   {   'canon': 'health_loss',
                      'content': {'loss'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'health_problem',
                      'content': {'problem'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'health_gain',
                      'content': {'gain'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'health_event',
                      'content': {'event'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'healthy': [   {   'canon': 'healthy_immunity',
                       'content': {'immunity'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'healthy_immunity',
                       'content': {'system', 'person', 'immune'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'hearing': [   {   'canon': 'hearing_loss',
                       'content': {'loss'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'immune': [   {   'canon': 'immune_system',
                      'content': {'system'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'immune_condition',
                      'content': {'condition'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'long': [   {   'canon': 'long_term',
                    'content': {'term'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'mammary': [   {   'canon': 'mammary_gland',
                       'content': {'gland'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'medical': [   {   'canon': 'medical_procedure',
                       'content': {'procedure'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'medical_test',
                       'content': {'test'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'mental': [   {   'canon': 'mental_condition',
                      'content': {'condition'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'mental_condition',
                      'content': {'state'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'organ': [   {   'canon': 'organ_transplant',
                     'content': {'transplant'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'parathyroid': [   {   'canon': 'parathyroid_gland',
                           'content': {'gland'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'part': [   {   'canon': 'part_of_body',
                    'content': {'body'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'physical': [   {   'canon': 'physical_condition',
                        'content': {'condition'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'physical_condition',
                        'content': {'state'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'pituitary': [   {   'canon': 'pituitary_gland',
                         'content': {'gland'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'qualifiable': [   {   'canon': 'qualifiable_state',
                           'content': {'state'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True},
                       {   'canon': 'qualifiable_time',
                           'content': {'time'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'qualified': [   {   'canon': 'qualified_age_bucket',
                         'content': {'bucket', 'age'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'quantifiable': [   {   'canon': 'quantifiable_time',
                            'content': {'time'},
                            'distance': 3,
                            'forward': True,
                            'reverse': True},
                        {   'canon': 'quantifiable_state',
                            'content': {'state'},
                            'distance': 3,
                            'forward': True,
                            'reverse': True}],
    'quantified': [   {   'canon': 'quantified_age_bucket',
                          'content': {'bucket', 'age'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'short': [   {   'canon': 'short_term',
                     'content': {'term'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'skeletal': [   {   'canon': 'skeletal_muscle',
                        'content': {'muscle'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'state': [   {   'canon': 'state_of_being',
                     'content': {'being'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'state_of_capability',
                     'content': {'capability'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'taste': [   {   'canon': 'taste_loss',
                     'content': {'loss'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'vision': [   {   'canon': 'vision_loss',
                      'content': {'loss'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'weak': [   {   'canon': 'weak_immunity',
                    'content': {'immunity'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'weakened': [   {   'canon': 'weak_immunity',
                        'content': {'systems', 'immune'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'young': [   {   'canon': 'young_child',
                     'content': {'child'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}]}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
