
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class NursingSpans(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'NursingSpans',
            'filename': 'nursing_spans',
            'queries': ['spans.sparql'],
            'transformers': ['spans']},
 'source': 'nursing.owl',
 'time': '2022-05-20 17:02:25.062704'}

    __data = {
    'aa': [   {   'canon': 'associates_degree',
                  'content': {'degree'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    'acute': [   {   'canon': 'acute_care',
                     'content': {'care'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'advanced': [   {   'canon': 'clinical_training',
                        'content': {'training', 'clinical'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'advanced_practice_registered_nurse',
                        'content': {'practice', 'nurse', 'registered'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'american': [   {   'canon': 'american_nurses_association',
                        'content': {'association', 'nurses'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'american_nurses_association',
                        'content': {'nursing', 'association'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'american_association_of_colleges_of_nursing',
                        'content': {'nursing', 'association', 'colleges'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'associate': [   {   'canon': 'associates_degree',
                         'content': {'degree'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    "associate's": [   {   'canon': 'associates_degree',
                           'content': {'degree'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'associates': [   {   'canon': 'associates_degree',
                          'content': {'degree'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'baccalaureate': [   {   'canon': 'bachelors_degree',
                             'content': {'level'},
                             'distance': 3,
                             'forward': True,
                             'reverse': True}],
    'bachelor': [   {   'canon': 'bachelor_of_arts',
                        'content': {'arts'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'bachelors_degree',
                        'content': {'degree'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'bachelor_of_science_in_nursing',
                        'content': {'nursing', 'science'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'bachelor_of_science',
                        'content': {'science'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    "bachelor's": [   {   'canon': 'bachelors_degree',
                          'content': {'degree'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'bachelors': [   {   'canon': 'bachelors_degree',
                         'content': {'degree'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'care': [   {   'canon': 'care_event',
                    'content': {'event'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'catholic': [   {   'canon': 'catholic_church',
                        'content': {'church'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'clinical': [   {   'canon': 'clinical_training',
                        'content': {'training'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'clinical_training',
                        'content': {'course'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'clinical_competency',
                        'content': {'competency'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'clinical_evaluation',
                        'content': {'evaluation'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'clinical_outcome',
                        'content': {'outcome'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'clinical_outcome_evaluation',
                        'content': {'evaluation', 'outcome'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'code': [   {   'canon': 'ethical_practice',
                    'content': {'practice', 'ethical'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'continued': [   {   'canon': 'continuous_learning',
                         'content': {'learning'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'continuous': [   {   'canon': 'continuous_learning',
                          'content': {'learning'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'doctoral': [   {   'canon': 'doctoral_degree',
                        'content': {'degree'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'doctoral_degree',
                        'content': {'program', 'degree'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'elapsed': [   {   'canon': 'elapsed_time',
                       'content': {'time'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'elderly': [   {   'canon': 'elderly_patient',
                       'content': {'patient'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'emergency': [   {   'canon': 'emergency_room',
                         'content': {'room'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'ethical': [   {   'canon': 'ethical_practice',
                       'content': {'practice'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'facility': [   {   'canon': 'facility_closure',
                        'content': {'closure'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'fail': [   {   'canon': 'fail_to_rescue_rate',
                    'content': {'rescue', 'rate'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'failure-to-rescue': [   {   'canon': 'fail_to_rescue_rate',
                                 'content': {'rates'},
                                 'distance': 3,
                                 'forward': True,
                                 'reverse': True}],
    'fair': [   {   'canon': 'fair_pay',
                    'content': {'pay'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'family': [   {   'canon': 'family_nurse_practitioner',
                      'content': {'nurse', 'practitioner'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'female': [   {   'canon': 'female_patient',
                      'content': {'patient'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'florence': [   {   'canon': 'florence_nightingale',
                        'content': {'nightingale'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'gender': [   {   'canon': 'gender_bias',
                      'content': {'bias'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'geopolitical': [   {   'canon': 'geopolitical_entity',
                            'content': {'entity'},
                            'distance': 3,
                            'forward': True,
                            'reverse': True}],
    'health': [   {   'canon': 'health_care_provider',
                      'content': {'care', 'provider'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'health_care_specialist',
                      'content': {'care', 'specialist'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'health_care_specialist',
                      'content': {'care', 'provider'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'health_care',
                      'content': {'care'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'health_care_quality',
                      'content': {'care', 'quality'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'health_care_education',
                      'content': {'care', 'education'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'health_care_reform',
                      'content': {'care', 'reform'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'health_department',
                      'content': {'department'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'historical': [   {   'canon': 'historical_nursing',
                          'content': {'nursing'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'johnson': [   {   'canon': 'johnson_and_johnson',
                       'content': {'johnson'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'johnson_and_johnson',
                       'content': {'johnson', '&'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'labor': [   {   'canon': 'labor_event',
                     'content': {'event'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'long': [   {   'canon': 'long_term_health_care',
                    'content': {'care', 'health', 'term'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'long-term': [   {   'canon': 'long_term_health_care',
                         'content': {'care', 'health'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'male': [   {   'canon': 'male_patient',
                    'content': {'patient'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'master': [   {   'canon': 'master_of_science',
                      'content': {'science'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'master_of_science_in_nursing',
                      'content': {'nursing', 'science'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'masters_degree',
                      'content': {'degree'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'master_of_arts',
                      'content': {'arts'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    "master's": [   {   'canon': 'masters_degree',
                        'content': {'degree'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'masters': [   {   'canon': 'masters_degree',
                       'content': {'degree'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'medical': [   {   'canon': 'medical_building',
                       'content': {'building'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'medical_facility_closure',
                       'content': {'facility', 'closure'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'mental': [   {   'canon': 'mental_health',
                      'content': {'health'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'modern': [   {   'canon': 'modern_nursing',
                      'content': {'nursing'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'mortality': [   {   'canon': 'mortality_rate',
                         'content': {'rate'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'national': [   {   'canon': 'national_certification',
                        'content': {'certification'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'nurse': [   {   'canon': 'nurse_educator',
                     'content': {'educator'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True},
                 {   'canon': 'nurse_practitioner',
                     'content': {'practitioner'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'nursing': [   {   'canon': 'nursing_school',
                       'content': {'school'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'nursing_education',
                       'content': {'education'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'nursing_home',
                       'content': {'home'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'nursing_student',
                       'content': {'student'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'nursing_diploma',
                       'content': {'diploma'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'outcome': [   {   'canon': 'outcome_evaluation',
                       'content': {'evaluation'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'patient': [   {   'canon': 'patient_treatment',
                       'content': {'treatment'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'patient_care',
                       'content': {'care'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'patient_care',
                       'content': {'care', 'coordination'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'patient_treatment_plan',
                       'content': {'treatment', 'plan'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'pediactric': [   {   'canon': 'pediactric_patient',
                          'content': {'patient'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'peer': [   {   'canon': 'peer_review',
                    'content': {'review'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'periodic': [   {   'canon': 'peer_review',
                        'content': {'peer', 'review'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'personal': [   {   'canon': 'personal_touch',
                        'content': {'touch'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'political': [   {   'canon': 'political_group',
                         'content': {'group'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True},
                     {   'canon': 'political_activity',
                         'content': {'activity'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'primary': [   {   'canon': 'primary_care',
                       'content': {'care'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'professional': [   {   'canon': 'professional_development',
                            'content': {'development'},
                            'distance': 3,
                            'forward': True,
                            'reverse': True}],
    'protestant': [   {   'canon': 'protestant_church',
                          'content': {'church'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'psychiatric': [   {   'canon': 'psychiatric_mental_health_nurse_practitioner',
                           'content': {   'health',
                                          'mental',
                                          'nurse',
                                          'practitioner'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'public': [   {   'canon': 'public_health_department',
                      'content': {'health', 'department'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'quantifiable': [   {   'canon': 'quantifiable_measurement',
                            'content': {'measurement'},
                            'distance': 3,
                            'forward': True,
                            'reverse': True}],
    'race': [   {   'canon': 'racial_bias',
                    'content': {'bias'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'racial': [   {   'canon': 'racial_bias',
                      'content': {'bias'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'readmission': [   {   'canon': 'readmission_rate',
                           'content': {'rate'},
                           'distance': 3,
                           'forward': True,
                           'reverse': True}],
    'registered': [   {   'canon': 'registered_nurse',
                          'content': {'nurse'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'religious': [   {   'canon': 'religious_group',
                         'content': {'group'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'soft': [   {   'canon': 'soft_skill',
                    'content': {'skill'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'spanish': [   {   'canon': 'spanish_hospital',
                       'content': {'hospital'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'staffing': [   {   'canon': 'staffing_level',
                        'content': {'level'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True},
                    {   'canon': 'staffing_shortage',
                        'content': {'shortage'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'training': [   {   'canon': 'training_event',
                        'content': {'event'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'treatment': [   {   'canon': 'treatment_event',
                         'content': {'event'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'urgent': [   {   'canon': 'urgent_care',
                      'content': {'care'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'urgent_care',
                      'content': {'care', 'clinic'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'urgent_care',
                      'content': {'care', 'site'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'work': [   {   'canon': 'work_of_art',
                    'content': {'art'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}]}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
