
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class NursingLookup(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'NursingLookup',
            'filename': 'nursing_lookup',
            'files': ['nursing.txt'],
            'queries': ['lookup.sparql'],
            'transformers': ['lowercase', 'lookup']},
 'source': 'nursing.owl',
 'time': '2022-05-20 17:02:25.014704'}

    __data = {
    1: [   'certification',
           'associations',
           'organization',
           'apothecaries',
           'development',
           'readmission',
           'association',
           'reformation',
           'temporarily',
           'condition\r\n',
           'regulations',
           'evaluations',
           'nationality',
           'courseworks',
           'assocations',
           'departments',
           'coursework',
           'evaluation',
           'competency',
           'apothecary',
           'regulation',
           'pharmacist',
           'specialist',
           'profession',
           'department',
           'hospitals',
           'education',
           'condition',
           'temporary',
           'physician',
           'admission',
           'practices',
           'providers',
           'continent',
           'americans',
           'permanent',
           'learning',
           'provider',
           'location',
           'training',
           'receiver',
           'hospital',
           'staffing',
           'cardinal',
           'practice',
           'american',
           'colleges',
           'artefact',
           'activity',
           "master's",
           'educator',
           'duration',
           'shortage',
           'building',
           'quantity',
           'artifact',
           'pharmacy',
           'outcomes',
           'language',
           'doctoral',
           'company',
           'nursing',
           'surgery',
           'schools',
           'ordinal',
           'percent',
           'country',
           'quality',
           'courses',
           'edifice',
           'trained',
           'college',
           'chemist',
           'closure',
           'century',
           'outcome',
           'diploma',
           'student',
           'spanish',
           'product',
           'surgeon',
           'airport',
           'clinics',
           'patient',
           'empathy',
           'history',
           'action',
           'rule\r\n',
           'course',
           'nursed',
           'person',
           'plan\r\n',
           'spains',
           'salary',
           'strike',
           'reform',
           'europe',
           'clinic',
           'school',
           'health',
           'church',
           'nurses',
           'rules',
           'pmhnp',
           'nurse',
           'agent',
           'group',
           'sites',
           'staff',
           'spain',
           'money',
           'skill',
           'homes',
           'event',
           'rooms',
           'aacn',
           'site',
           'bias',
           'plan',
           'rule',
           '"rn"',
           'city',
           'time',
           'room',
           'regs',
           'home',
           'date',
           'aprn',
           'msc',
           'nps',
           'phd',
           'bsn',
           'rns',
           'fnp',
           'pay',
           'j&j',
           'msn',
           'ana',
           'rn',
           'er',
           'np'],
    2: [   'psychiatric_mental_health_nurse practitioner',
           'advanced_practice_registered nurse',
           'american_nursing association',
           'american_nurses association',
           'clinical_outcome evaluation',
           'advanced_clinical training',
           'patient_care coordination',
           'family_nurse practitioner',
           'medical_facility closure',
           'quantifiable measurement',
           'professional development',
           'public_health department',
           'failure-to-rescue rates',
           'doctoral_degree program',
           'health_care specialist',
           'national certification',
           'patient_treatment plan',
           'long-term_health care',
           'long_term_health care',
           'health_care education',
           'long-term health_care',
           'florence nightingale',
           'health_care provider',
           'periodic_peer review',
           'baccalaureate level',
           'clinical evaluation',
           'geopolitical entity',
           'continuous learning',
           'clinical competency',
           'health_care quality',
           'nurse practitioner',
           "associate's degree",
           'continued learning',
           'outcome evaluation',
           'health_care reform',
           'urgent_care clinic',
           'pediactric patient',
           'historical nursing',
           'political activity',
           'patient treatment',
           'staffing shortage',
           'associates degree',
           'nursing education',
           "bachelor's degree",
           'health department',
           'clinical training',
           'johnson_& johnson',
           'protestant church',
           'facility closure',
           'bachelors degree',
           'associate degree',
           'readmission rate',
           'medical building',
           'registered nurse',
           'spanish hospital',
           'clinical outcome',
           'urgent_care site',
           'ethical practice',
           'religious group',
           'nursing student',
           'political group',
           'nursing diploma',
           'catholic church',
           'treatment event',
           'elderly patient',
           'doctoral degree',
           "master's degree",
           'clinical course',
           'bachelor degree',
           'modern nursing',
           'nursing school',
           'personal touch',
           'mortality rate',
           'nurse educator',
           'training event',
           'female patient',
           'masters degree',
           'emergency room',
           'staffing level',
           'mental health',
           'master degree',
           'nursing home',
           'elapsed time',
           'patient care',
           'male patient',
           'primary care',
           'labor event',
           'gender bias',
           'urgent care',
           'racial bias',
           'peer review',
           'health care',
           'course work',
           'care event',
           'soft skill',
           'acute care',
           'aa degree',
           'race bias',
           'fair pay'],
    3: [   'american nursing association',
           'american nurses association',
           'clinical outcome evaluation',
           'advanced clinical training',
           'family nurse practitioner',
           'patient care coordination',
           'medical facility closure',
           'public health department',
           'doctoral degree program',
           'patient treatment plan',
           'health care specialist',
           'health care education',
           'long-term health care',
           'periodic peer review',
           'health care provider',
           'bachelor of science',
           'johnson and johnson',
           'health care quality',
           'health care reform',
           'urgent care clinic',
           'johnson & johnson',
           'master of science',
           'bachelor of arts',
           'urgent care site',
           'master of arts',
           'set to close',
           'work of art'],
    4: [   'advanced practice registered nurse',
           'code for ethical practice',
           'long term health care',
           'fail to rescue rate'],
    5: [   'psychiatric mental health nurse practitioner',
           'bachelor of science in nursing',
           'master of science in nursing'],
    6: ['american association of colleges of nursing']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
