
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class NursingLabelsRev(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'NursingLabels',
            'filename': 'nursing_labels',
            'queries': ['labels.sparql'],
            'reverse': True,
            'transformers': ['labels']},
 'source': 'nursing.owl',
 'time': '2022-05-20 17:02:25.372703'}

    __data = {
    'Activity': ['activity'],
    'Acute Care': ['acute_care'],
    'Admission': ['admission'],
    'Advanced Practice Registered Nurse': [   'advanced_practice_registered_nurse'],
    'Agent': ['agent'],
    'Airport': ['airport'],
    'American': ['american'],
    'American Association of Colleges of Nursing': [   'american_association_of_colleges_of_nursing'],
    'American Nurses Association': ['american_nurses_association'],
    'Apothecary': ['apothecary'],
    'Artifact': ['artifact'],
    "Associate's Degree": ['associates_degree'],
    'Association': ['association'],
    'Bachelor of Arts': ['bachelor_of_arts'],
    'Bachelor of Science': ['bachelor_of_science'],
    'Bachelor of Science in Nursing': ['bachelor_of_science_in_nursing'],
    "Bachelor's Degree": ['bachelors_degree'],
    'Bias': ['bias'],
    'Building': ['building'],
    'Cardinal': ['cardinal'],
    'Care Event': ['care_event'],
    'Catholic Church': ['catholic_church'],
    'Century': ['century'],
    'Certification': ['certification'],
    'Chemist': ['chemist'],
    'Church': ['church'],
    'City': ['city'],
    'Clinic': ['clinic'],
    'Clinical Competency': ['clinical_competency'],
    'Clinical Evaluation': ['clinical_evaluation'],
    'Clinical Outcome': ['clinical_outcome'],
    'Clinical Outcome Evaluation': ['clinical_outcome_evaluation'],
    'Clinical Training': ['clinical_training'],
    'Closure': ['closure'],
    'College': ['college'],
    'Company': ['company'],
    'Competency': ['competency'],
    'Condition': ['condition'],
    'Continent': ['continent'],
    'Continuous Learning': ['continuous_learning'],
    'Country': ['country'],
    'Course': ['course'],
    'Date': ['date'],
    'Department': ['department'],
    'Development': ['development'],
    'Diploma': ['diploma'],
    'Doctoral Degree': ['doctoral_degree'],
    'Education': ['education'],
    'Educator': ['educator'],
    'Elapsed Time': ['elapsed_time'],
    'Elderly Patient': ['elderly_patient'],
    'Emergency Room': ['emergency_room'],
    'Empathy': ['empathy'],
    'Ethical Practice': ['ethical_practice'],
    'Europe': ['europe'],
    'Evaluation': ['evaluation'],
    'Event': ['event'],
    'Facility Closure': ['facility_closure'],
    'Fail To Rescue Rate': ['fail_to_rescue_rate'],
    'Fair Pay': ['fair_pay'],
    'Family Nurse Practitioner': ['family_nurse_practitioner'],
    'Female Patient': ['female_patient'],
    'Florence Nightingale': ['florence_nightingale'],
    'Gender Bias': ['gender_bias'],
    'Geopolitical Entity': ['geopolitical_entity'],
    'Group': ['group'],
    'Health': ['health'],
    'Health Care': ['health_care'],
    'Health Care Education': ['health_care_education'],
    'Health Care Provider': ['health_care_provider'],
    'Health Care Quality': ['health_care_quality'],
    'Health Care Reform': ['health_care_reform'],
    'Health Care Specialist': ['health_care_specialist'],
    'Health Department': ['health_department'],
    'Historical Nursing': ['historical_nursing'],
    'History': ['history'],
    'Home': ['home'],
    'Hospital': ['hospital'],
    'Johnson & Johnson': ['johnson_and_johnson'],
    'Labor Event': ['labor_event'],
    'Language': ['language'],
    'Learning': ['learning'],
    'Location': ['location'],
    'Long Term Health Care': ['long_term_health_care'],
    'Male Patient': ['male_patient'],
    'Master of Arts': ['master_of_arts'],
    'Master of Science': ['master_of_science'],
    'Master of Science in Nursing': ['master_of_science_in_nursing'],
    "Master's Degree": ['masters_degree'],
    'Medical Building': ['medical_building'],
    'Medical Facility Closure': ['medical_facility_closure'],
    'Mental Health': ['mental_health'],
    'Modern Nursing': ['modern_nursing'],
    'Money': ['money'],
    'Mortality Rate': ['mortality_rate'],
    'National Certification': ['national_certification'],
    'Nationality': ['nationality'],
    'Nurse': ['nurse'],
    'Nurse Educator': ['nurse_educator'],
    'Nurse Practitioner': ['nurse_practitioner'],
    'Nursing': ['nursing'],
    'Nursing Diploma': ['nursing_diploma'],
    'Nursing Education': ['nursing_education'],
    'Nursing Home': ['nursing_home'],
    'Nursing School': ['nursing_school'],
    'Nursing Student': ['nursing_student'],
    'Ordinal': ['ordinal'],
    'Organization': ['organization'],
    'Outcome': ['outcome'],
    'Outcome Evaluation': ['outcome_evaluation'],
    'Patient': ['patient'],
    'Patient Care': ['patient_care'],
    'Patient Treatment': ['patient_treatment'],
    'Patient Treatment Plan': ['patient_treatment_plan'],
    'Pay': ['pay'],
    'Pediactric Patient': ['pediactric_patient'],
    'Peer Review': ['peer_review'],
    'Percent': ['percent'],
    'Permanent': ['permanent'],
    'Person': ['person'],
    'Personal Touch': ['personal_touch'],
    'Pharmacist': ['pharmacist'],
    'Pharmacy': ['pharmacy'],
    'Physician': ['physician'],
    'Plan': ['plan'],
    'Political Activity': ['political_activity'],
    'Political Group': ['political_group'],
    'Practice': ['practice'],
    'Primary Care': ['primary_care'],
    'Product': ['product'],
    'Profession': ['profession'],
    'Professional Development': ['professional_development'],
    'Protestant Church': ['protestant_church'],
    'Provider': ['provider'],
    'Psychiatric Mental Health Nurse Practitioner': [   'psychiatric_mental_health_nurse_practitioner'],
    'Public Health Department': ['public_health_department'],
    'Quality': ['quality'],
    'Quantifiable Measurement': ['quantifiable_measurement'],
    'Quantity': ['quantity'],
    'Racial Bias': ['racial_bias'],
    'Readmission': ['readmission'],
    'Readmission Rate': ['readmission_rate'],
    'Receiver': ['receiver'],
    'Reform': ['reform'],
    'Registered Nurse': ['registered_nurse'],
    'Regulation': ['regulation'],
    'Religious Group': ['religious_group'],
    'Room': ['room'],
    'Rule': ['rule'],
    'School': ['school'],
    'Shortage': ['shortage'],
    'Site': ['site'],
    'Skill': ['skill'],
    'Soft Skill': ['soft_skill'],
    'Spain': ['spain'],
    'Spanish': ['spanish'],
    'Spanish Hospital': ['spanish_hospital'],
    'Specialist': ['specialist'],
    'Staff': ['staff'],
    'Staffing': ['staffing'],
    'Staffing Level': ['staffing_level'],
    'Staffing Shortage': ['staffing_shortage'],
    'Strike': ['strike'],
    'Student': ['student'],
    'Surgeon': ['surgeon'],
    'Surgery': ['surgery'],
    'Temporary': ['temporary'],
    'Time': ['time'],
    'Training': ['training'],
    'Training Event': ['training_event'],
    'Treatment Event': ['treatment_event'],
    'Urgent Care': ['urgent_care'],
    'Work of Art': ['work_of_art']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
