
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class NursingSynonymsRev(object):

    @staticmethod
    def prov() -> dict:
        return {
            'action': ['router.py',
                       'plac_core.py',
                       'owl2py_orchestrator.py',
                       'generate_runtime_dictionaries.py',
                       'generate_runtime_dictionary.py',
                       'owl_data_load_dict.py',
                       'common_utils.py'],
            'config': {'classname': 'NursingSynonyms',
                       'filename': 'nursing_synonyms',
                       'files': ['nursing.txt'],
                       'queries': ['synonyms.sparql'],
                       'reverse': True,
                       'transformers': ['lowercase', 'synonyms']},
            'source': 'nursing.owl',
            'time': '2022-05-20 17:02:25.334704'}

    __data = {
        '"rn"': ['nursing'],
        'aa degree': ['associates_degree'],
        'aacn': ['american_association_of_colleges_of_nursing'],
        'action': ['activity'],
        'activity': ['activity'],
        'acute care': ['acute_care'],
        'admission': ['admission'],
        'advanced clinical training': ['clinical_training'],
        'advanced practice registered nurse': ['advanced_practice_registered_nurse'],
        'agent': ['agent'],
        'airport': ['airport'],
        'american': ['american'],
        'american association of colleges of nursing': ['american_association_of_colleges_of_nursing'],
        'american nurses association': ['american_nurses_association'],
        'american nursing association': ['american_nurses_association'],
        'americans': ['american'],
        'ana': ['american_nurses_association'],
        'apothecaries': ['apothecary'],
        'apothecary': ['apothecary'],
        'aprn': ['advanced_practice_registered_nurse'],
        'artefact': ['artifact'],
        'artifact': ['artifact'],
        'assocations': ['association'],
        'associate degree': ['associates_degree'],
        "associate's degree": ['associates_degree'],
        'association': ['association'],
        'associations': ['association'],
        'baccalaureate level': ['bachelors_degree'],
        'bachelor degree': ['bachelors_degree'],
        'bachelor of arts': ['bachelor_of_arts'],
        'bachelor of science': ['bachelor_of_science'],
        'bachelor of science in nursing': ['bachelor_of_science_in_nursing'],
        "bachelor's degree": ['bachelors_degree'],
        'bias': ['bias'],
        'bsn': ['bachelor_of_science_in_nursing'],
        'building': ['building'],
        'cardinal': ['cardinal'],
        'care event': ['care_event'],
        'catholic church': ['catholic_church'],
        'century': ['century'],
        'certification': ['certification'],
        'chemist': ['chemist'],
        'church': ['church'],
        'city': ['city'],
        'clinic': ['clinic'],
        'clinical competency': ['clinical_competency'],
        'clinical course': ['clinical_training'],
        'clinical evaluation': ['clinical_evaluation'],
        'clinical outcome': ['clinical_outcome'],
        'clinical outcome evaluation': ['clinical_outcome_evaluation'],
        'clinical training': ['clinical_training'],
        'clinics': ['clinic'],
        'closure': ['closure'],
        'code for ethical practice': ['ethical_practice'],
        'college': ['college'],
        'colleges': ['college'],
        'company': ['company'],
        'competency': ['competency'],
        'condition\r\n': ['condition'],
        'continent': ['continent'],
        'continued learning': ['continuous_learning'],
        'continuous learning': ['continuous_learning'],
        'country': ['country'],
        'course': ['course'],
        'course work': ['course'],
        'courses': ['course'],
        'coursework': ['course'],
        'courseworks': ['course'],
        'date': ['date'],
        'department': ['department'],
        'departments': ['department'],
        'development': ['development'],
        'diploma': ['diploma'],
        'doctoral': ['doctoral_degree'],
        'doctoral degree': ['doctoral_degree'],
        'doctoral degree program': ['doctoral_degree'],
        'duration': ['elapsed_time'],
        'edifice': ['building'],
        'education': ['education'],
        'educator': ['educator'],
        'elapsed time': ['elapsed_time'],
        'elderly patient': ['elderly_patient'],
        'emergency room': ['emergency_room'],
        'empathy': ['empathy'],
        'er': ['emergency_room'],
        'ethical practice': ['ethical_practice'],
        'europe': ['europe'],
        'evaluation': ['evaluation'],
        'evaluations': ['evaluation'],
        'event': ['event'],
        'facility closure': ['facility_closure'],
        'fail to rescue rate': ['fail_to_rescue_rate'],
        'failure-to-rescue rates': ['fail_to_rescue_rate'],
        'fair pay': ['fair_pay'],
        'family nurse practitioner': ['family_nurse_practitioner'],
        'female patient': ['female_patient'],
        'florence nightingale': ['florence_nightingale'],
        'fnp': ['family_nurse_practitioner'],
        'gender bias': ['gender_bias'],
        'geopolitical entity': ['geopolitical_entity'],
        'group': ['group'],
        'health': ['health'],
        'health care': ['health_care'],
        'health care education': ['health_care_education'],
        'health care provider': ['health_care_provider', 'health_care_specialist'],
        'health care quality': ['health_care_quality'],
        'health care reform': ['health_care_reform'],
        'health care specialist': ['health_care_specialist'],
        'health department': ['health_department'],
        'historical nursing': ['historical_nursing'],
        'history': ['history'],
        'home': ['home'],
        'homes': ['home'],
        'hospital': ['hospital'],
        'hospitals': ['hospital'],
        'j&j': ['johnson_and_johnson'],
        'johnson & johnson': ['johnson_and_johnson'],
        'johnson and johnson': ['johnson_and_johnson'],
        'labor event': ['labor_event'],
        'language': ['language'],
        'learning': ['learning'],
        'location': ['location'],
        'long term health care': ['long_term_health_care'],
        'long-term health care': ['long_term_health_care'],
        'male patient': ['male_patient'],
        'master degree': ['masters_degree'],
        'master of arts': ['master_of_arts'],
        'master of science': ['master_of_science'],
        'master of science in nursing': ['master_of_science_in_nursing'],
        "master's": ['masters_degree'],
        "master's degree": ['masters_degree'],
        'medical building': ['medical_building'],
        'medical facility closure': ['medical_facility_closure'],
        'mental health': ['mental_health'],
        'modern nursing': ['modern_nursing'],
        'money': ['money'],
        'mortality rate': ['mortality_rate'],
        'msc': ['master_of_science'],
        'msn': ['master_of_science_in_nursing'],
        'national certification': ['national_certification'],
        'nationality': ['nationality'],
        'np': ['nurse_practitioner'],
        'nps': ['nurse_practitioner'],
        'nurse': ['nurse'],
        'nurse educator': ['nurse_educator'],
        'nurse practitioner': ['nurse_practitioner'],
        'nursed': ['nurse'],
        'nurses': ['nurse'],
        'nursing': ['nursing'],
        'nursing diploma': ['nursing_diploma'],
        'nursing education': ['nursing_education'],
        'nursing home': ['nursing_home'],
        'nursing school': ['nursing_school'],
        'nursing student': ['nursing_student'],
        'ordinal': ['ordinal'],
        'organization': ['organization'],
        'outcome': ['outcome'],
        'outcome evaluation': ['outcome_evaluation'],
        'outcomes': ['outcome'],
        'patient': ['patient'],
        'patient care': ['patient_care'],
        'patient care coordination': ['patient_care'],
        'patient treatment': ['patient_treatment'],
        'patient treatment plan': ['patient_treatment_plan'],
        'pay': ['pay'],
        'pediactric patient': ['pediactric_patient'],
        'peer review': ['peer_review'],
        'percent': ['percent'],
        'periodic peer review': ['peer_review'],
        'permanent': ['permanent'],
        'person': ['person'],
        'personal touch': ['personal_touch'],
        'pharmacist': ['pharmacist'],
        'pharmacy': ['pharmacy'],
        'phd': ['doctoral_degree'],
        'physician': ['physician'],
        'plan\r\n': ['plan'],
        'pmhnp': ['psychiatric_mental_health_nurse_practitioner'],
        'political activity': ['political_activity'],
        'political group': ['political_group'],
        'practice': ['practice'],
        'practices': ['practice'],
        'primary care': ['primary_care'],
        'product': ['product'],
        'profession': ['profession'],
        'professional development': ['professional_development'],
        'protestant church': ['protestant_church'],
        'provider': ['provider'],
        'providers': ['provider'],
        'psychiatric mental health nurse practitioner': ['psychiatric_mental_health_nurse_practitioner'],
        'public health department': ['public_health_department'],
        'quality': ['quality'],
        'quantifiable measurement': ['quantifiable_measurement'],
        'quantity': ['quantity'],
        'race bias': ['racial_bias'],
        'racial bias': ['racial_bias'],
        'readmission': ['readmission'],
        'readmission rate': ['readmission_rate'],
        'receiver': ['receiver'],
        'reform': ['reform'],
        'reformation': ['reform'],
        'registered nurse': ['registered_nurse'],
        'regs': ['regulation'],
        'regulation': ['regulation'],
        'regulations': ['regulation'],
        'religious group': ['religious_group'],
        'rn': ['registered_nurse'],
        'rns': ['registered_nurse'],
        'room': ['room'],
        'rooms': ['room'],
        'rule\r\n': ['rule'],
        'rules': ['rule'],
        'salary': ['pay'],
        'school': ['school'],
        'schools': ['school'],
        'set to close': ['closure'],
        'shortage': ['shortage'],
        'site': ['site'],
        'sites': ['site'],
        'skill': ['skill'],
        'soft skill': ['soft_skill'],
        'spain': ['spain'],
        'spains': ['spain'],
        'spanish': ['spain', 'spanish'],
        'spanish hospital': ['spanish_hospital'],
        'specialist': ['specialist'],
        'staff': ['staff'],
        'staffing': ['staffing'],
        'staffing level': ['staffing_level'],
        'staffing shortage': ['staffing_shortage'],
        'strike': ['strike'],
        'student': ['student'],
        'surgeon': ['surgeon'],
        'surgery': ['surgery'],
        'temporarily': ['temporary'],
        'temporary': ['temporary'],
        'time': ['time'],
        'trained': ['training'],
        'training': ['training'],
        'training event': ['training_event'],
        'treatment event': ['treatment_event'],
        'urgent care': ['urgent_care'],
        'urgent care clinic': ['urgent_care'],
        'urgent care site': ['urgent_care'],
        'work of art': ['work_of_art']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
