
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class NursingSynonyms(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'NursingSynonyms',
            'filename': 'nursing_synonyms',
            'files': ['nursing.txt'],
            'queries': ['synonyms.sparql'],
            'reverse': True,
            'transformers': ['lowercase', 'synonyms']},
 'source': 'nursing.owl',
 'time': '2022-05-20 17:02:25.331704'}

    __data = {
    'activity': ['activity', 'action'],
    'acute_care': ['acute care'],
    'admission': ['admission'],
    'advanced_practice_registered_nurse': [   'advanced practice registered '
                                              'nurse',
                                              'aprn'],
    'agent': ['agent'],
    'airport': ['airport'],
    'american': ['americans', 'american'],
    'american_association_of_colleges_of_nursing': [   'american association '
                                                       'of colleges of nursing',
                                                       'aacn'],
    'american_nurses_association': [   'american nursing association',
                                       'american nurses association',
                                       'ana'],
    'apothecary': ['apothecaries', 'apothecary'],
    'artifact': ['artefact', 'artifact'],
    'associates_degree': [   "associate's degree",
                             'associate degree',
                             'aa degree'],
    'association': ['associations', 'assocations', 'association'],
    'bachelor_of_arts': ['bachelor of arts'],
    'bachelor_of_science': ['bachelor of science'],
    'bachelor_of_science_in_nursing': ['bachelor of science in nursing', 'bsn'],
    'bachelors_degree': [   'baccalaureate level',
                            "bachelor's degree",
                            'bachelor degree'],
    'bias': ['bias'],
    'building': ['building', 'edifice'],
    'cardinal': ['cardinal'],
    'care_event': ['care event'],
    'catholic_church': ['catholic church'],
    'century': ['century'],
    'certification': ['certification'],
    'chemist': ['chemist'],
    'church': ['church'],
    'city': ['city'],
    'clinic': ['clinics', 'clinic'],
    'clinical_competency': ['clinical competency'],
    'clinical_evaluation': ['clinical evaluation'],
    'clinical_outcome': ['clinical outcome'],
    'clinical_outcome_evaluation': ['clinical outcome evaluation'],
    'clinical_training': [   'advanced clinical training',
                             'clinical training',
                             'clinical course'],
    'closure': ['set to close', 'closure'],
    'college': ['colleges', 'college'],
    'company': ['company'],
    'competency': ['competency'],
    'condition': ['condition\r\n'],
    'continent': ['continent'],
    'continuous_learning': ['continuous learning', 'continued learning'],
    'country': ['country'],
    'course': ['courseworks', 'course work', 'coursework', 'courses', 'course'],
    'date': ['date'],
    'department': ['departments', 'department'],
    'development': ['development'],
    'diploma': ['diploma'],
    'doctoral_degree': [   'doctoral degree program',
                           'doctoral degree',
                           'doctoral',
                           'phd'],
    'education': ['education'],
    'educator': ['educator'],
    'elapsed_time': ['elapsed time', 'duration'],
    'elderly_patient': ['elderly patient'],
    'emergency_room': ['emergency room', 'er'],
    'empathy': ['empathy'],
    'ethical_practice': ['code for ethical practice', 'ethical practice'],
    'europe': ['europe'],
    'evaluation': ['evaluations', 'evaluation'],
    'event': ['event'],
    'facility_closure': ['facility closure'],
    'fail_to_rescue_rate': ['failure-to-rescue rates', 'fail to rescue rate'],
    'fair_pay': ['fair pay'],
    'family_nurse_practitioner': ['family nurse practitioner', 'fnp'],
    'female_patient': ['female patient'],
    'florence_nightingale': ['florence nightingale'],
    'gender_bias': ['gender bias'],
    'geopolitical_entity': ['geopolitical entity'],
    'group': ['group'],
    'health': ['health'],
    'health_care': ['health care'],
    'health_care_education': ['health care education'],
    'health_care_provider': ['health care provider'],
    'health_care_quality': ['health care quality'],
    'health_care_reform': ['health care reform'],
    'health_care_specialist': [   'health care specialist',
                                  'health care provider'],
    'health_department': ['health department'],
    'historical_nursing': ['historical nursing'],
    'history': ['history'],
    'home': ['homes', 'home'],
    'hospital': ['hospitals', 'hospital'],
    'johnson_and_johnson': ['johnson and johnson', 'johnson & johnson', 'j&j'],
    'labor_event': ['labor event'],
    'language': ['language'],
    'learning': ['learning'],
    'location': ['location'],
    'long_term_health_care': ['long-term health care', 'long term health care'],
    'male_patient': ['male patient'],
    'master_of_arts': ['master of arts'],
    'master_of_science': ['master of science', 'msc'],
    'master_of_science_in_nursing': ['master of science in nursing', 'msn'],
    'masters_degree': ["master's degree", 'master degree', "master's"],
    'medical_building': ['medical building'],
    'medical_facility_closure': ['medical facility closure'],
    'mental_health': ['mental health'],
    'modern_nursing': ['modern nursing'],
    'money': ['money'],
    'mortality_rate': ['mortality rate'],
    'national_certification': ['national certification'],
    'nationality': ['nationality'],
    'nurse': ['nursed', 'nurses', 'nurse'],
    'nurse_educator': ['nurse educator'],
    'nurse_practitioner': ['nurse practitioner', 'nps', 'np'],
    'nursing': ['nursing', '"rn"'],
    'nursing_diploma': ['nursing diploma'],
    'nursing_education': ['nursing education'],
    'nursing_home': ['nursing home'],
    'nursing_school': ['nursing school'],
    'nursing_student': ['nursing student'],
    'ordinal': ['ordinal'],
    'organization': ['organization'],
    'outcome': ['outcomes', 'outcome'],
    'outcome_evaluation': ['outcome evaluation'],
    'patient': ['patient'],
    'patient_care': ['patient care coordination', 'patient care'],
    'patient_treatment': ['patient treatment'],
    'patient_treatment_plan': ['patient treatment plan'],
    'pay': ['salary', 'pay'],
    'pediactric_patient': ['pediactric patient'],
    'peer_review': ['periodic peer review', 'peer review'],
    'percent': ['percent'],
    'permanent': ['permanent'],
    'person': ['person'],
    'personal_touch': ['personal touch'],
    'pharmacist': ['pharmacist'],
    'pharmacy': ['pharmacy'],
    'physician': ['physician'],
    'plan': ['plan\r\n'],
    'political_activity': ['political activity'],
    'political_group': ['political group'],
    'practice': ['practices', 'practice'],
    'primary_care': ['primary care'],
    'product': ['product'],
    'profession': ['profession'],
    'professional_development': ['professional development'],
    'protestant_church': ['protestant church'],
    'provider': ['providers', 'provider'],
    'psychiatric_mental_health_nurse_practitioner': [   'psychiatric mental '
                                                        'health nurse '
                                                        'practitioner',
                                                        'pmhnp'],
    'public_health_department': ['public health department'],
    'quality': ['quality'],
    'quantifiable_measurement': ['quantifiable measurement'],
    'quantity': ['quantity'],
    'racial_bias': ['racial bias', 'race bias'],
    'readmission': ['readmission'],
    'readmission_rate': ['readmission rate'],
    'receiver': ['receiver'],
    'reform': ['reformation', 'reform'],
    'registered_nurse': ['registered nurse', 'rns', 'rn'],
    'regulation': ['regulations', 'regulation', 'regs'],
    'religious_group': ['religious group'],
    'room': ['rooms', 'room'],
    'rule': ['rule\r\n', 'rules'],
    'school': ['schools', 'school'],
    'shortage': ['shortage'],
    'site': ['sites', 'site'],
    'skill': ['skill'],
    'soft_skill': ['soft skill'],
    'spain': ['spanish', 'spains', 'spain'],
    'spanish': ['spanish'],
    'spanish_hospital': ['spanish hospital'],
    'specialist': ['specialist'],
    'staff': ['staff'],
    'staffing': ['staffing'],
    'staffing_level': ['staffing level'],
    'staffing_shortage': ['staffing shortage'],
    'strike': ['strike'],
    'student': ['student'],
    'surgeon': ['surgeon'],
    'surgery': ['surgery'],
    'temporary': ['temporarily', 'temporary'],
    'time': ['time'],
    'training': ['training', 'trained'],
    'training_event': ['training event'],
    'treatment_event': ['treatment event'],
    'urgent_care': ['urgent care clinic', 'urgent care site', 'urgent care'],
    'work_of_art': ['work of art']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
