
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class QuestionsLookup(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'QuestionsLookup',
            'filename': 'questions_lookup',
            'files': ['questions.txt'],
            'queries': ['lookup.sparql'],
            'transformers': ['lowercase', 'lookup']},
 'source': 'questions.owl',
 'time': '2022-05-13 12:06:42.404840'}

    __data = {
    1: [   'problem-solving',
           'comprehension',
           'organization',
           'hypothetical',
           'redirection',
           'application',
           'structuring',
           'disjunctive',
           'comparison',
           'clarifying',
           'convergent',
           'rhetorical',
           'evaluation',
           'evaluative',
           'refocusing',
           'synthesis',
           'prompting',
           'divergent',
           'ourselves',
           'affective',
           'knowledge',
           'inference',
           'onesself',
           'yourself',
           'analysis',
           'pronoun',
           'boolean',
           'probing',
           'leading',
           'ourself',
           'factual',
           'loaded',
           "what's",
           'myself',
           'choice',
           'yours',
           'your',
           'mine',
           'they',
           'them',
           'our',
           'her',
           'you',
           'she',
           'tag',
           'him',
           'my',
           'we',
           'it',
           'he',
           'me',
           'us',
           'i'],
    2: [   'present_perfect_continuous_where question',
           'present_perfect_continuous_why question',
           'future_perfect_continuous_how question',
           'past_perfect_continuous_what question',
           'past_perfect_continuous_how question',
           'past_perfect_continuous_why question',
           'present_perfect_continuous question',
           'future_perfect_continuous question',
           'open_present_simple_where question',
           'open_present_simple_what question',
           'open_present_simple_when question',
           'closed_present_simple_do question',
           'present_continuous_what question',
           'open_present_simple_who question',
           'open_present_simple_why question',
           'future_continuous_where question',
           'open_present_simple_how question',
           'past_perfect_continuous question',
           'present_continuous_who question',
           'present_continuous_why question',
           'future_continuous_why question',
           'closed_present_simple question',
           'past_continuous_where question',
           'present_simple_where question',
           'past_continuous_what question',
           'present_perfect_why question',
           'present_simple_what question',
           'present_perfect_how question',
           'past_continuous_why question',
           'future_simple_where question',
           'future_perfect_when question',
           'open_present_simple question',
           'future_simple_when question',
           'present_continuous question',
           'perfect_continuous question',
           'future_pefect_why question',
           'future_simple_how question',
           'future_continuous question',
           'past_perfect_when question',
           'present_simple_do question',
           'past_perfect_why question',
           'present_perfect statement',
           'past_perfect_how question',
           'past_simple_when question',
           'past_simple_how question',
           'past_continuous question',
           'past_simple_why question',
           'future_perfect statement',
           'past_simple_who question',
           'present_perfect question',
           'present_simple question',
           'future_perfect question',
           'past_perfect statement',
           'future_simple question',
           'perfect_tense question',
           'present_tense question',
           'what_is_your question',
           'second_person pronoun',
           'past_perfect question',
           'future_tense question',
           'simple_tense question',
           'third_person pronoun',
           'past_simple question',
           'first_person pronoun',
           'deductive inference',
           'continuous question',
           'past_tense question',
           'question component',
           'critical awareness',
           'general question',
           'special question',
           'double barreled',
           'problem solving',
           'recall question',
           'yes/no question',
           'polar question',
           'where question',
           'complete tense',
           'what question',
           'when question',
           'open question',
           'simple recall',
           'what_is your',
           'tag question',
           'why question',
           'how question',
           'who question',
           'wh question',
           'do question',
           'close ended',
           'open ended',
           "one's self",
           'ones self',
           'what is'],
    3: [   'present continuous question',
           'perfect continuous question',
           'future continuous question',
           'present perfect statement',
           'past continuous question',
           'present perfect question',
           'future perfect statement',
           'present simple question',
           'future perfect question',
           'present tense question',
           'past perfect statement',
           'perfect tense question',
           'future simple question',
           'past perfect question',
           'simple tense question',
           'future tense question',
           'second person pronoun',
           'first person pronoun',
           'third person pronoun',
           'past simple question',
           'past tense question',
           'what is your'],
    4: [   'present perfect continuous question',
           'future perfect continuous question',
           'past perfect continuous question',
           'present continuous what question',
           'future continuous where question',
           'present continuous why question',
           'present continuous who question',
           'past continuous where question',
           'future continuous why question',
           'closed present simple question',
           'past continuous what question',
           'present simple where question',
           'future perfect when question',
           'open present simple question',
           'future simple where question',
           'past continuous why question',
           'present perfect why question',
           'present simple what question',
           'present perfect how question',
           'future simple when question',
           'future pefect why question',
           'future simple how question',
           'past perfect when question',
           'present simple do question',
           'past perfect how question',
           'past simple when question',
           'past perfect why question',
           'past simple who question',
           'past simple how question',
           'past simple why question',
           'what is your question'],
    5: [   'present perfect continuous where question',
           'present perfect continuous why question',
           'future perfect continuous how question',
           'past perfect continuous what question',
           'past perfect continuous why question',
           'past perfect continuous how question',
           'open present simple where question',
           'open present simple what question',
           'closed present simple do question',
           'open present simple when question',
           'open present simple why question',
           'open present simple how question',
           'open present simple who question'],
    6: []}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
