
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class QuestionsSpans(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'QuestionsSpans',
            'filename': 'questions_spans',
            'queries': ['spans.sparql'],
            'transformers': ['spans']},
 'source': 'questions.owl',
 'time': '2022-05-13 12:06:42.440840'}

    __data = {
    'close': [   {   'canon': 'close_ended',
                     'content': {'ended'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'closed': [   {   'canon': 'closed_present_simple_question',
                      'content': {'question', 'present', 'simple'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'closed_present_simple_do_question',
                      'content': {'question', 'present', 'simple'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'complete': [   {   'canon': 'perfect_tense_question',
                        'content': {'tense'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'continuous': [   {   'canon': 'continuous_question',
                          'content': {'question'},
                          'distance': 3,
                          'forward': True,
                          'reverse': True}],
    'critical': [   {   'canon': 'critical_awareness',
                        'content': {'awareness'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'deductive': [   {   'canon': 'deductive_inference',
                         'content': {'inference'},
                         'distance': 3,
                         'forward': True,
                         'reverse': True}],
    'do': [   {   'canon': 'do_question',
                  'content': {'question'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    'double': [   {   'canon': 'double_barreled',
                      'content': {'barreled'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'first': [   {   'canon': 'first_person_pronoun',
                     'content': {'pronoun', 'person'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'future': [   {   'canon': 'future_simple_where_question',
                      'content': {'question', 'simple'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_pefect_why_question',
                      'content': {'pefect', 'question'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_perfect_continuous_question',
                      'content': {'perfect', 'continuous', 'question'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_continuous_why_question',
                      'content': {'continuous', 'question'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_perfect_continuous_how_question',
                      'content': {'perfect', 'continuous', 'question'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_continuous_question',
                      'content': {'continuous', 'question'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_perfect_when_question',
                      'content': {'perfect', 'question'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_perfect_question',
                      'content': {'perfect', 'question'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_simple_question',
                      'content': {'question', 'simple'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_perfect_statement',
                      'content': {'perfect', 'statement'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_simple_how_question',
                      'content': {'question', 'simple'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_continuous_where_question',
                      'content': {'continuous', 'question'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_simple_when_question',
                      'content': {'question', 'simple'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'future_tense_question',
                      'content': {'question', 'tense'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'how': [   {   'canon': 'how_question',
                   'content': {'question'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'open': [   {   'canon': 'open_present_simple_how_question',
                    'content': {'question', 'present', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'open_present_simple_who_question',
                    'content': {'question', 'present', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'open_present_simple_question',
                    'content': {'question', 'present', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'open_present_simple_why_question',
                    'content': {'question', 'present', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'open_ended',
                    'content': {'ended'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'open_ended',
                    'content': {'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'open_present_simple_where_question',
                    'content': {'question', 'present', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'open_present_simple_what_question',
                    'content': {'question', 'present', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'open_present_simple_when_question',
                    'content': {'question', 'present', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'past': [   {   'canon': 'past_simple_who_question',
                    'content': {'question', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_continuous_what_question',
                    'content': {'continuous', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_perfect_continuous_what_question',
                    'content': {'perfect', 'continuous', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_continuous_question',
                    'content': {'continuous', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_perfect_why_question',
                    'content': {'perfect', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_perfect_how_question',
                    'content': {'perfect', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_perfect_continuous_question',
                    'content': {'perfect', 'continuous', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_continuous_where_question',
                    'content': {'continuous', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_simple_when_question',
                    'content': {'question', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_simple_why_question',
                    'content': {'question', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_perfect_continuous_why_question',
                    'content': {'perfect', 'continuous', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_simple_question',
                    'content': {'question', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_perfect_when_question',
                    'content': {'perfect', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_perfect_statement',
                    'content': {'perfect', 'statement'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_continuous_why_question',
                    'content': {'continuous', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_simple_how_question',
                    'content': {'question', 'simple'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_perfect_continuous_how_question',
                    'content': {'perfect', 'continuous', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_tense_question',
                    'content': {'question', 'tense'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'past_perfect_question',
                    'content': {'perfect', 'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'perfect': [   {   'canon': 'perfect_continuous_question',
                       'content': {'continuous', 'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'perfect_tense_question',
                       'content': {'question', 'tense'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'present': [   {   'canon': 'present_simple_where_question',
                       'content': {'question', 'simple'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_tense_question',
                       'content': {'question', 'tense'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_perfect_continuous_question',
                       'content': {'perfect', 'continuous', 'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_continuous_question',
                       'content': {'continuous', 'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_simple_what_question',
                       'content': {'question', 'simple'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_simple_question',
                       'content': {'question', 'simple'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_continuous_what_question',
                       'content': {'continuous', 'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_perfect_how_question',
                       'content': {'perfect', 'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_perfect_why_question',
                       'content': {'perfect', 'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_continuous_who_question',
                       'content': {'continuous', 'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_continuous_why_question',
                       'content': {'continuous', 'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_perfect_continuous_why_question',
                       'content': {'perfect', 'continuous', 'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_simple_do_question',
                       'content': {'question', 'simple'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_perfect_continuous_where_question',
                       'content': {'perfect', 'continuous', 'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_perfect_question',
                       'content': {'perfect', 'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True},
                   {   'canon': 'present_perfect_statement',
                       'content': {'perfect', 'statement'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'problem': [   {   'canon': 'problem_solving',
                       'content': {'solving'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'question': [   {   'canon': 'question_component',
                        'content': {'component'},
                        'distance': 3,
                        'forward': True,
                        'reverse': True}],
    'recall': [   {   'canon': 'simple_recall',
                      'content': {'question'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'second': [   {   'canon': 'second_person_pronoun',
                      'content': {'pronoun', 'person'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'simple': [   {   'canon': 'simple_tense_question',
                      'content': {'question', 'tense'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True},
                  {   'canon': 'simple_recall',
                      'content': {'recall'},
                      'distance': 3,
                      'forward': True,
                      'reverse': True}],
    'special': [   {   'canon': 'wh_question',
                       'content': {'question'},
                       'distance': 3,
                       'forward': True,
                       'reverse': True}],
    'third': [   {   'canon': 'third_person_pronoun',
                     'content': {'pronoun', 'person'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'wh': [   {   'canon': 'wh_question',
                  'content': {'question'},
                  'distance': 3,
                  'forward': True,
                  'reverse': True}],
    'what': [   {   'canon': 'what_is_your_question',
                    'content': {'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True},
                {   'canon': 'what_question',
                    'content': {'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'when': [   {   'canon': 'when_question',
                    'content': {'question'},
                    'distance': 3,
                    'forward': True,
                    'reverse': True}],
    'where': [   {   'canon': 'where_question',
                     'content': {'question'},
                     'distance': 3,
                     'forward': True,
                     'reverse': True}],
    'who': [   {   'canon': 'who_question',
                   'content': {'question'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}],
    'why': [   {   'canon': 'why_question',
                   'content': {'question'},
                   'distance': 3,
                   'forward': True,
                   'reverse': True}]}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
