
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################

class QuestionsLabelsRev(object):

    @staticmethod
    def prov() -> dict:
        return {
 'action': ['router.py',
            'plac_core.py',
            'owl2py_orchestrator.py',
            'generate_runtime_dictionaries.py',
            'generate_runtime_dictionary.py',
            'owl_data_load_dict.py',
            'common_utils.py'],
 'config': {'classname': 'QuestionsLabels',
            'filename': 'questions_labels',
            'queries': ['labels.sparql'],
            'reverse': True,
            'transformers': ['labels']},
 'source': 'questions.owl',
 'time': '2022-05-13 12:06:42.651842'}

    __data = {
    'Affective': ['affective'],
    'Analysis': ['analysis'],
    'Application': ['application'],
    'Boolean': ['boolean'],
    'Choice': ['choice'],
    'Clarifying': ['clarifying'],
    'Close Ended': ['close_ended'],
    'Closed Present Simple Do Question': ['closed_present_simple_do_question'],
    'Closed Present Simple Question': ['closed_present_simple_question'],
    'Comparison': ['comparison'],
    'Comprehension': ['comprehension'],
    'Continuous Question': ['continuous_question'],
    'Convergent': ['convergent'],
    'Critical Awareness': ['critical_awareness'],
    'Disjunctive': ['disjunctive'],
    'Divergent': ['divergent'],
    'Do Question': ['do_question'],
    'Double Barreled': ['double_barreled'],
    'Evaluation': ['evaluation'],
    'Evaluative': ['evaluative'],
    'Factual': ['factual'],
    'First Person Pronoun': ['first_person_pronoun'],
    'Future Continuous Question': ['future_continuous_question'],
    'Future Continuous Where Question': ['future_continuous_where_question'],
    'Future Continuous Why Question': ['future_continuous_why_question'],
    'Future Pefect Why Question': ['future_pefect_why_question'],
    'Future Perfect Continuous How Question': [   'future_perfect_continuous_how_question'],
    'Future Perfect Continuous Question': [   'future_perfect_continuous_question'],
    'Future Perfect Question': ['future_perfect_question'],
    'Future Perfect Statement': ['future_perfect_statement'],
    'Future Perfect When Question': ['future_perfect_when_question'],
    'Future Simple How Question': ['future_simple_how_question'],
    'Future Simple Question': ['future_simple_question'],
    'Future Simple When Question': ['future_simple_when_question'],
    'Future Simple Where Question': ['future_simple_where_question'],
    'Future Tense Question': ['future_tense_question'],
    'He': ['he'],
    'Her': ['her'],
    'Him': ['him'],
    'How Question': ['how_question'],
    'Hypothetical': ['hypothetical'],
    'I': ['i'],
    'Inference': ['inference'],
    'It': ['it'],
    'Knowledge': ['wh_question'],
    'Leading': ['leading'],
    'Loaded': ['loaded'],
    'Me': ['me'],
    'Mine': ['mine'],
    'My': ['my'],
    'Myself': ['myself'],
    'Open Ended': ['open_ended'],
    'Open Present Simple How Question': ['open_present_simple_how_question'],
    'Open Present Simple Question': ['open_present_simple_question'],
    'Open Present Simple What Question': ['open_present_simple_what_question'],
    'Open Present Simple When Question': ['open_present_simple_when_question'],
    'Open Present Simple Where Question': [   'open_present_simple_where_question'],
    'Open Present Simple Who Question': ['open_present_simple_who_question'],
    'Open Present Simple Why Question': ['open_present_simple_why_question'],
    'Organization': ['organization'],
    'Our': ['our'],
    'Ourselves': ['ourselves'],
    'Past Continuous Question': ['past_continuous_question'],
    'Past Continuous What Question': ['past_continuous_what_question'],
    'Past Continuous Where Question': ['past_continuous_where_question'],
    'Past Continuous Why Question': ['past_continuous_why_question'],
    'Past Perfect Continuous How Question': [   'past_perfect_continuous_how_question'],
    'Past Perfect Continuous Question': ['past_perfect_continuous_question'],
    'Past Perfect Continuous What Question': [   'past_perfect_continuous_what_question'],
    'Past Perfect Continuous Why Question': [   'past_perfect_continuous_why_question'],
    'Past Perfect How Question': ['past_perfect_how_question'],
    'Past Perfect Question': ['past_perfect_question'],
    'Past Perfect Statement': ['past_perfect_statement'],
    'Past Perfect When Question': ['past_perfect_when_question'],
    'Past Perfect Why Question': ['past_perfect_why_question'],
    'Past Simple How Question': ['past_simple_how_question'],
    'Past Simple Question': ['past_simple_question'],
    'Past Simple When Question': ['past_simple_when_question'],
    'Past Simple Who Question': ['past_simple_who_question'],
    'Past Simple Why Question': ['past_simple_why_question'],
    'Past Tense Question': ['past_tense_question'],
    'Perfect Continuous Question': ['perfect_continuous_question'],
    'Perfect Tense Question': ['perfect_tense_question'],
    'Present Continuous Question': ['present_continuous_question'],
    'Present Continuous What Question': ['present_continuous_what_question'],
    'Present Continuous Who Question': ['present_continuous_who_question'],
    'Present Continuous Why Question': ['present_continuous_why_question'],
    'Present Perfect Continuous Question': [   'present_perfect_continuous_question'],
    'Present Perfect Continuous Where Question': [   'present_perfect_continuous_where_question'],
    'Present Perfect Continuous Why Question': [   'present_perfect_continuous_why_question'],
    'Present Perfect How Question': ['present_perfect_how_question'],
    'Present Perfect Question': ['present_perfect_question'],
    'Present Perfect Statement': ['present_perfect_statement'],
    'Present Perfect Why Question': ['present_perfect_why_question'],
    'Present Simple Do Question': ['present_simple_do_question'],
    'Present Simple Question': ['present_simple_question'],
    'Present Simple What Question': ['present_simple_what_question'],
    'Present Simple Where Question': ['present_simple_where_question'],
    'Present Tense Question': ['present_tense_question'],
    'Probing': ['probing'],
    'Problem Solving': ['problem_solving'],
    'Prompting': ['prompting'],
    'Pronoun': ['pronoun'],
    'Question Component': ['question_component'],
    'Redirection': ['redirection'],
    'Refocusing': ['refocusing'],
    'Rhetorical': ['rhetorical'],
    'Second Person Pronoun': ['second_person_pronoun'],
    'She': ['she'],
    'Simple Recall': ['simple_recall'],
    'Simple Tense Question': ['simple_tense_question'],
    'Structuring': ['structuring'],
    'Synthesis': ['synthesis'],
    'Tag': ['tag'],
    'Them': ['them'],
    'They': ['they'],
    'Third Person Pronoun': ['third_person_pronoun'],
    'Us': ['us'],
    'We': ['we'],
    'What Is': ['what_is'],
    'What Is Your Question': ['what_is_your_question'],
    'What Question': ['what_question'],
    'When Question': ['when_question'],
    'Where Question': ['where_question'],
    'Who Question': ['who_question'],
    'Why Question': ['why_question'],
    'You': ['you'],
    'Your': ['your'],
    'Yourself': ['yourself']}

    def data(self) -> dict:
        return self.__data

    def find(self,
             term: str) -> str or None:
        if term in self.__data:
            return self.__data[term]
